// Animated Treemap — Animation, route: jsx
// Source: animated-treemap
//
// Self-contained: every local import is inlined below. Requires only d3, motion, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useMemo, useState } from 'react';
import * as d3 from 'd3';
import { motion } from 'motion/react';

// ---- inlined from animatedTreemap ----
/** A region or division groups children; a state carries one population per census year. */
type PopulationNode = {
  name: string;
  values?: number[];
  children?: PopulationNode[];
};

/** Census years covered, one animation step each. */
const censusYears = [1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990];

/** U.S. resident population by state, 1900-1990, grouped region > division > state. Source: U.S. Census Bureau. */
const usPopulation: PopulationNode = {
  name: 'United States',
  children: [
    {
      name: 'Northeast',
      children: [
        {
          name: 'New England',
          children: [
            { name: 'Connecticut', values: [908420, 1114756, 1380631, 1606903, 1709242, 2007280, 2535234, 3031709, 3107576, 3287116] },
            { name: 'Maine', values: [694466, 742371, 768014, 797423, 847226, 913774, 969265, 992048, 1124660, 1227928] },
            { name: 'Massachusetts', values: [2805346, 3366416, 3852356, 4249614, 4316721, 4690514, 5148578, 5689170, 5737037, 6016425] },
            { name: 'New Hampshire', values: [411588, 430572, 443083, 465293, 491524, 533242, 606921, 737681, 920610, 1109252] },
            { name: 'Rhode Island', values: [428556, 542610, 604397, 687497, 713346, 791896, 859488, 946725, 947154, 1003464] },
            { name: 'Vermont', values: [343641, 355956, 352428, 359611, 359231, 377747, 389881, 444330, 511456, 562758] }
          ]
        },
        {
          name: 'Middle Atlantic',
          children: [
            { name: 'New Jersey', values: [1883669, 2537167, 3155900, 4041334, 4160165, 4835329, 6066782, 7168164, 7364823, 7730188] },
            { name: 'New York', values: [7268894, 9113614, 10385227, 12588066, 13479142, 14830192, 16782304, 18236967, 17558072, 17990455] },
            { name: 'Pennsylvania', values: [6302115, 7665111, 8720017, 9631350, 9900180, 10498012, 11319366, 11793909, 11863895, 11881643] }
          ]
        }
      ]
    },
    {
      name: 'Midwest',
      children: [
        {
          name: 'East North Central',
          children: [
            { name: 'Illinois', values: [4821550, 5638591, 6485280, 7630654, 7897241, 8712176, 10081158, 11113976, 11426518, 11430602] },
            { name: 'Indiana', values: [2516462, 2700876, 2930390, 3238503, 3427796, 3934224, 4662498, 5193669, 5490224, 5544159] },
            { name: 'Michigan', values: [2420982, 2810173, 3668412, 4842325, 5256106, 6371766, 7823194, 8875083, 9262078, 9295297] },
            { name: 'Ohio', values: [4157545, 4767121, 5759394, 6646697, 6907612, 7946627, 9706397, 10652017, 10797630, 10847115] },
            { name: 'Wisconsin', values: [2069042, 2333860, 2632067, 2939006, 3137587, 3434575, 3951777, 4417731, 4705767, 4891769] }
          ]
        },
        {
          name: 'West North Central',
          children: [
            { name: 'Iowa', values: [2231853, 2224771, 2404021, 2470939, 2538268, 2621073, 2757537, 2824376, 2913808, 2776755] },
            { name: 'Kansas', values: [1470495, 1690949, 1769257, 1880999, 1801028, 1905299, 2178611, 2246578, 2363679, 2477574] },
            { name: 'Minnesota', values: [1751394, 2075708, 2387125, 2563953, 2792300, 2982483, 3413864, 3804971, 4075970, 4375099] },
            { name: 'Missouri', values: [3106665, 3293335, 3404055, 3629367, 3784664, 3954653, 4319813, 4676501, 4916686, 5117073] },
            { name: 'Nebraska', values: [1066300, 1192214, 1296372, 1377963, 1315834, 1325510, 1411330, 1483493, 1569825, 1578385] },
            { name: 'North Dakota', values: [319146, 577056, 646872, 680845, 641935, 619636, 632446, 617761, 652717, 638800] },
            { name: 'South Dakota', values: [401570, 583888, 636547, 692849, 642961, 652740, 680514, 665507, 690768, 696004] }
          ]
        }
      ]
    },
    {
      name: 'South',
      children: [
        {
          name: 'East South Central',
          children: [
            { name: 'Alabama', values: [1828697, 2138093, 2348174, 2646248, 2832961, 3061743, 3266740, 3444165, 3893888, 4040587] },
            { name: 'Kentucky', values: [2147174, 2289905, 2416630, 2614589, 2845627, 2944806, 3038156, 3218706, 3660777, 3685296] },
            { name: 'Mississippi', values: [1551270, 1797114, 1790618, 2009821, 2183796, 2178914, 2178141, 2216912, 2520638, 2573216] },
            { name: 'Tennessee', values: [2020616, 2184789, 2337885, 2616556, 2915841, 3291718, 3567089, 3923687, 4591120, 4877185] }
          ]
        },
        {
          name: 'West South Central',
          children: [
            { name: 'Arkansas', values: [1311564, 1574449, 1752204, 1854482, 1949387, 1909511, 1786272, 1923295, 2286435, 2350725] },
            { name: 'Louisiana', values: [1381625, 1656388, 1798509, 2101593, 2363880, 2683516, 3257022, 3641306, 4205900, 4219973] },
            { name: 'Oklahoma', values: [790391, 1657155, 2028283, 2396040, 2336434, 2233351, 2328284, 2559229, 3025290, 3145585] },
            { name: 'Texas', values: [3048710, 3896542, 4663228, 5824715, 6414824, 7711194, 9579677, 11196730, 14229191, 16986510] }
          ]
        },
        {
          name: 'South Atlantic',
          children: [
            { name: 'Delaware', values: [184735, 202322, 223003, 238380, 266505, 318085, 446292, 548104, 594338, 666168] },
            { name: 'District of Columbia', values: [278718, 331069, 437571, 486869, 663091, 802178, 763956, 756510, 638333, 606900] },
            { name: 'Florida', values: [528542, 752619, 968470, 1468211, 1897414, 2771305, 4951560, 6789443, 9746324, 12937926] },
            { name: 'Georgia', values: [2216331, 2609121, 2895832, 2908506, 3123723, 3444578, 3943116, 4589575, 5463105, 6478216] },
            { name: 'Maryland', values: [1188044, 1295346, 1449661, 1631526, 1821244, 2343001, 3100689, 3922399, 4216975, 4781468] },
            { name: 'North Carolina', values: [1893810, 2206287, 2559123, 3170276, 3571623, 4061929, 4556155, 5082059, 5881766, 6628637] },
            { name: 'South Carolina', values: [1340316, 1515400, 1683724, 1738765, 1899804, 2117027, 2382594, 2590516, 3121820, 3486703] },
            { name: 'Virginia', values: [1854184, 2061612, 2309187, 2421851, 2677773, 3318680, 3966949, 4648494, 5346818, 6187358] },
            { name: 'West Virginia', values: [958800, 1221119, 1463701, 1729205, 1901974, 2005552, 1860421, 1744237, 1949644, 1793477] }
          ]
        }
      ]
    },
    {
      name: 'West',
      children: [
        {
          name: 'Pacific',
          children: [
            { name: 'Alaska', values: [63592, 64356, 55036, 59278, 72524, 128643, 226167, 300382, 401851, 550043] },
            { name: 'California', values: [1485053, 2377549, 3426861, 5677251, 6907387, 10586223, 15717204, 19953134, 23667902, 29760021] },
            { name: 'Hawaii', values: [154001, 191874, 255881, 368300, 422770, 499794, 632772, 768561, 964691, 1108229] },
            { name: 'Oregon', values: [413536, 672765, 783389, 953786, 1089684, 1521341, 1768687, 2091385, 2633105, 2842321] },
            { name: 'Washington', values: [518103, 1141990, 1356621, 1563396, 1736191, 2378963, 2853214, 3409169, 4132156, 4866692] }
          ]
        },
        {
          name: 'Mountain',
          children: [
            { name: 'Arizona', values: [122931, 204354, 334162, 435573, 499261, 749587, 1302161, 1770900, 2718215, 3665228] },
            { name: 'Colorado', values: [539700, 799024, 939629, 1035791, 1123296, 1325089, 1753947, 2207259, 2889964, 3294394] },
            { name: 'Idaho', values: [161772, 325594, 431866, 445032, 524873, 588637, 667191, 712567, 943935, 1006749] },
            { name: 'Montana', values: [243329, 376053, 548889, 537606, 559456, 591024, 674767, 694409, 786690, 799065] },
            { name: 'Nevada', values: [42335, 81875, 77407, 91058, 110247, 160083, 285278, 488738, 800493, 1201833] },
            { name: 'New Mexico', values: [195310, 327301, 360350, 423317, 531818, 681187, 951023, 1016000, 1302894, 1515069] },
            { name: 'Utah', values: [276749, 373351, 449396, 507847, 550310, 688862, 890627, 1059273, 1461037, 1722850] },
            { name: 'Wyoming', values: [92531, 145965, 194402, 225565, 250742, 290529, 330066, 332416, 469557, 453588] }
          ]
        }
      ]
    }
  ]
};

const MARGIN = { top: 28, right: 4, bottom: 4, left: 4 };
const STEP_MS = 1600;
const FONT_SIZE = 9;
/** Mean advance width of 9px sans-serif, used to drop labels that would overflow their cell. */
const CHAR_WIDTH = 5;
const LABEL_INSET = 3;
/** Region hues are mixed toward the page background so the light labels stay readable on them. */
const BG = '#16181a';

type Cell = {
  key: string;
  region: string;
  value: number;
  x: number;
  y: number;
  w: number;
  h: number;
};

type Frame = { year: number; total: number; k: number; cells: Cell[] };

/** One label per animation step, and a nested hierarchy whose leaves carry one value per step. */
export type Data = { years: number[]; population: PopulationNode };

const DEMO: Data = { years: censusYears, population: usPopulation };

const format = d3.format(',d');

export default function AnimatedTreemap({ data = DEMO, width }: { data?: Data; width: number }) {
  const height = Math.round(width * 0.92) + MARGIN.top;
  const innerWidth = Math.max(1, width - MARGIN.left - MARGIN.right);
  const innerHeight = Math.max(1, height - MARGIN.top - MARGIN.bottom);

  const frames = useMemo<Frame[]>(() => {
    const root = d3
      .hierarchy(data.population)
      .sum((d) => (d.values ? d3.sum(d.values) : 0))
      .sort((a, b) => (b.value ?? 0) - (a.value ?? 0));

    const treemap = d3
      .treemap<PopulationNode>()
      .tile(d3.treemapResquarify) // keeps each cell's orientation stable as values change
      .padding((d) => (d.height === 1 ? 1 : 0))
      .round(true);

    // Lay out once on the all-year total so resquarify locks the orientation every step reuses.
    treemap.size([innerWidth, innerHeight])(root);

    const totals = data.years.map((_, i) => root.sum((d) => d.values?.[i] ?? 0).value ?? 0);
    const max = d3.max(totals) ?? 1;

    return data.years.map((year, i) => {
      const total = totals[i];
      // Scaling the whole map by sqrt of its share of the peak keeps areas comparable across years.
      const k = Math.sqrt(total / max);
      const laid = treemap.size([innerWidth * k, innerHeight * k])(
        root.sum((d) => d.values?.[i] ?? 0)
      );
      const tx = ((1 - k) / 2) * innerWidth;
      const ty = ((1 - k) / 2) * innerHeight;

      const cells = laid.leaves().map((leaf) => ({
        key: leaf.data.name,
        region: leaf.ancestors().at(-2)?.data.name ?? '',
        value: leaf.value ?? 0,
        x: leaf.x0 + tx,
        y: leaf.y0 + ty,
        w: leaf.x1 - leaf.x0,
        h: leaf.y1 - leaf.y0
      }));

      return { year, total, k, cells };
    });
  }, [data, innerWidth, innerHeight]);

  const color = useMemo(
    () =>
      d3.scaleOrdinal<string, string>(
        (data.population.children ?? []).map((d) => d.name),
        d3.schemeObservable10.map((hue) => d3.interpolateRgb(hue, BG)(0.4))
      ),
    [data]
  );

  const [step, setStep] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => setStep((s) => (s + 1) % data.years.length), STEP_MS);
    return () => clearInterval(timer);
  }, [data]);

  if (width === 0) return null;

  const frame = frames[step];
  const transition = { duration: STEP_MS / 1000, ease: 'linear' as const };

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Animated treemap of U.S. population by state, each census from 1900 to 1990"
    >
      <text x={MARGIN.left} y={18} fill="var(--text)" fontSize={13}>
        <tspan fontWeight="bold">{frame.year}</tspan>
        <tspan fill="var(--muted)">{`  ${format(frame.total)}`}</tspan>
      </text>
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`} fontSize={FONT_SIZE}>
        {/* The outer frame tracks the national total, so growth reads even when shares hold steady. */}
        <motion.g
          initial={false}
          animate={{ x: ((1 - frame.k) / 2) * innerWidth, y: ((1 - frame.k) / 2) * innerHeight }}
          transition={transition}
        >
          <motion.rect
            initial={false}
            animate={{ width: frame.k * innerWidth, height: frame.k * innerHeight }}
            transition={transition}
            fill="none"
            stroke="var(--line)"
          />
        </motion.g>
        {frame.cells.map((cell) => {
          const value = format(cell.value);
          const room = cell.w - LABEL_INSET * 2;
          const fitsName = cell.h >= 14 && cell.key.length * CHAR_WIDTH <= room;
          const fitsValue = cell.h >= 24 && value.length * CHAR_WIDTH <= room;

          return (
            <motion.g
              key={cell.key}
              initial={false}
              animate={{ x: cell.x, y: cell.y }}
              transition={transition}
            >
              <title>{`${cell.key}\n${value}`}</title>
              <motion.rect
                initial={false}
                animate={{ width: cell.w, height: cell.h }}
                transition={transition}
                fill={color(cell.region)}
              />
              {fitsName && (
                <text x={LABEL_INSET} y={11} fill="var(--text)">
                  {cell.key}
                </text>
              )}
              {fitsValue && (
                <text x={LABEL_INSET} y={21} fill="var(--text)" fillOpacity={0.7}>
                  {value}
                </text>
              )}
            </motion.g>
          );
        })}
      </g>
    </svg>
  );
}
