// Antimeridian Cutting — Geo, route: jsx
// Source: antimeridian-cutting
//
// Self-contained: every local import is inlined below. Requires only d3, geojson, react, topojson-client, topojson-specification, us-atlas, world-atlas.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { feature, mesh } from 'topojson-client';
import countries110m from 'world-atlas/countries-110m.json';
import statesUs from 'us-atlas/states-10m.json';
import type { GeometryCollection, Topology } from 'topojson-specification';
import type { Feature, FeatureCollection, Geometry, MultiLineString } from 'geojson';
import { useEffect, useMemo, useState } from 'react';
import * as d3 from 'd3';

// ---- inlined from geo ----
// The atlases ship untyped JSON. One cast per topology at this boundary keeps every
// consumer strict, and converting here means each chart does not re-derive the same
// geometry at module load.

type Named = { name: string };
type NamedFeature = Feature<Geometry, Named>;

const world = countries110m as unknown as Topology<{
  countries: GeometryCollection<Named>;
  land: GeometryCollection;
}>;

const us = statesUs as unknown as Topology<{
  states: GeometryCollection<Named>;
  nation: GeometryCollection;
}>;

const worldCountries = feature(
  world,
  world.objects.countries
) as FeatureCollection<Geometry, Named>;

const worldLand = feature(world, world.objects.land) as FeatureCollection<Geometry>;

/** Shared borders only, so neighbouring outlines are stroked once instead of twice. */
const worldBorders = mesh(
  world,
  world.objects.countries,
  (a, b) => a !== b
) as MultiLineString;

const usNation = feature(us, us.objects.nation) as FeatureCollection<Geometry>;

const usStateBorders = mesh(
  us,
  us.objects.states,
  (a, b) => a !== b
) as MultiLineString;

/**
 * The 50 states plus DC. geoAlbersUsa cannot project FIPS ids of 60 and above
 * (territories) and returns null for them, which becomes a NaN centroid downstream.
 * Use this rather than the raw collection for anything Albers-projected.
 */
const usStates: NamedFeature[] = (
  feature(us, us.objects.states) as FeatureCollection<Geometry, Named>
).features.filter((d) => Number(d.id) < 60);

const usStatesCollection: FeatureCollection<Geometry, Named> = {
  type: 'FeatureCollection',
  features: usStates
};

/**
 * FNV-1a over an id, run through the murmur3 finalizer. Two-character FIPS ids barely
 * differ, and without the finalizer they map to a near-constant. Returns [0, 1).
 * Charts use it to synthesize per-region values deterministically instead of fetching.
 */
function hashUnit(id: string, salt = 0): number {
  let h = 2166136261 ^ salt;
  for (let i = 0; i < id.length; i++) {
    h = Math.imul(h ^ id.charCodeAt(i), 16777619);
  }
  h ^= h >>> 16;
  h = Math.imul(h, 2246822507);
  h ^= h >>> 13;
  return (h >>> 0) / 4294967296;
}

/** The notebook's 960x500 frame, and its scale of 150 within that frame. */
const ASPECT = 500 / 960;
const SCALE_RATIO = 150 / 500;
const MAX_HEIGHT = 520;
/** Matches the notebook's tick(): 0.1 degrees of yaw and pitch per frame. */
const DEGREES_PER_FRAME = 0.1;
/** Below this the caption cannot fit on one line, so it is dropped. */
const CAPTION_MIN_WIDTH = 460;

const sphere: d3.GeoSphere = { type: 'Sphere' };
const graticule = d3.geoGraticule10();

const ARIA_LABEL =
  'World land in a conic equal-area projection, rotating continuously through arbitrary ' +
  'aspects. Geometry crossing the antimeridian is cut during projection, so it reappears at ' +
  'the opposite edge instead of streaking across the map.';

export default function AntimeridianCutting({ width }: { width: number }) {
  const height = Math.min(Math.round(width * ASPECT), MAX_HEIGHT);
  const [rotate, setRotate] = useState<[number, number]>([0, 0]);

  useEffect(() => {
    let frame = requestAnimationFrame(function tick() {
      setRotate(([lambda, phi]) => [
        (lambda + DEGREES_PER_FRAME) % 360,
        (phi + DEGREES_PER_FRAME) % 360
      ]);
      frame = requestAnimationFrame(tick);
    });
    return () => cancelAnimationFrame(frame);
  }, []);

  const paths = useMemo(() => {
    const projection = d3
      .geoConicEqualArea()
      .center([0, 33])
      .rotate(rotate)
      .scale(height * SCALE_RATIO)
      .translate([width / 2, height / 2])
      .precision(0.3);
    const path = d3.geoPath(projection);
    return {
      outline: path(sphere) ?? '',
      grid: path(graticule) ?? '',
      land: path(worldLand) ?? ''
    };
  }, [rotate, width, height]);

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label={ARIA_LABEL}
    >
      <path d={paths.grid} fill="none" stroke="var(--line)" strokeWidth={0.5} />
      {/* Stroking the land is what makes the cut legible: the straight segments hugging the
          outline are edges D3 introduced when it split a polygon at ±180° of rotated longitude. */}
      <path
        d={paths.land}
        fill="var(--accent)"
        fillOpacity={0.85}
        stroke="var(--text)"
        strokeWidth={0.5}
      />
      <path d={paths.outline} fill="none" stroke="var(--muted)" strokeWidth={1} />
      {width >= CAPTION_MIN_WIDTH && (
        <text x={8} y={height - 8} fill="var(--muted)" fontSize={11}>
          Cut along the antimeridian during projection, so any rotation is drawn without artifacts
        </text>
      )}
    </svg>
  );
}
