// Bar Chart — Basic, route: jsx
// Source: bar-chart_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from data ----
/** Relative frequency of letters in English text. */
const letterFrequency = [
  { letter: 'E', frequency: 0.1202 },
  { letter: 'T', frequency: 0.091 },
  { letter: 'A', frequency: 0.0812 },
  { letter: 'O', frequency: 0.0768 },
  { letter: 'I', frequency: 0.0731 },
  { letter: 'N', frequency: 0.0695 },
  { letter: 'S', frequency: 0.0628 },
  { letter: 'R', frequency: 0.0602 },
  { letter: 'H', frequency: 0.0592 },
  { letter: 'D', frequency: 0.0432 },
  { letter: 'L', frequency: 0.0398 },
  { letter: 'U', frequency: 0.0288 },
  { letter: 'C', frequency: 0.0271 },
  { letter: 'M', frequency: 0.0261 },
  { letter: 'F', frequency: 0.023 },
  { letter: 'Y', frequency: 0.0211 },
  { letter: 'W', frequency: 0.0209 },
  { letter: 'G', frequency: 0.0203 },
  { letter: 'P', frequency: 0.0182 },
  { letter: 'B', frequency: 0.0149 }
];

/** Deterministic synthetic series so hot reloads do not reshuffle the chart. */
const timeSeries = Array.from({ length: 120 }, (_, i) => ({
  date: new Date(2024, 0, 1 + i * 3),
  value: 100 + Math.sin(i / 7) * 22 + Math.sin(i / 23) * 38 + i * 0.45
}));

const MARGIN = { top: 16, right: 16, bottom: 36, left: 52 };

/** One bar per category, sized by its frequency. */
export type Data = { letter: string; frequency: number }[];

export default function BarChart({ data = letterFrequency, width }:
  { data?: Data; width: number }) {
  const height = Math.round(width * 0.5);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const x = useMemo(
    () =>
      d3
        .scaleBand()
        .domain(data.map((d) => d.letter))
        .range([0, innerWidth])
        .padding(0.15),
    [data, innerWidth]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([0, d3.max(data, (d) => d.frequency) ?? 0])
        .nice()
        .range([innerHeight, 0]),
    [data, innerHeight]
  );

  const xTicks: Tick[] = useMemo(
    () => x.domain().map((v) => ({ value: v, offset: (x(v) ?? 0) + x.bandwidth() / 2 })),
    [x]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(5).map((v) => ({ value: d3.format('.0%')(v), offset: y(v) })),
    [y]
  );

  if (width === 0) return null;

  return (
    <svg viewBox={`0 0 ${width} ${height}`} width="100%" height={height} role="img"
         aria-label="Bar chart of English letter frequency">
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />
        {data.map((d) => (
          <rect
            key={d.letter}
            x={x(d.letter)}
            y={y(d.frequency)}
            width={x.bandwidth()}
            height={innerHeight - y(d.frequency)}
            fill="var(--accent)"
          />
        ))}
      </g>
    </svg>
  );
}
