// Box Plot — Distribution, route: jsx
// Source: box-plot_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from boxPlot ----
// Seeded synthetic diamond carat/price pairs, standing in for the source
// notebook's diamonds.csv. Mulberry32 PRNG for determinism.
function mulberry32(seed: number) {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function randomNormal(rng: () => number, mean: number, stdDev: number) {
  const u1 = rng();
  const u2 = rng();
  const z = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
  return mean + z * stdDev;
}

const rng = mulberry32(20260813);

type Diamond = { carat: number; price: number };

// Carat skews toward small stones (power curve), price rises roughly with
// carat cubed plus noise, mirroring the shape of the real diamonds dataset.
const diamonds: Diamond[] = Array.from({ length: 2000 }, () => {
  const carat = Math.round((0.2 + Math.pow(rng(), 2.3) * 2.8) * 100) / 100;
  const basePrice = 300 + Math.pow(carat, 3) * 4200;
  const price = Math.max(300, Math.round(basePrice + randomNormal(rng, 0, basePrice * 0.25)));
  return { carat, price };
});

const MARGIN = { top: 16, right: 16, bottom: 36, left: 52 };

/** One observation per row: binned along carat, summarized as a box over price. */
export type Data = { carat: number; price: number }[];

type BinStats = {
  x0: number;
  x1: number;
  q1: number;
  q2: number;
  q3: number;
  r0: number;
  r1: number;
  outliers: Data;
};

// Deterministic pseudo-random offset for outlier jitter, standing in for the
// notebook's Math.random() (banned: nothing here may vary between renders).
function jitter(i: number) {
  const frac = Math.sin(i * 12.9898) * 43758.5453;
  return (frac - Math.floor(frac) - 0.5) * 4;
}

export default function BoxPlot({ data = diamonds, width }: { data?: Data; width: number }) {
  const height = Math.round(width * 0.62);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const thresholds = Math.max(4, Math.round(innerWidth / 40));

  const bins: BinStats[] = useMemo(() => {
    const raw = d3
      .bin<Data[number], number>()
      .thresholds(thresholds)
      .value((d) => d.carat)(data);

    return raw
      .filter((bin) => bin.length > 0)
      .map((bin) => {
        const sorted = [...bin].sort((a, b) => a.price - b.price);
        const values = sorted.map((d) => d.price);
        const min = values[0];
        const max = values[values.length - 1];
        const q1 = d3.quantile(values, 0.25) ?? min;
        const q2 = d3.quantile(values, 0.5) ?? min;
        const q3 = d3.quantile(values, 0.75) ?? max;
        const iqr = q3 - q1;
        const r0 = Math.max(min, q1 - iqr * 1.5);
        const r1 = Math.min(max, q3 + iqr * 1.5);
        return {
          x0: bin.x0 ?? 0,
          x1: bin.x1 ?? 0,
          q1,
          q2,
          q3,
          r0,
          r1,
          outliers: sorted.filter((d) => d.price < r0 || d.price > r1)
        };
      });
  }, [data, thresholds]);

  const x = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([d3.min(bins, (d) => d.x0) ?? 0, d3.max(bins, (d) => d.x1) ?? 1])
        .range([0, innerWidth]),
    [bins, innerWidth]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([d3.min(bins, (d) => d.r0) ?? 0, d3.max(bins, (d) => d.r1) ?? 1])
        .nice()
        .range([innerHeight, 0]),
    [bins, innerHeight]
  );

  const xTicks: Tick[] = useMemo(
    () => x.ticks(thresholds).map((v) => ({ value: d3.format('.1f')(v), offset: x(v) })),
    [x, thresholds]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(6).map((v) => ({ value: d3.format('~s')(v), offset: y(v) })),
    [y]
  );

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Box plot of diamond price distribution by carat"
    >
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />
        {bins.map((bin) => {
          const center = x((bin.x0 + bin.x1) / 2);
          const boxLeft = x(bin.x0) + 1;
          const boxRight = x(bin.x1);
          return (
            <g key={bin.x0}>
              <line
                x1={center}
                x2={center}
                y1={y(bin.r1)}
                y2={y(bin.r0)}
                stroke="var(--muted)"
              />
              <rect
                x={boxLeft}
                y={y(bin.q3)}
                width={Math.max(0, boxRight - boxLeft)}
                height={Math.max(0, y(bin.q1) - y(bin.q3))}
                fill="var(--panel)"
                stroke="var(--muted)"
              />
              <line
                x1={boxLeft}
                x2={boxRight}
                y1={y(bin.q2)}
                y2={y(bin.q2)}
                stroke="var(--accent)"
                strokeWidth={2}
              />
              {bin.outliers.map((d, i) => (
                <circle
                  key={`${bin.x0}-${d.carat}-${d.price}-${i}`}
                  cx={center + jitter(i)}
                  cy={y(d.price)}
                  r={2}
                  fill="var(--accent)"
                  fillOpacity={0.35}
                />
              ))}
            </g>
          );
        })}
      </g>
    </svg>
  );
}
