// Brushable Scatterplot — Interaction, route: ref
// Source: brushable-scatterplot
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useMemo, useRef } from 'react';
import * as d3 from 'd3';

// ---- inlined from scatterplot ----
type Car = { name: string; mpg: number; hp: number };

/** Motor Trend 1974: fuel efficiency (mpg) vs engine power (hp) for 32 cars. */
const cars: Car[] = [
  { name: 'Mazda RX4', mpg: 21, hp: 110 },
  { name: 'Mazda RX4 Wag', mpg: 21, hp: 110 },
  { name: 'Datsun 710', mpg: 22.8, hp: 93 },
  { name: 'Hornet 4 Drive', mpg: 21.4, hp: 110 },
  { name: 'Hornet Sportabout', mpg: 18.7, hp: 175 },
  { name: 'Valiant', mpg: 18.1, hp: 105 },
  { name: 'Duster 360', mpg: 14.3, hp: 245 },
  { name: 'Merc 240D', mpg: 24.4, hp: 62 },
  { name: 'Merc 230', mpg: 22.8, hp: 95 },
  { name: 'Merc 280', mpg: 19.2, hp: 123 },
  { name: 'Merc 280C', mpg: 17.8, hp: 123 },
  { name: 'Merc 450SE', mpg: 16.4, hp: 180 },
  { name: 'Merc 450SL', mpg: 17.3, hp: 180 },
  { name: 'Merc 450SLC', mpg: 15.2, hp: 180 },
  { name: 'Cadillac Fleetwood', mpg: 10.4, hp: 205 },
  { name: 'Lincoln Continental', mpg: 10.4, hp: 215 },
  { name: 'Chrysler Imperial', mpg: 14.7, hp: 230 },
  { name: 'Fiat 128', mpg: 32.4, hp: 66 },
  { name: 'Honda Civic', mpg: 30.4, hp: 52 },
  { name: 'Toyota Corolla', mpg: 33.9, hp: 65 },
  { name: 'Toyota Corona', mpg: 21.5, hp: 97 },
  { name: 'Dodge Challenger', mpg: 15.5, hp: 150 },
  { name: 'AMC Javelin', mpg: 15.2, hp: 150 },
  { name: 'Camaro Z28', mpg: 13.3, hp: 245 },
  { name: 'Pontiac Firebird', mpg: 19.2, hp: 175 },
  { name: 'Fiat X1-9', mpg: 27.3, hp: 66 },
  { name: 'Porsche 914-2', mpg: 26, hp: 91 },
  { name: 'Lotus Europa', mpg: 30.4, hp: 113 },
  { name: 'Ford Pantera L', mpg: 15.8, hp: 264 },
  { name: 'Ferrari Dino', mpg: 19.7, hp: 175 },
  { name: 'Maserati Bora', mpg: 15, hp: 335 },
  { name: 'Volvo 142E', mpg: 21.4, hp: 109 }
];

const MARGIN = { top: 24, right: 24, bottom: 34, left: 44 };

/** One dot per row, placed by its two measurements. */
export type Data = { mpg: number; hp: number }[];

export default function BrushableScatterplot({ data = cars, width }:
  { data?: Data; width: number }) {
  const svgRef = useRef<SVGSVGElement | null>(null);
  const height = Math.round(width * 0.55);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const x = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([0, d3.max(data, (d) => d.mpg) as number])
        .nice()
        .range([0, innerWidth]),
    [data, innerWidth]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([0, d3.max(data, (d) => d.hp) as number])
        .nice()
        .range([innerHeight, 0]),
    [data, innerHeight]
  );

  useEffect(() => {
    const node = svgRef.current;
    if (!node || innerWidth <= 0 || innerHeight <= 0) return;

    const svg = d3.select(node);
    svg.selectAll('*').remove();

    const root = svg.append('g').attr('transform', `translate(${MARGIN.left},${MARGIN.top})`);

    root
      .append('g')
      .attr('class', 'axis')
      .attr('transform', `translate(0,${innerHeight})`)
      .call(d3.axisBottom(x))
      .call((g) => g.select('.domain').remove())
      .call((g) =>
        g
          .append('text')
          .attr('x', innerWidth)
          .attr('y', -4)
          .attr('fill', 'var(--muted)')
          .attr('font-weight', 600)
          .attr('text-anchor', 'end')
          .text('Miles per gallon')
      );

    root
      .append('g')
      .attr('class', 'axis')
      .call(d3.axisLeft(y))
      .call((g) => g.select('.domain').remove())
      .call((g) =>
        g
          .select('.tick:last-of-type text')
          .clone()
          .attr('x', 4)
          .attr('text-anchor', 'start')
          .attr('font-weight', 600)
          .text('Horsepower')
      );

    const status = root
      .append('text')
      .attr('class', 'axis')
      .attr('y', -10)
      .text('Drag a rectangle to select cars.');

    const dot = root
      .append('g')
      .attr('fill', 'none')
      .attr('stroke', 'var(--accent)')
      .attr('stroke-width', 1.5)
      .selectAll('circle')
      .data(data)
      .join('circle')
      .attr('cx', (d) => x(d.mpg))
      .attr('cy', (d) => y(d.hp))
      .attr('r', 3);

    const brush = d3
      .brush()
      .extent([
        [0, 0],
        [innerWidth, innerHeight]
      ])
      .on('start brush end', (event: d3.D3BrushEvent<unknown>) => {
        const selection = event.selection as [[number, number], [number, number]] | null;
        if (selection) {
          const [[x0, y0], [x1, y1]] = selection;
          dot.attr('stroke', 'var(--muted)');
          const inside = dot.filter(
            (d) => x0 <= x(d.mpg) && x(d.mpg) < x1 && y0 <= y(d.hp) && y(d.hp) < y1
          );
          inside.attr('stroke', 'var(--accent)');
          status.text(`${inside.size()} of ${data.length} cars selected.`);
        } else {
          dot.attr('stroke', 'var(--accent)');
          status.text('Drag a rectangle to select cars.');
        }
      });

    root.append('g').call(brush);

    return () => {
      root.on('.brush', null);
      svg.selectAll('*').remove();
    };
  }, [data, innerWidth, innerHeight, x, y]);

  if (width === 0) return null;

  return (
    <svg
      ref={svgRef}
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      style={{ touchAction: 'none' }}
      role="img"
      aria-label="Brushable scatterplot of fuel efficiency against engine power for 32 cars; dragging a rectangle highlights the cars inside it."
    />
  );
}
