// Brushable Scatterplot Matrix — Multivariate, route: ref
// Source: brushable-scatterplot-matrix
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import * as d3 from 'd3';
import { useEffect, useMemo, useRef } from 'react';

// ---- inlined from splom ----
type PenguinSpecies = 'Adelie' | 'Chinstrap' | 'Gentoo';
type PenguinDimension = 'culmenLength' | 'culmenDepth' | 'flipperLength' | 'bodyMass';
type Penguin = Record<PenguinDimension, number> & { species: PenguinSpecies };

const penguinSpecies: PenguinSpecies[] = ['Adelie', 'Chinstrap', 'Gentoo'];

const penguinDimensions: { key: PenguinDimension; label: string }[] = [
  { key: 'culmenLength', label: 'Culmen length' },
  { key: 'culmenDepth', label: 'Culmen depth' },
  { key: 'flipperLength', label: 'Flipper length' },
  { key: 'bodyMass', label: 'Body mass' }
];

type Group = {
  species: PenguinSpecies;
  count: number;
  stats: Record<PenguinDimension, [mean: number, sd: number]>;
};

/** Per-species means and standard deviations of the Palmer Station penguin measurements. */
const GROUPS: Group[] = [
  {
    species: 'Adelie',
    count: 45,
    stats: {
      culmenLength: [38.8, 2.66],
      culmenDepth: [18.3, 1.22],
      flipperLength: [190.0, 6.5],
      bodyMass: [3700, 459]
    }
  },
  {
    species: 'Chinstrap',
    count: 30,
    stats: {
      culmenLength: [48.8, 3.34],
      culmenDepth: [18.4, 1.14],
      flipperLength: [195.8, 7.1],
      bodyMass: [3733, 384]
    }
  },
  {
    species: 'Gentoo',
    count: 45,
    stats: {
      culmenLength: [47.5, 3.08],
      culmenDepth: [15.0, 0.98],
      flipperLength: [217.2, 6.5],
      bodyMass: [5076, 504]
    }
  }
];

// Seeded so the matrix is byte-identical across reloads.
const normal = d3.randomNormal.source(d3.randomLcg(0.42))(0, 1);

/** Weights on a bird's shared size factor; the rest is independent noise. Keeps unit variance. */
const SIZE_LOADING: Record<PenguinDimension, number> = {
  culmenLength: 0.5,
  culmenDepth: 0.45,
  flipperLength: 0.8,
  bodyMass: 0.8
};

function draw(stats: Group['stats'], key: PenguinDimension, size: number): number {
  const [mean, sd] = stats[key];
  const loading = SIZE_LOADING[key];
  return mean + sd * (loading * size + Math.sqrt(1 - loading * loading) * normal());
}

const penguins: Penguin[] = GROUPS.flatMap(({ species, count, stats }) =>
  d3.range(count).map(() => {
    const size = normal();
    return {
      species,
      culmenLength: Math.round(draw(stats, 'culmenLength', size) * 10) / 10,
      culmenDepth: Math.round(draw(stats, 'culmenDepth', size) * 10) / 10,
      flipperLength: Math.round(draw(stats, 'flipperLength', size)),
      bodyMass: Math.round(draw(stats, 'bodyMass', size) / 25) * 25
    };
  })
);

const MARGIN = { top: 44, right: 12, bottom: 34, left: 48 };
const PADDING = 22;
const RADIUS = 2.6;

type Cell = [number, number];

const format = (v: number) => (Math.abs(v) >= 1000 ? d3.format('~s')(v) : String(v));

/** One row per observation, the numeric columns crossed into cells, and the classes to color by. */
export type Data = {
  rows: Penguin[];
  dimensions: { key: PenguinDimension; label: string }[];
  species: PenguinSpecies[];
};

const DEMO: Data = { rows: penguins, dimensions: penguinDimensions, species: penguinSpecies };

export default function BrushableScatterplotMatrix({ data = DEMO, width }:
  { data?: Data; width: number }) {
  const svgRef = useRef<SVGSVGElement | null>(null);
  const dimensions = data.dimensions;
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const size = innerWidth / dimensions.length;
  const height = innerWidth + MARGIN.top + MARGIN.bottom;

  // One horizontal scale per dimension, in cell-local coordinates, reused down its column.
  const xScales = useMemo(
    () =>
      dimensions.map((d) =>
        d3
          .scaleLinear()
          .domain(d3.extent(data.rows, (p) => p[d.key]) as [number, number])
          .nice()
          .range([PADDING / 2, size - PADDING / 2])
      ),
    [data, dimensions, size]
  );

  const yScales = useMemo(
    () => xScales.map((x) => x.copy().range([size - PADDING / 2, PADDING / 2])),
    [xScales, size]
  );

  const color = useMemo(
    () => d3.scaleOrdinal<string, string>().domain(data.species).range(d3.schemeObservable10),
    [data]
  );

  useEffect(() => {
    const node = svgRef.current;
    if (!node || innerWidth <= 0) return;

    const svg = d3.select(node);
    svg.selectAll('*').remove();

    const matrix = size * dimensions.length;
    const root = svg.append('g').attr('transform', `translate(${MARGIN.left},${MARGIN.top})`);

    const legend = root.append('g').attr('class', 'axis');
    data.species.forEach((species, i) => {
      const g = legend.append('g').attr('transform', `translate(${i * 110},-26)`);
      g.append('circle').attr('r', 4).attr('fill', color(species));
      g.append('text').attr('x', 9).attr('dy', '0.32em').text(species);
    });

    const status = root
      .append('text')
      .attr('class', 'axis')
      .attr('y', -8)
      .text('Drag inside any cell to highlight those penguins everywhere.');

    const drawAxes = (
      scales: d3.ScaleLinear<number, number>[],
      axis: (scale: d3.ScaleLinear<number, number>) => d3.Axis<d3.NumberValue>,
      place: (i: number) => string
    ) =>
      root
        .append('g')
        .attr('class', 'axis')
        .selectAll<SVGGElement, unknown>('g')
        .data(scales)
        .join('g')
        .attr('transform', (_, i) => place(i))
        .each(function (scale) {
          d3.select(this).call(axis(scale));
        })
        .call((g) => g.select('.domain').remove())
        .call((g) => g.selectAll('.tick line').attr('class', 'grid'));

    // Tick size spanning the whole matrix turns each axis into that column's or row's grid lines.
    const ticks = (a: d3.Axis<d3.NumberValue>) => a.ticks(3).tickFormat((v) => format(Number(v)));
    drawAxes(xScales, (s) => ticks(d3.axisBottom(s)).tickSize(matrix), (i) => `translate(${i * size},0)`);
    drawAxes(yScales, (s) => ticks(d3.axisLeft(s)).tickSize(-matrix), (j) => `translate(0,${j * size})`);

    const cell = root
      .append('g')
      .selectAll<SVGGElement, Cell>('g')
      .data(d3.cross(d3.range(dimensions.length), d3.range(dimensions.length)))
      .join('g')
      .attr('transform', ([i, j]) => `translate(${i * size},${j * size})`);

    cell
      .append('rect')
      .attr('fill', 'none')
      .attr('stroke', 'var(--line)')
      .attr('x', PADDING / 2)
      .attr('y', PADDING / 2)
      .attr('width', size - PADDING)
      .attr('height', size - PADDING);

    cell.each(function ([i, j]) {
      d3.select(this)
        .selectAll<SVGCircleElement, Penguin>('circle')
        .data(data.rows)
        .join('circle')
        .attr('cx', (d) => xScales[i](d[dimensions[i].key]))
        .attr('cy', (d) => yScales[j](d[dimensions[j].key]));
    });

    const circle = cell
      .selectAll<SVGCircleElement, Penguin>('circle')
      .attr('r', RADIUS)
      .attr('fill', (d) => color(d.species))
      .attr('fill-opacity', 0.7);

    const paint = (inside: ((d: Penguin) => boolean) | null) => {
      circle
        .attr('r', (d) => (inside && !inside(d) ? 1.4 : RADIUS))
        .attr('fill', (d) => (inside && !inside(d) ? 'var(--muted)' : color(d.species)))
        .attr('fill-opacity', (d) => (inside && !inside(d) ? 0.2 : 0.85));
      const count = inside ? data.rows.filter(inside).length : 0;
      status.text(
        inside
          ? `${count} of ${data.rows.length} penguins selected.`
          : 'Drag inside any cell to highlight those penguins everywhere.'
      );
    };

    let brushCell: SVGGElement | undefined;

    const brush = d3
      .brush<Cell>()
      .extent([
        [PADDING / 2, PADDING / 2],
        [size - PADDING / 2, size - PADDING / 2]
      ])
      .on('start', function () {
        // Only one cell owns a brush at a time; clear whichever held it before.
        if (brushCell && brushCell !== this) d3.select<SVGGElement, Cell>(brushCell).call(brush.move, null);
        brushCell = this;
      })
      .on('brush', (event: d3.D3BrushEvent<Cell>, [i, j]: Cell) => {
        if (!event.selection) return;
        const [[x0, y0], [x1, y1]] = event.selection as [[number, number], [number, number]];
        paint((d) => {
          const px = xScales[i](d[dimensions[i].key]);
          const py = yScales[j](d[dimensions[j].key]);
          return px >= x0 && px <= x1 && py >= y0 && py <= y1;
        });
      })
      .on('end', (event: d3.D3BrushEvent<Cell>) => {
        if (!event.selection) paint(null);
      });

    cell.call(brush);

    root
      .append('g')
      .attr('font-size', 11)
      .attr('font-weight', 600)
      .attr('fill', 'var(--text)')
      .attr('pointer-events', 'none')
      .selectAll('text')
      // ~6px per bold 11px character; drop the label rather than let it spill past its cell.
      .data(dimensions.filter((d) => d.label.length * 6 <= size - PADDING * 1.5))
      .join('text')
      .attr('x', (d) => dimensions.indexOf(d) * size + PADDING)
      .attr('y', (d) => dimensions.indexOf(d) * size + PADDING)
      .attr('dy', '0.71em')
      .text((d) => d.label);

    return () => {
      cell.on('.brush', null);
      svg.selectAll('*').remove();
    };
  }, [data, innerWidth, size, dimensions, xScales, yScales, color]);

  if (width === 0) return null;

  return (
    <svg
      ref={svgRef}
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      style={{ touchAction: 'none' }}
      role="img"
      aria-label="Brushable scatterplot matrix of four penguin body measurements colored by species; dragging a rectangle in one cell highlights the same penguins in every other cell. Synthetic data from a seeded generator matched to the Palmer Station penguin summary statistics, not the observations themselves."
    />
  );
}
