// Choropleth — Geo, route: jsx
// Source: choropleth_2
//
// Self-contained: every local import is inlined below. Requires only d3, geojson, react, topojson-client, topojson-specification, us-atlas, world-atlas.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { feature, mesh } from 'topojson-client';
import countries110m from 'world-atlas/countries-110m.json';
import statesUs from 'us-atlas/states-10m.json';
import type { GeometryCollection, Topology } from 'topojson-specification';
import type { Feature, FeatureCollection, Geometry, MultiLineString } from 'geojson';
import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from geo ----
// The atlases ship untyped JSON. One cast per topology at this boundary keeps every
// consumer strict, and converting here means each chart does not re-derive the same
// geometry at module load.

type Named = { name: string };
type NamedFeature = Feature<Geometry, Named>;

const world = countries110m as unknown as Topology<{
  countries: GeometryCollection<Named>;
  land: GeometryCollection;
}>;

const us = statesUs as unknown as Topology<{
  states: GeometryCollection<Named>;
  nation: GeometryCollection;
}>;

const worldCountries = feature(
  world,
  world.objects.countries
) as FeatureCollection<Geometry, Named>;

const worldLand = feature(world, world.objects.land) as FeatureCollection<Geometry>;

/** Shared borders only, so neighbouring outlines are stroked once instead of twice. */
const worldBorders = mesh(
  world,
  world.objects.countries,
  (a, b) => a !== b
) as MultiLineString;

const usNation = feature(us, us.objects.nation) as FeatureCollection<Geometry>;

const usStateBorders = mesh(
  us,
  us.objects.states,
  (a, b) => a !== b
) as MultiLineString;

/**
 * The 50 states plus DC. geoAlbersUsa cannot project FIPS ids of 60 and above
 * (territories) and returns null for them, which becomes a NaN centroid downstream.
 * Use this rather than the raw collection for anything Albers-projected.
 */
const usStates: NamedFeature[] = (
  feature(us, us.objects.states) as FeatureCollection<Geometry, Named>
).features.filter((d) => Number(d.id) < 60);

const usStatesCollection: FeatureCollection<Geometry, Named> = {
  type: 'FeatureCollection',
  features: usStates
};

/**
 * FNV-1a over an id, run through the murmur3 finalizer. Two-character FIPS ids barely
 * differ, and without the finalizer they map to a near-constant. Returns [0, 1).
 * Charts use it to synthesize per-region values deterministically instead of fetching.
 */
function hashUnit(id: string, salt = 0): number {
  let h = 2166136261 ^ salt;
  for (let i = 0; i < id.length; i++) {
    h = Math.imul(h ^ id.charCodeAt(i), 16777619);
  }
  h ^= h >>> 16;
  h = Math.imul(h, 2246822507);
  h ^= h >>> 13;
  return (h >>> 0) / 4294967296;
}

// geo.ts carries state-level geometry only, not counties, so this reworks the
// notebook's county unemployment map at the state grain it actually has on hand.
const MARGIN = { top: 48, right: 8, bottom: 20, left: 8 };
const LEGEND = { x: 14, y: 16, width: 240, height: 10 };
const DOMAIN: [number, number] = [1, 10];
const format = (d: number) => `${d}%`;

/** One rate per state FIPS id, and the value range the colour scale spans. The basemap is fixed. */
export type Data = { rates: Map<string, number>; domain: [number, number] };

// Synthesizes a plausible unemployment-style rate per state, deterministic across reloads.
const DEMO: Data = {
  rates: new Map<string, number>(
    usStatesCollection.features.map((d) => {
      const id = String(d.id);
      return [id, Math.round((DOMAIN[0] + hashUnit(id, 11) * (DOMAIN[1] - DOMAIN[0])) * 10) / 10];
    })
  ),
  domain: DOMAIN
};

export default function Choropleth({ data = DEMO, width }: { data?: Data; width: number }) {
  const { rates, domain } = data;
  const height = Math.round(width * 0.62);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const color = useMemo(() => d3.scaleQuantize<string>(domain, d3.schemeBlues[9]), [domain]);

  const path = useMemo(() => {
    const projection = d3.geoAlbersUsa().fitSize([innerWidth, innerHeight], usStatesCollection);
    return d3.geoPath(projection);
  }, [innerWidth, innerHeight]);

  const thresholds = color.thresholds();
  const legendScale = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([-1, color.range().length - 1])
        .range([LEGEND.x, LEGEND.x + LEGEND.width]),
    [color]
  );

  if (width === 0) return null;

  const showLegend = width >= LEGEND.width + 120;
  const swatchWidth = LEGEND.width / color.range().length;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Choropleth map of the United States shaded by unemployment rate per state"
    >
      {showLegend && (
        <>
          <text x={LEGEND.x} y={12} fill="var(--text)" fontSize={11} fontWeight={600}>
            Unemployment rate (%)
          </text>
          {color.range().map((c, i) => (
            <rect
              key={c}
              x={LEGEND.x + i * swatchWidth}
              y={LEGEND.y}
              width={swatchWidth + 0.5}
              height={LEGEND.height}
              fill={c}
            />
          ))}
          <g className="axis" transform={`translate(0,${LEGEND.y + LEGEND.height})`}>
            {thresholds.map((t, i) => (
              <g key={t} transform={`translate(${legendScale(i)},0)`}>
                <line y1={0} y2={5} />
                <text y={17} textAnchor="middle">
                  {format(Math.round(t))}
                </text>
              </g>
            ))}
          </g>
        </>
      )}

      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        {usStatesCollection.features.map((d) => {
          const shape = path(d);
          const rate = rates.get(String(d.id));
          if (!shape || rate === undefined) return null;
          return (
            <path key={String(d.id)} d={shape} fill={color(rate)}>
              <title>{`${d.properties.name}\n${format(rate)}`}</title>
            </path>
          );
        })}
        <path
          d={path(usStateBorders) ?? undefined}
          fill="none"
          stroke="var(--panel)"
          strokeWidth={0.75}
          strokeLinejoin="round"
        />
      </g>
    </svg>
  );
}
