// Chord Dependency Diagram — Network, route: jsx
// Source: chord-dependency-diagram_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from chordDependency ----
type DependencyLink = { source: string; target: string; value: number };

/**
 * Package-level imports in the Flare ActionScript visualization toolkit, restricted to
 * the 20 packages with the heaviest traffic. Self-links are intra-package imports.
 */
const flareImports: DependencyLink[] = [
  { source: 'analytics.cluster', target: 'animate', value: 2 },
  { source: 'analytics.cluster', target: 'vis.data', value: 8 },
  { source: 'analytics.cluster', target: 'analytics.cluster', value: 5 },
  { source: 'analytics.cluster', target: 'util', value: 3 },
  { source: 'analytics.cluster', target: 'vis.operator', value: 1 },
  { source: 'analytics.graph', target: 'animate', value: 5 },
  { source: 'analytics.graph', target: 'vis.data', value: 14 },
  { source: 'analytics.graph', target: 'util', value: 5 },
  { source: 'analytics.graph', target: 'vis.operator', value: 6 },
  { source: 'analytics.graph', target: 'analytics.graph', value: 1 },
  { source: 'analytics.graph', target: 'vis', value: 1 },
  { source: 'animate', target: 'animate', value: 30 },
  { source: 'animate', target: 'util', value: 9 },
  { source: 'animate', target: 'animate.interpolate', value: 1 },
  { source: 'animate.interpolate', target: 'util', value: 2 },
  { source: 'animate.interpolate', target: 'animate.interpolate', value: 16 },
  { source: 'data', target: 'data', value: 7 },
  { source: 'data', target: 'util', value: 1 },
  { source: 'data', target: 'data.converters', value: 2 },
  { source: 'data.converters', target: 'data.converters', value: 7 },
  { source: 'data.converters', target: 'data', value: 17 },
  { source: 'data.converters', target: 'util', value: 1 },
  { source: 'display', target: 'display', value: 3 },
  { source: 'display', target: 'util', value: 1 },
  { source: 'physics', target: 'physics', value: 22 },
  { source: 'query', target: 'query', value: 61 },
  { source: 'query', target: 'util', value: 6 },
  { source: 'query.methods', target: 'query.methods', value: 39 },
  { source: 'query.methods', target: 'query', value: 32 },
  { source: 'scale', target: 'scale', value: 19 },
  { source: 'scale', target: 'util', value: 14 },
  { source: 'util', target: 'util', value: 23 },
  { source: 'vis', target: 'animate', value: 3 },
  { source: 'vis', target: 'vis.operator', value: 2 },
  { source: 'vis', target: 'vis.data', value: 2 },
  { source: 'vis', target: 'vis.axis', value: 2 },
  { source: 'vis', target: 'util', value: 1 },
  { source: 'vis', target: 'vis.controls', value: 1 },
  { source: 'vis.axis', target: 'animate', value: 3 },
  { source: 'vis.axis', target: 'vis', value: 2 },
  { source: 'vis.axis', target: 'scale', value: 4 },
  { source: 'vis.axis', target: 'util', value: 3 },
  { source: 'vis.axis', target: 'display', value: 5 },
  { source: 'vis.axis', target: 'vis.axis', value: 7 },
  { source: 'vis.controls', target: 'vis.controls', value: 12 },
  { source: 'vis.controls', target: 'vis', value: 3 },
  { source: 'vis.controls', target: 'vis.operator.layout', value: 1 },
  { source: 'vis.controls', target: 'util', value: 3 },
  { source: 'vis.controls', target: 'vis.data', value: 2 },
  { source: 'vis.controls', target: 'animate', value: 2 },
  { source: 'vis.controls', target: 'display', value: 1 },
  { source: 'vis.data', target: 'vis.data', value: 26 },
  { source: 'vis.data', target: 'util', value: 17 },
  { source: 'vis.data', target: 'data', value: 3 },
  { source: 'vis.data', target: 'animate', value: 2 },
  { source: 'vis.data', target: 'display', value: 1 },
  { source: 'vis.data', target: 'scale', value: 9 },
  { source: 'vis.legend', target: 'animate', value: 1 },
  { source: 'vis.legend', target: 'vis.data', value: 1 },
  { source: 'vis.legend', target: 'scale', value: 4 },
  { source: 'vis.legend', target: 'vis.legend', value: 4 },
  { source: 'vis.legend', target: 'display', value: 6 },
  { source: 'vis.legend', target: 'util', value: 6 },
  { source: 'vis.operator', target: 'animate', value: 7 },
  { source: 'vis.operator', target: 'vis', value: 3 },
  { source: 'vis.operator', target: 'vis.operator', value: 11 },
  { source: 'vis.operator', target: 'util', value: 5 },
  { source: 'vis.operator', target: 'vis.data', value: 1 },
  { source: 'vis.operator.encoder', target: 'animate', value: 3 },
  { source: 'vis.operator.encoder', target: 'scale', value: 3 },
  { source: 'vis.operator.encoder', target: 'vis.operator.encoder', value: 4 },
  { source: 'vis.operator.encoder', target: 'vis.data', value: 8 },
  { source: 'vis.operator.encoder', target: 'vis.operator', value: 2 },
  { source: 'vis.operator.encoder', target: 'util', value: 3 },
  { source: 'vis.operator.layout', target: 'scale', value: 6 },
  { source: 'vis.operator.layout', target: 'vis.data', value: 34 },
  { source: 'vis.operator.layout', target: 'vis.axis', value: 4 },
  { source: 'vis.operator.layout', target: 'util', value: 20 },
  { source: 'vis.operator.layout', target: 'vis.operator.layout', value: 14 },
  { source: 'vis.operator.layout', target: 'animate', value: 6 },
  { source: 'vis.operator.layout', target: 'vis.operator', value: 2 },
  { source: 'vis.operator.layout', target: 'physics', value: 3 },
  { source: 'vis.operator.layout', target: 'vis', value: 1 }
];

/** Directed imports: `value` imports flow from the `source` package to the `target` one. */
export type Data = { source: string; target: string; value: number }[];

const MAX_SIZE = 620;
/** Longest package name is 20 characters, at roughly 0.6 em per character in this sans. */
const LABEL_CHARS = 20;
const EM_PER_CHAR = 0.6;
const MIN_SIZE_FOR_LABELS = 380;

export default function ChordDependencyDiagram({
  data = flareImports,
  width
}: {
  data?: Data;
  width: number;
}) {
  const size = Math.min(width, MAX_SIZE);
  const height = size;

  const fontSize = Math.max(8, Math.min(11, size / 58));
  const showLabels = size >= MIN_SIZE_FOR_LABELS;
  const gutter = showLabels ? fontSize * LABEL_CHARS * EM_PER_CHAR + 12 : 14;
  const innerRadius = Math.max(20, size / 2 - gutter);
  const outerRadius = innerRadius + 10;

  const { names, matrix } = useMemo(() => {
    const sorted = d3.sort(d3.union(data.map((d) => d.source), data.map((d) => d.target)));
    const index = new Map(sorted.map((name, i) => [name, i]));
    const dense = sorted.map(() => new Array<number>(sorted.length).fill(0));
    for (const { source, target, value } of data) {
      dense[index.get(source) ?? 0][index.get(target) ?? 0] += value;
    }
    return { names: sorted, matrix: dense };
  }, [data]);

  const chords = useMemo(
    () =>
      d3
        .chordDirected()
        .padAngle(10 / innerRadius)
        .sortSubgroups(d3.descending)
        .sortChords(d3.descending)(matrix),
    [matrix, innerRadius]
  );

  const arc = useMemo(
    () => d3.arc<d3.ChordGroup>().innerRadius(innerRadius).outerRadius(outerRadius),
    [innerRadius, outerRadius]
  );

  const ribbon = useMemo(
    () =>
      d3
        .ribbonArrow<d3.Chord, d3.ChordSubgroup>()
        .radius(innerRadius - 1)
        .padAngle(1 / innerRadius),
    [innerRadius]
  );

  const colors = useMemo(
    () => d3.quantize(d3.interpolateRainbow, names.length),
    [names.length]
  );

  /** Outgoing and incoming import counts per package, for the arc tooltips. */
  const flow = useMemo(
    () =>
      names.map((_, i) => ({
        out: d3.sum(chords, (c) => (c.source.index === i ? c.source.value : 0)),
        in: d3.sum(chords, (c) => (c.target.index === i ? c.source.value : 0))
      })),
    [names, chords]
  );

  if (width === 0) return null;

  return (
    <svg
      viewBox={`${-size / 2} ${-height / 2} ${size} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Chord dependency diagram of imports between Flare toolkit packages"
    >
      <g fillOpacity={0.7}>
        {chords.map((c) => (
          <path
            key={`${c.source.index}-${c.target.index}`}
            d={ribbon(c) ?? undefined}
            fill={colors[c.source.index]}
          >
            <title>{`${names[c.source.index]} → ${names[c.target.index]}: ${c.source.value}`}</title>
          </path>
        ))}
      </g>
      <g>
        {chords.groups.map((g) => (
          <path key={g.index} d={arc(g) ?? undefined} fill={colors[g.index]}>
            <title>{`${names[g.index]}\n${flow[g.index].out} outgoing →\n${flow[g.index].in} incoming ←`}</title>
          </path>
        ))}
      </g>
      {showLabels && (
        <g fontSize={fontSize} fill="var(--text)">
          {chords.groups.map((g) => {
            const angle = (g.startAngle + g.endAngle) / 2;
            // A label needs about one font-size of arc to sit on without touching its neighbour.
            if ((g.endAngle - g.startAngle) * outerRadius < fontSize) return null;
            const flip = angle > Math.PI;
            return (
              <text
                key={g.index}
                dy="0.35em"
                textAnchor={flip ? 'end' : 'start'}
                transform={`rotate(${(angle * 180) / Math.PI - 90}) translate(${outerRadius + 5})${
                  flip ? ' rotate(180)' : ''
                }`}
              >
                {names[g.index]}
              </text>
            );
          })}
        </g>
      )}
    </svg>
  );
}
