// Color Legend — Encoding, route: jsx
// Source: color-legend
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo, type ReactNode } from 'react';
import * as d3 from 'd3';

const MARGIN = { top: 10, right: 18, bottom: 10, left: 18 };
const PANEL_HEIGHT = 76;
const BAND_Y = 24;
const BAND_HEIGHT = 22;

// Gradient ids are document-global, so they carry the chart id as a prefix.
const SEQUENTIAL_ID = 'color-legend-sequential-ramp';
const DIVERGING_ID = 'color-legend-diverging-ramp';

const STOP_COUNT = 33;
const THRESHOLDS = [2.5, 3.1, 3.5, 3.9, 6, 7, 8, 9.5];
const AGE_GROUPS = ['<10', '10-19', '20-29', '30-39', '40-49', '50-59', '60-69', '70-79', '≥80'];

type Tick = { value: string; offset: number };

/** Sample a continuous scale across its own domain so a non-linear scale keeps its shape. */
function rampStops(color: (value: number) => string, lo: number, hi: number) {
  return d3.range(STOP_COUNT).map((i) => {
    const t = i / (STOP_COUNT - 1);
    return { offset: t, color: color(lo + t * (hi - lo)) };
  });
}

/** Rule 7: a label wider than its slot is dropped rather than allowed to overlap its neighbour. */
function fits(value: string, slot: number) {
  return value.length * 6.4 + 6 <= slot;
}

function Panel({
  title,
  y,
  ticks,
  tickLine = true,
  children
}: {
  title: string;
  y: number;
  ticks: Tick[];
  tickLine?: boolean;
  children: ReactNode;
}) {
  return (
    <g transform={`translate(0,${y})`}>
      <text y={12} fill="var(--text)" fontSize={12} fontWeight={600}>
        {title}
      </text>
      <g transform={`translate(0,${BAND_Y})`}>{children}</g>
      <g className="axis" transform={`translate(0,${BAND_Y + BAND_HEIGHT})`}>
        {ticks.map(({ value, offset }) => (
          <g key={value} transform={`translate(${offset},0)`}>
            {tickLine && <line y1={0} y2={5} />}
            <text y={17} textAnchor="middle">
              {value}
            </text>
          </g>
        ))}
      </g>
    </g>
  );
}

export default function ColorLegend({ width }: { width: number }) {
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const height = MARGIN.top + PANEL_HEIGHT * 4 + MARGIN.bottom;

  const sequentialStops = useMemo(() => {
    const color = d3.scaleSequential(d3.interpolateViridis).domain([0, 100]);
    return rampStops(color, 0, 100);
  }, []);

  const divergingStops = useMemo(() => {
    const color = d3.scaleDiverging(d3.interpolatePiYG).domain([-0.1, 0, 0.1]);
    return rampStops(color, -0.1, 0.1);
  }, []);

  const sequentialTicks: Tick[] = useMemo(() => {
    const x = d3.scaleLinear().domain([0, 100]).range([0, innerWidth]);
    return x.ticks(6).map((v) => ({ value: `${v}`, offset: x(v) }));
  }, [innerWidth]);

  const divergingTicks: Tick[] = useMemo(() => {
    const x = d3.scaleLinear().domain([-0.1, 0.1]).range([0, innerWidth]);
    const format = d3.format('+.0%');
    return x.ticks(6).map((v) => ({ value: format(v), offset: x(v) }));
  }, [innerWidth]);

  // Threshold: n breaks make n + 1 equal blocks, and the labels sit on the block boundaries.
  const blockWidth = innerWidth / (THRESHOLDS.length + 1);

  const thresholdTicks: Tick[] = useMemo(
    () =>
      THRESHOLDS.map((v, i) => ({ value: `${v}`, offset: (i + 1) * blockWidth })).filter((t) =>
        fits(t.value, blockWidth)
      ),
    [blockWidth]
  );

  const ordinal = useMemo(
    () =>
      d3
        .scaleBand<string>()
        .domain(AGE_GROUPS)
        .range([0, innerWidth])
        .paddingInner(0.06),
    [innerWidth]
  );

  const ordinalTicks: Tick[] = useMemo(
    () =>
      AGE_GROUPS.map((v) => ({ value: v, offset: (ordinal(v) ?? 0) + ordinal.bandwidth() / 2 })).filter(
        (t) => fits(t.value, ordinal.step())
      ),
    [ordinal]
  );

  if (width === 0) return null;

  return (
    <svg viewBox={`0 0 ${width} ${height}`} width="100%" height={height} role="img"
         aria-label="Catalogue of color legends: continuous sequential, continuous diverging, quantized threshold, and ordinal swatches">
      <defs>
        <linearGradient id={SEQUENTIAL_ID} x1="0%" x2="100%" y1="0%" y2="0%">
          {sequentialStops.map((s) => (
            <stop key={s.offset} offset={s.offset} stopColor={s.color} />
          ))}
        </linearGradient>
        <linearGradient id={DIVERGING_ID} x1="0%" x2="100%" y1="0%" y2="0%">
          {divergingStops.map((s) => (
            <stop key={s.offset} offset={s.offset} stopColor={s.color} />
          ))}
        </linearGradient>
      </defs>
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <Panel title="Sequential: Temperature (°F)" y={0} ticks={sequentialTicks}>
          <rect width={innerWidth} height={BAND_HEIGHT} fill={`url(#${SEQUENTIAL_ID})`} />
        </Panel>

        <Panel title="Diverging: Daily change" y={PANEL_HEIGHT} ticks={divergingTicks}>
          <rect width={innerWidth} height={BAND_HEIGHT} fill={`url(#${DIVERGING_ID})`} />
        </Panel>

        <Panel title="Threshold: Unemployment rate (%)" y={PANEL_HEIGHT * 2} ticks={thresholdTicks}>
          {d3.schemeRdBu[9].map((fill, i) => (
            <rect key={fill} x={i * blockWidth} width={blockWidth} height={BAND_HEIGHT} fill={fill} />
          ))}
        </Panel>

        <Panel title="Ordinal: Age (years)" y={PANEL_HEIGHT * 3} ticks={ordinalTicks} tickLine={false}>
          {AGE_GROUPS.map((group, i) => (
            <rect key={group} x={ordinal(group) ?? 0} width={ordinal.bandwidth()} height={BAND_HEIGHT}
                  fill={d3.schemeSpectral[9][i]} />
          ))}
        </Panel>
      </g>
    </svg>
  );
}
