// Connected Scatterplot — Basic, route: jsx
// Source: connected-scatterplot_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from connectedScatterplot ----
type DrivingYear = { year: number; miles: number; gas: number };

/** US driving: miles per person vs inflation-adjusted gas price, 1956-2010 (Hannah Fairfield, NYT). */
const driving: DrivingYear[] = [
  { year: 1956, miles: 3683.6965, gas: 2.3829 },
  { year: 1957, miles: 3722.7648, gas: 2.4026 },
  { year: 1958, miles: 3776.8595, gas: 2.2539 },
  { year: 1959, miles: 3912.0962, gas: 2.3079 },
  { year: 1960, miles: 3942.1488, gas: 2.2658 },
  { year: 1961, miles: 3984.2224, gas: 2.2526 },
  { year: 1962, miles: 4089.4064, gas: 2.2158 },
  { year: 1963, miles: 4230.6536, gas: 2.1237 },
  { year: 1964, miles: 4383.9219, gas: 2.1039 },
  { year: 1965, miles: 4546.2059, gas: 2.1368 },
  { year: 1966, miles: 4681.4425, gas: 2.1421 },
  { year: 1967, miles: 4837.716, gas: 2.1408 },
  { year: 1968, miles: 5048.0841, gas: 2.1263 },
  { year: 1969, miles: 5216.3787, gas: 2.0737 },
  { year: 1970, miles: 5384.6732, gas: 2.0118 },
  { year: 1971, miles: 5652.1412, gas: 1.9316 },
  { year: 1972, miles: 5979.7145, gas: 1.8737 },
  { year: 1973, miles: 6160.0301, gas: 1.9026 },
  { year: 1974, miles: 5946.6566, gas: 2.3447 },
  { year: 1975, miles: 6117.9564, gas: 2.3079 },
  { year: 1976, miles: 6400.4508, gas: 2.3237 },
  { year: 1977, miles: 6634.861, gas: 2.3592 },
  { year: 1978, miles: 6890.308, gas: 2.2288 },
  { year: 1979, miles: 6755.0714, gas: 2.6829 },
  { year: 1980, miles: 6670.9241, gas: 3.2974 },
  { year: 1981, miles: 6743.0503, gas: 3.2961 },
  { year: 1982, miles: 6836.2134, gas: 2.9197 },
  { year: 1983, miles: 6938.3921, gas: 2.6566 },
  { year: 1984, miles: 7127.7235, gas: 2.475 },
  { year: 1985, miles: 7326.0706, gas: 2.3618 },
  { year: 1986, miles: 7554.4703, gas: 1.7605 },
  { year: 1987, miles: 7776.8595, gas: 1.7553 },
  { year: 1988, miles: 8089.4064, gas: 1.6842 },
  { year: 1989, miles: 8395.9428, gas: 1.7473 },
  { year: 1990, miles: 8537.1901, gas: 1.8763 },
  { year: 1991, miles: 8528.1743, gas: 1.7776 },
  { year: 1992, miles: 8675.432, gas: 1.6855 },
  { year: 1993, miles: 8843.7265, gas: 1.5974 },
  { year: 1994, miles: 8906.837, gas: 1.5842 },
  { year: 1995, miles: 9144.2524, gas: 1.5987 },
  { year: 1996, miles: 9183.3208, gas: 1.6737 },
  { year: 1997, miles: 9405.71, gas: 1.6461 },
  { year: 1998, miles: 9577.0098, gas: 1.3881 },
  { year: 1999, miles: 9688.2044, gas: 1.4987 },
  { year: 2000, miles: 9706.2359, gas: 1.8947 },
  { year: 2001, miles: 9685.1991, gas: 1.7658 },
  { year: 2002, miles: 9802.4042, gas: 1.6381 },
  { year: 2003, miles: 9853.4936, gas: 1.8592 },
  { year: 2004, miles: 9991.7355, gas: 2.1421 },
  { year: 2005, miles: 10054.846, gas: 2.5329 },
  { year: 2006, miles: 10030.8039, gas: 2.7934 },
  { year: 2007, miles: 10012.7724, gas: 2.9487 },
  { year: 2008, miles: 9871.5252, gas: 3.3066 },
  { year: 2009, miles: 9652.1412, gas: 2.3776 },
  { year: 2010, miles: 9592.0361, gas: 2.6066 },
];

/** One row per year, in the order the connecting line should visit them. */
export type Data = { year: number; miles: number; gas: number }[];

const MARGIN = { top: 22, right: 28, bottom: 36, left: 56 };
const LABEL_GAP = 26;

type Point = { year: number; x: number; y: number };
type Side = 'top' | 'right' | 'bottom' | 'left';
type Label = Point & { side: Side };

const ANCHOR: Record<Side, { dy: string; dx: string; textAnchor: 'start' | 'middle' | 'end' }> = {
  top: { dy: '-0.7em', dx: '0', textAnchor: 'middle' },
  right: { dy: '0.32em', dx: '0.5em', textAnchor: 'start' },
  bottom: { dy: '1.4em', dx: '0', textAnchor: 'middle' },
  left: { dy: '0.32em', dx: '-0.5em', textAnchor: 'end' }
};

function unitAway(from: Point | undefined, to: Point): [number, number] {
  if (!from) return [0, 0];
  const dx = to.x - from.x;
  const dy = to.y - from.y;
  const length = Math.hypot(dx, dy) || 1;
  return [dx / length, dy / length];
}

/** Anchor on the outside of the turn: the bisector pointing away from both neighbours. */
function labelSide(previous: Point | undefined, current: Point, next: Point | undefined): Side {
  const [ax, ay] = unitAway(previous, current);
  const [bx, by] = unitAway(next, current);
  let vx = ax + bx;
  let vy = ay + by;
  if (Math.hypot(vx, vy) < 0.35) {
    // Near-collinear, so the turn has no outside: use the upward normal to the travel direction.
    const tx = (next?.x ?? current.x) - (previous?.x ?? current.x);
    const ty = (next?.y ?? current.y) - (previous?.y ?? current.y);
    vx = tx > 0 ? ty : -ty;
    vy = tx > 0 ? -tx : tx;
  }
  return Math.abs(vx) > Math.abs(vy) ? (vx > 0 ? 'right' : 'left') : (vy > 0 ? 'bottom' : 'top');
}

export default function ConnectedScatterplot({
  data = driving,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.round(width * 0.62);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const x = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain(d3.extent(data, (d) => d.miles) as [number, number])
        .nice()
        .range([0, innerWidth]),
    [data, innerWidth]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain(d3.extent(data, (d) => d.gas) as [number, number])
        .nice()
        .range([innerHeight, 0]),
    [data, innerHeight]
  );

  const points: Point[] = useMemo(
    () => data.map((d) => ({ year: d.year, x: x(d.miles), y: y(d.gas) })),
    [data, x, y]
  );

  const path = useMemo(
    () =>
      d3
        .line<Point>()
        .x((d) => d.x)
        .y((d) => d.y)
        .curve(d3.curveCatmullRom)(points) ?? '',
    [points]
  );

  // Label every fifth year plus both endpoints, dropping any that would crowd one already kept.
  const labels: Label[] = useMemo(() => {
    const kept: Label[] = [];
    points.forEach((point, i) => {
      const isMilestone = point.year % 5 === 0 || i === 0 || i === points.length - 1;
      if (!isMilestone) return;
      if (kept.some((k) => Math.hypot(k.x - point.x, k.y - point.y) < LABEL_GAP)) return;
      kept.push({ ...point, side: labelSide(points[i - 1], point, points[i + 1]) });
    });
    return kept;
  }, [points]);

  const xTicks: Tick[] = useMemo(
    () => x.ticks(innerWidth / 90).map((v) => ({ value: d3.format(',')(v), offset: x(v) })),
    [x, innerWidth]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(5).map((v) => ({ value: d3.format('$.2f')(v), offset: y(v) })),
    [y]
  );

  if (width === 0) return null;

  return (
    <svg viewBox={`0 0 ${width} ${height}`} width="100%" height={height} role="img"
         aria-label="Connected scatterplot of US miles driven per person against the price of gas, 1956 to 2010">
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />
        <path d={path} fill="none" stroke="var(--accent)" strokeWidth={2.5}
              strokeLinejoin="round" strokeLinecap="round" />
        {points.map((p) => (
          <circle key={p.year} cx={p.x} cy={p.y} r={3} fill="var(--bg)"
                  stroke="var(--accent)" strokeWidth={1.75} />
        ))}
        <g fontSize={10} fill="var(--text)" stroke="var(--bg)" strokeWidth={3} paintOrder="stroke">
          {labels.map((l) => (
            <text key={l.year} x={l.x} y={l.y} dx={ANCHOR[l.side].dx} dy={ANCHOR[l.side].dy}
                  textAnchor={ANCHOR[l.side].textAnchor}>
              {l.year}
            </text>
          ))}
        </g>
        <text x={innerWidth} y={innerHeight - 6} textAnchor="end" fontSize={11}
              fontWeight={600} fill="var(--muted)">
          Miles per person per year
        </text>
        <text x={4} y={-8} fontSize={11} fontWeight={600} fill="var(--muted)">
          Cost per gallon
        </text>
      </g>
    </svg>
  );
}
