// Consistent Hashing — Algorithms, route: jsx
// Source: original:essay/consistent-hashing
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useState } from 'react';
import * as d3 from 'd3';

// ---- inlined from consistenthash ----
/**
 * Consistent hashing on a ring: 60 keys at seeded hash angles, a scripted sequence of node
 * joins and leaves, and per-event ownership plus exactly which keys moved.
 */

const KEY_COUNT = 60;
const SEED = 20260823;

/** mulberry32: a fixed seed keeps every ring identical across reloads. */
function seededRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const random = seededRandom(SEED);

/** Hash angle per key, degrees clockwise from the top of the ring. */
const keyAngles: number[] = Array.from({ length: KEY_COUNT }, () => random() * 360);

/** Every node that ever participates; joins and leaves pick from this pool. */
const NODE_NAMES = ['A', 'B', 'C', 'D', 'E', 'F'] as const;
const nodeAngles: number[] = NODE_NAMES.map(() => random() * 360);

interface HashEpoch {
  label: string;
  joined: string | null;
  left: string | null;
  /** Indices into NODE_NAMES, the nodes present in this epoch. */
  nodes: number[];
  /** Per key, the owning node as an index into NODE_NAMES. */
  owner: number[];
  /** Keys whose owner changed at this event, with the previous owner for the arc. */
  moved: { key: number; from: number; to: number }[];
}

/** First node clockwise from the key's angle owns it. */
function assign(present: number[]): number[] {
  return keyAngles.map((angle) => {
    let best = -1;
    let bestGap = Infinity;
    for (const n of present) {
      const gap = (nodeAngles[n] - angle + 360) % 360;
      if (gap < bestGap) {
        bestGap = gap;
        best = n;
      }
    }
    return best;
  });
}

/** Ends on a join, so the closing frame's counter makes the almost-nothing-moves argument. */
const SCRIPT: { label: string; joined?: string; left?: string }[] = [
  { label: '4 nodes serve 60 keys' },
  { label: 'E joins', joined: 'E' },
  { label: 'B leaves', left: 'B' },
  { label: 'F joins', joined: 'F' }
];

const epochs: HashEpoch[] = [];
{
  let present = [0, 1, 2, 3];
  let owner = assign(present);
  epochs.push({ label: SCRIPT[0].label, joined: null, left: null, nodes: present, owner, moved: [] });
  for (const event of SCRIPT.slice(1)) {
    if (event.joined) present = [...present, NODE_NAMES.findIndex((n) => n === event.joined)];
    if (event.left) present = present.filter((n) => NODE_NAMES[n] !== event.left);
    const next = assign(present);
    const moved = owner
      .map((from, key) => ({ key, from, to: next[key] }))
      .filter(({ from, to }) => from !== to);
    epochs.push({
      label: event.label,
      joined: event.joined ?? null,
      left: event.left ?? null,
      nodes: present,
      owner: next,
      moved
    });
    owner = next;
  }
}

const TICK_MS = 60;
const EPOCH_TICKS = 55;
const HOLD_TICKS = 30;
const FLASH_PHASE = 0.55;
const FLASH = '#e0538a';
const END = epochs.length * EPOCH_TICKS + HOLD_TICKS;

const NODE_COLORS = d3.schemeObservable10;

export default function ConsistentHashing({ width }: { width: number }) {
  const w = Math.max(1, width);
  const R = w * 0.29;
  const cx = w / 2;
  const cy = R + 30;
  const height = Math.round(2 * R + 84);
  const keyR = Math.max(2.5, w * 0.006);
  const nodeR = Math.max(6, w * 0.014);

  // The SSR frame is the settled final ring; the effect rewinds and replays the events.
  const [step, setStep] = useState(epochs.length * EPOCH_TICKS);

  useEffect(() => {
    setStep(0);
    const id = window.setInterval(() => setStep((s) => (s >= END ? 0 : s + 1)), TICK_MS);
    return () => window.clearInterval(id);
  }, []);

  const epochIndex = Math.min(epochs.length - 1, Math.floor(step / EPOCH_TICKS));
  const t = Math.min(1, (step - epochIndex * EPOCH_TICKS) / EPOCH_TICKS);
  const epoch = epochs[epochIndex];
  const flashing = epochIndex > 0 && t < FLASH_PHASE;
  const flashOpacity = flashing ? 1 - t / FLASH_PHASE : 0;

  const point = (angle: number, radius: number): [number, number] => {
    const rad = (angle * Math.PI) / 180;
    return [cx + radius * Math.sin(rad), cy - radius * Math.cos(rad)];
  };

  if (width === 0) return null;

  /** Arcs from each moved key to its new owner, bowing through the ring's interior. */
  const arcs = !flashing
    ? []
    : epoch.moved.map(({ key, to }) => {
        const from = keyAngles[key];
        const gap = (nodeAngles[to] - from + 360) % 360;
        const [x0, y0] = point(from, R);
        const [x1, y1] = point(from + gap / 2, R * 0.45);
        const [x2, y2] = point(nodeAngles[to], R);
        return `M${x0.toFixed(1)},${y0.toFixed(1)}Q${x1.toFixed(1)},${y1.toFixed(1)} ${x2.toFixed(1)},${y2.toFixed(1)}`;
      });

  const movedNow = new Set(flashing ? epoch.moved.map((m) => m.key) : []);
  const leaving =
    epoch.left !== null && flashing ? NODE_NAMES.findIndex((n) => n === epoch.left) : -1;

  return (
    <svg
      viewBox={`0 0 ${w} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Consistent hashing on a ring of 60 keys: as nodes join and leave, only the keys in the affected arc flash and hand over to a new owner, while the unmoved majority keeps its color — the moved-versus-total counter is the argument"
    >
      <circle cx={cx} cy={cy} r={R} fill="none" stroke="var(--line)" strokeWidth={1.2} />
      {arcs.map((d, i) => (
        <path key={i} d={d} fill="none" stroke={FLASH} strokeWidth={1.2} opacity={flashOpacity * 0.7} />
      ))}
      {keyAngles.map((angle, key) => {
        const [x, y] = point(angle, R);
        return (
          <g key={key}>
            {movedNow.has(key) && (
              <circle cx={x} cy={y} r={keyR * 2.4} fill={FLASH} opacity={flashOpacity * 0.6} />
            )}
            <circle cx={x} cy={y} r={keyR} fill={NODE_COLORS[epoch.owner[key]]} />
          </g>
        );
      })}
      {leaving >= 0 &&
        (() => {
          const [x, y] = point(nodeAngles[leaving], R);
          return (
            <circle
              cx={x}
              cy={y}
              r={nodeR}
              fill="none"
              stroke={NODE_COLORS[leaving]}
              strokeWidth={1.5}
              opacity={flashOpacity * 0.6}
            />
          );
        })()}
      {epoch.nodes.map((n) => {
        const [x, y] = point(nodeAngles[n], R);
        const [lx, ly] = point(nodeAngles[n], R + nodeR + 12);
        const justJoined = flashing && epoch.joined === NODE_NAMES[n];
        return (
          <g key={n}>
            <circle
              cx={x}
              cy={y}
              r={nodeR}
              fill={NODE_COLORS[n]}
              stroke={justJoined ? FLASH : 'var(--bg)'}
              strokeWidth={justJoined ? 2.5 : 1.5}
            />
            <text
              x={lx}
              y={ly + 4}
              textAnchor="middle"
              fontSize={12}
              fontWeight={600}
              fill="var(--text)"
            >
              {NODE_NAMES[n]}
            </text>
          </g>
        );
      })}
      <text x={cx} y={cy - 6} textAnchor="middle" fill="var(--text)" fontSize={13} fontWeight={600}>
        {epoch.label}
      </text>
      <text x={cx} y={cy + 12} textAnchor="middle" fill="var(--muted)" fontSize={11}>
        {epochIndex === 0
          ? 'each key belongs to the next node clockwise'
          : `${epoch.moved.length} of ${KEY_COUNT} keys moved`}
      </text>
    </svg>
  );
}
