// ECDF — Distribution, route: jsx
// Source: original:gaps/ecdf
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from ecdf ----
// Seeded session durations in minutes, log-normal-ish: most sessions are short,
// a long tail is not. Mulberry32 PRNG for determinism.
function mulberry32(seed: number) {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const rng = mulberry32(19680704);

function randomNormal(mean: number, stdDev: number) {
  const u1 = rng();
  const u2 = rng();
  const z = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
  return mean + z * stdDev;
}

const sessionDurations: number[] = Array.from({ length: 240 }, () =>
  Math.round(Math.exp(randomNormal(1.9, 0.7)) * 10) / 10
);

const MARGIN = { top: 16, right: 16, bottom: 36, left: 54 };
const QUANTILES = [0.25, 0.5, 0.75];

/** The raw sample: one observation per value. No bins, no bandwidth — that is the point. */
export type Data = number[];

export default function EcdfChart({ data = sessionDurations, width }: { data?: Data; width: number }) {
  const height = Math.round(width * 0.62);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const sorted = useMemo(() => [...data].sort(d3.ascending), [data]);

  const x = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([0, d3.max(sorted) ?? 1])
        .nice()
        .range([0, innerWidth]),
    [sorted, innerWidth]
  );

  const y = useMemo(() => d3.scaleLinear().domain([0, 1]).range([innerHeight, 0]), [innerHeight]);

  const path = useMemo(() => {
    const step = d3
      .line<[number, number]>()
      .x((d) => x(d[0]))
      .y((d) => y(d[1]))
      .curve(d3.curveStepAfter);
    const points: [number, number][] = [
      [0, 0],
      ...sorted.map((v, i) => [v, (i + 1) / sorted.length] as [number, number])
    ];
    return step(points) ?? '';
  }, [sorted, x, y]);

  const xTicks: Tick[] = useMemo(
    () => x.ticks(Math.max(3, Math.round(innerWidth / 70))).map((v) => ({ value: String(v), offset: x(v) })),
    [x, innerWidth]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(5).map((v) => ({ value: d3.format('.0%')(v), offset: y(v) })),
    [y]
  );

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Empirical cumulative distribution of session durations, with quartiles marked"
    >
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />
        {QUANTILES.map((q) => {
          const value = d3.quantileSorted(sorted, q) ?? 0;
          return (
            <g key={q}>
              <line
                x1={0}
                x2={x(value)}
                y1={y(q)}
                y2={y(q)}
                stroke="var(--muted)"
                strokeDasharray="3 3"
              />
              <line
                x1={x(value)}
                x2={x(value)}
                y1={y(q)}
                y2={innerHeight}
                stroke="var(--muted)"
                strokeDasharray="3 3"
              />
              <text x={x(value) + 4} y={y(q) - 4} fontSize={10} fill="var(--text)">
                p{Math.round(q * 100)} = {d3.format('.3~r')(value)}
              </text>
            </g>
          );
        })}
        <path d={path} fill="none" stroke="var(--accent)" strokeWidth={2} />
      </g>
    </svg>
  );
}
