// Electric Usage — Heatmap, route: jsx
// Source: electric-usage-2019
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from electricUsage ----
const DAYS_IN_YEAR = 365;
const HOURS_PER_DAY = 24;
const YEAR_START = new Date(Date.UTC(2019, 0, 1));

// Seeded PRNG so the year is byte identical on every render, reload and machine.
function mulberry32(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Net kW pulled from the grid each hour: household load minus rooftop solar, so summer noon goes negative. */
function buildYear(): number[] {
  const random = mulberry32(20190101);
  const values: number[] = [];

  for (let day = 0; day < DAYS_IN_YEAR; day++) {
    // +1 in deep winter, -1 at the summer solstice.
    const season = Math.cos((2 * Math.PI * (day - 6)) / DAYS_IN_YEAR);
    const sunrise = 7.4 + 1.6 * season;
    const sunset = 17.6 - 1.6 * season;
    const clearSky = 0.45 + 0.55 * random() ** 0.6;
    const panelPeak = 9.4 - 2.0 * season;
    const chargeStart = random() < 0.55 ? 18 + Math.floor(random() * 4) : -1;
    const isOutage = day >= 281 && day < 285;

    for (let hour = 0; hour < HOURS_PER_DAY; hour++) {
      if (isOutage) {
        values.push(0);
        continue;
      }
      const daylight = Math.max(0, Math.sin((Math.PI * (hour - sunrise)) / (sunset - sunrise)));
      const solar = panelPeak * clearSky * daylight ** 1.3;
      const base = 0.55 + 0.15 * random();
      const morning = 1.5 * Math.exp(-((hour - 7) ** 2) / 3);
      const evening = 1.9 * Math.exp(-((hour - 19) ** 2) / 5);
      const furnace = Math.max(0, season) * 3.4 * Math.exp(-((hour - 6) ** 2) / 4);
      const car = hour >= chargeStart && hour < chargeStart + 4 ? 9.6 : 0;
      values.push(base + morning + evening + furnace + car - solar);
    }
  }

  return values;
}

const netUsage = buildYear();

const MARGIN = { top: 58, right: 14, bottom: 42, left: 52 };
const LEGEND_WIDTH = 240;
const RAMP_ID = 'electric-usage-ramp';
const STOP_COUNT = 25;

/** One reading per hour, day-major (index = day * hoursPerDay + hour), with the grid it fills. */
export type Data = {
  usage: number[];
  days: number;
  hoursPerDay: number;
  yearStart: Date;
};

const DEMO: Data = {
  usage: netUsage,
  days: DAYS_IN_YEAR,
  hoursPerDay: HOURS_PER_DAY,
  yearStart: YEAR_START
};

function formatHour(hour: number) {
  if (hour === 0) return '12 AM';
  if (hour === 12) return '12 PM';
  return hour < 12 ? `${hour} AM` : `${hour - 12} PM`;
}

export default function ElectricUsage({ data = DEMO, width }: { data?: Data; width: number }) {
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = Math.round(width * 0.28);
  const height = MARGIN.top + innerHeight + MARGIN.bottom;
  const cellWidth = innerWidth / data.days;
  const cellHeight = innerHeight / data.hoursPerDay;

  const color = useMemo(() => {
    // Symmetric about zero so an hour of draw and an hour of export read as equally saturated.
    const magnitude = d3.max(data.usage, (v) => Math.abs(v)) ?? 8;
    return d3
      .scaleDiverging<string>((t) => d3.interpolateRdBu(1 - t))
      .domain([-magnitude, 0, magnitude]);
  }, [data]);

  const cells = useMemo(
    () =>
      data.usage.map((value, i) => ({
        x: Math.floor(i / data.hoursPerDay) * cellWidth,
        y: (i % data.hoursPerDay) * cellHeight,
        fill: color(value)
      })),
    [data, color, cellWidth, cellHeight]
  );

  const months = useMemo(() => {
    const format = d3.utcFormat('%b');
    const start = data.yearStart;
    const starts = d3
      .utcMonths(start, d3.utcYear.offset(start, 1))
      .map((month) => ({ label: format(month), day: d3.utcDay.count(start, month) }));
    return starts.map((month, i) => ({
      ...month,
      x: month.day * cellWidth,
      center: ((month.day + (starts[i + 1]?.day ?? data.days)) / 2) * cellWidth
    }));
  }, [data, cellWidth]);

  const legend = useMemo(() => {
    const [lo, , hi] = color.domain();
    const position = d3.scaleLinear().domain([lo, hi]).range([0, LEGEND_WIDTH]);
    const format = d3.format('+d');
    return {
      stops: d3.range(STOP_COUNT).map((i) => {
        const t = i / (STOP_COUNT - 1);
        return { offset: t, color: color(lo + t * (hi - lo)) };
      }),
      ticks: position.ticks(5).map((v) => ({ value: format(v), offset: position(v) }))
    };
  }, [color]);

  // Suppress labels that would collide at narrow widths rather than letting them overlap.
  const hourStep = cellHeight >= 9 ? 3 : 6;
  const showMonths = innerWidth / 12 >= 26;

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Heatmap of a year of hourly household electricity, day of year across and hour of day down, red where power is drawn from the grid and blue where rooftop solar exports it. Synthetic data from a seeded generator, not real utility meter readings."
    >
      <defs>
        <linearGradient id={RAMP_ID} x1="0%" x2="100%" y1="0%" y2="0%">
          {legend.stops.map((stop) => (
            <stop key={stop.offset} offset={stop.offset} stopColor={stop.color} />
          ))}
        </linearGradient>
      </defs>

      <g transform={`translate(${MARGIN.left},10)`}>
        <text dy="0.71em" fontSize={11} fontWeight={600} fill="var(--text)">
          Net power consumption (kW)
        </text>
        <rect y={16} width={LEGEND_WIDTH} height={10} fill={`url(#${RAMP_ID})`} />
        {legend.ticks.map((tick) => (
          <g key={tick.offset} transform={`translate(${tick.offset},26)`}>
            <line y2={4} stroke="var(--muted)" />
            <text y={16} textAnchor="middle" fontSize={10} fill="var(--muted)">
              {tick.value}
            </text>
          </g>
        ))}
      </g>

      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <g shapeRendering="crispEdges">
          {cells.map((cell, i) => (
            <rect
              key={i}
              x={cell.x}
              y={cell.y}
              width={cellWidth + 0.5}
              height={cellHeight}
              fill={cell.fill}
            />
          ))}
        </g>

        {months.map((month) => (
          <g key={month.label}>
            {month.day > 0 && (
              <line x1={month.x} x2={month.x} y1={0} y2={innerHeight} stroke="var(--bg)" />
            )}
            {showMonths && (
              <text
                x={month.center}
                y={innerHeight + 16}
                textAnchor="middle"
                fontSize={11}
                fill="var(--muted)"
              >
                {month.label}
              </text>
            )}
          </g>
        ))}

        {d3.range(0, data.hoursPerDay, hourStep).map((hour) => (
          <text
            key={hour}
            x={-8}
            y={(hour + 0.5) * cellHeight}
            dy="0.32em"
            textAnchor="end"
            fontSize={10}
            fill="var(--muted)"
          >
            {formatHour(hour)}
          </text>
        ))}

        <text y={innerHeight + 34} fontSize={10} fill="var(--muted)">
          Synthetic data from a seeded generator, not real utility meter readings.
        </text>
      </g>
    </svg>
  );
}
