// Epicyclic Gearing — Animation, route: jsx
// Source: epicyclic-gearing
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useMemo, useState } from 'react';
import * as d3 from 'd3';

type Gear = {
  name: string;
  fill: string;
  teeth: number;
  /** Signed pitch radius in unit space. Angular velocity is spin / radius, so the
   *  sign encodes mesh direction and the magnitude encodes the gear ratio. */
  radius: number;
  origin: [number, number];
  annulus?: boolean;
};

const MARGIN = 8;
const MAX_HEIGHT = 520;
/** Vertical band reserved under the gears for the ratio caption. */
const CAPTION_SPACE = 18;
/** Below this the caption cannot fit on one line, so it is dropped. */
const CAPTION_MIN_WIDTH = 420;
/** Outermost extent in unit space: ring pitch radius plus its rim. */
const UNIT_EXTENT = 0.5 + 3 * 0.008;
const TOOTH_RADIUS = 0.008;
const HOLE_RADIUS = 0.02;
/** Sun turns at spin / 0.1 degrees, so this is 48 degrees per second. */
const DEGREES_PER_MS = 0.0048;

const X = Math.sin((2 * Math.PI) / 3);
const Y = Math.cos((2 * Math.PI) / 3);

// schemeBlues[9] steps 2, 3 and 4, matching the source notebook.
const GEARS: Gear[] = [
  { name: 'ring', fill: '#c6dbef', teeth: 80, radius: -0.5, origin: [0, 0], annulus: true },
  { name: 'sun', fill: '#6baed6', teeth: 16, radius: 0.1, origin: [0, 0] },
  { name: 'planet-a', fill: '#9ecae1', teeth: 32, radius: -0.2, origin: [0, -0.3] },
  { name: 'planet-b', fill: '#9ecae1', teeth: 32, radius: -0.2, origin: [-0.3 * X, -0.3 * Y] },
  { name: 'planet-c', fill: '#9ecae1', teeth: 32, radius: -0.2, origin: [0.3 * X, -0.3 * Y] }
];

/** Involute-free gear outline: alternating arcs at the root and tip radii, plus a
 *  counter-wound bore that the nonzero fill rule punches out. */
function gearPath(teeth: number, unitRadius: number, scale: number, annulus: boolean): string {
  const tooth = TOOTH_RADIUS * scale;
  const r2 = Math.abs(unitRadius) * scale;
  let r0 = r2 - tooth;
  let r1 = r2 + tooth;
  let r3 = HOLE_RADIUS * scale;
  if (annulus) {
    r3 = r0;
    r0 = r1;
    r1 = r3;
    r3 = r2 + tooth * 3;
  }
  const da = Math.PI / teeth;
  let a0 = -Math.PI / 2 + (annulus ? da : 0);
  const path = [`M${r0 * Math.cos(a0)},${r0 * Math.sin(a0)}`];
  for (let i = 0; i < teeth; i += 1) {
    path.push(
      `A${r0},${r0} 0 0,1 ${r0 * Math.cos((a0 += da))},${r0 * Math.sin(a0)}`,
      `L${r2 * Math.cos(a0)},${r2 * Math.sin(a0)}`,
      `L${r1 * Math.cos((a0 += da / 3))},${r1 * Math.sin(a0)}`,
      `A${r1},${r1} 0 0,1 ${r1 * Math.cos((a0 += da / 3))},${r1 * Math.sin(a0)}`,
      `L${r2 * Math.cos((a0 += da / 3))},${r2 * Math.sin(a0)}`,
      `L${r0 * Math.cos(a0)},${r0 * Math.sin(a0)}`
    );
  }
  path.push(`M0,${-r3}A${r3},${r3} 0 0,0 0,${r3}A${r3},${r3} 0 0,0 0,${-r3}Z`);
  return path.join('');
}

export default function EpicyclicGearing({ width }: { width: number }) {
  const height = Math.min(Math.round(width * 0.62), MAX_HEIGHT);
  const scale = (Math.min(width, height - CAPTION_SPACE) / 2 - MARGIN) / UNIT_EXTENT;

  const [spin, setSpin] = useState(0);

  useEffect(() => {
    const timer = d3.timer((elapsed) => setSpin(elapsed * DEGREES_PER_MS));
    return () => timer.stop();
  }, []);

  const shapes = useMemo(
    () =>
      GEARS.map((gear) => ({
        name: gear.name,
        fill: gear.fill,
        radius: gear.radius,
        d: gearPath(gear.teeth, gear.radius, scale, gear.annulus ?? false),
        cx: gear.origin[0] * scale,
        cy: gear.origin[1] * scale
      })),
    [scale]
  );

  if (width === 0) return null;

  return (
    <svg
      viewBox={`${-width / 2} ${-height / 2} ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Animated epicyclic gear train: a 16 tooth sun gear driving three 32 tooth planets inside an 80 tooth ring gear"
    >
      <g stroke="var(--bg)" strokeWidth={1}>
        {shapes.map((s) => (
          <path
            key={s.name}
            d={s.d}
            fill={s.fill}
            transform={`translate(${s.cx},${s.cy}) rotate(${(spin / s.radius) % 360})`}
          />
        ))}
      </g>
      {width >= CAPTION_MIN_WIDTH && (
        <text
          y={height / 2 - 5}
          textAnchor="middle"
          fontSize={11}
          fill="var(--muted)"
          aria-hidden="true"
        >
          sun 16 · planets 32 · ring 80 · carrier fixed, ring turns at 1/5 of sun speed
        </text>
      )}
    </svg>
  );
}
