// Hexbin Area — Distribution, route: jsx
// Source: hexbin-area
//
// Self-contained: every local import is inlined below. Requires only d3, d3-hexbin, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo, useState } from 'react';
import * as d3 from 'd3';
import { hexbin as createHexbin } from 'd3-hexbin';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from hexbin ----
/** mulberry32, seeded so the sample is byte-identical on every reload. */
function createRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

type Diamond = { carat: number; price: number };

/** Cutters aim at retail round weights, which is what puts vertical banding in the field. */
const ANCHOR_CARATS = [0.3, 0.31, 0.4, 0.41, 0.5, 0.51, 0.7, 0.71, 0.9, 1.0, 1.01, 1.2, 1.5, 1.51, 2.0, 2.5, 3.0];

function createDiamonds(count: number, seed: number): Diamond[] {
  const random = createRandom(seed);
  const normal = () => {
    const u = random() || Number.EPSILON; // Box-Muller diverges at exactly zero
    return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * random());
  };
  const diamonds: Diamond[] = [];
  while (diamonds.length < count) {
    // Squaring the index biases the draw toward the small stones that dominate the market.
    const anchor = ANCHOR_CARATS[Math.floor(random() ** 2 * ANCHOR_CARATS.length)];
    const carat = Math.round(anchor * Math.exp(0.09 * normal()) * 100) / 100;
    const price = Math.round(4200 * carat ** 1.9 * Math.exp(0.3 * normal()));
    if (carat >= 0.2 && carat <= 4 && price >= 250) diamonds.push({ carat, price });
  }
  return diamonds;
}

const diamonds: Diamond[] = createDiamonds(1600, 20260813);

const MARGIN = { top: 16, right: 16, bottom: 36, left: 52 };
const CAPTION_MIN_WIDTH = 420;

type Shape = 'hexagon' | 'circle';

/** A log axis labelled at every tick is unreadable; keep the chosen mantissas only. */
function logTicks(scale: d3.ScaleLogarithmic<number, number>, mantissas: number[]): number[] {
  return scale.ticks().filter((v) => {
    const mantissa = v / 10 ** Math.floor(Math.log10(v));
    return mantissas.some((m) => Math.abs(mantissa - m) < 1e-6);
  });
}

/** One row per observation; both axes are log-scaled, so every value must be positive. */
export type Data = { carat: number; price: number }[];

export default function HexbinArea({ data = diamonds, width }: { data?: Data; width: number }) {
  const [shape, setShape] = useState<Shape>('hexagon');

  const height = Math.round(width * 0.62);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;
  // Coarser bins than the colour-encoded sibling: an area encoding needs each bin large
  // enough that the size difference between neighbours is actually readable.
  const radius = Math.max(6, innerWidth / 60);

  const x = useMemo(
    () =>
      d3
        .scaleLog()
        .domain(d3.extent(data, (d) => d.carat) as [number, number])
        .range([radius, innerWidth - radius]),
    [data, innerWidth, radius]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLog()
        .domain(d3.extent(data, (d) => d.price) as [number, number])
        .range([innerHeight - radius, radius]),
    [data, innerHeight, radius]
  );

  const binner = useMemo(
    () =>
      createHexbin<Diamond>()
        .x((d) => x(d.carat))
        .y((d) => y(d.price))
        .radius(radius)
        .extent([
          [0, 0],
          [innerWidth, innerHeight]
        ]),
    [x, y, radius, innerWidth, innerHeight]
  );

  const bins = useMemo(() => binner(data), [binner, data]);

  // sqrt keeps count proportional to drawn area; SQRT2 lets the fullest bin fill its cell.
  const size = useMemo(
    () =>
      d3
        .scaleSqrt()
        .domain([0, d3.max(bins, (b) => b.length) ?? 1])
        .range([0, radius * Math.SQRT2]),
    [bins, radius]
  );

  const xTicks: Tick[] = useMemo(
    () => logTicks(x, [1, 2, 3, 5]).map((v) => ({ value: d3.format('~g')(v), offset: x(v) })),
    [x]
  );

  const yTicks: Tick[] = useMemo(
    () => logTicks(y, [1, 2, 5]).map((v) => ({ value: d3.format('~s')(v), offset: y(v) })),
    [y]
  );

  const legend = useMemo(() => {
    const peak = d3.max(bins, (b) => b.length) ?? 1;
    const steps = [...new Set([1, Math.round(peak / 4), peak])].filter((v) => v > 0);
    let cursor = 0;
    return steps.map((value) => {
      const marks = size(value);
      cursor += marks;
      const center = cursor;
      cursor += marks + 12;
      return { value, radius: marks, center };
    });
  }, [bins, size]);

  if (width === 0) return null;

  const legendMark = size.range()[1];
  // Centre the row on its largest mark so the caption clears the "$ Price" label at every width.
  const legendTop = 34 + legendMark;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Hexagonal binning of 1600 diamonds by carat and price, with the count per bin encoded as mark area rather than colour. Synthetic seeded sample, not the real diamonds dataset."
    >
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        <g fill="var(--muted)" fillOpacity={0.75} stroke="var(--bg)" strokeWidth={0.5}>
          {bins.map((bin) =>
            shape === 'hexagon' ? (
              <path
                key={`${bin.x},${bin.y}`}
                transform={`translate(${bin.x},${bin.y})`}
                d={binner.hexagon(size(bin.length))}
              />
            ) : (
              <circle key={`${bin.x},${bin.y}`} cx={bin.x} cy={bin.y} r={size(bin.length)} />
            )
          )}
        </g>
        {/* Drawn after the bins so the baseline stays crisp under the lowest marks. */}
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />
        <g fontSize={11} transform={`translate(${innerWidth},10)`} textAnchor="end">
          <text
            x={-56}
            fill={shape === 'hexagon' ? 'var(--accent)' : 'var(--muted)'}
            style={{ cursor: 'pointer' }}
            onClick={() => setShape('hexagon')}
          >
            hexagons
          </text>
          <text
            x={0}
            fill={shape === 'circle' ? 'var(--accent)' : 'var(--muted)'}
            style={{ cursor: 'pointer' }}
            onClick={() => setShape('circle')}
          >
            circles
          </text>
        </g>
        {/* Upper left is the one empty corner: no light stone carries a high price. */}
        <g transform={`translate(6,${legendTop})`}>
          <text y={-legendMark - 8} fill="var(--muted)" fontSize={11}>
            diamonds per bin
          </text>
          <g fill="var(--muted)" fillOpacity={0.75} stroke="var(--bg)" strokeWidth={0.5}>
            {legend.map((step) =>
              shape === 'hexagon' ? (
                <path
                  key={step.value}
                  transform={`translate(${step.center},0)`}
                  d={binner.hexagon(step.radius)}
                />
              ) : (
                <circle key={step.value} cx={step.center} cy={0} r={step.radius} />
              )
            )}
          </g>
          {legend.map((step) => (
            <text
              key={step.value}
              x={step.center}
              y={legendMark + 12}
              fill="var(--muted)"
              fontSize={10}
              textAnchor="middle"
            >
              {step.value}
            </text>
          ))}
        </g>
        {innerWidth >= CAPTION_MIN_WIDTH && (
          <text x={innerWidth} y={innerHeight - 26} fill="var(--muted)" fontSize={10} textAnchor="end">
            Synthetic data from a seeded generator, not the real diamonds dataset.
          </text>
        )}
        <text
          x={innerWidth}
          y={innerHeight - 8}
          fill="var(--text)"
          fontSize={12}
          fontWeight="bold"
          textAnchor="end"
        >
          Carats
        </text>
        <text x={4} y={12} fill="var(--text)" fontSize={12} fontWeight="bold">
          $ Price
        </text>
      </g>
    </svg>
  );
}
