// Hexbin — Distribution, route: jsx
// Source: hexbin
//
// Self-contained: every local import is inlined below. Requires only d3, d3-hexbin, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';
import { hexbin as createHexbin } from 'd3-hexbin';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from hexbin ----
/** mulberry32, seeded so the sample is byte-identical on every reload. */
function createRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

type Diamond = { carat: number; price: number };

/** Cutters aim at retail round weights, which is what puts vertical banding in the field. */
const ANCHOR_CARATS = [0.3, 0.31, 0.4, 0.41, 0.5, 0.51, 0.7, 0.71, 0.9, 1.0, 1.01, 1.2, 1.5, 1.51, 2.0, 2.5, 3.0];

function createDiamonds(count: number, seed: number): Diamond[] {
  const random = createRandom(seed);
  const normal = () => {
    const u = random() || Number.EPSILON; // Box-Muller diverges at exactly zero
    return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * random());
  };
  const diamonds: Diamond[] = [];
  while (diamonds.length < count) {
    // Squaring the index biases the draw toward the small stones that dominate the market.
    const anchor = ANCHOR_CARATS[Math.floor(random() ** 2 * ANCHOR_CARATS.length)];
    const carat = Math.round(anchor * Math.exp(0.09 * normal()) * 100) / 100;
    const price = Math.round(4200 * carat ** 1.9 * Math.exp(0.3 * normal()));
    if (carat >= 0.2 && carat <= 4 && price >= 250) diamonds.push({ carat, price });
  }
  return diamonds;
}

const diamonds: Diamond[] = createDiamonds(1600, 20260813);

const MARGIN = { top: 16, right: 16, bottom: 36, left: 52 };
const LEGEND_STEPS = 5;

/** A log axis labelled at every tick is unreadable; keep the chosen mantissas only. */
function logTicks(scale: d3.ScaleLogarithmic<number, number>, mantissas: number[]): number[] {
  return scale.ticks().filter((v) => {
    const mantissa = v / 10 ** Math.floor(Math.log10(v));
    return mantissas.some((m) => Math.abs(mantissa - m) < 1e-6);
  });
}

/** One row per observation; both axes are log-scaled, so every value must be positive. */
export type Data = { carat: number; price: number }[];

export default function Hexbin({ data = diamonds, width }: { data?: Data; width: number }) {
  const height = Math.round(width * 0.62);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;
  // Insetting the ranges by one radius keeps edge hexagons off the axes.
  const radius = Math.max(5, innerWidth / 70);

  const x = useMemo(
    () =>
      d3
        .scaleLog()
        .domain(d3.extent(data, (d) => d.carat) as [number, number])
        .range([radius, innerWidth - radius]),
    [data, innerWidth, radius]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLog()
        .domain(d3.extent(data, (d) => d.price) as [number, number])
        .range([innerHeight - radius, radius]),
    [data, innerHeight, radius]
  );

  const binner = useMemo(
    () =>
      createHexbin<Diamond>()
        .x((d) => x(d.carat))
        .y((d) => y(d.price))
        .radius(radius)
        .extent([
          [0, 0],
          [innerWidth, innerHeight]
        ]),
    [x, y, radius, innerWidth, innerHeight]
  );

  const bins = useMemo(() => binner(data), [binner, data]);

  const color = useMemo(() => {
    const peak = d3.max(bins, (b) => b.length) ?? 1;
    // Halving the domain, as the notebook does, keeps the crowded core from flattening into one tone.
    return d3
      .scaleSequential(d3.interpolateRgb('#2f3439', '#d4a24c'))
      .domain([0, Math.max(1, peak / 2)])
      .clamp(true);
  }, [bins]);

  const xTicks: Tick[] = useMemo(
    () => logTicks(x, [1, 2, 3, 5]).map((v) => ({ value: d3.format('~g')(v), offset: x(v) })),
    [x]
  );

  const yTicks: Tick[] = useMemo(
    () => logTicks(y, [1, 2, 5]).map((v) => ({ value: d3.format('~s')(v), offset: y(v) })),
    [y]
  );

  const legend = useMemo(() => {
    const [, top] = color.domain();
    return d3.range(LEGEND_STEPS).map((i) => {
      const value = (top * (i + 1)) / LEGEND_STEPS;
      return { value, label: String(Math.round(value)) };
    });
  }, [color]);

  if (width === 0) return null;

  const hexagon = binner.hexagon();
  const legendSwatch = Math.max(9, innerWidth / 60);

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Hexagonal binning of 1600 diamonds by carat and price, shaded by count per bin"
    >
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        <g stroke="var(--bg)" strokeWidth={0.5}>
          {bins.map((bin) => (
            <path
              key={`${bin.x},${bin.y}`}
              transform={`translate(${bin.x},${bin.y})`}
              d={hexagon}
              fill={color(bin.length)}
            />
          ))}
        </g>
        {/* Drawn after the bins so the baseline stays crisp under the lowest hexagons. */}
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />
        {/* Upper left is the one empty corner: no light stone carries a high price. */}
        <g transform="translate(4,30)">
          <text y={-5} fill="var(--muted)" fontSize={11}>
            diamonds per bin
          </text>
          {legend.map((step, i) => (
            <g key={step.label} transform={`translate(${i * legendSwatch},0)`}>
              <rect width={legendSwatch} height={legendSwatch} fill={color(step.value)} />
              <text
                x={legendSwatch / 2}
                y={legendSwatch + 11}
                fill="var(--muted)"
                fontSize={10}
                textAnchor="middle"
              >
                {step.label}
              </text>
            </g>
          ))}
        </g>
        <text x={innerWidth} y={innerHeight - 8} fill="var(--text)" fontSize={12} fontWeight="bold" textAnchor="end">
          Carats
        </text>
        <text x={4} y={12} fill="var(--text)" fontSize={12} fontWeight="bold">
          $ Price
        </text>
      </g>
    </svg>
  );
}
