// Horizontal Bar Chart — Basic, route: jsx
// Source: horizontal-bar-chart_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from data ----
/** Relative frequency of letters in English text. */
const letterFrequency = [
  { letter: 'E', frequency: 0.1202 },
  { letter: 'T', frequency: 0.091 },
  { letter: 'A', frequency: 0.0812 },
  { letter: 'O', frequency: 0.0768 },
  { letter: 'I', frequency: 0.0731 },
  { letter: 'N', frequency: 0.0695 },
  { letter: 'S', frequency: 0.0628 },
  { letter: 'R', frequency: 0.0602 },
  { letter: 'H', frequency: 0.0592 },
  { letter: 'D', frequency: 0.0432 },
  { letter: 'L', frequency: 0.0398 },
  { letter: 'U', frequency: 0.0288 },
  { letter: 'C', frequency: 0.0271 },
  { letter: 'M', frequency: 0.0261 },
  { letter: 'F', frequency: 0.023 },
  { letter: 'Y', frequency: 0.0211 },
  { letter: 'W', frequency: 0.0209 },
  { letter: 'G', frequency: 0.0203 },
  { letter: 'P', frequency: 0.0182 },
  { letter: 'B', frequency: 0.0149 }
];

/** Deterministic synthetic series so hot reloads do not reshuffle the chart. */
const timeSeries = Array.from({ length: 120 }, (_, i) => ({
  date: new Date(2024, 0, 1 + i * 3),
  value: 100 + Math.sin(i / 7) * 22 + Math.sin(i / 23) * 38 + i * 0.45
}));

const ROW_HEIGHT = 26;
const MARGIN = { top: 8, right: 40, bottom: 34, left: 30 };
const MIN_LABEL_BAR_WIDTH = 24;

const format = d3.format('.1%');

/** One bar per row, drawn top to bottom in the order given. */
export type Data = { letter: string; frequency: number }[];

export default function HorizontalBarChart({ data = letterFrequency, width }:
  { data?: Data; width: number }) {
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = data.length * ROW_HEIGHT;
  const height = innerHeight + MARGIN.top + MARGIN.bottom;

  const x = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([0, d3.max(data, (d) => d.frequency) ?? 0])
        .range([0, Math.max(innerWidth, 0)]),
    [data, innerWidth]
  );

  const y = useMemo(
    () =>
      d3
        .scaleBand<string>()
        .domain(data.map((d) => d.letter))
        .range([0, innerHeight])
        .padding(0.1),
    [data, innerHeight]
  );

  const xTicks: Tick[] = useMemo(
    () =>
      x.ticks(Math.max(2, Math.round(innerWidth / 80))).map((v) => ({
        value: format(v),
        offset: x(v)
      })),
    [x, innerWidth]
  );

  if (width === 0) return null;

  const bandwidth = y.bandwidth();

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Horizontal bar chart of the relative frequency of letters in the English language"
    >
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        {data.map((d) => {
          const barWidth = x(d.frequency);
          const top = y(d.letter) ?? 0;
          const middle = top + bandwidth / 2;
          const outside = barWidth < MIN_LABEL_BAR_WIDTH;
          return (
            <g key={d.letter}>
              <rect x={0} y={top} width={barWidth} height={bandwidth} fill="var(--accent)" />
              <text x={-8} y={middle} dy="0.32em" textAnchor="end" fontSize={11} fill="var(--text)">
                {d.letter}
              </text>
              <text
                x={outside ? barWidth + 4 : barWidth - 4}
                y={middle}
                dy="0.32em"
                textAnchor={outside ? 'start' : 'end'}
                fontSize={10}
                fill={outside ? 'var(--text)' : 'white'}
              >
                {format(d.frequency)}
              </text>
            </g>
          );
        })}
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />
      </g>
    </svg>
  );
}
