// Hertzsprung-Russell Diagram — Distribution, route: jsx
// Source: hertzsprung-russell-diagram
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from hrDiagram ----
/** mulberry32, seeded so the catalogue is byte-identical on every reload. */
function createRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

type Star = { id: number; bv: number; magnitude: number; color: string };

/** Main-sequence ridge: B-V colour index against absolute visual magnitude, by spectral type. */
const RIDGE: [number, number][] = [
  [-0.33, -3.6],
  [-0.2, -1.1],
  [-0.1, 0.6],
  [0.0, 1.1],
  [0.15, 1.9],
  [0.3, 2.6],
  [0.45, 3.5],
  [0.65, 4.83],
  [0.81, 5.9],
  [1.15, 7.35],
  [1.4, 8.8],
  [1.5, 9.9],
  [1.6, 11.8],
  [1.8, 13.5],
  [2.0, 14.6]
];

function mainSequence(bv: number): number {
  const found = RIDGE.findIndex(([b]) => b >= bv);
  const upper = found <= 0 ? (found === 0 ? 1 : RIDGE.length - 1) : found;
  const [b0, m0] = RIDGE[upper - 1];
  const [b1, m1] = RIDGE[upper];
  return m0 + ((m1 - m0) * (bv - b0)) / (b1 - b0);
}

type Population = { share: number; place: (u: number, n: () => number) => [number, number] };

/** Bias a uniform across a range; exponent above 1 crowds the low (bluer) end. */
function skew(u: number, lo: number, hi: number, exponent: number): number {
  return lo + (hi - lo) * u ** exponent;
}

const POPULATIONS: Population[] = [
  // Upper main sequence: hot, bright, and rare.
  { share: 0.09, place: (u, n) => bandPoint(skew(u, -0.33, 0.3, 1.6), n, 0.45) },
  // The crowded solar-type waist where most catalogued stars sit.
  { share: 0.4, place: (u, n) => bandPoint(skew(u, 0.3, 1.0, 0.9), n, 0.5) },
  // Cool dwarfs, thinning toward the faint red end.
  { share: 0.19, place: (u, n) => bandPoint(skew(u, 1.0, 2.0, 1.9), n, 0.6) },
  // Red clump: the dense knot of core-helium-burning giants.
  { share: 0.18, place: (_u, n) => [1.02 + n() * 0.13, 0.75 + n() * 0.45] },
  // Red giant branch, climbing cooler and brighter off the clump.
  { share: 0.06, place: (u, n) => [0.88 + u * 0.75 + n() * 0.06, 2.6 - u * 4 + n() * 0.5] },
  // Subgiants bridging the turn-off to the giant branch.
  { share: 0.02, place: (u, n) => [0.55 + u * 0.45, 3.4 - u * 0.8 + n() * 0.35] },
  // A scatter of supergiants along the top.
  { share: 0.015, place: (u, n) => [0.05 + u * 1.85, -3.2 + n() * 1.1] },
  // White dwarfs: a sequence roughly ten magnitudes under dwarfs of the same colour.
  { share: 0.045, place: (u, n) => whiteDwarf(-0.05 + u * 0.75, n) }
];

function bandPoint(bv: number, n: () => number, scatter: number): [number, number] {
  return [bv, mainSequence(bv) + n() * scatter];
}

function whiteDwarf(bv: number, n: () => number): [number, number] {
  return [bv, 11 + bv * 2.6 + n() * 0.7];
}

const BV_LIMIT = [-0.36, 2.12] as const;
const MAGNITUDE_LIMIT = [-6, 16.5] as const;

function createCatalogue(count: number, seed: number): Star[] {
  const random = createRandom(seed);
  const normal = () => {
    const u = random() || Number.EPSILON; // Box-Muller diverges at exactly zero
    return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * random());
  };
  const stars: Star[] = [];
  while (stars.length < count) {
    let pick = random();
    const population = POPULATIONS.find((p) => (pick -= p.share) <= 0) ?? POPULATIONS[0];
    const [bv, magnitude] = population.place(random(), normal);
    const inRange =
      bv >= BV_LIMIT[0] &&
      bv <= BV_LIMIT[1] &&
      magnitude >= MAGNITUDE_LIMIT[0] &&
      magnitude <= MAGNITUDE_LIMIT[1];
    if (inRange) stars.push({ id: stars.length, bv, magnitude, color: bvToColor(bv) });
  }
  return stars;
}

function redChannel(v: number): number {
  if (v < 0) {
    const t = (v + 0.4) / 0.4;
    return 0.61 + 0.11 * t + 0.1 * t * t;
  }
  if (v < 0.4) return 0.83 + 0.17 * (v / 0.4);
  return 1;
}

function greenChannel(v: number): number {
  if (v < 0) {
    const t = (v + 0.4) / 0.4;
    return 0.7 + 0.07 * t + 0.1 * t * t;
  }
  if (v < 0.4) return 0.87 + 0.11 * (v / 0.4);
  if (v < 1.6) return 0.98 - 0.16 * ((v - 0.4) / 1.2);
  const t = (v - 1.6) / 0.4;
  return 0.82 - 0.5 * t * t;
}

function blueChannel(v: number): number {
  if (v < 0.4) return 1;
  if (v < 1.5) {
    const t = (v - 0.4) / 1.1;
    return 1 - 0.47 * t + 0.1 * t * t;
  }
  if (v < 1.94) {
    const t = (v - 1.5) / 0.44;
    return 0.63 - 0.6 * t * t;
  }
  return 0;
}

/** Approximate blackbody hue for a B-V colour index (the D3 gallery's bv2rgb). */
function bvToColor(bv: number): string {
  const v = Math.max(-0.4, Math.min(2, bv));
  const hex = (t: number) =>
    Math.round(Math.min(1, Math.max(0, t)) * 255)
      .toString(16)
      .padStart(2, '0');
  return `#${hex(redChannel(v))}${hex(greenChannel(v))}${hex(blueChannel(v))}`;
}

const catalogue: Star[] = createCatalogue(1600, 20260813);

const MARGIN = { top: 48, right: 20, bottom: 54, left: 56 };
const BV_DOMAIN: [number, number] = [-0.42, 2.22];
// Brighter magnitudes are numerically smaller, and they belong at the TOP: the range runs
// downward rather than the usual [innerHeight, 0].
const MAGNITUDE_DOMAIN: [number, number] = [-6.5, 17];
const TEMPERATURES = [20000, 10000, 8000, 7000, 6000, 5000, 4000, 3000];
const SKY = '#0a0d13';

/** Ballesteros' relation inverted: the B-V index a blackbody of this temperature shows. */
function colorIndex(temperature: number): number {
  const u = 8464 / temperature;
  return (u - 2.1344 + Math.hypot(0.9936, u)) / 1.6928;
}

const ANNOTATIONS = [
  { label: 'supergiants', bv: 2.15, magnitude: -5, anchor: 'end' as const },
  { label: 'giants', bv: 1.62, magnitude: 1.6, anchor: 'start' as const },
  { label: 'main sequence', bv: 0.18, magnitude: 7.6, anchor: 'start' as const },
  { label: 'white dwarfs', bv: 0.78, magnitude: 13.2, anchor: 'start' as const }
];

/** One point per star: colour index, absolute magnitude, and the mark's own colour. */
export type Data = { id: number; bv: number; magnitude: number; color: string }[];

export default function HertzsprungRussell({ data = catalogue, width }:
  { data?: Data; width: number }) {
  const height = Math.round(width * 0.78);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const x = useMemo(
    () => d3.scaleLinear().domain(BV_DOMAIN).range([0, innerWidth]),
    [innerWidth]
  );

  const y = useMemo(
    () => d3.scaleLinear().domain(MAGNITUDE_DOMAIN).range([0, innerHeight]),
    [innerHeight]
  );

  const xTicks: Tick[] = useMemo(
    () => x.ticks(6).map((v) => ({ value: d3.format('+.1f')(v), offset: x(v) })),
    [x]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(6).map((v) => ({ value: d3.format('+d')(v), offset: y(v) })),
    [y]
  );

  const temperatureTicks: Tick[] = useMemo(
    () => TEMPERATURES.map((t) => ({ value: d3.format(',')(t), offset: x(colorIndex(t)) })),
    [x]
  );

  if (width === 0) return null;

  const radius = Math.max(0.9, innerWidth / 620);

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Hertzsprung-Russell diagram of 1600 stars: absolute magnitude against colour index, showing the main sequence, the giant branch and a clump of white dwarfs"
    >
      <rect width={width} height={height} rx={6} fill={SKY} />
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />

        {/* Temperature reads off the same axis as colour index, so it gets its own scale above. */}
        <g className="axis">
          {temperatureTicks.map(({ value, offset }) => (
            <g key={value} transform={`translate(${offset},0)`}>
              <line y1={0} y2={5} />
              <text y={-7} textAnchor="middle">
                {value}
              </text>
            </g>
          ))}
        </g>

        <g>
          {data.map((star) => (
            <circle
              key={star.id}
              cx={x(star.bv)}
              cy={y(star.magnitude)}
              r={radius}
              fill={star.color}
              fillOpacity={0.72}
            />
          ))}
        </g>

        {ANNOTATIONS.map((note) => (
          <text
            key={note.label}
            x={x(note.bv)}
            y={y(note.magnitude)}
            textAnchor={note.anchor}
            fill="#c9cdd4"
            fontSize={11}
            fontStyle="italic"
          >
            {note.label}
          </text>
        ))}

        {/* Drawn last so the baseline stays crisp under the faintest red dwarfs. */}
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />

        <text x={innerWidth / 2} y={-28} textAnchor="middle" fill="var(--text)" fontSize={12}>
          &larr; hotter &nbsp;&nbsp;<tspan fontWeight="bold">Temperature K</tspan>&nbsp;&nbsp; colder &rarr;
        </text>
        <text
          x={innerWidth / 2}
          y={innerHeight + 40}
          textAnchor="middle"
          fill="var(--text)"
          fontSize={12}
        >
          &larr; blue &nbsp;&nbsp;<tspan fontWeight="bold">Colour index B&ndash;V</tspan>&nbsp;&nbsp; red &rarr;
        </text>
        <text
          textAnchor="middle"
          fill="var(--text)"
          fontSize={12}
          transform={`translate(-42,${innerHeight / 2}) rotate(-90)`}
        >
          &larr; dimmer &nbsp;&nbsp;<tspan fontWeight="bold">Absolute magnitude M</tspan>&nbsp;&nbsp; brighter &rarr;
        </text>
      </g>
    </svg>
  );
}
