// Huffman Coding — Algorithms, route: jsx
// Source: original:essay/huffman-coding
//
// Self-contained: every local import is inlined below. Requires only motion, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useMemo, useState } from 'react';
import { motion } from 'motion/react';

// ---- inlined from huffman ----
/**
 * Huffman coding over one fixed sentence: the merge trace, a per-epoch forest layout,
 * the final codes, and the running encoded-bit counts.
 *
 * Huffman is deterministic given a tie-break, so unlike the other algorithm traces this
 * one needs no PRNG: ties are broken by node creation order.
 */

const SENTENCE = 'GREED ON THE TWO LIGHTEST TREES, PROVABLY, BUILDS THE BEST CODE.';

interface HuffNode {
  id: number;
  /** null for internal nodes. */
  symbol: string | null;
  weight: number;
  left: number;
  right: number;
  /** Merge epoch that created this node; 0 for leaves. */
  mergedAt: number;
}

/** One node's place in the forest: x in leaf-slot units, h levels above the baseline. */
interface NodePos {
  x: number;
  h: number;
}

const frequencies = new Map<string, number>();
for (const ch of SENTENCE) frequencies.set(ch, (frequencies.get(ch) ?? 0) + 1);

const nodes: HuffNode[] = [...frequencies]
  .sort((a, b) => a[1] - b[1] || a[0].localeCompare(b[0]))
  .map(([symbol, weight], id) => ({ id, symbol, weight, left: -1, right: -1, mergedAt: 0 }));

const LEAVES = nodes.length;
const MERGES = LEAVES - 1;
const FIXED_BITS = Math.ceil(Math.log2(LEAVES));

const parent = new Array<number>(2 * LEAVES - 1).fill(-1);

{
  const roots = nodes.map((n) => n.id);
  for (let epoch = 1; epoch <= MERGES; ++epoch) {
    roots.sort((a, b) => nodes[a].weight - nodes[b].weight || a - b);
    const [left, right] = [roots[0], roots[1]];
    const merged: HuffNode = {
      id: nodes.length,
      symbol: null,
      weight: nodes[left].weight + nodes[right].weight,
      left,
      right,
      mergedAt: epoch
    };
    nodes.push(merged);
    parent[left] = merged.id;
    parent[right] = merged.id;
    roots.splice(0, 2);
    roots.push(merged.id);
  }
}

const isRootAt = (id: number, epoch: number) =>
  nodes[id].mergedAt <= epoch && (parent[id] < 0 || nodes[parent[id]].mergedAt > epoch);

/**
 * positions[epoch][id]: where node `id` sits after `epoch` merges. Roots line up in weight
 * order, so the two lightest are always the leftmost pair. A node created later holds its
 * creation-epoch position throughout earlier epochs, letting it fade in without flying.
 */
const positions: NodePos[][] = [];

for (let epoch = 0; epoch <= MERGES; ++epoch) {
  const pos = new Array<NodePos>(nodes.length);
  const roots = nodes.filter((n) => isRootAt(n.id, epoch)).map((n) => n.id);
  roots.sort((a, b) => nodes[a].weight - nodes[b].weight || a - b);
  let slot = 0;
  const place = (id: number): NodePos => {
    const node = nodes[id];
    if (node.left < 0) return (pos[id] = { x: slot++ + 0.5, h: 0 });
    const l = place(node.left);
    const r = place(node.right);
    return (pos[id] = { x: (l.x + r.x) / 2, h: Math.max(l.h, r.h) + 1 });
  };
  roots.forEach(place);
  positions.push(pos);
}

for (const node of nodes) {
  for (let epoch = 0; epoch < node.mergedAt; ++epoch) {
    positions[epoch][node.id] = positions[node.mergedAt][node.id];
  }
}

const MAX_H = positions[MERGES][nodes.length - 1].h;

const codes = new Map<string, string>();
{
  const walk = (id: number, code: string) => {
    const node = nodes[id];
    if (node.symbol !== null) codes.set(node.symbol, code || '0');
    else {
      walk(node.left, code + '0');
      walk(node.right, code + '1');
    }
  };
  walk(nodes.length - 1, '');
}

/** cumulativeBits[i]: Huffman bits used once SENTENCE[0..i] is encoded. */
const cumulativeBits: number[] = [];
{
  let total = 0;
  for (const ch of SENTENCE) {
    total += (codes.get(ch) as string).length;
    cumulativeBits.push(total);
  }
}

const HUFFMAN_TOTAL = cumulativeBits[cumulativeBits.length - 1];
const FIXED_TOTAL = FIXED_BITS * SENTENCE.length;

const TICK_MS = 50;
const EPOCH_TICKS = 8;
const HOLD_TICKS = 44;
const TWEEN = { duration: 0.35, ease: 'easeInOut' } as const;
const MERGE_FLASH = '#e0538a';

const ENCODE_START = (MERGES + 1) * EPOCH_TICKS;
const END = ENCODE_START + SENTENCE.length + HOLD_TICKS;

const glyphOf = (symbol: string) => (symbol === ' ' ? '␣' : symbol);

export default function HuffmanCoding({ width }: { width: number }) {
  const w = Math.max(1, width);
  const slotW = w / LEAVES;
  const treeTop = 10;
  const treeH = w * 0.34;
  const treeBase = treeTop + treeH;
  const levelH = treeH / (MAX_H + 0.4);
  const radius = Math.min(slotW * 0.34, levelH * 0.36, 10);
  const glyph = w / (SENTENCE.length + 2);
  const sentenceY = treeBase + 24 + glyph * 1.2;
  const barX = Math.min(96, w * 0.18);
  const barMax = Math.max(1, w - barX - 70);
  const barTop = sentenceY + 12;
  const height = Math.round(barTop + 2 * 15 + 20);

  // The SSR frame is the finished tree with the whole sentence encoded; the effect rewinds.
  const [step, setStep] = useState(ENCODE_START + SENTENCE.length);

  useEffect(() => {
    setStep(0);
    const id = window.setInterval(() => setStep((s) => (s >= END ? 0 : s + 1)), TICK_MS);
    return () => window.clearInterval(id);
  }, []);

  const epoch = Math.min(MERGES, Math.floor(step / EPOCH_TICKS));
  const encoded = Math.max(0, Math.min(step - ENCODE_START, SENTENCE.length));
  const layout = positions[epoch];

  const px = (x: number) => x * slotW;
  const py = (h: number) => treeBase - h * levelH;

  const merging = useMemo(() => {
    if (epoch < 1) return new Set<number>();
    const made = nodes[LEAVES + epoch - 1];
    return new Set([made.id, made.left, made.right]);
  }, [epoch]);

  if (width === 0) return null;

  const huffBits = encoded > 0 ? cumulativeBits[encoded - 1] : 0;
  const fixedBits = FIXED_BITS * encoded;
  const current = encoded > 0 && encoded < SENTENCE.length ? SENTENCE[encoded] : null;
  const saved = Math.round((1 - HUFFMAN_TOTAL / FIXED_TOTAL) * 100);

  const bars = [
    { name: 'Huffman', bits: huffBits, fill: 'var(--accent)' },
    { name: `${FIXED_BITS}-bit fixed`, bits: fixedBits, fill: 'var(--muted)' }
  ];

  return (
    <svg
      viewBox={`0 0 ${w} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Huffman coding built bottom-up over one sentence's letter frequencies: each merge greedily joins the two lightest trees, and once the tree is complete the sentence encodes live, its variable-length bit count pulling ahead of fixed-width encoding"
    >
      {nodes.map((node) =>
        node.left < 0 ? null : (
          <g key={`e${node.id}`}>
            {[node.left, node.right].map((child) => (
              <motion.line
                key={child}
                initial={false}
                animate={{
                  x1: px(layout[node.id].x),
                  y1: py(layout[node.id].h),
                  x2: px(layout[child].x),
                  y2: py(layout[child].h),
                  opacity: node.mergedAt <= epoch ? 0.55 : 0
                }}
                transition={TWEEN}
                stroke="var(--muted)"
                strokeWidth={1.2}
              />
            ))}
          </g>
        )
      )}
      {nodes.map((node) => {
        const leaf = node.left < 0;
        const hot = merging.has(node.id);
        return (
          <motion.g
            key={node.id}
            initial={false}
            animate={{
              x: px(layout[node.id].x),
              y: py(layout[node.id].h),
              opacity: node.mergedAt <= epoch ? 1 : 0
            }}
            transition={TWEEN}
          >
            <circle
              r={leaf ? radius : radius * 0.78}
              fill={hot ? MERGE_FLASH : leaf ? 'var(--accent)' : 'var(--line)'}
            />
            <text
              y={radius * 0.36}
              textAnchor="middle"
              fontSize={radius * (leaf ? 1.05 : 0.85)}
              fontWeight={leaf ? 600 : 400}
              fill={leaf || hot ? '#fff' : 'var(--text)'}
              fontFamily="ui-monospace, SFMono-Regular, Menlo, monospace"
            >
              {leaf ? glyphOf(node.symbol as string) : node.weight}
            </text>
          </motion.g>
        );
      })}
      <g fontFamily="ui-monospace, SFMono-Regular, Menlo, monospace">
        {[...SENTENCE].map((ch, i) => (
          <text
            key={i}
            x={(i + 1.5) * glyph}
            y={sentenceY}
            textAnchor="middle"
            fontSize={glyph * 1.3}
            fill={i < encoded ? 'var(--muted)' : 'var(--text)'}
            opacity={i < encoded ? 0.5 : 1}
          >
            {ch}
          </text>
        ))}
      </g>
      {bars.map(({ name, bits, fill }, b) => (
        <g key={name} transform={`translate(0,${barTop + b * 15})`}>
          <text x={barX - 8} y={9} textAnchor="end" fill="var(--muted)" fontSize={10}>
            {name}
          </text>
          <rect x={barX} y={2} width={(bits / FIXED_TOTAL) * barMax} height={8} fill={fill} rx={2} />
          <text x={barX + barMax + 6} y={10} fill="var(--muted)" fontSize={10}>
            {bits}
          </text>
        </g>
      ))}
      <text x={4} y={height - 6} fill="var(--muted)" fontSize={11}>
        {epoch < MERGES
          ? `merge ${epoch} of ${MERGES}: the two lightest trees join`
          : encoded < SENTENCE.length && current
            ? `'${glyphOf(current)}' → ${codes.get(current) ?? ''}`
            : `${HUFFMAN_TOTAL} bits vs ${FIXED_TOTAL} fixed-width · ${saved}% saved`}
      </text>
    </svg>
  );
}
