// Line Chart with Tooltip — Time Series, route: jsx
// Source: line-with-tooltip_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo, useState, type PointerEvent } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from lineTooltip ----
type ClosePoint = { date: Date; close: number };

const DAYS = 260;

/** mulberry32: a fixed seed keeps the series identical across reloads. */
function seededRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const random = seededRandom(20260813);

/**
 * Synthetic daily closes standing in for a real equity price history: a slow uptrend,
 * two sine cycles, and a mean-reverting random walk so the path is not visibly drawn.
 */
const dailyCloses: ClosePoint[] = (() => {
  let drift = 0;
  return Array.from({ length: DAYS }, (_, day) => {
    drift = drift * 0.94 + (random() - 0.5) * 3.4;
    const cycle =
      14 * Math.sin((2 * Math.PI * day) / 97) + 5 * Math.sin((2 * Math.PI * day) / 29);
    return {
      date: new Date(Date.UTC(2024, 0, 1 + day)),
      close: 128 + day * 0.14 + cycle + drift
    };
  });
})();

const MARGIN = { top: 20, right: 20, bottom: 36, left: 52 };
const FONT = 12;
// Callout width is estimated from character count so the flip decision needs no getBBox.
const CHAR_WIDTH = 6.6;
const PAD = 8;
const GAP = 12;

/** One closing price per day, in chronological order. */
export type Data = { date: Date; close: number }[];

const formatDate = d3.utcFormat('%b %-d, %Y');
const formatValue = d3.format('$.2f');
const bisectDate = d3.bisector<Data[number], Date>((d) => d.date).center;

export default function LineWithTooltip({
  data = dailyCloses,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.round(width * 0.54);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const [focusIndex, setFocusIndex] = useState<number | null>(null);

  const x = useMemo(
    () =>
      d3
        .scaleUtc()
        .domain(d3.extent(data, (d) => d.date) as [Date, Date])
        .range([0, innerWidth]),
    [data, innerWidth]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([0, d3.max(data, (d) => d.close) ?? 0])
        .nice()
        .range([innerHeight, 0]),
    [data, innerHeight]
  );

  const path = useMemo(
    () =>
      d3
        .line<Data[number]>()
        .x((d) => x(d.date))
        .y((d) => y(d.close))(data) ?? '',
    [data, x, y]
  );

  const xTicks: Tick[] = useMemo(
    () =>
      x.ticks(Math.max(2, Math.round(innerWidth / 90))).map((v) => ({
        value: d3.utcFormat('%b %Y')(v),
        offset: x(v)
      })),
    [x, innerWidth]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(Math.max(3, Math.round(innerHeight / 40))).map((v) => ({
      value: String(v),
      offset: y(v)
    })),
    [y, innerHeight]
  );

  const callout = useMemo(() => {
    if (focusIndex === null) return null;
    const point = data[focusIndex];
    const lines = [formatDate(point.date), formatValue(point.close)];
    const boxWidth = Math.max(...lines.map((line) => line.length)) * CHAR_WIDTH + PAD * 2;
    const boxHeight = PAD * 2 + FONT * 2 + 4;
    const cx = x(point.date);
    const cy = y(point.close);
    // Flip to the left of the marker rather than let the box leave the plot area.
    const flipped = cx + GAP + boxWidth > innerWidth;
    return {
      lines,
      cx,
      cy,
      boxWidth,
      boxHeight,
      boxX: flipped ? cx - GAP - boxWidth : cx + GAP,
      boxY: Math.min(Math.max(cy - boxHeight / 2, 0), Math.max(innerHeight - boxHeight, 0))
    };
  }, [data, focusIndex, x, y, innerWidth, innerHeight]);

  function handlePointerMove(event: PointerEvent<SVGSVGElement>) {
    const [mx] = d3.pointer(event, event.currentTarget);
    setFocusIndex(bisectDate(data, x.invert(mx - MARGIN.left)));
  }

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Line chart of a daily closing price with a pointer-following tooltip. Synthetic data from a seeded generator, not real market prices."
      style={{ touchAction: 'none' }}
      onPointerMove={handlePointerMove}
      onPointerLeave={() => setFocusIndex(null)}
    >
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />
        <text x={-MARGIN.left} y={-6} fill="var(--muted)" fontSize={11}>
          ↑ Daily close ($)
        </text>
        <path
          d={path}
          fill="none"
          stroke="var(--accent)"
          strokeWidth={1.6}
          strokeLinejoin="round"
          strokeLinecap="round"
        />
        {callout && (
          <g pointerEvents="none">
            <line
              x1={callout.cx}
              x2={callout.cx}
              y1={0}
              y2={innerHeight}
              stroke="var(--line)"
              strokeWidth={1}
            />
            <circle cx={callout.cx} cy={callout.cy} r={4} fill="var(--accent)" />
            <rect
              x={callout.boxX}
              y={callout.boxY}
              width={callout.boxWidth}
              height={callout.boxHeight}
              rx={4}
              fill="var(--panel)"
              stroke="var(--line)"
            />
            {callout.lines.map((line, i) => (
              <text
                key={line}
                x={callout.boxX + PAD}
                y={callout.boxY + PAD + FONT * (i + 0.8)}
                fill="var(--text)"
                fontSize={FONT}
                fontWeight={i === 0 ? 600 : 400}
                stroke="var(--panel)"
                strokeWidth={3}
                paintOrder="stroke"
              >
                {line}
              </text>
            ))}
          </g>
        )}
        {innerWidth > 300 && (
          <text x={0} y={innerHeight + 32} fill="var(--muted)" fontSize={10}>
            Synthetic data from a seeded generator, not real market prices.
          </text>
        )}
      </g>
    </svg>
  );
}
