// Mobile Patent Suits — Network, route: ref
// Source: mobile-patent-suits
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useMemo, useRef } from 'react';
import * as d3 from 'd3';

// ---- inlined from mobilePatentSuits ----
/** Patent-related lawsuits in mobile communications, circa 2011. Source: Thomson Reuters. */
type Suit = { source: string; target: string; type: SuitType };
type SuitType = 'licensing' | 'suit' | 'resolved';

const SUIT_TYPES: SuitType[] = ['licensing', 'suit', 'resolved'];

const suits: Suit[] = [
  { source: 'Microsoft', target: 'Amazon', type: 'licensing' },
  { source: 'Microsoft', target: 'HTC', type: 'licensing' },
  { source: 'Samsung', target: 'Apple', type: 'suit' },
  { source: 'Motorola', target: 'Apple', type: 'suit' },
  { source: 'Nokia', target: 'Apple', type: 'resolved' },
  { source: 'HTC', target: 'Apple', type: 'suit' },
  { source: 'Kodak', target: 'Apple', type: 'suit' },
  { source: 'Microsoft', target: 'Barnes & Noble', type: 'suit' },
  { source: 'Microsoft', target: 'Foxconn', type: 'suit' },
  { source: 'Oracle', target: 'Google', type: 'suit' },
  { source: 'Apple', target: 'HTC', type: 'suit' },
  { source: 'Microsoft', target: 'Inventec', type: 'suit' },
  { source: 'Samsung', target: 'Kodak', type: 'resolved' },
  { source: 'LG', target: 'Kodak', type: 'resolved' },
  { source: 'RIM', target: 'Kodak', type: 'suit' },
  { source: 'Sony', target: 'LG', type: 'suit' },
  { source: 'Kodak', target: 'LG', type: 'resolved' },
  { source: 'Apple', target: 'Nokia', type: 'resolved' },
  { source: 'Qualcomm', target: 'Nokia', type: 'resolved' },
  { source: 'Apple', target: 'Motorola', type: 'suit' },
  { source: 'Microsoft', target: 'Motorola', type: 'suit' },
  { source: 'Motorola', target: 'Microsoft', type: 'suit' },
  { source: 'Huawei', target: 'ZTE', type: 'suit' },
  { source: 'Ericsson', target: 'ZTE', type: 'suit' },
  { source: 'Kodak', target: 'Samsung', type: 'resolved' },
  { source: 'Apple', target: 'Samsung', type: 'suit' },
  { source: 'Kodak', target: 'RIM', type: 'suit' },
  { source: 'Nokia', target: 'Qualcomm', type: 'suit' },
];

const suitCompanies: string[] = Array.from(
  new Set(suits.flatMap((d) => [d.source, d.target]))
);

interface SimNode extends d3.SimulationNodeDatum {
  id: string;
}

interface SimLink extends d3.SimulationLinkDatum<SimNode> {
  type: SuitType;
}

const SEED = 20260813;
const SETTLE_TICKS = 400;
/** Band reserved at the top of the centered viewBox for the type legend. */
const LEGEND_HEIGHT = 24;
const NODE_RADIUS = 4;

/** The parties, the directed edges between them, and the edge types to colour and list. */
export type Data = {
  companies: string[];
  suits: { source: string; target: string; type: SuitType }[];
  types: SuitType[];
};

const DEMO: Data = { companies: suitCompanies, suits, types: SUIT_TYPES };

/** Reciprocal suits (Microsoft <-> Motorola) overlap as straight lines, so every edge bows. */
function linkArc(d: SimLink): string {
  const source = d.source as SimNode;
  const target = d.target as SimNode;
  const [x1, y1, x2, y2] = [source.x ?? 0, source.y ?? 0, target.x ?? 0, target.y ?? 0];
  const r = Math.hypot(x2 - x1, y2 - y1);
  return `M${x1},${y1}A${r},${r} 0 0,1 ${x2},${y2}`;
}

export default function MobilePatentSuits({
  data = DEMO,
  width
}: {
  data?: Data;
  width: number;
}) {
  const ref = useRef<SVGSVGElement>(null);
  const height = Math.round(width * 0.62);

  const color = useMemo(
    () => d3.scaleOrdinal<SuitType, string>(data.types, d3.schemeObservable10),
    [data]
  );

  // Fixed starting positions: d3-force only seeds a node whose x is NaN, so these survive.
  const seedNodes = useMemo<SimNode[]>(() => {
    const random = d3.randomLcg(SEED);
    return data.companies.map((id) => ({
      id,
      x: (random() - 0.5) * width * 0.5,
      y: (random() - 0.5) * height * 0.5,
    }));
  }, [data, width, height]);

  useEffect(() => {
    const element = ref.current;
    if (!element || width === 0) return;

    const svg = d3.select(element);
    svg.selectAll('*').remove(); // StrictMode runs this effect twice in development.

    // Copy so a re-run starts from the seed positions rather than the settled ones.
    const nodes: SimNode[] = seedNodes.map((n) => ({ ...n }));
    const links: SimLink[] = data.suits.map((s) => ({ ...s }));

    const simulation = d3
      .forceSimulation<SimNode>(nodes)
      .randomSource(d3.randomLcg(SEED))
      .force(
        'link',
        d3
          .forceLink<SimNode, SimLink>(links)
          .id((d) => d.id)
          .distance(60)
      )
      .force('charge', d3.forceManyBody<SimNode>().strength(-420))
      .force('x', d3.forceX<SimNode>().strength(0.06))
      .force('y', d3.forceY<SimNode>(LEGEND_HEIGHT / 2).strength(0.12))
      .stop();

    // Per-type markers, as they do not inherit the path's stroke.
    svg
      .append('defs')
      .selectAll('marker')
      .data(data.types)
      .join('marker')
      .attr('id', (d) => `mps-arrow-${d}`)
      .attr('viewBox', '0 -5 10 10')
      .attr('refX', 15)
      .attr('refY', -0.5)
      .attr('markerWidth', 6)
      .attr('markerHeight', 6)
      .attr('orient', 'auto')
      .append('path')
      .attr('fill', (d) => color(d))
      .attr('d', 'M0,-5L10,0L0,5');

    const legend = svg
      .append('g')
      .attr('font-size', 11)
      .attr('fill', 'var(--muted)')
      .attr('transform', `translate(${8 - width / 2},${14 - height / 2})`);
    legend
      .selectAll('g')
      .data(data.types)
      .join('g')
      .attr('transform', (_, i) => `translate(${i * Math.min(96, width / data.types.length)},0)`)
      .call((g) => g.append('circle').attr('r', 4).attr('fill', (d) => color(d)))
      .call((g) =>
        g
          .append('text')
          .attr('x', 10)
          .attr('dy', '0.32em')
          .text((d) => d)
      );

    const link = svg
      .append('g')
      .attr('fill', 'none')
      .attr('stroke-width', 1.5)
      .selectAll<SVGPathElement, SimLink>('path')
      .data(links)
      .join('path')
      .attr('stroke', (d) => color(d.type))
      .attr('marker-end', (d) => `url(#mps-arrow-${d.type})`);

    const node = svg
      .append('g')
      .attr('font-size', 12)
      .attr('stroke-linecap', 'round')
      .attr('stroke-linejoin', 'round')
      .selectAll<SVGGElement, SimNode>('g')
      .data(nodes)
      .join('g');

    node
      .append('circle')
      .attr('r', NODE_RADIUS)
      .attr('fill', 'var(--text)')
      .attr('stroke', 'var(--bg)')
      .attr('stroke-width', 1.5);

    // Halo drawn first, beneath the label, so the name stays readable where edges pass under it.
    node
      .append('text')
      .attr('x', 8)
      .attr('y', '0.31em')
      .attr('fill', 'none')
      .attr('stroke', 'var(--bg)')
      .attr('stroke-width', 3)
      .text((d) => d.id);

    node
      .append('text')
      .attr('x', 8)
      .attr('y', '0.31em')
      .attr('fill', 'var(--text)')
      .text((d) => d.id);

    // Labels run to the right of their node, so the right clamp leaves room for them.
    const labelRoom = Math.min(96, width * 0.28);
    const ticked = () => {
      for (const d of nodes) {
        d.x = Math.max(NODE_RADIUS - width / 2, Math.min(width / 2 - labelRoom, d.x ?? 0));
        d.y = Math.max(
          LEGEND_HEIGHT - height / 2,
          Math.min(height / 2 - NODE_RADIUS - 2, d.y ?? 0)
        );
      }
      link.attr('d', linkArc);
      node.attr('transform', (d) => `translate(${d.x ?? 0},${d.y ?? 0})`);
    };

    simulation.tick(SETTLE_TICKS);
    ticked();
    simulation.on('tick', ticked);

    const drag = d3
      .drag<SVGGElement, SimNode>()
      .on('start', (event, d) => {
        if (!event.active) simulation.alphaTarget(0.3).restart();
        d.fx = d.x;
        d.fy = d.y;
      })
      .on('drag', (event, d) => {
        d.fx = event.x;
        d.fy = event.y;
      })
      .on('end', (event, d) => {
        if (!event.active) simulation.alphaTarget(0);
        d.fx = null;
        d.fy = null;
      });
    node.call(drag).style('cursor', 'grab');

    return () => {
      simulation.on('tick', null).stop();
      node.on('.drag', null);
      svg.selectAll('*').remove();
    };
  }, [data, width, height, seedNodes, color]);

  if (width === 0) return null;

  return (
    <svg
      ref={ref}
      viewBox={`${-width / 2} ${-height / 2} ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Directed graph of patent lawsuits, licensing deals and resolved disputes between mobile industry companies, circa 2011"
    />
  );
}
