// Moving Average — Time Series, route: jsx
// Source: moving-average
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

const MARGIN = { top: 16, right: 20, bottom: 36, left: 44 };
const DAYS = 730;
/** Odd windows only: a centered average needs an equal half-window on each side. */
const WINDOWS = [7, 31, 91];

/** One count per day, in chronological order and with no gaps. */
export type Data = { date: Date; count: number }[];

type Day = Data[number];
type Mean = { date: Date; value: number };

/** Seeded LCG, not Math.random, so the series survives hot reloads unchanged. */
function dailyCounts(days: number): Day[] {
  let seed = 20220101;
  return Array.from({ length: days }, (_, i) => {
    seed = (seed * 1103515245 + 12345) % 2147483648;
    const seasonal = 3.2 + 1.8 * Math.sin((2 * Math.PI * (i - 100)) / 365);
    return {
      date: new Date(2022, 0, 1 + i),
      count: Math.max(0, Math.round(seasonal + (seed / 2147483648 - 0.5) * 6))
    };
  });
}

const DEMO: Data = dailyCounts(DAYS);

/** Rolling sum in one pass. Windows that are not full are skipped, so no NaN reaches a path. */
function centeredMovingAverage(days: Day[], window: number): Mean[] {
  const half = Math.floor(window / 2);
  const means: Mean[] = [];
  let sum = 0;
  days.forEach(({ count }, i) => {
    sum += count;
    if (i >= window) sum -= days[i - window].count;
    if (i >= window - 1) means.push({ date: days[i - half].date, value: sum / window });
  });
  return means;
}

export default function MovingAverage({ data = DEMO, width }: { data?: Data; width: number }) {
  const height = Math.round(width * 0.5);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const x = useMemo(
    () =>
      d3
        .scaleTime()
        .domain(d3.extent(data, (d) => d.date) as [Date, Date])
        .range([0, innerWidth]),
    [data, innerWidth]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([0, d3.max(data, (d) => d.count) ?? 0])
        .nice()
        .range([innerHeight, 0]),
    [data, innerHeight]
  );

  const color = useMemo(
    () => d3.scaleOrdinal(WINDOWS.map(String), d3.schemeObservable10),
    []
  );

  const raw = useMemo(
    () =>
      d3
        .line<Day>()
        .x((d) => x(d.date))
        .y((d) => y(d.count))(data) ?? '',
    [data, x, y]
  );

  const averages = useMemo(() => {
    const line = d3
      .line<Mean>()
      .x((d) => x(d.date))
      .y((d) => y(d.value))
      .curve(d3.curveMonotoneX);
    return WINDOWS.map((window) => ({
      window,
      path: line(centeredMovingAverage(data, window)) ?? ''
    }));
  }, [data, x, y]);

  const xTicks: Tick[] = useMemo(
    () =>
      x.ticks(Math.max(2, Math.round(innerWidth / 110))).map((v) => ({
        value: d3.timeFormat('%b %Y')(v),
        offset: x(v)
      })),
    [x, innerWidth]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(5).map((v) => ({ value: String(v), offset: y(v) })),
    [y]
  );

  if (width === 0) return null;

  return (
    <svg viewBox={`0 0 ${width} ${height}`} width="100%" height={height} role="img"
         aria-label="Daily event counts with 7-day, 31-day and 91-day centered moving averages">
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />
        <text x={-MARGIN.left} y={-4} fill="var(--muted)" fontSize={11}>
          ↑ Events per day
        </text>
        <path d={raw} fill="none" stroke="var(--muted)" strokeOpacity={0.35} strokeWidth={0.75} />
        {averages.map((s) => (
          <path
            key={s.window}
            d={s.path}
            fill="none"
            stroke={color(String(s.window))}
            strokeWidth={s.window === WINDOWS[0] ? 1.25 : 2}
            strokeLinejoin="round"
            strokeLinecap="round"
          />
        ))}
        <g transform={`translate(${innerWidth - 76},2)`}>
          {averages.map((s, i) => (
            <g key={s.window} transform={`translate(0,${i * 15})`}>
              <line x1={0} x2={18} y1={0} y2={0} stroke={color(String(s.window))} strokeWidth={2} />
              <text x={24} dy="0.32em" fill="var(--muted)" fontSize={11}>
                {`${s.window}-day`}
              </text>
            </g>
          ))}
        </g>
      </g>
    </svg>
  );
}
