// Nested Treemap — Hierarchy, route: jsx
// Source: nested-treemap
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from nestedTreemap ----
/** A node is either a leaf carrying a budget or a grouping carrying children, never both. */
type BudgetNode = {
  name: string;
  value?: number;
  children?: BudgetNode[];
};

/** Invented research portfolio: 4 levels, 5 programs, 15 divisions, 40 projects, in $M. */
const researchBudget: BudgetNode = {
  name: 'Portfolio',
  children: [
    {
      name: 'Energy',
      children: [
        {
          name: 'Fusion',
          children: [
            { name: 'Tokamak', value: 420 },
            { name: 'Stellarator', value: 180 },
            { name: 'Diagnostics', value: 95 }
          ]
        },
        {
          name: 'Solar',
          children: [
            { name: 'Perovskite', value: 260 },
            { name: 'Thin Film', value: 140 },
            { name: 'Concentrator', value: 70 }
          ]
        },
        {
          name: 'Storage',
          children: [
            { name: 'Solid State', value: 310 },
            { name: 'Flow Cell', value: 150 },
            { name: 'Thermal', value: 85 }
          ]
        }
      ]
    },
    {
      name: 'Health',
      children: [
        {
          name: 'Genomics',
          children: [
            { name: 'Sequencing', value: 380 },
            { name: 'Editing', value: 240 },
            { name: 'Variant Atlas', value: 165 }
          ]
        },
        {
          name: 'Imaging',
          children: [
            { name: 'MRI', value: 290 },
            { name: 'PET', value: 120 },
            { name: 'Ultrasound', value: 75 }
          ]
        },
        {
          name: 'Vaccines',
          children: [
            { name: 'mRNA', value: 450 },
            { name: 'Trials', value: 200 },
            { name: 'Adjuvants', value: 110 }
          ]
        }
      ]
    },
    {
      name: 'Computing',
      children: [
        {
          name: 'Quantum',
          children: [
            { name: 'Superconducting', value: 360 },
            { name: 'Ion Trap', value: 275 },
            { name: 'Correction', value: 130 }
          ]
        },
        {
          name: 'Silicon',
          children: [
            { name: 'Photonics', value: 330 },
            { name: 'Memory', value: 210 },
            { name: 'Packaging', value: 145 }
          ]
        },
        {
          name: 'Systems',
          children: [
            { name: 'Networking', value: 160 },
            { name: 'Runtime', value: 115 },
            { name: 'Compilers', value: 90 }
          ]
        }
      ]
    },
    {
      name: 'Climate',
      children: [
        {
          name: 'Observation',
          children: [
            { name: 'Satellites', value: 520 },
            { name: 'Radar', value: 175 },
            { name: 'Buoys', value: 130 }
          ]
        },
        {
          name: 'Modeling',
          children: [
            { name: 'Circulation', value: 245 },
            { name: 'Ice Sheet', value: 135 },
            { name: 'Regional', value: 100 }
          ]
        },
        {
          name: 'Capture',
          children: [
            { name: 'Direct Air', value: 300 },
            { name: 'Mineral', value: 120 },
            { name: 'Ocean', value: 95 }
          ]
        }
      ]
    },
    {
      name: 'Space',
      children: [
        {
          name: 'Launch',
          children: [
            { name: 'Propulsion', value: 480 },
            { name: 'Structures', value: 190 }
          ]
        },
        {
          name: 'Payload',
          children: [
            { name: 'Optics', value: 265 },
            { name: 'Sensors', value: 155 },
            { name: 'Comms', value: 110 }
          ]
        },
        {
          name: 'Habitat',
          children: [
            { name: 'Life Support', value: 220 },
            { name: 'Shielding', value: 105 }
          ]
        }
      ]
    }
  ]
};

/** Root of a hierarchy: a leaf carries a value, a grouping carries children. Never both. */
export type Data = { name: string; value?: number; children?: Data[] };

type Cell = d3.HierarchyRectangularNode<Data>;

const MARGIN = { top: 8, right: 8, bottom: 8, left: 8 };
const FONT_SIZE = 10;
/** The band d3.treemap reserves above each node's children, and the only room a parent label has. */
const PADDING_TOP = 19;
/** Mean advance width of 10px sans-serif, used to drop labels that would overflow their rect. */
const CHAR_WIDTH = 5.6;
const LABEL_INSET = 3;
const SHADOW_ID = 'nested-treemap-shadow';

const format = d3.format(',d');

function pathOf(node: Cell): string {
  return node
    .ancestors()
    .map((a) => a.data.name)
    .reverse()
    .join('/');
}

export default function NestedTreemap({
  data = researchBudget,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.round(width * 1.05);
  const innerWidth = Math.max(1, width - MARGIN.left - MARGIN.right);
  const innerHeight = Math.max(1, height - MARGIN.top - MARGIN.bottom);

  const root = useMemo(
    () =>
      d3
        .treemap<Data>()
        .size([innerWidth, innerHeight])
        .paddingOuter(3)
        .paddingTop(PADDING_TOP)
        .paddingInner(1)
        .round(true)(
        d3
          .hierarchy(data)
          .sum((d) => d.value ?? 0)
          .sort((a, b) => (b.value ?? 0) - (a.value ?? 0))
      ),
    [data, innerWidth, innerHeight]
  );

  /** Ancestors are drawn first so each level's shadow falls on the frame it sits inside. */
  const layers = useMemo(
    () =>
      Array.from(d3.group(root.descendants(), (d) => d.height)).sort((a, b) => b[0] - a[0]),
    [root]
  );

  const color = useMemo(
    () => d3.scaleSequential([root.height + 1, -1], d3.interpolateMagma),
    [root.height]
  );

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Nested treemap of a research budget, every level drawn as a labelled frame around its children"
    >
      <filter id={SHADOW_ID}>
        <feDropShadow floodOpacity={0.3} dx={0} dy={2} stdDeviation={3} />
      </filter>
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`} fontSize={FONT_SIZE}>
        {layers.map(([nodeHeight, nodes]) => {
          const fill = color(nodeHeight);
          const labelFill = d3.lab(fill).l > 45 ? 'var(--bg)' : 'var(--text)';

          return (
            <g key={nodeHeight} filter={`url(#${SHADOW_ID})`}>
              {nodes.map((d) => {
                const cellWidth = d.x1 - d.x0;
                const cellHeight = d.y1 - d.y0;
                const value = format(d.value ?? 0);
                const room = cellWidth - LABEL_INSET * 2;
                const isParent = Boolean(d.children);
                const bandHeight = isParent ? PADDING_TOP : cellHeight;
                const fitsName = bandHeight >= 13 && d.data.name.length * CHAR_WIDTH < room;
                // A leaf stacks its value on a second line; a parent keeps both on its one band.
                const fitsValue = isParent
                  ? (d.data.name.length + value.length + 2) * CHAR_WIDTH < room
                  : cellHeight >= 26 && value.length * CHAR_WIDTH < room;

                return (
                  <g key={pathOf(d)} transform={`translate(${d.x0},${d.y0})`}>
                    <title>{`${pathOf(d)}\n${value}`}</title>
                    <rect width={cellWidth} height={cellHeight} fill={fill} />
                    {fitsName && (
                      <text x={LABEL_INSET} y={13} fill={labelFill}>
                        {d.data.name}
                        {fitsValue && isParent && <tspan fillOpacity={0.7}>{` ${value}`}</tspan>}
                      </text>
                    )}
                    {fitsName && fitsValue && !isParent && (
                      <text x={LABEL_INSET} y={23} fill={labelFill} fillOpacity={0.7}>
                        {value}
                      </text>
                    )}
                  </g>
                );
              })}
            </g>
          );
        })}
      </g>
    </svg>
  );
}
