// Parallel Coordinates — Multivariate, route: jsx
// Source: parallel-coordinates
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from parallelCoordinates ----
/** mulberry32, seeded so the fleet is byte-identical on every reload. */
function createRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

type Car = {
  name: string;
  cylinders: number;
  displacement: number;
  power: number;
  weight: number;
  acceleration: number;
  economy: number;
  year: number;
};

type Dimension = {
  key: Exclude<keyof Car, 'name'>;
  label: string;
  format: string;
  ticks: number;
};

const carDimensions: Dimension[] = [
  { key: 'cylinders', label: 'cylinders', format: 'd', ticks: 3 },
  { key: 'displacement', label: 'displacement', format: 'd', ticks: 6 },
  { key: 'power', label: 'power (hp)', format: 'd', ticks: 6 },
  { key: 'weight', label: 'weight (lb)', format: ',d', ticks: 6 },
  { key: 'acceleration', label: '0-60 mph (s)', format: '.0f', ticks: 6 },
  { key: 'economy', label: 'economy (mpg)', format: '.0f', ticks: 6 },
  { key: 'year', label: 'model year', format: 'd', ticks: 6 }
];

const MAKES = ['Alcyone', 'Bellwether', 'Corvid', 'Dunlin', 'Eider', 'Fulmar', 'Godwit', 'Harrier'];

/** Displacement class per cylinder count, and how often each count appears. */
const ENGINES = [
  { cylinders: 4, share: 0.46, displacement: 112, spread: 22 },
  { cylinders: 6, share: 0.28, displacement: 205, spread: 30 },
  { cylinders: 8, share: 0.26, displacement: 330, spread: 45 }
];

function createCars(seed: number, count: number): Car[] {
  const random = createRandom(seed);
  /** Box-Muller, so the correlated noise is bell shaped rather than boxy. */
  const noise = () => {
    const u = random() || Number.EPSILON;
    return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * random());
  };

  const cars: Car[] = [];
  for (let i = 0; i < count; i++) {
    const draw = random();
    let cumulative = 0;
    const engine = ENGINES.find((e) => (cumulative += e.share) >= draw) ?? ENGINES[0];

    const displacement = Math.round(engine.displacement + noise() * engine.spread);
    const power = Math.round(20 + 0.42 * displacement + noise() * 17);
    const weight = Math.round(1500 + 6.5 * displacement + noise() * 250);
    const year = 70 + Math.floor(random() * 13);
    const acceleration = 21 - 0.055 * power + noise() * 1.9;
    const economy = 56 - 0.009 * weight - 0.02 * power + 0.35 * (year - 76) + noise() * 3.1;

    cars.push({
      name: `${MAKES[i % MAKES.length]} ${200 + i}`,
      cylinders: engine.cylinders,
      displacement,
      power,
      weight,
      acceleration: Math.round(acceleration * 10) / 10,
      economy: Math.round(economy * 10) / 10,
      year: 1900 + year
    });
  }
  return cars;
}

const cars: Car[] = createCars(20260813, 160);

const MARGIN = { top: 30, right: 34, bottom: 48, left: 46 };
const COLOR_KEY = 'economy' as const;
const LEGEND_WIDTH = 132;

/** One vehicle: a name plus the seven numeric measures the axes read. */
type Vehicle = {
  name: string;
  cylinders: number;
  displacement: number;
  power: number;
  weight: number;
  acceleration: number;
  economy: number;
  year: number;
};

/** The rows, plus the measures to draw as axes in left-to-right order. */
export type Data = {
  rows: Vehicle[];
  dimensions: {
    key: Exclude<keyof Vehicle, 'name'>;
    label: string;
    format: string;
    ticks: number;
  }[];
};

const DEMO: Data = { rows: cars, dimensions: carDimensions };

export default function ParallelCoordinates({
  data = DEMO,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.round(width * 0.62);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const x = useMemo(
    () =>
      d3
        .scalePoint<string>()
        .domain(data.dimensions.map((d) => d.key))
        .range([0, innerWidth]),
    [data, innerWidth]
  );

  const axes = useMemo(
    () =>
      data.dimensions.map((dim) => {
        const [lo, hi] = d3.extent(data.rows, (c) => c[dim.key]);
        return {
          dim,
          scale: d3
            .scaleLinear()
            .domain([lo ?? 0, hi ?? 0])
            .nice()
            .range([innerHeight, 0])
        };
      }),
    [data, innerHeight]
  );

  // Viridis truncated at its dark end so the lowest values stay legible on the dark panel.
  const color = useMemo(() => {
    const [lo, hi] = d3.extent(data.rows, (c) => c[COLOR_KEY]);
    return d3.scaleSequential([lo ?? 0, hi ?? 0], (t) => d3.interpolateViridis(0.15 + 0.8 * t));
  }, [data]);

  const lines = useMemo(() => {
    const path = d3.line<[number, number]>();
    return data.rows
      .slice()
      .sort((a, b) => d3.ascending(a[COLOR_KEY], b[COLOR_KEY]))
      .map((car) => ({
        name: car.name,
        stroke: color(car[COLOR_KEY]),
        d: path(axes.map(({ dim, scale }) => [x(dim.key) ?? 0, scale(car[dim.key])])) ?? ''
      }));
  }, [data, axes, x, color]);

  const legendStops = useMemo(() => {
    const [lo, hi] = color.domain();
    return d3.range(11).map((i) => ({ offset: i / 10, stop: color(lo + ((hi - lo) * i) / 10) }));
  }, [color]);

  if (width === 0) return null;

  const [economyLow, economyHigh] = color.domain();

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Parallel coordinates of 160 vehicles across seven measures, colored by fuel economy"
    >
      <defs>
        <linearGradient id="parallel-coordinates-ramp">
          {legendStops.map(({ offset, stop }) => (
            <stop key={offset} offset={offset} stopColor={stop} />
          ))}
        </linearGradient>
      </defs>
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <g fill="none" strokeWidth={1.2} strokeOpacity={0.42}>
          {lines.map((line) => (
            <path key={line.name} d={line.d} stroke={line.stroke}>
              <title>{line.name}</title>
            </path>
          ))}
        </g>

        {axes.map(({ dim, scale }, index) => {
          const format = d3.format(dim.format);
          const anchor = index === 0 ? 'start' : index === axes.length - 1 ? 'end' : 'middle';
          return (
            <g key={dim.key} className="axis" transform={`translate(${x(dim.key) ?? 0},0)`}>
              <line y1={0} y2={innerHeight} />
              {scale.ticks(dim.ticks).map((value) => (
                <g key={value} transform={`translate(0,${scale(value)})`}>
                  <line x1={-4} x2={0} />
                  <text x={-8} dy="0.32em" textAnchor="end">
                    {format(value)}
                  </text>
                </g>
              ))}
              <text y={-12} textAnchor={anchor} style={{ fill: 'var(--text)', fontWeight: 500 }}>
                {dim.label}
              </text>
            </g>
          );
        })}

        <g className="axis" transform={`translate(0,${innerHeight + 24})`}>
          <text y={-6} style={{ fill: 'var(--text)' }}>
            economy (mpg)
          </text>
          <rect width={LEGEND_WIDTH} height={8} fill="url(#parallel-coordinates-ramp)" />
          <text y={20}>{d3.format('.0f')(economyLow)}</text>
          <text x={LEGEND_WIDTH} y={20} textAnchor="end">
            {d3.format('.0f')(economyHigh)}
          </text>
        </g>
      </g>
    </svg>
  );
}
