// Phases of the Moon — Astronomy, route: jsx
// Source: phases-of-the-moon
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

const YEAR = 2026;
const MARGIN = { top: 12, right: 10, bottom: 24, left: 66 };
const RAD = Math.PI / 180;
const PHASE_NAMES = [
  'New moon',
  'Waxing crescent',
  'First quarter',
  'Waxing gibbous',
  'Full moon',
  'Waning gibbous',
  'Last quarter',
  'Waning crescent'
];

// Fraction of the synodic month elapsed: 0 new, 0.25 first quarter, 0.5 full, 0.75 last quarter.
// Low precision ephemeris: mean longitudes plus the principal equation of centre for each body.
function moonPhase(date: Date): number {
  const days = date.getTime() / 86400000 - 10957.5; // days since J2000.0 (2000-01-01 12:00 UT)
  const moonAnomaly = (134.963 + 13.064993 * days) * RAD;
  const sunAnomaly = (357.529 + 0.98560028 * days) * RAD;
  const moonLongitude = 218.316 + 13.176396 * days + 6.289 * Math.sin(moonAnomaly);
  const sunLongitude = 280.459 + 0.98564736 * days + 1.915 * Math.sin(sunAnomaly);
  const elongation = (moonLongitude - sunLongitude) / 360;
  return elongation - Math.floor(elongation);
}

// The lit face is one semicircle of the limb plus one half ellipse of terminator whose x radius
// is the signed cosine of the phase. That sign flips the second sweep flag, which is the only
// difference between a crescent (terminator bulging toward the lit limb) and a gibbous.
// At the quarters the x radius is 0, which SVG draws as the straight terminator it should be.
function moonFace(radius: number, phase: number): string {
  const bulge = Math.cos(2 * Math.PI * phase);
  const waxing = phase < 0.5;
  const limbSweep = waxing ? 1 : 0; // 1 sweeps through +x, so a waxing moon lights its right limb
  const terminatorSweep = (bulge >= 0) === waxing ? 0 : 1;
  const r = radius.toFixed(2);
  const top = (-radius).toFixed(2);
  const rx = (Math.abs(bulge) * radius).toFixed(2);
  return `M0,${top}A${r},${r} 0 0 ${limbSweep} 0,${r}A${rx},${r} 0 0 ${terminatorSweep} 0,${top}Z`;
}

export default function PhasesOfTheMoon({ width }: { width: number }) {
  const height = Math.round(width * 0.5);

  const layout = useMemo(() => {
    // 39 day slots: up to 31 days pushed right by the weekday the month opens on.
    const dayScale = d3
      .scalePoint<number>()
      .domain(d3.range(1, 40))
      .range([MARGIN.left, width - MARGIN.right])
      .padding(1);
    const monthScale = d3
      .scalePoint<number>()
      .domain(d3.range(12))
      .range([MARGIN.top, height - MARGIN.bottom])
      .padding(1);

    const radius = Math.max(2, Math.min(dayScale.step() * 0.44, monthScale.step() * 0.32));
    const formatDate = d3.utcFormat('%B %-d, %Y');
    const start = new Date(Date.UTC(YEAR, 0, 1));
    const end = new Date(Date.UTC(YEAR + 1, 0, 1));

    const days = d3.utcDays(start, end).map((date) => {
      const offset = d3.utcMonth(date).getUTCDay() || 7; // Sunday closes the week, as in the original
      const phase = moonPhase(d3.utcHour.offset(date, 12));
      return {
        key: date.toISOString().slice(0, 10),
        x: dayScale(date.getUTCDate() + offset) ?? 0,
        y: monthScale(date.getUTCMonth()) ?? 0,
        day: date.getUTCDate(),
        face: moonFace(radius, phase),
        title: `${formatDate(date)}  ${PHASE_NAMES[Math.round(phase * 8) % 8]}`
      };
    });

    const months = d3.utcMonths(start, end).map((month) => ({
      key: month.getUTCMonth(),
      label: d3.utcFormat('%B')(month).toUpperCase(),
      y: monthScale(month.getUTCMonth()) ?? 0
    }));

    return { days, months, radius };
  }, [width, height]);

  if (width === 0) return null;

  const { days, months, radius } = layout;
  const dayFontSize = radius * 0.55;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label={`Calendar of moon phases for every day of ${YEAR}, one row per month, with each day drawn as the illuminated fraction of the lunar disc. Illumination is computed from a low precision lunar ephemeris and is accurate to within a few hours.`}
    >
      <g fontSize={Math.max(8, width / 97)} fill="var(--text)" letterSpacing="0.06em">
        {months.map((month) => (
          <text key={month.key} x={8} y={month.y} dy="0.32em">
            {month.label}
          </text>
        ))}
      </g>
      <g textAnchor="middle">
        {days.map((day) => (
          <g key={day.key} transform={`translate(${day.x},${day.y})`}>
            <circle r={radius} fill="var(--line)" />
            <path d={day.face} fill="var(--text)" />
            {dayFontSize >= 4 && (
              <text y={-radius} dy="-0.4em" fontSize={dayFontSize} fill="var(--muted)">
                {day.day}
              </text>
            )}
            <title>{day.title}</title>
          </g>
        ))}
      </g>
      <text x={MARGIN.left} y={height - 6} fontSize={11} fill="var(--muted)">
        {YEAR}. Illumination computed from a low precision lunar ephemeris, accurate to within a
        few hours.
      </text>
    </svg>
  );
}
