// Poisson-Disc Sampling — Algorithms, route: jsx
// Source: algorithms:sampling/dbb02448b0f93e4c82c3
//
// Self-contained: every local import is inlined below. Requires only react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useMemo, useState } from 'react';

// ---- inlined from sampling ----
type Point = [number, number];

/** mulberry32: a fixed seed keeps every sampler identical across reloads. */
function seededRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Every sampler runs in a box 1 unit wide and `boxHeight` tall, so a resize only rescales. */
const BOX_HEIGHT = 0.55;
const PANEL_HEIGHT = 0.42;

function nearest(points: Point[], x: number, y: number): Point {
  let best = points[0];
  let bestDistance = Infinity;
  for (const p of points) {
    const distance = (p[0] - x) * (p[0] - x) + (p[1] - y) * (p[1] - y);
    if (distance < bestDistance) {
      bestDistance = distance;
      best = p;
    }
  }
  return best;
}

/** Independent uniform draws: the sampler that clumps and leaves gaps. */
function uniformSamples(count: number, seed: number, boxHeight = BOX_HEIGHT): Point[] {
  const random = seededRandom(seed);
  return Array.from({ length: count }, () => [random(), random() * boxHeight] as Point);
}

type Candidate = { point: Point; nearest: Point; isBest: boolean };
type BestCandidateStep = { point: Point; candidates: Candidate[] };

/** Mitchell's best-candidate: each sample is the one of k draws farthest from its nearest neighbour. */
function bestCandidateSteps(
  count: number,
  k: number,
  seed: number,
  boxHeight = BOX_HEIGHT
): BestCandidateStep[] {
  const random = seededRandom(seed);
  const placed: Point[] = [[random(), random() * boxHeight]];
  const steps: BestCandidateStep[] = [{ point: placed[0], candidates: [] }];

  for (let i = 1; i < count; ++i) {
    const candidates: Candidate[] = [];
    let bestIndex = 0;
    let bestDistance = -1;

    for (let j = 0; j < k; ++j) {
      const point: Point = [random(), random() * boxHeight];
      const near = nearest(placed, point[0], point[1]);
      const distance = Math.hypot(near[0] - point[0], near[1] - point[1]);
      if (distance > bestDistance) {
        bestDistance = distance;
        bestIndex = j;
      }
      candidates.push({ point, nearest: near, isBest: false });
    }

    candidates[bestIndex].isBest = true;
    placed.push(candidates[bestIndex].point);
    steps.push({ point: candidates[bestIndex].point, candidates });
  }

  return steps;
}

type PoissonStep = { point: Point; parent: Point | null };
type PoissonRun = {
  steps: PoissonStep[];
  radius: number;
  cellSize: number;
  gridWidth: number;
  gridHeight: number;
};

/**
 * Bridson's algorithm: a background grid of cells smaller than radius/sqrt(2) holds at most one
 * sample each, so the minimum-distance test only ever reads a 5x5 neighbourhood.
 */
function poissonDiscSamples(
  radius: number,
  seed: number,
  boxHeight = BOX_HEIGHT,
  k = 30
): PoissonRun {
  const random = seededRandom(seed);
  const radius2 = radius * radius;
  const annulus = 3 * radius2;
  const cellSize = radius * Math.SQRT1_2;
  const gridWidth = Math.ceil(1 / cellSize);
  const gridHeight = Math.ceil(boxHeight / cellSize);
  const grid: (Point | undefined)[] = new Array(gridWidth * gridHeight);
  const active: Point[] = [];
  const steps: PoissonStep[] = [];

  const far = (x: number, y: number): boolean => {
    const i0 = Math.max((x / cellSize | 0) - 2, 0);
    const j0 = Math.max((y / cellSize | 0) - 2, 0);
    const i1 = Math.min((x / cellSize | 0) + 3, gridWidth);
    const j1 = Math.min((y / cellSize | 0) + 3, gridHeight);
    for (let j = j0; j < j1; ++j) {
      for (let i = i0; i < i1; ++i) {
        const s = grid[j * gridWidth + i];
        if (s && (s[0] - x) * (s[0] - x) + (s[1] - y) * (s[1] - y) < radius2) return false;
      }
    }
    return true;
  };

  const emit = (x: number, y: number, parent: Point | null) => {
    const s: Point = [x, y];
    active.push(s);
    grid[gridWidth * (y / cellSize | 0) + (x / cellSize | 0)] = s;
    steps.push({ point: s, parent });
  };

  emit(random(), random() * boxHeight, null);

  while (active.length) {
    const index = (random() * active.length) | 0;
    const s = active[index];
    let placed = false;

    for (let j = 0; j < k && !placed; ++j) {
      const angle = 2 * Math.PI * random();
      const r = Math.sqrt(random() * annulus + radius2);
      const x = s[0] + r * Math.cos(angle);
      const y = s[1] + r * Math.sin(angle);
      if (x >= 0 && x < 1 && y >= 0 && y < boxHeight && far(x, y)) {
        emit(x, y, s);
        placed = true;
      }
    }

    // Exhausting k candidates retires the sample: nothing more fits around it.
    if (!placed) {
      active[index] = active[active.length - 1];
      active.pop();
    }
  }

  return { steps, radius, cellSize, gridWidth, gridHeight };
}

const uniformPoints = uniformSamples(700, 20260813);
const bestCandidateRun = bestCandidateSteps(300, 8, 20260814);
const poissonRun = poissonDiscSamples(0.032, 20260815);

/** The comparison panels share a point count, taken from whatever Poisson-disc yields. */
const comparisonPoisson = poissonDiscSamples(0.055, 20260816, PANEL_HEIGHT);
const comparisonCount = comparisonPoisson.steps.length;

const comparisonSets: { label: string; points: Point[] }[] = [
  { label: 'Uniform random', points: uniformSamples(comparisonCount, 20260817, PANEL_HEIGHT) },
  {
    label: 'Best candidate',
    points: bestCandidateSteps(comparisonCount, 8, 20260818, PANEL_HEIGHT).map((s) => s.point)
  },
  { label: 'Poisson disc', points: comparisonPoisson.steps.map((s) => s.point) }
];

const PAD = 6;
const TICK_MS = 28;
const PAUSE_TICKS = 26;
const TOTAL_TICKS = poissonRun.steps.length;

export default function PoissonDiscSampling({ width }: { width: number }) {
  const scale = Math.max(1, width - PAD * 2);
  const height = Math.round(scale * BOX_HEIGHT) + PAD * 2;
  const radius = Math.max(1.5, scale / 340);

  // The completed sample set is the initial state, so the first frame is never empty.
  const [tick, setTick] = useState(TOTAL_TICKS);

  useEffect(() => {
    setTick(0);
    const id = window.setInterval(
      () => setTick((t) => (t + 1) % (TOTAL_TICKS + PAUSE_TICKS)),
      TICK_MS
    );
    return () => window.clearInterval(id);
  }, []);

  const { cells, samples, gridPath, cell } = useMemo(() => {
    const cell = poissonRun.cellSize * scale;
    const at = (p: readonly [number, number]) => [PAD + p[0] * scale, PAD + p[1] * scale] as const;

    // Each accepted sample claims exactly one background cell — that is the whole speedup.
    const cells = poissonRun.steps.map((step) => ({
      x: PAD + Math.floor(step.point[0] / poissonRun.cellSize) * cell,
      y: PAD + Math.floor(step.point[1] / poissonRun.cellSize) * cell
    }));

    const samples = poissonRun.steps.map((step) => ({
      point: at(step.point),
      parent: step.parent ? at(step.parent) : null
    }));

    const vertical = Array.from({ length: poissonRun.gridWidth }, (_, i) => `M${PAD + i * cell},${PAD}V${PAD + scale * BOX_HEIGHT}`);
    const horizontal = Array.from({ length: poissonRun.gridHeight }, (_, j) => `M${PAD},${PAD + j * cell}H${PAD + scale}`);

    return { cells, samples, gridPath: vertical.concat(horizontal).join(''), cell };
  }, [scale]);

  if (width === 0) return null;

  const shown = Math.min(tick, TOTAL_TICKS);
  // The step decoration is dropped once the run finishes, so the resting frame is just the samples.
  const current = shown > 0 && shown < TOTAL_TICKS ? samples[shown - 1] : null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label={`Bridson's Poisson-disc sampling: samples land at least a fixed distance apart, accelerated by a background grid whose cells hold at most one sample each`}
    >
      <path d={gridPath} fill="none" stroke="var(--line)" strokeWidth={0.5} opacity={0.6} />

      <g fill="var(--accent)" opacity={0.12}>
        {cells.slice(0, shown).map((c, i) => (
          <rect
            key={i}
            x={c.x}
            y={c.y}
            width={Math.min(cell, PAD + scale - c.x)}
            height={Math.min(cell, PAD + scale * BOX_HEIGHT - c.y)}
          />
        ))}
      </g>

      {current && (
        <g>
          <circle
            cx={current.point[0]}
            cy={current.point[1]}
            r={poissonRun.radius * scale}
            fill="none"
            stroke="var(--accent)"
            strokeWidth={1}
            opacity={0.5}
          />
          {current.parent && (
            <line
              x1={current.parent[0]}
              y1={current.parent[1]}
              x2={current.point[0]}
              y2={current.point[1]}
              stroke="var(--accent)"
              strokeWidth={1.5}
            />
          )}
        </g>
      )}

      {samples.slice(0, shown).map((s, i) => (
        <circle
          key={i}
          cx={s.point[0]}
          cy={s.point[1]}
          r={radius}
          fill={current && i === shown - 1 ? 'var(--accent)' : 'var(--text)'}
        />
      ))}

      <rect x={PAD} y={PAD} width={scale} height={scale * BOX_HEIGHT} fill="none" stroke="var(--line)" />
    </svg>
  );
}
