// Predator and Prey — Time Series, route: jsx
// Source: predator-and-prey
//
// Self-contained: every local import is inlined below. Requires only d3, motion, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useMemo, useState } from 'react';
import * as d3 from 'd3';
import { motion } from 'motion/react';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

const MARGIN = { top: 18, right: 20, bottom: 52, left: 46 };
const PREY_COLOR = d3.schemeObservable10[4];
const PREDATOR_COLOR = d3.schemeObservable10[2];

const ALPHA = 0.6667;
const BETA = 1.3333;
const GAMMA = 1;
const DELTA = 1;
const PREY_0 = 1.4;
const PREDATOR_0 = 1.6;

const T_MAX = 24;
const SAMPLE_STEP = 0.05;
const SUBSTEPS = 5;
const FRAME_MS = 40;
const FRAME_STRIDE = 2;
const PHASE_MIN_WIDTH = 560;
const PANEL_GAP = 44;

type Sample = { t: number; prey: number; predator: number };

function derivative(prey: number, predator: number): [number, number] {
  return [ALPHA * prey - BETA * prey * predator, DELTA * prey * predator - GAMMA * predator];
}

// Classical RK4. The Lotka-Volterra invariant drifts by ~5e-10 over t=24 at this step,
// so the phase orbit retraces itself instead of spiralling.
function integrate(): Sample[] {
  const h = SAMPLE_STEP / SUBSTEPS;
  let prey = PREY_0;
  let predator = PREDATOR_0;
  const samples: Sample[] = [{ t: 0, prey, predator }];
  for (let i = 1; i <= Math.round(T_MAX / SAMPLE_STEP); i++) {
    for (let s = 0; s < SUBSTEPS; s++) {
      const [a1, b1] = derivative(prey, predator);
      const [a2, b2] = derivative(prey + (h / 2) * a1, predator + (h / 2) * b1);
      const [a3, b3] = derivative(prey + (h / 2) * a2, predator + (h / 2) * b2);
      const [a4, b4] = derivative(prey + h * a3, predator + h * b3);
      prey += (h / 6) * (a1 + 2 * a2 + 2 * a3 + a4);
      predator += (h / 6) * (b1 + 2 * b2 + 2 * b3 + b4);
    }
    samples.push({ t: i * SAMPLE_STEP, prey, predator });
  }
  return samples;
}

export default function PredatorAndPrey({ width }: { width: number }) {
  const height = Math.round(width * 0.5);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const showPhase = innerWidth >= PHASE_MIN_WIDTH;
  const phaseSize = showPhase ? Math.min(innerHeight, Math.round(innerWidth * 0.4)) : 0;
  const seriesWidth = showPhase ? innerWidth - phaseSize - PANEL_GAP : innerWidth;

  const samples = useMemo(() => integrate(), []);
  const [frame, setFrame] = useState(0);

  useEffect(() => {
    const timer = setInterval(
      () => setFrame((f) => (f + FRAME_STRIDE) % samples.length),
      FRAME_MS
    );
    return () => clearInterval(timer);
  }, [samples.length]);

  const x = useMemo(() => d3.scaleLinear([0, T_MAX], [0, seriesWidth]), [seriesWidth]);

  const y = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([0, d3.max(samples, (s) => Math.max(s.prey, s.predator)) ?? 0])
        .nice()
        .range([innerHeight, 0]),
    [samples, innerHeight]
  );

  const paths = useMemo(() => {
    const line = (accessor: (s: Sample) => number) =>
      d3.line<Sample>().x((s) => x(s.t)).y((s) => y(accessor(s)))(samples) ?? '';
    return { prey: line((s) => s.prey), predator: line((s) => s.predator) };
  }, [samples, x, y]);

  const phaseX = useMemo(
    () => d3.scaleLinear([0, d3.max(samples, (s) => s.prey) ?? 0], [0, phaseSize]).nice(),
    [samples, phaseSize]
  );

  const phaseY = useMemo(
    () => d3.scaleLinear([0, d3.max(samples, (s) => s.predator) ?? 0], [phaseSize, 0]).nice(),
    [samples, phaseSize]
  );

  const orbit = useMemo(
    () => d3.line<Sample>().x((s) => phaseX(s.prey)).y((s) => phaseY(s.predator))(samples) ?? '',
    [samples, phaseX, phaseY]
  );

  const xTicks: Tick[] = useMemo(
    () => x.ticks(6).map((v) => ({ value: v === 0 ? 't = 0' : String(v), offset: x(v) })),
    [x]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(5).map((v) => ({ value: String(v), offset: y(v) })),
    [y]
  );

  const phaseXTicks: Tick[] = useMemo(
    () => phaseX.ticks(4).map((v) => ({ value: String(v), offset: phaseX(v) })),
    [phaseX]
  );

  const phaseYTicks: Tick[] = useMemo(
    () => phaseY.ticks(4).map((v) => ({ value: String(v), offset: phaseY(v) })),
    [phaseY]
  );

  if (width === 0) return null;

  const now = samples[frame] ?? samples[0];
  const series = [
    { label: 'Prey', color: PREY_COLOR, path: paths.prey, value: now.prey },
    { label: 'Predators', color: PREDATOR_COLOR, path: paths.predator, value: now.predator }
  ];
  const tween = { duration: FRAME_MS / 1000, ease: 'linear' } as const;

  return (
    <svg viewBox={`0 0 ${width} ${height}`} width="100%" height={height} role="img"
         aria-label="Lotka-Volterra predator and prey model integrated by Runge-Kutta. Both populations oscillate, with the predator peak trailing the prey peak, and the phase portrait closes into a single orbit around the equilibrium at one unit of prey and half a unit of predators.">
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={seriesWidth} />
        <AxisBottom ticks={xTicks} height={innerHeight} width={seriesWidth} />
        <text x={-MARGIN.left} y={-5} fill="var(--muted)" fontSize={11}>
          ↑ Population
        </text>
        <line x1={x(now.t)} x2={x(now.t)} y1={0} y2={innerHeight} stroke="var(--line)" />
        {series.map((s, i) => (
          <g key={s.label}>
            <path d={s.path} fill="none" stroke={s.color} strokeWidth={1.6} />
            <motion.circle initial={false} transition={tween} r={4} fill={s.color}
                           animate={{ cx: x(now.t), cy: y(s.value) }} />
            <g transform={`translate(${i * 92},${innerHeight + 40})`}>
              <line x1={0} x2={16} y1={-4} y2={-4} stroke={s.color} strokeWidth={2.5} />
              <text x={22} y={0} fill="var(--muted)" fontSize={11}>
                {s.label}
              </text>
            </g>
          </g>
        ))}
        {seriesWidth >= 320 && (
          <text x={seriesWidth} y={innerHeight + 40} textAnchor="end" fill="var(--muted)"
                fontSize={11}>
            {`α=${ALPHA} β=${BETA} γ=${GAMMA} δ=${DELTA}`}
          </text>
        )}

        {showPhase && (
          <g transform={`translate(${seriesWidth + PANEL_GAP},${innerHeight - phaseSize})`}>
            <AxisLeft ticks={phaseYTicks} width={phaseSize} />
            <AxisBottom ticks={phaseXTicks} height={phaseSize} width={phaseSize} />
            <text x={-6} y={-5} fill="var(--muted)" fontSize={11}>
              ↑ Predators
            </text>
            <path d={orbit} fill="none" stroke="var(--muted)" strokeWidth={1.4} opacity={0.55} />
            <circle cx={phaseX(GAMMA / DELTA)} cy={phaseY(ALPHA / BETA)} r={3}
                    fill="var(--text)" />
            <text x={phaseX(GAMMA / DELTA) + 8} y={phaseY(ALPHA / BETA) + 4}
                  fill="var(--muted)" fontSize={11}>
              equilibrium
            </text>
            <motion.circle initial={false} transition={tween} r={4.5} fill="var(--accent)"
                           animate={{ cx: phaseX(now.prey), cy: phaseY(now.predator) }} />
            <text x={phaseSize} y={phaseSize + 40} textAnchor="end" fill="var(--muted)"
                  fontSize={11}>
              Prey →
            </text>
          </g>
        )}
      </g>
    </svg>
  );
}
