// Projection Comparison — Geo, route: jsx
// Source: projection-comparison
//
// Self-contained: every local import is inlined below. Requires only d3, d3-geo-projection, geojson, react, topojson-client, topojson-specification, us-atlas, world-atlas.
// d3-geo-projection ships no types — keep untyped-modules.d.ts beside this file.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

/// <reference path="./untyped-modules.d.ts" />

import { feature, mesh } from 'topojson-client';
import countries110m from 'world-atlas/countries-110m.json';
import statesUs from 'us-atlas/states-10m.json';
import type { GeometryCollection, Topology } from 'topojson-specification';
import type { Feature, FeatureCollection, Geometry, MultiLineString } from 'geojson';
import { useMemo } from 'react';
import * as d3 from 'd3';
import { geoAitoff, geoMollweide, geoRobinson, geoWinkel3 } from 'd3-geo-projection';

// ---- inlined from geo ----
// The atlases ship untyped JSON. One cast per topology at this boundary keeps every
// consumer strict, and converting here means each chart does not re-derive the same
// geometry at module load.

type Named = { name: string };
type NamedFeature = Feature<Geometry, Named>;

const world = countries110m as unknown as Topology<{
  countries: GeometryCollection<Named>;
  land: GeometryCollection;
}>;

const us = statesUs as unknown as Topology<{
  states: GeometryCollection<Named>;
  nation: GeometryCollection;
}>;

const worldCountries = feature(
  world,
  world.objects.countries
) as FeatureCollection<Geometry, Named>;

const worldLand = feature(world, world.objects.land) as FeatureCollection<Geometry>;

/** Shared borders only, so neighbouring outlines are stroked once instead of twice. */
const worldBorders = mesh(
  world,
  world.objects.countries,
  (a, b) => a !== b
) as MultiLineString;

const usNation = feature(us, us.objects.nation) as FeatureCollection<Geometry>;

const usStateBorders = mesh(
  us,
  us.objects.states,
  (a, b) => a !== b
) as MultiLineString;

/**
 * The 50 states plus DC. geoAlbersUsa cannot project FIPS ids of 60 and above
 * (territories) and returns null for them, which becomes a NaN centroid downstream.
 * Use this rather than the raw collection for anything Albers-projected.
 */
const usStates: NamedFeature[] = (
  feature(us, us.objects.states) as FeatureCollection<Geometry, Named>
).features.filter((d) => Number(d.id) < 60);

const usStatesCollection: FeatureCollection<Geometry, Named> = {
  type: 'FeatureCollection',
  features: usStates
};

/**
 * FNV-1a over an id, run through the murmur3 finalizer. Two-character FIPS ids barely
 * differ, and without the finalizer they map to a near-constant. Returns [0, 1).
 * Charts use it to synthesize per-region values deterministically instead of fetching.
 */
function hashUnit(id: string, salt = 0): number {
  let h = 2166136261 ^ salt;
  for (let i = 0; i < id.length; i++) {
    h = Math.imul(h ^ id.charCodeAt(i), 16777619);
  }
  h ^= h >>> 16;
  h = Math.imul(h, 2246822507);
  h ^= h >>> 13;
  return (h >>> 0) / 4294967296;
}

const MARGIN = { top: 8, right: 8, bottom: 8, left: 8 };
const LABEL_HEIGHT = 20;
const CELL_ASPECT = 0.62;

const sphere: d3.GeoSphere = { type: 'Sphere' };
const graticule = d3.geoGraticule10();

const PROJECTIONS: { name: string; create: () => d3.GeoProjection }[] = [
  { name: 'Equal Earth', create: d3.geoEqualEarth },
  { name: 'Mercator', create: d3.geoMercator },
  { name: 'Mollweide', create: geoMollweide },
  { name: 'Robinson', create: geoRobinson },
  { name: 'Winkel tripel', create: geoWinkel3 },
  { name: 'Aitoff', create: geoAitoff },
  { name: 'Azimuthal equal-area', create: d3.geoAzimuthalEqualArea },
  { name: 'Orthographic', create: d3.geoOrthographic },
];

type Cell = {
  name: string;
  x: number;
  y: number;
  outline: string;
  grid: string;
  land: string;
};

export default function ProjectionComparison({ width }: { width: number }) {
  const columns = width < 640 ? 2 : 4;
  const rows = Math.ceil(PROJECTIONS.length / columns);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const cellWidth = innerWidth / columns;
  const cellHeight = Math.round(cellWidth * CELL_ASPECT);
  const height = MARGIN.top + MARGIN.bottom + rows * (cellHeight + LABEL_HEIGHT);

  const cells: Cell[] = useMemo(() => {
    if (cellWidth <= 0) return [];
    // Each projection is fitted to its own cell, so cells share a frame but not a scale.
    return PROJECTIONS.map(({ name, create }, i) => {
      const projection = create().fitSize([cellWidth - 8, cellHeight - 8], sphere).precision(0.3);
      const path = d3.geoPath(projection);
      return {
        name,
        x: (i % columns) * cellWidth,
        y: Math.floor(i / columns) * (cellHeight + LABEL_HEIGHT),
        outline: path(sphere) ?? '',
        grid: path(graticule) ?? '',
        land: path(worldLand) ?? '',
      };
    });
  }, [cellWidth, cellHeight, columns]);

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="World land under eight map projections, small multiples"
    >
      <defs>
        {cells.map((cell) => (
          <clipPath key={cell.name} id={`projcmp-${slug(cell.name)}`}>
            <path d={cell.outline} />
          </clipPath>
        ))}
      </defs>
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        {cells.map((cell) => (
          <g key={cell.name} transform={`translate(${cell.x + 4},${cell.y + 4})`}>
            <g clipPath={`url(#projcmp-${slug(cell.name)})`}>
              <path d={cell.grid} fill="none" stroke="var(--line)" strokeWidth={0.5} />
              <path d={cell.land} fill="var(--accent)" fillOpacity={0.85} />
            </g>
            <path d={cell.outline} fill="none" stroke="var(--muted)" strokeWidth={0.75} />
            {cell.name.length * 6.4 < cellWidth && (
              <text
                x={cellWidth / 2 - 4}
                y={cellHeight + 9}
                textAnchor="middle"
                fill="var(--muted)"
                fontSize={11}
              >
                {cell.name}
              </text>
            )}
          </g>
        ))}
      </g>
    </svg>
  );
}

const slug = (name: string) => name.toLowerCase().replace(/[^a-z]+/g, '-');
