// Quicksort — Algorithms, route: jsx
// Source: algorithms:sorting/e1e1e7e2c360bec054ba
//
// Self-contained: every local import is inlined below. Requires only d3, motion, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useMemo, useState } from 'react';
import * as d3 from 'd3';
import { motion } from 'motion/react';

// ---- inlined from sorting ----
/** mulberry32: a fixed seed keeps every sort trace identical across reloads. */
function seededRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Fisher-Yates over 0..n-1. Values double as identities, so `value` is a stable React key. */
function shuffled(n: number, seed: number): number[] {
  const random = seededRandom(seed);
  const array = Array.from({ length: n }, (_, i) => i);
  for (let i = n - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

// --- quicksort, animated ------------------------------------------------------

/** One frame per swap and per partition announcement; `pivotValue` is -1 when idle. */
type QuicksortFrame = {
  array: number[];
  left: number;
  right: number;
  pivotValue: number;
};

const quicksortSize = 48;

/** Bostock's median-index quicksort, instrumented to emit a frame per mutation. */
function traceQuicksort(input: number[]): QuicksortFrame[] {
  const array = input.slice();
  const frames: QuicksortFrame[] = [];
  let left = 0;
  let right = array.length;
  let pivotValue = -1;
  const record = () => frames.push({ array: array.slice(), left, right, pivotValue });

  function swap(i: number, j: number) {
    if (i === j) return;
    [array[i], array[j]] = [array[j], array[i]];
    record();
  }

  function partition(lo: number, hi: number, pivot: number): number {
    const v = array[pivot];
    swap(pivot, --hi);
    for (let i = lo; i < hi; ++i) if (array[i] <= v) swap(i, lo++);
    swap(lo, hi);
    return lo;
  }

  function recurse(lo: number, hi: number) {
    if (lo >= hi - 1) return;
    const pivot = (lo + hi) >> 1;
    left = lo;
    right = hi;
    pivotValue = array[pivot];
    record();
    const split = partition(lo, hi, pivot);
    recurse(lo, split);
    recurse(split + 1, hi);
  }

  record();
  recurse(0, array.length);
  left = 0;
  right = array.length;
  pivotValue = -1;
  record();
  return frames;
}

const quicksortFrames: QuicksortFrame[] = traceQuicksort(shuffled(quicksortSize, 20260813));

// --- quicksort recursion threads, static --------------------------------------

/** Where one element sits after `time` swaps. A thread is that history, top to bottom. */
type ThreadStep = { time: number; index: number };

const threadSize = 20;

/** Same quicksort, recorded as index histories: every swap braids two threads together. */
function traceThreads(input: number[]): { value: number; steps: ThreadStep[] }[] {
  const array = input.slice();
  const swaps: [number, number][] = [];

  function swap(i: number, j: number) {
    if (i === j) return;
    [array[i], array[j]] = [array[j], array[i]];
    swaps.push([i, j]);
  }

  function partition(lo: number, hi: number, pivot: number): number {
    const v = array[pivot];
    swap(pivot, --hi);
    for (let i = lo; i < hi; ++i) if (array[i] <= v) swap(i, lo++);
    swap(lo, hi);
    return lo;
  }

  (function recurse(lo: number, hi: number) {
    if (lo >= hi - 1) return;
    const split = partition(lo, hi, (lo + hi) >> 1);
    recurse(lo, split);
    recurse(split + 1, hi);
  })(0, array.length);

  const order = input.slice();
  const steps: ThreadStep[][] = input.map(() => []);
  order.forEach((value, index) => steps[value].push({ time: 0, index }));
  swaps.forEach(([i, j], t) => {
    const vi = order[i];
    const vj = order[j];
    order[i] = vj;
    order[j] = vi;
    steps[vi].push({ time: t + 1, index: j });
    steps[vj].push({ time: t + 1, index: i });
  });
  // A closing step at time = rows carries each thread down to the baseline.
  steps.forEach((s) => s.push({ time: swaps.length + 1, index: s[s.length - 1].index }));

  return steps.map((s, value) => ({ value, steps: s }));
}

const threads = traceThreads(shuffled(threadSize, 20260813));
const threadRows = threads[0].steps[threads[0].steps.length - 1].time;

// --- mergesort, animated ------------------------------------------------------

/** Per element: which slot it occupies and which of the two buffers it is in. */
type MergesortFrame = { index: number[]; band: number[]; pass: number };

const mergesortSize = 48;

/** Bottom-up mergesort. Each copy moves one element into the other buffer band. */
function traceMergesort(input: number[]): { frames: MergesortFrame[]; passRows: number[][] } {
  const n = input.length;
  const index = new Array<number>(n);
  const band = new Array<number>(n).fill(0);
  input.forEach((value, i) => (index[value] = i));

  const frames: MergesortFrame[] = [];
  const passRows: number[][] = [];
  let pass = 0;
  const record = () => frames.push({ index: index.slice(), band: band.slice(), pass });

  let source = input.slice();
  let target = new Array<number>(n);
  let outBand = 1;
  record();

  for (let width = 1; width < n; width <<= 1) {
    for (let lo = 0; lo < n; lo += width << 1) {
      const mid = Math.min(lo + width, n);
      const hi = Math.min(lo + (width << 1), n);
      let i0 = lo;
      let i1 = mid;
      for (let j = lo; j < hi; ++j) {
        const take = i0 < mid && (i1 >= hi || source[i0] <= source[i1]) ? i0++ : i1++;
        const value = source[take];
        target[j] = value;
        index[value] = j;
        band[value] = outBand;
        record();
      }
    }
    passRows.push(target.slice());
    pass++;
    record();
    [source, target] = [target, source];
    outBand ^= 1;
  }

  return { frames, passRows };
}

const mergesortInput = shuffled(mergesortSize, 20260813);

const { frames: mergesortFrames, passRows: mergesortPassRows } =
  traceMergesort(mergesortInput);

const FRAME_MS = 55;
const HOLD_FRAMES = 26;
const TWEEN = { duration: FRAME_MS / 1000, ease: 'easeInOut' } as const;
const LAST = quicksortFrames.length - 1;

/** Each element is a needle: its angle encodes value, so a sorted array is a smooth fan. */
export default function Quicksort({ width }: { width: number }) {
  const height = Math.round(width * 0.46);
  const length = Math.max(1, Math.min(height - 48, width * 0.11));
  const pad = Math.ceil(length * 0.72) + 6;
  const innerWidth = Math.max(1, width - 2 * pad);
  const baseY = Math.max(1, height - 30);

  const [step, setStep] = useState(LAST);

  useEffect(() => {
    const timer = setInterval(
      () => setStep((s) => (s + 1) % (quicksortFrames.length + HOLD_FRAMES)),
      FRAME_MS
    );
    return () => clearInterval(timer);
  }, []);

  const x = useMemo(
    () => d3.scalePoint(d3.range(quicksortSize), [pad, pad + innerWidth]),
    [pad, innerWidth]
  );

  const color = useMemo(
    () => d3.scaleSequential([0, quicksortSize - 1], (t) => d3.interpolateTurbo(0.06 + 0.88 * t)),
    []
  );

  const angle = useMemo(() => d3.scaleLinear([0, quicksortSize - 1], [-45, 45]), []);

  if (width === 0) return null;

  const frame = quicksortFrames[Math.min(step, LAST)];
  const sorting = frame.pivotValue >= 0;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Quicksort animated as a row of needles, one per array element, whose angle encodes value. The active partition is drawn in colour with its pivot picked out in white, everything outside it is greyed, and the finished sort resolves into a smooth left-to-right fan."
    >
      <g transform={`translate(0,${baseY})`}>
        {frame.array.map((value, i) => {
          const active = i >= frame.left && i < frame.right;
          const pivot = value === frame.pivotValue;
          return (
            <motion.g key={value} initial={false} animate={{ x: x(i) ?? 0 }} transition={TWEEN}>
              <line
                y1={0}
                y2={-length}
                transform={`rotate(${angle(value)})`}
                stroke={pivot ? 'var(--text)' : active ? color(value) : 'var(--line)'}
                strokeWidth={pivot ? 2.8 : 1.6}
                strokeLinecap="round"
              />
            </motion.g>
          );
        })}
        {sorting && (
          <line
            x1={x(frame.left) ?? 0}
            x2={x(frame.right - 1) ?? 0}
            y1={10}
            y2={10}
            stroke="var(--accent)"
            strokeWidth={2}
          />
        )}
      </g>
      <text x={pad} y={height - 8} fill="var(--muted)" fontSize={11}>
        {sorting ? `partitioning [${frame.left}, ${frame.right})` : `${quicksortSize} elements sorted`}
      </text>
      <text x={width - pad} y={height - 8} textAnchor="end" fill="var(--muted)" fontSize={11}>
        {`step ${Math.min(step, LAST)} / ${LAST}`}
      </text>
    </svg>
  );
}
