// Quicksort Recursion Threads — Algorithms, route: jsx
// Source: algorithms:sorting/6dcc9a177065881b1bc4
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from sorting ----
/** mulberry32: a fixed seed keeps every sort trace identical across reloads. */
function seededRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Fisher-Yates over 0..n-1. Values double as identities, so `value` is a stable React key. */
function shuffled(n: number, seed: number): number[] {
  const random = seededRandom(seed);
  const array = Array.from({ length: n }, (_, i) => i);
  for (let i = n - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

// --- quicksort, animated ------------------------------------------------------

/** One frame per swap and per partition announcement; `pivotValue` is -1 when idle. */
type QuicksortFrame = {
  array: number[];
  left: number;
  right: number;
  pivotValue: number;
};

const quicksortSize = 48;

/** Bostock's median-index quicksort, instrumented to emit a frame per mutation. */
function traceQuicksort(input: number[]): QuicksortFrame[] {
  const array = input.slice();
  const frames: QuicksortFrame[] = [];
  let left = 0;
  let right = array.length;
  let pivotValue = -1;
  const record = () => frames.push({ array: array.slice(), left, right, pivotValue });

  function swap(i: number, j: number) {
    if (i === j) return;
    [array[i], array[j]] = [array[j], array[i]];
    record();
  }

  function partition(lo: number, hi: number, pivot: number): number {
    const v = array[pivot];
    swap(pivot, --hi);
    for (let i = lo; i < hi; ++i) if (array[i] <= v) swap(i, lo++);
    swap(lo, hi);
    return lo;
  }

  function recurse(lo: number, hi: number) {
    if (lo >= hi - 1) return;
    const pivot = (lo + hi) >> 1;
    left = lo;
    right = hi;
    pivotValue = array[pivot];
    record();
    const split = partition(lo, hi, pivot);
    recurse(lo, split);
    recurse(split + 1, hi);
  }

  record();
  recurse(0, array.length);
  left = 0;
  right = array.length;
  pivotValue = -1;
  record();
  return frames;
}

const quicksortFrames: QuicksortFrame[] = traceQuicksort(shuffled(quicksortSize, 20260813));

// --- quicksort recursion threads, static --------------------------------------

/** Where one element sits after `time` swaps. A thread is that history, top to bottom. */
type ThreadStep = { time: number; index: number };

const threadSize = 20;

/** Same quicksort, recorded as index histories: every swap braids two threads together. */
function traceThreads(input: number[]): { value: number; steps: ThreadStep[] }[] {
  const array = input.slice();
  const swaps: [number, number][] = [];

  function swap(i: number, j: number) {
    if (i === j) return;
    [array[i], array[j]] = [array[j], array[i]];
    swaps.push([i, j]);
  }

  function partition(lo: number, hi: number, pivot: number): number {
    const v = array[pivot];
    swap(pivot, --hi);
    for (let i = lo; i < hi; ++i) if (array[i] <= v) swap(i, lo++);
    swap(lo, hi);
    return lo;
  }

  (function recurse(lo: number, hi: number) {
    if (lo >= hi - 1) return;
    const split = partition(lo, hi, (lo + hi) >> 1);
    recurse(lo, split);
    recurse(split + 1, hi);
  })(0, array.length);

  const order = input.slice();
  const steps: ThreadStep[][] = input.map(() => []);
  order.forEach((value, index) => steps[value].push({ time: 0, index }));
  swaps.forEach(([i, j], t) => {
    const vi = order[i];
    const vj = order[j];
    order[i] = vj;
    order[j] = vi;
    steps[vi].push({ time: t + 1, index: j });
    steps[vj].push({ time: t + 1, index: i });
  });
  // A closing step at time = rows carries each thread down to the baseline.
  steps.forEach((s) => s.push({ time: swaps.length + 1, index: s[s.length - 1].index }));

  return steps.map((s, value) => ({ value, steps: s }));
}

const threads = traceThreads(shuffled(threadSize, 20260813));
const threadRows = threads[0].steps[threads[0].steps.length - 1].time;

// --- mergesort, animated ------------------------------------------------------

/** Per element: which slot it occupies and which of the two buffers it is in. */
type MergesortFrame = { index: number[]; band: number[]; pass: number };

const mergesortSize = 48;

/** Bottom-up mergesort. Each copy moves one element into the other buffer band. */
function traceMergesort(input: number[]): { frames: MergesortFrame[]; passRows: number[][] } {
  const n = input.length;
  const index = new Array<number>(n);
  const band = new Array<number>(n).fill(0);
  input.forEach((value, i) => (index[value] = i));

  const frames: MergesortFrame[] = [];
  const passRows: number[][] = [];
  let pass = 0;
  const record = () => frames.push({ index: index.slice(), band: band.slice(), pass });

  let source = input.slice();
  let target = new Array<number>(n);
  let outBand = 1;
  record();

  for (let width = 1; width < n; width <<= 1) {
    for (let lo = 0; lo < n; lo += width << 1) {
      const mid = Math.min(lo + width, n);
      const hi = Math.min(lo + (width << 1), n);
      let i0 = lo;
      let i1 = mid;
      for (let j = lo; j < hi; ++j) {
        const take = i0 < mid && (i1 >= hi || source[i0] <= source[i1]) ? i0++ : i1++;
        const value = source[take];
        target[j] = value;
        index[value] = j;
        band[value] = outBand;
        record();
      }
    }
    passRows.push(target.slice());
    pass++;
    record();
    [source, target] = [target, source];
    outBand ^= 1;
  }

  return { frames, passRows };
}

const mergesortInput = shuffled(mergesortSize, 20260813);

const { frames: mergesortFrames, passRows: mergesortPassRows } =
  traceMergesort(mergesortInput);

const MARGIN = { top: 20, right: 12, bottom: 24, left: 12 };

/**
 * The whole recursion laid out at once: time runs downward, one row per swap, and every
 * element is a thread that holds its column until a partition braids it across to another.
 */
export default function QuicksortThreads({ width }: { width: number }) {
  const height = Math.round(width * 1.45);
  const innerWidth = Math.max(1, width - MARGIN.left - MARGIN.right);
  const innerHeight = Math.max(1, height - MARGIN.top - MARGIN.bottom);
  const rowHeight = innerHeight / threadRows;
  const spacing = innerWidth / Math.max(1, threadSize - 1);
  const stroke = Math.max(1.2, Math.min(rowHeight * 0.6, spacing * 0.3));

  const color = useMemo(
    () => d3.scaleSequential([0, threadSize - 1], (t) => d3.interpolateTurbo(0.06 + 0.88 * t)),
    []
  );

  const paths = useMemo(() => {
    const x = (index: number) => index * spacing;
    const y = (time: number) => time * rowHeight;
    return threads.map(({ value, steps }) => {
      let d = `M${x(steps[0].index)},${y(0)}`;
      // Hold the column to the midpoint of the row, then cross into the new column.
      for (let k = 1; k < steps.length; k++) {
        d += `V${y(steps[k].time) - rowHeight / 2}L${x(steps[k].index)},${y(steps[k].time)}`;
      }
      return { value, d };
    });
  }, [spacing, rowHeight]);

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Quicksort drawn as threads. Twenty coloured threads start shuffled along the top, each swap braids two of them across each other on its own row, and by the bottom the colours have resolved into an ordered spectrum."
    >
      <text x={MARGIN.left} y={13} fill="var(--muted)" fontSize={11}>
        shuffled
      </text>
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        {paths.map(({ value, d }) => (
          // Halo before its own thread, so later threads pass visibly over earlier ones.
          <g key={value}>
            <path d={d} fill="none" stroke="var(--bg)" strokeWidth={stroke + 3} />
            <path
              d={d}
              fill="none"
              stroke={color(value)}
              strokeWidth={stroke}
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </g>
        ))}
      </g>
      <text x={MARGIN.left} y={height - 8} fill="var(--muted)" fontSize={11}>
        sorted
      </text>
      <text x={width - MARGIN.right} y={height - 8} textAnchor="end" fill="var(--muted)" fontSize={11}>
        {`${threadSize} elements · ${threadRows - 1} swaps`}
      </text>
    </svg>
  );
}
