// Radial Area Chart — Radial, route: jsx
// Source: radial-area-chart_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useId, useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from radialArea ----
type TemperatureDay = {
  date: Date;
  avg: number;
  min: number;
  max: number;
  minmin: number;
  maxmax: number;
};

/** Deterministic LCG: the seasonal series must survive hot reloads unchanged. */
function makeRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state * 1664525 + 1013904223) % 4294967296;
    return state / 4294967296;
  };
}

const YEAR_START_radialArea = Date.UTC(2000, 0, 1);
const DAY_MS = 86400000;
const DAYS = 366; // 2000 is a leap year, so the ring covers every calendar day

function seasonal(dayOfYear: number, phase: number, amplitude: number): number {
  return amplitude * Math.sin((2 * Math.PI * (dayOfYear - phase)) / DAYS);
}

/** Daily temperature band for a coastal-Californian climate: mild, peaking in September. */
const temperatureByDay: TemperatureDay[] = (() => {
  const random = makeRandom(20180101);
  return Array.from({ length: DAYS }, (_, i) => {
    const avg = 56 + seasonal(i, 165, 7.5) + (random() - 0.5) * 2.4;
    const min = avg - (6.5 + random() * 2.5);
    const max = avg + (7.5 + seasonal(i, 165, 2) + random() * 3);
    return {
      date: new Date(YEAR_START_radialArea + i * DAY_MS),
      avg: Math.round(avg * 10) / 10,
      min: Math.round(min * 10) / 10,
      max: Math.round(max * 10) / 10,
      minmin: Math.round((min - (5 + random() * 6)) * 10) / 10,
      maxmax: Math.round((max + (6 + random() * 14)) * 10) / 10
    };
  });
})();

const MAX_SIZE = 520;
const MARGIN = 18;
const INNER_RADIUS_RATIO = 0.42;
const LEGEND_ROW_HEIGHT = 16;

const YEAR_START = new Date(Date.UTC(2000, 0, 1));
const YEAR_END = new Date(Date.UTC(2001, 0, 1) - 1);

/** One row per day, plus the span of time the ring wraps around. */
export type Data = {
  days: { date: Date; avg: number; min: number; max: number; minmin: number; maxmax: number }[];
  start: Date;
  end: Date;
};

const DEMO: Data = { days: temperatureByDay, start: YEAR_START, end: YEAR_END };

export default function RadialAreaChart({
  data = DEMO,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.min(width, MAX_SIZE);
  const outerRadius = Math.min(width, height) / 2 - MARGIN;
  const innerRadius = outerRadius * INNER_RADIUS_RATIO;
  const monthPathId = useId().replace(/:/g, '');

  const months = useMemo(() => d3.utcMonths(data.start, data.end), [data]);

  const x = useMemo(
    () => d3.scaleUtc().domain([data.start, data.end]).range([0, 2 * Math.PI]),
    [data]
  );

  const y = useMemo(
    () =>
      d3
        .scaleRadial()
        .domain([
          d3.min(data.days, (d) => d.minmin) ?? 0,
          d3.max(data.days, (d) => d.maxmax) ?? 0
        ])
        .range([innerRadius, outerRadius]),
    [data, innerRadius, outerRadius]
  );

  // curveLinearClosed joins December back to January so the band reads as one ring.
  const band = useMemo(
    () =>
      d3
        .areaRadial<TemperatureDay>()
        .curve(d3.curveLinearClosed)
        .angle((d) => x(d.date)),
    [x]
  );

  const extremesPath = useMemo(
    () => band.innerRadius((d) => y(d.minmin)).outerRadius((d) => y(d.maxmax))(data.days),
    [data, band, y]
  );

  const rangePath = useMemo(
    () => band.innerRadius((d) => y(d.min)).outerRadius((d) => y(d.max))(data.days),
    [data, band, y]
  );

  const meanPath = useMemo(
    () =>
      d3
        .lineRadial<TemperatureDay>()
        .curve(d3.curveLinearClosed)
        .angle((d) => x(d.date))
        .radius((d) => y(d.avg))(data.days),
    [data, x, y]
  );

  const rings = useMemo(() => y.ticks(5).filter((t) => t > y.domain()[0]), [y]);

  if (width === 0) return null;

  // Abbreviated: "September" overruns one month of inner arc at every size this chart renders at.
  const formatMonth = d3.utcFormat('%b');

  return (
    <svg
      viewBox={`${-width / 2} ${-height / 2} ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Radial area chart of daily temperature range and recorded extremes over one year"
      strokeLinejoin="round"
      strokeLinecap="round"
    >
      <path d={extremesPath ?? undefined} fill="var(--accent)" fillOpacity={0.14} />
      <path d={rangePath ?? undefined} fill="var(--accent)" fillOpacity={0.32} />
      <path d={meanPath ?? undefined} fill="none" stroke="var(--accent)" strokeWidth={1.5} />

      <g fontSize={10} fill="var(--muted)">
        {months.map((month, i) => {
          const next = d3.utcMonth.offset(month, 1);
          const [x0, y0] = d3.pointRadial(x(month), innerRadius);
          const [x1, y1] = d3.pointRadial(x(month), outerRadius);
          const [ax, ay] = d3.pointRadial(x(next), innerRadius);
          return (
            <g key={month.toISOString()}>
              <line x1={x0} y1={y0} x2={x1} y2={y1} stroke="var(--line)" />
              <path
                id={`${monthPathId}-${i}`}
                fill="none"
                d={`M${x0},${y0}A${innerRadius},${innerRadius} 0,0,1 ${ax},${ay}`}
              />
              <text>
                <textPath href={`#${monthPathId}-${i}`} startOffset={6}>
                  {formatMonth(month)}
                </textPath>
              </text>
            </g>
          );
        })}
      </g>

      <g fill="none" textAnchor="middle" fontSize={10}>
        {rings.map((tick, i) => (
          <g key={tick}>
            <circle r={y(tick)} stroke="var(--line)" />
            {[-y(tick), y(tick)].map((offset) => (
              <text
                key={offset}
                y={offset}
                dy="0.35em"
                fill="var(--muted)"
                stroke="var(--bg)"
                strokeWidth={4}
                paintOrder="stroke"
              >
                {`${tick}${i ? '' : '°F'}`}
              </text>
            ))}
          </g>
        ))}
      </g>

      <g fontSize={10}>
        {[
          { label: 'record range', opacity: 0.14 },
          { label: 'average range', opacity: 0.32 },
          { label: 'daily average', opacity: 1 }
        ].map((entry, i) => (
          <g key={entry.label} transform={`translate(${-innerRadius * 0.62},${(i - 1) * LEGEND_ROW_HEIGHT})`}>
            <rect width={10} height={10} fill="var(--accent)" fillOpacity={entry.opacity} />
            <text x={15} y={5} dy="0.35em" fill="var(--text)">
              {entry.label}
            </text>
          </g>
        ))}
      </g>
    </svg>
  );
}
