// Grouped Radial Stacked Bar Chart — Radial, route: jsx
// Source: radial-stacked-bar-chart_3
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from radialStackedGrouped ----
type RegionLoad = {
  region: string;
  serving: number;
  training: number;
  analytics: number;
  backup: number;
};

const REGION_SERIES = ['serving', 'training', 'analytics', 'backup'] as const;

/**
 * Synthetic compute hours per day by region and workload class, listed alphabetically.
 * Input order is deliberately unsorted so the chart's ranked angular domain does visible work.
 * Totals are heavily skewed, as real regional load is: the tight off-center frame only fits
 * because a few hubs dominate and the tail is short.
 */
const regionLoad: RegionLoad[] = [
  { region: 'AMS', serving: 204, training: 158, analytics: 97, backup: 51 },
  { region: 'ARN', serving: 35, training: 21, analytics: 14, backup: 7 },
  { region: 'ATL', serving: 124, training: 96, analytics: 59, backup: 31 },
  { region: 'BOM', serving: 85, training: 45, analytics: 28, backup: 20 },
  { region: 'CDG', serving: 71, training: 43, analytics: 28, backup: 16 },
  { region: 'DFW', serving: 279, training: 167, analytics: 112, backup: 62 },
  { region: 'DUB', serving: 39, training: 30, analytics: 19, backup: 10 },
  { region: 'FRA', serving: 730, training: 380, analytics: 243, backup: 167 },
  { region: 'GRU', serving: 60, training: 31, analytics: 20, backup: 13 },
  { region: 'HKG', serving: 164, training: 99, analytics: 66, backup: 36 },
  { region: 'IAD', serving: 1278, training: 767, analytics: 511, backup: 284 },
  { region: 'ICN', serving: 129, training: 67, analytics: 43, backup: 29 },
  { region: 'JNB', serving: 29, training: 15, analytics: 10, backup: 6 },
  { region: 'LHR', serving: 531, training: 319, analytics: 212, backup: 118 },
  { region: 'MAD', serving: 42, training: 22, analytics: 14, backup: 9 },
  { region: 'MIA', serving: 50, training: 30, analytics: 20, backup: 10 },
  { region: 'NRT', serving: 365, training: 190, analytics: 122, backup: 83 },
  { region: 'ORD', serving: 206, training: 108, analytics: 69, backup: 47 },
  { region: 'SEA', serving: 104, training: 63, analytics: 42, backup: 23 },
  { region: 'SFO', serving: 784, training: 608, analytics: 372, backup: 196 },
  { region: 'SIN', serving: 376, training: 291, analytics: 179, backup: 94 },
  { region: 'SYD', serving: 56, training: 43, analytics: 27, backup: 14 },
  { region: 'TLV', serving: 27, training: 21, analytics: 13, backup: 7 },
  { region: 'YYZ', serving: 81, training: 63, analytics: 38, backup: 20 }
];

/** One row per angular band: its label plus a value for each stacked series. */
type Row = { region: string; serving: number; training: number; analytics: number; backup: number };

/** The rows, plus the series to stack in order from the inner ring outward. */
export type Data = { rows: Row[]; series: Exclude<keyof Row, 'region'>[] };

const DEMO: Data = { rows: regionLoad, series: [...REGION_SERIES] };

const MAX_SIZE = 560;
const INNER_RADIUS_RATIO = 0.2;
const OUTER_RADIUS_RATIO = 0.54;
// The frame sits above center: ranking puts the long bars at 12 o'clock and the short tail below.
const VIEWBOX_TOP_RATIO = 0.62;
const LEGEND_ROW_HEIGHT = 16;

const formatHours = d3.format(',');
const formatTick = d3.format('~s');

export default function RadialStackedBarGrouped({
  data = DEMO,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.min(width, MAX_SIZE);
  const innerRadius = height * INNER_RADIUS_RATIO;
  const outerRadius = height * OUTER_RADIUS_RATIO;

  const series: d3.Series<Row, string>[] = useMemo(
    () => d3.stack<Row, string>().keys(data.series)(data.rows),
    [data]
  );

  // The sorted variant: the angular domain is ranked by total, not left in input order.
  const x = useMemo(() => {
    const total = (d: Row) => data.series.reduce((sum, key) => sum + d[key], 0);
    return d3
      .scaleBand<string>()
      .domain(
        d3.groupSort(
          data.rows,
          (group) => -d3.sum(group, total),
          (d) => d.region
        )
      )
      .range([0, 2 * Math.PI])
      .align(0);
  }, [data]);

  const color = useMemo(
    () => d3.scaleOrdinal<string, string>().domain(data.series).range(d3.schemeObservable10),
    [data]
  );

  const y = useMemo(
    () =>
      d3
        .scaleRadial()
        .domain([0, d3.max(series, (s) => d3.max(s, (d) => d[1]) ?? 0) ?? 0])
        .range([innerRadius, outerRadius]),
    [series, innerRadius, outerRadius]
  );

  // A radial y-scale keeps the segments area-proportional rather than radius-proportional.
  const arc = useMemo(
    () =>
      d3
        .arc<d3.SeriesPoint<Row>>()
        .innerRadius((d) => y(d[0]))
        .outerRadius((d) => y(d[1]))
        .startAngle((d) => x(d.data.region) ?? 0)
        .endAngle((d) => (x(d.data.region) ?? 0) + x.bandwidth())
        .padAngle(1.5 / innerRadius)
        .padRadius(innerRadius),
    [x, y, innerRadius]
  );

  const rings = useMemo(() => y.ticks(6).slice(1), [y]);

  if (width === 0) return null;

  const topRing = rings[rings.length - 1] ?? 0;
  const midAngle = (region: string) => (x(region) ?? 0) + x.bandwidth() / 2;

  return (
    <svg
      viewBox={`${-width / 2} ${-height * VIEWBOX_TOP_RATIO} ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Radial stacked bar chart of synthetic daily compute hours by region and workload class, with regions ranked by total from largest at twelve o'clock"
    >
      {series.map((s) => (
        <g key={s.key} fill={color(s.key)}>
          {s.map((d) => (
            <path key={d.data.region} d={arc(d) ?? undefined}>
              <title>{`${d.data.region} ${s.key}\n${formatHours(d[1] - d[0])} hours`}</title>
            </path>
          ))}
        </g>
      ))}

      <g textAnchor="middle" fontSize={10} fill="var(--muted)">
        {data.rows.map((d) => {
          const angle = midAngle(d.region);
          // Labels on the left half read upside down unless their local frame is flipped.
          const isLeftHalf = (angle + Math.PI / 2) % (2 * Math.PI) < Math.PI;
          return (
            <g
              key={d.region}
              transform={`rotate(${(angle * 180) / Math.PI - 90}) translate(${innerRadius},0)`}
            >
              <line x2={-5} stroke="var(--line)" />
              <text
                transform={isLeftHalf ? 'rotate(90) translate(0,15)' : 'rotate(-90) translate(0,-8)'}
              >
                {d.region}
              </text>
            </g>
          );
        })}
      </g>

      {/* Radial ticks hang to the left of the vertical, clear of the tall ranked bars behind them. */}
      <g fill="none" textAnchor="end" fontSize={10}>
        <text x={-6} y={-y(topRing)} dy="-1em" fill="var(--muted)">
          Compute hours
        </text>
        {rings.map((tick) => (
          <g key={tick}>
            <circle r={y(tick)} stroke="var(--line)" strokeOpacity={0.8} />
            <text
              x={-6}
              y={-y(tick)}
              dy="0.35em"
              fill="var(--muted)"
              stroke="var(--bg)"
              strokeWidth={4}
              paintOrder="stroke"
            >
              {formatTick(tick)}
            </text>
          </g>
        ))}
      </g>

      <g fontSize={11}>
        {data.series.map((key, i) => (
          <g
            key={key}
            transform={`translate(${-innerRadius * 0.5},${
              (i - data.series.length / 2) * LEGEND_ROW_HEIGHT
            })`}
          >
            <rect width={10} height={10} fill={color(key)} />
            <text x={16} y={5} dy="0.35em" fill="var(--text)">
              {key}
            </text>
          </g>
        ))}
      </g>
    </svg>
  );
}
