// Radial Tidy Tree — Radial, route: jsx
// Source: radial-tree_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from radialTree ----
/** A module is either a leaf export or a grouping of them; only leaves are terminal. */
type ModuleNode = {
  name: string;
  children?: ModuleNode[];
};

/**
 * The D3 module ecosystem, 53 leaves at depths 2 and 3. The uneven depth is the point:
 * a tidy tree parks each leaf at its own depth's radius, where a dendrogram would pull
 * every one of them out to a single shared ring.
 */
const d3Modules: ModuleNode = {
  name: 'd3',
  children: [
    {
      name: 'Array',
      children: [
        {
          name: 'Summary',
          children: [{ name: 'mean' }, { name: 'median' }, { name: 'deviation' }, { name: 'quantile' }]
        },
        {
          name: 'Search',
          children: [{ name: 'bisect' }, { name: 'least' }, { name: 'greatest' }]
        },
        {
          name: 'Group',
          children: [{ name: 'group' }, { name: 'rollup' }, { name: 'cross' }]
        }
      ]
    },
    {
      name: 'Scale',
      children: [
        {
          name: 'Numeric',
          children: [
            { name: 'linear' },
            { name: 'log' },
            { name: 'pow' },
            { name: 'symlog' },
            { name: 'time' }
          ]
        },
        {
          name: 'Discrete',
          children: [
            { name: 'band' },
            { name: 'point' },
            { name: 'ordinal' },
            { name: 'quantize' }
          ]
        }
      ]
    },
    {
      name: 'Shape',
      children: [
        {
          name: 'Builders',
          children: [
            { name: 'arc' },
            { name: 'area' },
            { name: 'line' },
            { name: 'pie' },
            { name: 'stack' }
          ]
        },
        {
          name: 'Curves',
          children: [
            { name: 'basis' },
            { name: 'bundle' },
            { name: 'cardinal' },
            { name: 'natural' },
            { name: 'step' }
          ]
        }
      ]
    },
    {
      name: 'Hierarchy',
      children: [
        {
          name: 'Layouts',
          children: [
            { name: 'tree' },
            { name: 'cluster' },
            { name: 'pack' },
            { name: 'partition' },
            { name: 'treemap' }
          ]
        },
        { name: 'stratify' }
      ]
    },
    {
      name: 'Geo',
      children: [
        {
          name: 'Maps',
          children: [{ name: 'albers' }, { name: 'mercator' }, { name: 'orthographic' }]
        },
        { name: 'graticule' }
      ]
    },
    {
      name: 'Force',
      children: [{ name: 'center' }, { name: 'collide' }, { name: 'link' }, { name: 'manyBody' }]
    },
    {
      name: 'Color',
      children: [{ name: 'hcl' }, { name: 'hsl' }, { name: 'lab' }, { name: 'rgb' }]
    },
    {
      name: 'Time',
      children: [{ name: 'format' }, { name: 'interval' }, { name: 'ticks' }]
    },
    {
      name: 'Gesture',
      children: [{ name: 'brush' }, { name: 'drag' }, { name: 'zoom' }]
    }
  ]
};

/** A hierarchy root: every node carries a name, and internal nodes carry their children. */
export type Data = { name: string; children?: Data[] };

type Node = d3.HierarchyPointNode<Data>;
type Link = d3.HierarchyPointLink<Data>;

const MAX_SIZE = 560;
/** Radial room held outside the outermost ring for leaf labels. */
const LABEL_MARGIN = 78;
const FONT_SIZE = 10;
/** Mean advance width of 10px sans-serif, used to drop labels that would overflow. */
const CHAR_WIDTH = 5.6;
const LABEL_GAP = 6;

function pathOf(node: Node): string {
  return node
    .ancestors()
    .map((a) => a.data.name)
    .reverse()
    .join('/');
}

export default function RadialTree({
  data = d3Modules,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.min(width, MAX_SIZE);
  const halfSize = Math.min(width, height) / 2;
  const radius = Math.max(halfSize - LABEL_MARGIN, 0);

  // x is the angle in radians, y is the radius.
  const root = useMemo(() => {
    const hierarchy = d3
      .hierarchy(data)
      .sort((a, b) => d3.ascending(a.data.name, b.data.name));
    // Dividing by depth widens the wedge given to inner siblings, so crowded outer
    // subtrees do not squeeze the branches near the center.
    return d3
      .tree<Data>()
      .size([2 * Math.PI, radius])
      .separation((a, b) => (a.parent === b.parent ? 1 : 2) / a.depth)(hierarchy);
  }, [data, radius]);

  const link = useMemo(
    () =>
      d3
        .linkRadial<Link, Node>()
        .angle((d) => d.x)
        .radius((d) => d.y),
    []
  );

  const ringGap = radius / Math.max(root.height, 1);

  if (width === 0) return null;

  return (
    <svg
      viewBox={`${-width / 2} ${-height / 2} ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Radial tidy tree of the D3 module ecosystem"
    >
      <g fontSize={FONT_SIZE} strokeLinejoin="round">
        {root.links().map((l) => (
          <path
            key={pathOf(l.target)}
            d={link(l) ?? undefined}
            fill="none"
            stroke="var(--line)"
            strokeWidth={1.5}
          />
        ))}
        {root.descendants().map((d) => {
          const isLeaf = !d.children;
          // Leaf labels read outward, internal labels read back toward the parent ring;
          // past half a turn the glyphs are flipped, which swaps the local +x direction.
          const towardStart = (d.x < Math.PI) === isLeaf;
          const room = isLeaf ? halfSize - d.y - LABEL_GAP : ringGap - LABEL_GAP * 2;
          const fits = d.data.name.length * CHAR_WIDTH < room;
          const spin = (d.x * 180) / Math.PI - 90;

          return (
            <g
              key={pathOf(d)}
              transform={`rotate(${spin}) translate(${d.y},0) rotate(${d.x >= Math.PI ? 180 : 0})`}
            >
              <title>{pathOf(d)}</title>
              <circle r={2.5} fill={isLeaf ? 'var(--accent)' : 'var(--muted)'} />
              {fits && (
                <text
                  dy="0.32em"
                  x={towardStart ? LABEL_GAP : -LABEL_GAP}
                  textAnchor={towardStart ? 'start' : 'end'}
                  fill={isLeaf ? 'var(--text)' : 'var(--muted)'}
                  stroke="var(--bg)"
                  strokeWidth={3}
                  paintOrder="stroke"
                >
                  {d.data.name}
                </text>
              )}
            </g>
          );
        })}
      </g>
    </svg>
  );
}
