// Radial Dendrogram — Radial, route: jsx
// Source: radial-cluster_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from radialCluster ----
/** A node is a classification rank; only the nodes without children are instruments. */
interface InstrumentNode {
  name: string;
  children?: InstrumentNode[];
}

/**
 * Hornbostel-Sachs instrument classification, 43 leaves at depths 2 through 4.
 * The uneven depth is the point: d3.cluster drags every instrument out to the same
 * outer ring, so Theremin lands beside Saxophone two levels below it.
 */
const instrumentClasses: InstrumentNode = {
  name: 'Instruments',
  children: [
    {
      name: 'Idiophone',
      children: [
        {
          name: 'Struck',
          children: [
            { name: 'Marimba' },
            { name: 'Vibraphone' },
            { name: 'Xylophone' },
            { name: 'Glockenspiel' },
            { name: 'Celesta' }
          ]
        },
        { name: 'Shaken', children: [{ name: 'Maraca' }, { name: 'Cabasa' }] },
        { name: 'Scraped', children: [{ name: 'Guiro' }, { name: 'Washboard' }] }
      ]
    },
    {
      name: 'Membranophone',
      children: [
        {
          name: 'Struck',
          children: [
            { name: 'Timpani' },
            { name: 'Snare' },
            { name: 'Bass Drum' },
            { name: 'Bongo' },
            { name: 'Tabla' }
          ]
        },
        { name: 'Friction', children: [{ name: 'Cuica' }] }
      ]
    },
    {
      name: 'Chordophone',
      children: [
        {
          name: 'Plucked',
          children: [
            { name: 'Guitar' },
            { name: 'Harp' },
            { name: 'Lute' },
            { name: 'Sitar' },
            { name: 'Banjo' },
            { name: 'Mandolin' }
          ]
        },
        {
          name: 'Bowed',
          children: [
            { name: 'Violin' },
            { name: 'Viola' },
            { name: 'Cello' },
            { name: 'Erhu' },
            { name: 'Double Bass' }
          ]
        },
        { name: 'Hammered', children: [{ name: 'Piano' }, { name: 'Dulcimer' }] }
      ]
    },
    {
      name: 'Aerophone',
      children: [
        {
          name: 'Woodwind',
          children: [
            {
              name: 'Reed',
              children: [
                { name: 'Oboe' },
                { name: 'Clarinet' },
                { name: 'Bassoon' },
                { name: 'Saxophone' }
              ]
            },
            {
              name: 'Edge',
              children: [{ name: 'Flute' }, { name: 'Piccolo' }, { name: 'Recorder' }]
            }
          ]
        },
        {
          name: 'Brass',
          children: [
            { name: 'Trumpet' },
            { name: 'Trombone' },
            { name: 'Horn' },
            { name: 'Tuba' }
          ]
        },
        { name: 'Free Reed', children: [{ name: 'Accordion' }, { name: 'Harmonica' }] }
      ]
    },
    {
      name: 'Electrophone',
      children: [{ name: 'Theremin' }, { name: 'Synthesizer' }]
    }
  ]
};

/** A hierarchy root: every node carries a name, and internal nodes carry their children. */
export type Data = { name: string; children?: Data[] };

type Node = d3.HierarchyPointNode<Data>;
type Link = d3.HierarchyPointLink<Data>;

const MAX_SIZE = 560;
/** Radial room reserved outside the outer ring for the longest leaf label. */
const LABEL_SPACE = 84;
const FONT_SIZE = 10;
const LABEL_GAP = 6;

function pathOf(node: Node): string {
  return node
    .ancestors()
    .map((a) => a.data.name)
    .reverse()
    .join('/');
}

export default function RadialCluster({
  data = instrumentClasses,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.min(width, MAX_SIZE);
  const radius = Math.max(Math.min(width, height) / 2 - LABEL_SPACE, 0);

  // The layout's first dimension is the angle, the second the radius.
  const root = useMemo(() => {
    const hierarchy = d3
      .hierarchy(data)
      .sort((a, b) => d3.ascending(a.data.name, b.data.name));
    return d3
      .cluster<Data>()
      .size([2 * Math.PI, radius])
      // Cousins get twice a sibling's gap, shrinking with depth so outer rings do not splay.
      .separation((a, b) => (a.parent === b.parent ? 1 : 2) / a.depth)(hierarchy);
  }, [data, radius]);

  const link = useMemo(
    () =>
      d3
        .linkRadial<Link, Node>()
        .angle((d) => d.x)
        .radius((d) => d.y),
    []
  );

  // Leaves crowd as the chart shrinks; under one font size of arc the labels would collide.
  const labelsFit = useMemo(() => {
    const angles = root.leaves().map((d) => d.x);
    const gap = d3.min(angles.slice(1).map((a, i) => a - angles[i])) ?? 0;
    return gap * radius >= FONT_SIZE;
  }, [root, radius]);

  if (width === 0) return null;

  return (
    <svg
      viewBox={`${-width / 2} ${-height / 2} ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Radial dendrogram of the Hornbostel-Sachs instrument classification"
    >
      <g fill="none" stroke="var(--line)" strokeWidth={1.5}>
        {root.links().map((l) => (
          <path key={pathOf(l.target)} d={link(l) ?? undefined} />
        ))}
      </g>

      <g fontSize={FONT_SIZE} strokeLinejoin="round">
        {root.descendants().map((d) => {
          const isLeaf = !d.children;
          // Leaves read outward, ranks read inward; both flip on the left half to stay upright.
          const startsAtNode = d.x < Math.PI === isLeaf;
          const flipped = d.x >= Math.PI;

          return (
            <g
              key={pathOf(d)}
              transform={`rotate(${(d.x * 180) / Math.PI - 90}) translate(${d.y},0)`}
            >
              <title>{pathOf(d)}</title>
              <circle r={2.5} fill={isLeaf ? 'var(--accent)' : 'var(--muted)'} />
              {labelsFit && d.depth > 0 && (
                <text
                  transform={flipped ? 'rotate(180)' : undefined}
                  dy="0.31em"
                  x={startsAtNode ? LABEL_GAP : -LABEL_GAP}
                  textAnchor={startsAtNode ? 'start' : 'end'}
                  fill={isLeaf ? 'var(--text)' : 'var(--muted)'}
                  stroke="var(--bg)"
                  strokeWidth={3}
                  paintOrder="stroke"
                >
                  {d.data.name}
                </text>
              )}
            </g>
          );
        })}
      </g>
    </svg>
  );
}
