// Realtime Horizon Chart — Time Series, route: jsx
// Source: realtime-horizon-chart
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useId, useMemo, useState } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from realtimeHorizon ----
// The notebook drives its walks with Math.random. An LCG replaces it so the first paint is
// identical on the server, in the browser, and across hot reloads.
const SEED = 20260813;
const STEP = 0.06;

const SERIES_COUNT = 8;
const SAMPLE_COUNT = 220;
const PERIOD_MS = 250;

const advance = (seed: number) => (seed * 1664525 + 1013904223) >>> 0;

const walk = (value: number, seed: number) =>
  Math.max(0, Math.min(1, value + (seed / 4294967296 - 0.5) * STEP));

type WalkState = { series: number[][]; seed: number };

function initialWalk(): WalkState {
  let seed = SEED;
  const series: number[][] = [];
  for (let i = 0; i < SERIES_COUNT; i++) {
    const row: number[] = [];
    let value = 0.2 + (0.6 * i) / (SERIES_COUNT - 1);
    for (let j = 0; j < SAMPLE_COUNT; j++) {
      seed = advance(seed);
      value = walk(value, seed);
      row.push(value);
    }
    series.push(row);
  }
  return { series, seed };
}

/** One tick: every row shifts left by a sample and gains one new value on the right. */
function stepWalk({ series, seed }: WalkState): WalkState {
  let next = seed;
  const shifted = series.map((row) => {
    next = advance(next);
    return [...row.slice(1), walk(row[row.length - 1], next)];
  });
  return { series: shifted, seed: next };
}

const MARGIN = { top: 14, right: 12, bottom: 46, left: 30 };
const BANDS = 4;
const GAP = 2;
const SPAN_SECONDS = ((SAMPLE_COUNT - 1) * PERIOD_MS) / 1000;

// Reversed so magnitude reads as brightness against the gallery's dark ground.
const bandColors = [...d3.schemeGreens[BANDS + 1]].reverse().slice(0, BANDS);

export default function RealtimeHorizonChart({ width }: { width: number }) {
  const step = Math.max(16, Math.min(28, Math.round(width / 24)));
  const trackHeight = SERIES_COUNT * (step + GAP) - GAP;
  const height = MARGIN.top + trackHeight + MARGIN.bottom;
  const innerWidth = Math.max(0, width - MARGIN.left - MARGIN.right);
  const clipId = `horizon-row-${useId().replace(/:/g, '')}`;

  const [walk, setWalk] = useState(initialWalk);

  useEffect(() => {
    const id = window.setInterval(() => setWalk(stepWalk), PERIOD_MS);
    return () => window.clearInterval(id);
  }, []);

  const area = useMemo(() => {
    const x = d3.scaleLinear().domain([0, SAMPLE_COUNT - 1]).range([0, innerWidth]);
    const y = d3.scaleLinear().domain([0, 1]).range([0, -BANDS * step]);
    return d3
      .area<number>()
      .x((_, j) => x(j))
      .y0(0)
      .y1((d) => y(d));
  }, [innerWidth, step]);

  const paths = useMemo(() => walk.series.map((row) => area(row) ?? ''), [walk, area]);

  const xTicks: Tick[] = useMemo(() => {
    const t = d3.scaleLinear().domain([-SPAN_SECONDS, 0]).range([0, innerWidth]);
    return t
      .ticks(Math.max(2, Math.round(innerWidth / 90)))
      .map((v) => ({ value: v === 0 ? 'now' : `${v}s`, offset: t(v) }));
  }, [innerWidth]);

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label={`Realtime horizon chart: ${SERIES_COUNT} channels of a seeded random walk, each folded into ${BANDS} colour bands, with the newest sample at the right edge. Synthetic data from a seeded generator, not a real telemetry feed.`}
    >
      <defs>
        <clipPath id={clipId}>
          <rect x={0} y={0} width={innerWidth} height={step} />
        </clipPath>
      </defs>

      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        {paths.map((d, i) => (
          <g key={i} transform={`translate(0,${i * (step + GAP)})`}>
            {/* --bg, not --panel: the card is already --panel, so a lane needs to sit darker. */}
            <rect width={innerWidth} height={step} fill="var(--bg)" />
            <g clipPath={`url(#${clipId})`}>
              {bandColors.map((fill, band) => (
                <path
                  key={band}
                  d={d}
                  fill={fill}
                  transform={`translate(0,${(band + 1) * step})`}
                />
              ))}
            </g>
            <text
              x={-8}
              y={step / 2}
              dy="0.32em"
              textAnchor="end"
              fill="var(--muted)"
              fontSize={Math.min(11, step * 0.5)}
              style={{ fontVariantNumeric: 'tabular-nums' }}
            >
              {i}
            </text>
          </g>
        ))}

        {/* The write head: new samples land here and everything older slides left. */}
        <line
          x1={innerWidth}
          x2={innerWidth}
          y1={-4}
          y2={trackHeight + 4}
          stroke="var(--accent)"
          strokeWidth={1}
        />

        <AxisBottom ticks={xTicks} height={trackHeight + 10} width={innerWidth} />

        <text x={0} y={trackHeight + 42} fill="var(--muted)" fontSize={10}>
          Synthetic data from a seeded generator, not a real telemetry feed.
        </text>
      </g>
    </svg>
  );
}
