// Scatterplot with Shapes — Basic, route: jsx
// Source: scatterplot-with-shapes
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from scatterplotShapes ----
type IrisFlower = {
  sepalLength: number;
  sepalWidth: number;
  species: 'setosa' | 'versicolor' | 'virginica';
};

/** Every third row of Fisher's iris measurements, 17 per species. Fixed so the chart never reshuffles. */
const iris: IrisFlower[] = [
  { sepalLength: 5.1, sepalWidth: 3.5, species: 'setosa' },
  { sepalLength: 4.6, sepalWidth: 3.1, species: 'setosa' },
  { sepalLength: 4.6, sepalWidth: 3.4, species: 'setosa' },
  { sepalLength: 4.9, sepalWidth: 3.1, species: 'setosa' },
  { sepalLength: 4.8, sepalWidth: 3.0, species: 'setosa' },
  { sepalLength: 5.7, sepalWidth: 4.4, species: 'setosa' },
  { sepalLength: 5.7, sepalWidth: 3.8, species: 'setosa' },
  { sepalLength: 5.1, sepalWidth: 3.7, species: 'setosa' },
  { sepalLength: 4.8, sepalWidth: 3.4, species: 'setosa' },
  { sepalLength: 5.2, sepalWidth: 3.5, species: 'setosa' },
  { sepalLength: 4.8, sepalWidth: 3.1, species: 'setosa' },
  { sepalLength: 5.5, sepalWidth: 4.2, species: 'setosa' },
  { sepalLength: 5.5, sepalWidth: 3.5, species: 'setosa' },
  { sepalLength: 5.1, sepalWidth: 3.4, species: 'setosa' },
  { sepalLength: 4.4, sepalWidth: 3.2, species: 'setosa' },
  { sepalLength: 4.8, sepalWidth: 3.0, species: 'setosa' },
  { sepalLength: 5.3, sepalWidth: 3.7, species: 'setosa' },
  { sepalLength: 7.0, sepalWidth: 3.2, species: 'versicolor' },
  { sepalLength: 5.5, sepalWidth: 2.3, species: 'versicolor' },
  { sepalLength: 6.3, sepalWidth: 3.3, species: 'versicolor' },
  { sepalLength: 5.2, sepalWidth: 2.7, species: 'versicolor' },
  { sepalLength: 6.0, sepalWidth: 2.2, species: 'versicolor' },
  { sepalLength: 6.7, sepalWidth: 3.1, species: 'versicolor' },
  { sepalLength: 6.2, sepalWidth: 2.2, species: 'versicolor' },
  { sepalLength: 6.1, sepalWidth: 2.8, species: 'versicolor' },
  { sepalLength: 6.4, sepalWidth: 2.9, species: 'versicolor' },
  { sepalLength: 6.7, sepalWidth: 3.0, species: 'versicolor' },
  { sepalLength: 5.5, sepalWidth: 2.4, species: 'versicolor' },
  { sepalLength: 6.0, sepalWidth: 2.7, species: 'versicolor' },
  { sepalLength: 6.7, sepalWidth: 3.1, species: 'versicolor' },
  { sepalLength: 5.5, sepalWidth: 2.5, species: 'versicolor' },
  { sepalLength: 5.8, sepalWidth: 2.6, species: 'versicolor' },
  { sepalLength: 5.7, sepalWidth: 3.0, species: 'versicolor' },
  { sepalLength: 5.1, sepalWidth: 2.5, species: 'versicolor' },
  { sepalLength: 6.3, sepalWidth: 3.3, species: 'virginica' },
  { sepalLength: 6.3, sepalWidth: 2.9, species: 'virginica' },
  { sepalLength: 4.9, sepalWidth: 2.5, species: 'virginica' },
  { sepalLength: 7.2, sepalWidth: 3.6, species: 'virginica' },
  { sepalLength: 6.8, sepalWidth: 3.0, species: 'virginica' },
  { sepalLength: 6.4, sepalWidth: 3.2, species: 'virginica' },
  { sepalLength: 7.7, sepalWidth: 2.6, species: 'virginica' },
  { sepalLength: 5.6, sepalWidth: 2.8, species: 'virginica' },
  { sepalLength: 6.7, sepalWidth: 3.3, species: 'virginica' },
  { sepalLength: 6.1, sepalWidth: 3.0, species: 'virginica' },
  { sepalLength: 7.4, sepalWidth: 2.8, species: 'virginica' },
  { sepalLength: 6.3, sepalWidth: 2.8, species: 'virginica' },
  { sepalLength: 6.3, sepalWidth: 3.4, species: 'virginica' },
  { sepalLength: 6.9, sepalWidth: 3.1, species: 'virginica' },
  { sepalLength: 5.8, sepalWidth: 2.7, species: 'virginica' },
  { sepalLength: 6.7, sepalWidth: 3.0, species: 'virginica' },
  { sepalLength: 6.2, sepalWidth: 3.4, species: 'virginica' }
];

const irisSpecies: IrisFlower['species'][] = ['setosa', 'versicolor', 'virginica'];

const MARGIN = { top: 22, right: 20, bottom: 44, left: 52 };
const SYMBOL_SIZE = 90;

/** Points to plot, plus the species list that fixes one shape and colour per category. */
export type Data = {
  points: { species: string; sepalLength: number; sepalWidth: number }[];
  species: string[];
};

const DEMO: Data = { points: iris, species: irisSpecies };

export default function ScatterplotShapes({
  data = DEMO,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.round(width * 0.62);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const x = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain(d3.extent(data.points, (d) => d.sepalLength) as [number, number])
        .nice()
        .range([0, innerWidth]),
    [data, innerWidth]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain(d3.extent(data.points, (d) => d.sepalWidth) as [number, number])
        .nice()
        .range([innerHeight, 0]),
    [data, innerHeight]
  );

  const color = useMemo(
    () => d3.scaleOrdinal<string, string>().domain(data.species).range(d3.schemeObservable10),
    [data]
  );

  // One path string per species, reused by every point of that species.
  const shape = useMemo(() => {
    const paths = data.species.map(
      (_, i) => d3.symbol(d3.symbolsFill[i % d3.symbolsFill.length], SYMBOL_SIZE)() ?? ''
    );
    return d3.scaleOrdinal<string, string>().domain(data.species).range(paths);
  }, [data]);

  const xTicks: Tick[] = useMemo(
    () => x.ticks(Math.max(2, Math.round(innerWidth / 80))).map((v) => ({ value: String(v), offset: x(v) })),
    [x, innerWidth]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(6).map((v) => ({ value: String(v), offset: y(v) })),
    [y]
  );

  if (width === 0) return null;

  return (
    <svg viewBox={`0 0 ${width} ${height}`} width="100%" height={height} role="img"
         aria-label="Scatterplot of iris sepal width against sepal length, one shape and color per species">
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />

        <g className="axis">
          {xTicks.map(({ value, offset }) => (
            <line key={value} className="grid" x1={offset} x2={offset} y1={0} y2={innerHeight} />
          ))}
        </g>

        <g className="axis">
          <text x={innerWidth} y={innerHeight + MARGIN.bottom - 6} textAnchor="end">
            Sepal length (cm) →
          </text>
          <text x={-MARGIN.left} y={-8} textAnchor="start">
            ↑ Sepal width (cm)
          </text>
        </g>

        <g strokeWidth={1.5}>
          {data.points.map((d, i) => (
            <path
              key={`${d.species}-${i}`}
              transform={`translate(${x(d.sepalLength)},${y(d.sepalWidth)})`}
              d={shape(d.species)}
              fill={color(d.species)}
              fillOpacity={0.85}
            />
          ))}
        </g>

        <g className="axis" transform={`translate(${innerWidth - 92},4)`}>
          {data.species.map((species, i) => (
            <g key={species} transform={`translate(0,${i * 16})`}>
              <path d={shape(species)} fill={color(species)} />
              <text x={10} dy="0.32em" textAnchor="start">
                {species}
              </text>
            </g>
          ))}
        </g>
      </g>
    </svg>
  );
}
