// Sequences Sunburst — Hierarchy, route: jsx
// Source: sequences-sunburst
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo, useState } from 'react';
import * as d3 from 'd3';

// ---- inlined from sequences ----
type VisitSequence = { path: string; count: number };

/**
 * Synthetic site-visit paths, one row per complete root-to-leaf sequence.
 * "end" marks a real exit; a path without it was truncated at the six-step cap.
 */
const visitSequences: VisitSequence[] = [
  { path: 'home-end', count: 1240 },
  { path: 'home-product-end', count: 860 },
  { path: 'home-product-product-end', count: 430 },
  { path: 'home-product-product-account-end', count: 165 },
  { path: 'home-product-product-product-end', count: 148 },
  { path: 'home-product-product-product-product-end', count: 52 },
  { path: 'home-product-account-end', count: 210 },
  { path: 'home-product-search-end', count: 175 },
  { path: 'home-product-search-product-end', count: 120 },
  { path: 'home-search-end', count: 640 },
  { path: 'home-search-product-end', count: 380 },
  { path: 'home-search-product-product-end', count: 155 },
  { path: 'home-search-product-account-end', count: 96 },
  { path: 'home-search-search-end', count: 132 },
  { path: 'home-search-search-product-end', count: 88 },
  { path: 'home-account-end', count: 355 },
  { path: 'home-account-product-end', count: 128 },
  { path: 'home-account-home-end', count: 74 },
  { path: 'home-other-end', count: 220 },
  { path: 'home-other-home-end', count: 96 },
  { path: 'home-home-end', count: 180 },
  { path: 'home-home-product-end', count: 110 },
  { path: 'product-end', count: 1580 },
  { path: 'product-product-end', count: 720 },
  { path: 'product-product-product-end', count: 310 },
  { path: 'product-product-product-product-end', count: 118 },
  { path: 'product-product-product-product-product', count: 44 },
  { path: 'product-product-account-end', count: 145 },
  { path: 'product-account-end', count: 460 },
  { path: 'product-account-product-end', count: 132 },
  { path: 'product-search-end', count: 395 },
  { path: 'product-search-product-end', count: 225 },
  { path: 'product-search-product-product-end', count: 92 },
  { path: 'product-home-end', count: 340 },
  { path: 'product-home-product-end', count: 165 },
  { path: 'product-home-search-end', count: 84 },
  { path: 'product-other-end', count: 150 },
  { path: 'search-end', count: 830 },
  { path: 'search-product-end', count: 610 },
  { path: 'search-product-product-end', count: 265 },
  { path: 'search-product-product-product-end', count: 76 },
  { path: 'search-product-account-end', count: 118 },
  { path: 'search-search-end', count: 210 },
  { path: 'search-home-end', count: 195 },
  { path: 'search-home-product-end', count: 105 },
  { path: 'search-other-end', count: 88 },
  { path: 'account-end', count: 520 },
  { path: 'account-product-end', count: 185 },
  { path: 'account-home-end', count: 140 },
  { path: 'account-account-end', count: 95 },
  { path: 'other-end', count: 430 },
  { path: 'other-home-end', count: 175 },
  { path: 'other-product-end', count: 120 },
  { path: 'other-search-end', count: 68 }
];

type SeqNode = { name: string; value?: number; children?: SeqNode[] };
type Cell = d3.HierarchyRectangularNode<SeqNode>;

const MARGIN = { top: 8, right: 8, bottom: 8, left: 8 };
const MAX_DIAMETER = 540;
const CRUMB_HEIGHT = 30;
const CRUMB_GAP = 14;
const CRUMB_TIP = 10;
const MAX_STEPS = 6;
/** Arcs thinner than this are invisible at gallery size and only cost render time. */
const MIN_ANGLE = 0.001;

const STEPS = ['home', 'product', 'search', 'account', 'other', 'end'];
const formatCount = d3.format(',');

/** Visit paths as hyphen-joined step names with a count, plus the step names they draw on. */
export type Data = {
  sequences: { path: string; count: number }[];
  steps: string[];
};

const DEMO: Data = { sequences: visitSequences, steps: STEPS };

/** Rolls flat "a-b-end" paths up into a tree; interior counts are summed by the layout. */
function buildHierarchy(rows: VisitSequence[]): SeqNode {
  const root: SeqNode = { name: 'root', children: [] };
  for (const { path, count } of rows) {
    const parts = path.split('-');
    let node = root;
    parts.forEach((name, i) => {
      const children = node.children ?? (node.children = []);
      if (i === parts.length - 1) {
        children.push({ name, value: count });
        return;
      }
      let child = children.find((c) => c.name === name && c.children);
      if (!child) {
        child = { name, children: [] };
        children.push(child);
      }
      node = child;
    });
  }
  return root;
}

function keyOf(node: Cell): string {
  const names = node.ancestors().map((n) => n.data.name);
  return names.reverse().join('/');
}

/** Chevron pointing right, notched on the left for every crumb but the first. */
function crumbPoints(crumbWidth: number, index: number): string {
  const mid = CRUMB_HEIGHT / 2;
  const points = ['0,0', `${crumbWidth},0`, `${crumbWidth + CRUMB_TIP},${mid}`,
    `${crumbWidth},${CRUMB_HEIGHT}`, `0,${CRUMB_HEIGHT}`];
  if (index > 0) points.push(`${CRUMB_TIP},${mid}`);
  return points.join(' ');
}

export default function SequencesSunburst({
  data = DEMO,
  width
}: {
  data?: Data;
  width: number;
}) {
  const [hovered, setHovered] = useState<string | null>(null);

  const diameter = Math.max(1, Math.min(width - MARGIN.left - MARGIN.right, MAX_DIAMETER));
  const radius = diameter / 2;
  const height = MARGIN.top + CRUMB_HEIGHT + CRUMB_GAP + diameter + MARGIN.bottom;
  const crumbWidth = Math.max(44, Math.min(78, (width - 88) / MAX_STEPS));

  const color = useMemo(
    () =>
      d3
        .scaleOrdinal<string, string>()
        .domain(data.steps)
        .range([...d3.schemeObservable10.slice(0, 5), '#6b7075']),
    [data]
  );

  const root = useMemo(
    () =>
      d3.partition<SeqNode>().size([2 * Math.PI, radius * radius])(
        d3
          .hierarchy(buildHierarchy(data.sequences))
          .sum((d) => d.value ?? 0)
          .sort((a, b) => (b.value ?? 0) - (a.value ?? 0))
      ),
    [data, radius]
  );

  const cells = useMemo(
    () => root.descendants().filter((d) => d.depth > 0 && d.x1 - d.x0 > MIN_ANGLE),
    [root]
  );

  const byKey = useMemo(() => new Map(cells.map((d) => [keyOf(d), d])), [cells]);

  const arc = useMemo(
    () =>
      d3
        .arc<Cell>()
        .startAngle((d) => d.x0)
        .endAngle((d) => d.x1)
        .padAngle(1 / radius)
        .padRadius(radius)
        .innerRadius((d) => Math.sqrt(d.y0))
        .outerRadius((d) => Math.max(Math.sqrt(d.y0), Math.sqrt(d.y1) - 1)),
    [radius]
  );

  /** Hit target for each cell runs out to the rim, so thin outer rings stay hoverable. */
  const hitArc = useMemo(
    () =>
      d3
        .arc<Cell>()
        .startAngle((d) => d.x0)
        .endAngle((d) => d.x1)
        .innerRadius((d) => Math.sqrt(d.y0))
        .outerRadius(radius),
    [radius]
  );

  const hoveredCell = hovered ? byKey.get(hovered) ?? null : null;
  const sequence = hoveredCell ? hoveredCell.ancestors().reverse().slice(1) : [];
  const activeKeys = new Set(sequence.map(keyOf));
  const percentage = hoveredCell
    ? ((100 * (hoveredCell.value ?? 0)) / (root.value || 1)).toPrecision(3)
    : null;

  if (width === 0) return null;

  return (
    <svg
      viewBox={`${-width / 2} ${-height / 2} ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Sunburst of site visit paths rolled up from sequences, with a breadcrumb trail of the hovered path"
      fontSize={12}
    >
      <g transform={`translate(${-width / 2 + MARGIN.left},${-height / 2 + MARGIN.top})`}>
        {sequence.map((d, i) => (
          <g key={keyOf(d)} transform={`translate(${i * crumbWidth},0)`}>
            <polygon
              points={crumbPoints(crumbWidth, i)}
              fill={color(d.data.name)}
              stroke="var(--bg)"
            />
            <text
              x={(crumbWidth + CRUMB_TIP) / 2}
              y={CRUMB_HEIGHT / 2}
              dy="0.35em"
              textAnchor="middle"
              fill="var(--bg)"
            >
              {d.data.name}
            </text>
          </g>
        ))}
        {percentage && (
          <text
            x={sequence.length * crumbWidth + CRUMB_TIP + 10}
            y={CRUMB_HEIGHT / 2}
            dy="0.35em"
            fill="var(--muted)"
          >
            {percentage}%
          </text>
        )}
      </g>

      <g transform={`translate(0,${(CRUMB_HEIGHT + CRUMB_GAP) / 2})`}>
        <text textAnchor="middle" pointerEvents="none">
          <tspan x={0} y={0} dy="-0.2em" fontSize={34} fill="var(--text)">
            {percentage ? `${percentage}%` : formatCount(root.value ?? 0)}
          </tspan>
          <tspan x={0} y={0} dy="1.9em" fontSize={11} fill="var(--muted)">
            {percentage ? 'of visits begin this way' : 'visits, hover a segment'}
          </tspan>
        </text>
        {cells.map((d) => {
          const key = keyOf(d);
          return (
            <path
              key={key}
              d={arc(d) ?? undefined}
              fill={color(d.data.name)}
              fillOpacity={!hoveredCell || activeKeys.has(key) ? 1 : 0.3}
            />
          );
        })}
        <g fill="none" pointerEvents="all" onMouseLeave={() => setHovered(null)}>
          {cells.map((d) => {
            const key = keyOf(d);
            return (
              <path key={key} d={hitArc(d) ?? undefined} onMouseEnter={() => setHovered(key)} />
            );
          })}
        </g>
      </g>
    </svg>
  );
}
