// Sieve of Eratosthenes — Algorithms, route: jsx
// Source: original:essay/sieve
//
// Self-contained: every local import is inlined below. Requires only react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useMemo, useState } from 'react';

// ---- inlined from sieve ----
/**
 * Sieve of Eratosthenes over 1..300 as an event trace. Each sweeping prime p <= sqrt(300)
 * strikes its multiples starting at p*p — every smaller multiple was already struck, which
 * is the visible proof that stopping at the square root is legal. After the sweeps the
 * unstruck survivors resolve as prime in order. Fully deterministic, no randomness.
 */

const SIEVE_N = 300;
const SIEVE_COLS = 20;
const SIEVE_ROWS = 15;

/** Every prime <= sqrt(300); each sweeps in its own color. */
const SWEEPERS = [2, 3, 5, 7, 11, 13, 17];

interface SieveEvent {
  /** 'start' declares p prime and begins its sweep; 'strike' crosses out one multiple;
   *  'resolve' declares one unstruck survivor prime after the sweeps end. */
  kind: 'start' | 'strike' | 'resolve';
  /** The sweeping prime, or the resolved prime for 'resolve'. */
  p: number;
  /** The cell struck, for 'strike'; otherwise equal to p. */
  n: number;
}

const struck = new Set<number>([1]);
const events: SieveEvent[] = [];

for (const p of SWEEPERS) {
  events.push({ kind: 'start', p, n: p });
  for (let k = p * p; k <= SIEVE_N; k += p) {
    struck.add(k);
    events.push({ kind: 'strike', p, n: k });
  }
}

for (let x = 2; x <= SIEVE_N; ++x) {
  if (!struck.has(x) && !SWEEPERS.includes(x)) events.push({ kind: 'resolve', p: x, n: x });
}

const sieveEvents = events;
const PRIME_COUNT = SWEEPERS.length + events.filter((e) => e.kind === 'resolve').length;

const TICK_MS = 45;
const TARGET_TICKS = 240;
const HOLD_TICKS = 40;
const PRIME_COLORS = ['#4269d0', '#efb118', '#ff725c', '#6cc5b0', '#3ca951', '#ff8ab7', '#a463f2'];
const colorOf = (p: number) => PRIME_COLORS[SWEEPERS.indexOf(p)] ?? 'var(--accent)';

export default function SieveOfEratosthenes({ width }: { width: number }) {
  const cell = Math.max(1, width) / SIEVE_COLS;
  const gridHeight = cell * SIEVE_ROWS;
  const height = Math.round(gridHeight + 22);

  // The SSR frame is the finished sieve, all 62 primes resolved; the effect replays it.
  const [step, setStep] = useState(sieveEvents.length);

  useEffect(() => {
    const perTick = Math.max(1, Math.ceil(sieveEvents.length / TARGET_TICKS));
    const end = sieveEvents.length + perTick * HOLD_TICKS;
    setStep(0);
    const id = window.setInterval(() => setStep((s) => (s >= end ? 0 : s + perTick)), TICK_MS);
    return () => window.clearInterval(id);
  }, []);

  const cellSquare = useMemo(() => {
    const inset = cell * 0.06;
    const side = cell - 2 * inset;
    return (n: number) =>
      `M${(((n - 1) % SIEVE_COLS) * cell + inset).toFixed(1)},${((((n - 1) / SIEVE_COLS) | 0) * cell + inset).toFixed(1)}h${side.toFixed(1)}v${side.toFixed(1)}h${(-side).toFixed(1)}Z`;
  }, [cell]);

  /** The numbers never move or restyle, so the layer is built once per cell size. */
  const numbers = useMemo(
    () => (
      <g fontFamily="ui-monospace, SFMono-Regular, Menlo, monospace">
        {Array.from({ length: SIEVE_N }, (_, k) => (
          <text
            key={k + 1}
            x={((k % SIEVE_COLS) + 0.5) * cell}
            y={(((k / SIEVE_COLS) | 0) + 0.5) * cell + cell * 0.12}
            textAnchor="middle"
            fontSize={cell * 0.32}
            fill={k === 0 ? 'var(--muted)' : 'var(--text)'}
            opacity={k === 0 ? 0.4 : 0.9}
          >
            {k + 1}
          </text>
        ))}
      </g>
    ),
    [cell]
  );

  const shown = Math.min(step, sieveEvents.length);

  const state = useMemo(() => {
    const strikesByPrime = new Map<number, string[]>();
    const resolved: number[] = [];
    let sweeping = -1;
    for (let k = 0; k < shown; ++k) {
      const event = sieveEvents[k];
      if (event.kind === 'start') {
        resolved.push(event.p);
        sweeping = event.p;
      } else if (event.kind === 'strike') {
        const list = strikesByPrime.get(event.p) ?? [];
        list.push(cellSquare(event.n));
        strikesByPrime.set(event.p, list);
      } else {
        resolved.push(event.n);
        sweeping = -1;
      }
    }
    return {
      layers: [...strikesByPrime].map(([p, squares]) => ({ p, d: squares.join('') })),
      resolved,
      sweeping
    };
  }, [shown, cellSquare]);

  if (width === 0) return null;

  const current = shown > 0 && shown < sieveEvents.length ? sieveEvents[shown - 1] : null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Sieve of Eratosthenes over 1 to 300: each prime up to the square root of 300 sweeps its multiples in its own color, strikes layering translucently on composites like 210, and when the sweeps stop at 17 the untouched survivors — the primes — are already decided"
    >
      {numbers}
      {state.layers.map(({ p, d }) => (
        <path key={p} d={d} fill={colorOf(p)} opacity={0.28} />
      ))}
      {state.sweeping > 0 && (
        <path d={cellSquare(state.sweeping)} fill={colorOf(state.sweeping)} opacity={0.55} />
      )}
      {current?.kind === 'strike' && (
        <path d={cellSquare(current.n)} fill={colorOf(current.p)} opacity={0.85} />
      )}
      {state.resolved.map((p) => (
        <circle
          key={p}
          cx={(((p - 1) % SIEVE_COLS) + 0.5) * cell}
          cy={((((p - 1) / SIEVE_COLS) | 0) + 0.5) * cell}
          r={cell * 0.38}
          fill="none"
          stroke="var(--accent)"
          strokeWidth={Math.max(1, cell * 0.05)}
        />
      ))}
      <text x={4} y={height - 6} fill="var(--muted)" fontSize={11}>
        {state.sweeping > 0
          ? `p = ${state.sweeping}, striking its multiples from ${state.sweeping}×${state.sweeping} up`
          : shown > 0
            ? 'swept only to √300 ≈ 17 · every untouched number is already prime'
            : `numbers 1..${SIEVE_N}`}
      </text>
      <text x={width - 4} y={height - 6} textAnchor="end" fill="var(--muted)" fontSize={11}>
        {state.resolved.length === PRIME_COUNT
          ? `all ${PRIME_COUNT} primes ≤ ${SIEVE_N} found`
          : `${state.resolved.length} primes found`}
      </text>
    </svg>
  );
}
