// Spike Map — Geo, route: jsx
// Source: spike-map_2
//
// Self-contained: every local import is inlined below. Requires only d3, geojson, react, topojson-client, topojson-specification, us-atlas, world-atlas.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { feature, mesh } from 'topojson-client';
import countries110m from 'world-atlas/countries-110m.json';
import statesUs from 'us-atlas/states-10m.json';
import type { GeometryCollection, Topology } from 'topojson-specification';
import type { Feature, FeatureCollection, Geometry, MultiLineString } from 'geojson';
import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from geo ----
// The atlases ship untyped JSON. One cast per topology at this boundary keeps every
// consumer strict, and converting here means each chart does not re-derive the same
// geometry at module load.

type Named = { name: string };
type NamedFeature = Feature<Geometry, Named>;

const world = countries110m as unknown as Topology<{
  countries: GeometryCollection<Named>;
  land: GeometryCollection;
}>;

const us = statesUs as unknown as Topology<{
  states: GeometryCollection<Named>;
  nation: GeometryCollection;
}>;

const worldCountries = feature(
  world,
  world.objects.countries
) as FeatureCollection<Geometry, Named>;

const worldLand = feature(world, world.objects.land) as FeatureCollection<Geometry>;

/** Shared borders only, so neighbouring outlines are stroked once instead of twice. */
const worldBorders = mesh(
  world,
  world.objects.countries,
  (a, b) => a !== b
) as MultiLineString;

const usNation = feature(us, us.objects.nation) as FeatureCollection<Geometry>;

const usStateBorders = mesh(
  us,
  us.objects.states,
  (a, b) => a !== b
) as MultiLineString;

/**
 * The 50 states plus DC. geoAlbersUsa cannot project FIPS ids of 60 and above
 * (territories) and returns null for them, which becomes a NaN centroid downstream.
 * Use this rather than the raw collection for anything Albers-projected.
 */
const usStates: NamedFeature[] = (
  feature(us, us.objects.states) as FeatureCollection<Geometry, Named>
).features.filter((d) => Number(d.id) < 60);

const usStatesCollection: FeatureCollection<Geometry, Named> = {
  type: 'FeatureCollection',
  features: usStates
};

/**
 * FNV-1a over an id, run through the murmur3 finalizer. Two-character FIPS ids barely
 * differ, and without the finalizer they map to a near-constant. Returns [0, 1).
 * Charts use it to synthesize per-region values deterministically instead of fetching.
 */
function hashUnit(id: string, salt = 0): number {
  let h = 2166136261 ^ salt;
  for (let i = 0; i < id.length; i++) {
    h = Math.imul(h ^ id.charCodeAt(i), 16777619);
  }
  h ^= h >>> 16;
  h = Math.imul(h, 2246822507);
  h ^= h >>> 13;
  return (h >>> 0) / 4294967296;
}

const MARGIN = { top: 8, right: 8, bottom: 24, left: 8 };
const SPIKE_WIDTH = 7;

/** Deterministic stand-in for a per-state metric: FNV-1a over the FIPS id, then the
 *  murmur3 finalizer, which two-character ids need to spread at all. Cubed so a
 *  handful of states tower over the rest the way real population does. */
function syntheticValue(id: string): number {
  let hash = 2166136261;
  for (let index = 0; index < id.length; index += 1) {
    hash = Math.imul(hash ^ id.charCodeAt(index), 16777619);
  }
  hash ^= hash >>> 16;
  hash = Math.imul(hash, 2246822507);
  hash ^= hash >>> 13;
  hash = Math.imul(hash, 3266489909);
  hash ^= hash >>> 16;
  return Math.round(250_000 + ((hash >>> 0) / 4294967295) ** 3 * 38_000_000);
}

/** One value per region, keyed by the FIPS id of the state it is drawn on. */
export type Data = { id: string; name: string; value: number }[];

const DEMO: Data = usStates.map((d) => ({
  id: String(d.id),
  name: d.properties.name,
  value: syntheticValue(String(d.id))
}));

function spikePath(length: number): string {
  return `M${-SPIKE_WIDTH / 2},0L0,${-length}L${SPIKE_WIDTH / 2},0`;
}

const formatValue = d3.format(',.0f');

export default function SpikeMap({ data = DEMO, width }: { data?: Data; width: number }) {
  const height = Math.round(width * 0.62);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const path = useMemo(() => {
    const projection = d3.geoAlbersUsa().fitSize([innerWidth, innerHeight], usNation);
    return d3.geoPath(projection);
  }, [innerWidth, innerHeight]);

  const length = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([0, d3.max(data, (d) => d.value) ?? 0])
        .range([0, innerHeight * 0.42]),
    [data, innerHeight]
  );

  // Tall spikes first so the short ones stay clickable on top of them.
  const spikes = useMemo(() => {
    const byId = new Map(data.map((d) => [d.id, d]));
    return usStates
      .flatMap((feature) => {
        const datum = byId.get(String(feature.id));
        if (!datum) return [];
        const [cx, cy] = path.centroid(feature);
        return [{ ...datum, cx, cy }];
      })
      .filter((d) => Number.isFinite(d.cx) && Number.isFinite(d.cy))
      .sort((a, b) => d3.descending(a.value, b.value));
  }, [data, path]);

  const legend = useMemo(() => {
    const ticks = length.ticks(4).slice(1);
    const format = length.tickFormat(4, 's');
    return ticks.map((value, index) => ({
      value,
      label: format(value),
      x: innerWidth - (ticks.length - index) * 26
    }));
  }, [length, innerWidth]);

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Spike map of a synthetic per-state metric across the United States"
    >
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <path d={path(usNation) ?? undefined} fill="var(--line)" />
        <path
          d={path(usStateBorders) ?? undefined}
          fill="none"
          stroke="var(--muted)"
          strokeOpacity={0.5}
          strokeLinejoin="round"
        />

        <g fill="var(--accent)" fillOpacity={0.45} stroke="var(--accent)" strokeWidth={0.5}>
          {spikes.map((d) => (
            <path key={d.id} transform={`translate(${d.cx},${d.cy})`} d={spikePath(length(d.value))}>
              <title>{`${d.name}\n${formatValue(d.value)}`}</title>
            </path>
          ))}
        </g>

        <g className="axis" transform={`translate(0,${innerHeight})`} textAnchor="middle">
          {legend.map((d) => (
            <g key={d.value} transform={`translate(${d.x},0)`}>
              <path
                d={spikePath(length(d.value))}
                fill="var(--accent)"
                fillOpacity={0.45}
                stroke="var(--accent)"
                strokeWidth={0.5}
              />
              <text dy="1em">{d.label}</text>
            </g>
          ))}
        </g>
      </g>
    </svg>
  );
}
