// Spilhaus Shoreline Map — Geo, route: jsx
// Source: spilhaus-shoreline-map
//
// Self-contained: every local import is inlined below. Requires only d3, geojson, react, topojson-client, topojson-specification, us-atlas, world-atlas.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { feature, mesh } from 'topojson-client';
import countries110m from 'world-atlas/countries-110m.json';
import statesUs from 'us-atlas/states-10m.json';
import type { GeometryCollection, Topology } from 'topojson-specification';
import type { Feature, FeatureCollection, Geometry, MultiLineString } from 'geojson';
import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from geo ----
// The atlases ship untyped JSON. One cast per topology at this boundary keeps every
// consumer strict, and converting here means each chart does not re-derive the same
// geometry at module load.

type Named = { name: string };
type NamedFeature = Feature<Geometry, Named>;

const world = countries110m as unknown as Topology<{
  countries: GeometryCollection<Named>;
  land: GeometryCollection;
}>;

const us = statesUs as unknown as Topology<{
  states: GeometryCollection<Named>;
  nation: GeometryCollection;
}>;

const worldCountries = feature(
  world,
  world.objects.countries
) as FeatureCollection<Geometry, Named>;

const worldLand = feature(world, world.objects.land) as FeatureCollection<Geometry>;

/** Shared borders only, so neighbouring outlines are stroked once instead of twice. */
const worldBorders = mesh(
  world,
  world.objects.countries,
  (a, b) => a !== b
) as MultiLineString;

const usNation = feature(us, us.objects.nation) as FeatureCollection<Geometry>;

const usStateBorders = mesh(
  us,
  us.objects.states,
  (a, b) => a !== b
) as MultiLineString;

/**
 * The 50 states plus DC. geoAlbersUsa cannot project FIPS ids of 60 and above
 * (territories) and returns null for them, which becomes a NaN centroid downstream.
 * Use this rather than the raw collection for anything Albers-projected.
 */
const usStates: NamedFeature[] = (
  feature(us, us.objects.states) as FeatureCollection<Geometry, Named>
).features.filter((d) => Number(d.id) < 60);

const usStatesCollection: FeatureCollection<Geometry, Named> = {
  type: 'FeatureCollection',
  features: usStates
};

/**
 * FNV-1a over an id, run through the murmur3 finalizer. Two-character FIPS ids barely
 * differ, and without the finalizer they map to a near-constant. Returns [0, 1).
 * Charts use it to synthesize per-region values deterministically instead of fetching.
 */
function hashUnit(id: string, salt = 0): number {
  let h = 2166136261 ^ salt;
  for (let i = 0; i < id.length; i++) {
    h = Math.imul(h ^ id.charCodeAt(i), 16777619);
  }
  h ^= h >>> 16;
  h = Math.imul(h, 2246822507);
  h ^= h >>> 13;
  return (h >>> 0) / 4294967296;
}

const MARGIN = { top: 8, right: 8, bottom: 8, left: 8 };

const sphere: d3.GeoSphere = { type: 'Sphere' };
const graticule = d3.geoGraticule10();

// Spilhaus framing: an oblique stereographic centred on the South Pacific with a
// near-hemispheric clip, which unrolls the world ocean into a single connected body and
// pushes every landmass out to the rim. Rotation, centre and clip angle are the
// notebook's; only the scale divisor is looser (10.1 there) so the sphere edge stays in
// frame instead of being cropped away.
const ROTATE: [number, number] = [95, 45];
const CENTER: [number, number] = [30, -5];
const CLIP_ANGLE = 166;
const SCALE_DIVISOR = 12.5;

export default function SpilhausShorelineMap({ width }: { width: number }) {
  const height = width;
  const size = Math.min(width - MARGIN.left - MARGIN.right, height - MARGIN.top - MARGIN.bottom);

  const paths = useMemo(() => {
    if (size <= 0) return null;
    const projection = d3
      .geoStereographic()
      .rotate(ROTATE)
      .center(CENTER)
      .clipAngle(CLIP_ANGLE)
      .translate([size / 2, size / 2])
      .scale(size / SCALE_DIVISOR)
      .precision(0.5);
    const path = d3.geoPath(projection);
    return {
      outline: path(sphere) ?? '',
      land: path(worldLand) ?? '',
      grid: path(graticule) ?? '',
    };
  }, [size]);

  if (width === 0 || !paths) return null;

  // Sphere and land as one subpath with even-odd winding is the ocean: inside the globe
  // and outside every landmass. Clipping the blurred land to it puts the glow offshore.
  const oceanClip = paths.outline + paths.land;
  const blur = size / 90;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Spilhaus projection of the world ocean as a single continuous body, land pushed to the rim"
    >
      <defs>
        <filter id="spilhaus-glow" x="-20%" y="-20%" width="140%" height="140%">
          <feGaussianBlur stdDeviation={blur} />
        </filter>
        <clipPath id="spilhaus-ocean">
          <path d={oceanClip} clipRule="evenodd" />
        </clipPath>
        <clipPath id="spilhaus-sphere">
          <path d={paths.outline} />
        </clipPath>
      </defs>
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <path d={paths.outline} fill="var(--line)" />
        <path d={paths.land} fill="var(--bg)" />
        <g clipPath="url(#spilhaus-ocean)">
          <path d={paths.land} fill="var(--accent)" filter="url(#spilhaus-glow)" />
        </g>
        <path
          d={paths.grid}
          clipPath="url(#spilhaus-sphere)"
          fill="none"
          stroke="var(--muted)"
          strokeWidth={0.4}
          strokeOpacity={0.25}
        />
        <path d={paths.land} fill="none" stroke="var(--muted)" strokeWidth={0.6} />
        <path
          d={paths.outline}
          fill="none"
          stroke="var(--muted)"
          strokeWidth={1.2}
          strokeOpacity={0.7}
        />
      </g>
    </svg>
  );
}
