// Stacked Bar Chart — Comparison, route: jsx
// Source: stacked-bar-chart_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from stackedBar ----
// Electricity generation mix by country, most recent full year, terawatt-hours.
// Approximate published figures, rounded for readability.
const GENERATION_SOURCES = ['Coal', 'Natural gas', 'Nuclear', 'Hydro', 'Wind & solar'];

type CountryGenerationRow = { country: string; values: number[] };

const electricityGenerationByCountry: CountryGenerationRow[] = [
  { country: 'China', values: [5240, 380, 420, 1350, 1080] },
  { country: 'United States', values: [780, 1720, 780, 260, 660] },
  { country: 'India', values: [1420, 60, 45, 155, 180] },
  { country: 'Russia', values: [180, 560, 220, 215, 5] },
  { country: 'Japan', values: [310, 350, 65, 85, 110] },
  { country: 'Germany', values: [140, 65, 0, 20, 175] },
  { country: 'South Korea', values: [190, 165, 175, 6, 30] },
  { country: 'Canada', values: [35, 75, 95, 380, 45] },
  { country: 'Brazil', values: [15, 55, 15, 400, 55] },
  { country: 'France', values: [5, 20, 340, 55, 55] },
  { country: 'Indonesia', values: [220, 65, 0, 25, 5] },
  { country: 'Australia', values: [125, 55, 0, 15, 55] }
];

const MARGIN = { top: 40, right: 16, bottom: 32, left: 56 };
const LEGEND_SWATCH = 11;

const formatValue = d3.format(',');

/** One row per country whose `values` line up, in order, with the `sources` they stack. */
export type Data = {
  sources: string[];
  rows: { country: string; values: number[] }[];
};

const DEMO: Data = { sources: GENERATION_SOURCES, rows: electricityGenerationByCountry };

export default function StackedBarChart({ data = DEMO, width }: { data?: Data; width: number }) {
  const height = Math.round(width * 0.58);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const color = useMemo(
    () =>
      d3
        .scaleOrdinal<string, string>()
        .domain(data.sources)
        .range(d3.schemeObservable10)
        .unknown('var(--muted)'),
    [data]
  );

  const rows = useMemo(
    () => [...data.rows].sort((a, b) => d3.sum(b.values) - d3.sum(a.values)),
    [data]
  );

  const series = useMemo(
    () =>
      d3
        .stack<CountryGenerationRow, string>()
        .keys(data.sources)
        .value((d, key) => d.values[data.sources.indexOf(key)] ?? 0)(rows),
    [data, rows]
  );

  const x = useMemo(
    () =>
      d3
        .scaleBand<string>()
        .domain(rows.map((d) => d.country))
        .range([0, Math.max(innerWidth, 0)])
        .padding(0.2),
    [rows, innerWidth]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([0, d3.max(series, (d) => d3.max(d, (p) => p[1])) ?? 0])
        .nice()
        .range([Math.max(innerHeight, 0), 0]),
    [series, innerHeight]
  );

  const xTicks: Tick[] = useMemo(
    () => x.domain().map((v) => ({ value: v, offset: (x(v) ?? 0) + x.bandwidth() / 2 })),
    [x]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(6).map((v) => ({ value: formatValue(v), offset: y(v) })),
    [y]
  );

  if (width === 0) return null;

  const bandwidth = x.bandwidth();
  const legendStep = Math.min(150, innerWidth / data.sources.length);

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label={
        'Stacked bar chart of electricity generation by country and source, in terawatt-hours. ' +
        'Countries run left to right sorted by total generation descending, each bar stacking ' +
        'coal, natural gas, nuclear, hydro, and wind plus solar.'
      }
    >
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />

        {series.map((layer) => (
          <g key={layer.key} fill={color(layer.key)}>
            {layer.map((point) => {
              const left = x(point.data.country) ?? 0;
              const segmentHeight = Math.max(y(point[0]) - y(point[1]), 0);
              return (
                <rect
                  key={point.data.country}
                  x={left}
                  y={y(point[1])}
                  width={bandwidth}
                  height={segmentHeight}
                >
                  <title>{`${point.data.country} · ${layer.key}: ${formatValue(
                    point[1] - point[0]
                  )} TWh`}</title>
                </rect>
              );
            })}
          </g>
        ))}

        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />

        <g transform="translate(0,-24)">
          {data.sources.map((source, i) => (
            <g key={source} transform={`translate(${i * legendStep},0)`}>
              <rect width={LEGEND_SWATCH} height={LEGEND_SWATCH} fill={color(source)} />
              <text x={LEGEND_SWATCH + 5} y={LEGEND_SWATCH - 1} fontSize={11} fill="var(--text)">
                {source}
              </text>
            </g>
          ))}
        </g>
      </g>
    </svg>
  );
}
