// Stacked Area Chart — Basic, route: jsx
// Source: stacked-area-chart_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from stackedArea ----
/**
 * US unemployed persons by industry, 2000-2010 (BLS), sampled quarterly and
 * narrowed to the eight largest industries so the series stay legible.
 */
const INDUSTRIES = [
  'Retail & Wholesale',
  'Manufacturing',
  'Leisure & Hospitality',
  'Business Services',
  'Construction',
  'Education & Health',
  'Government',
  'Finance'
] as const;

type Industry = (typeof INDUSTRIES)[number];

type UnemploymentRow = { date: Date } & Record<Industry, number>;

const QUARTERS: [string, ...number[]][] = [
  ['2000-01-01', 1000, 734, 782, 655, 745, 353, 430, 228],
  ['2000-04-01', 793, 736, 658, 517, 447, 329, 269, 197],
  ['2000-07-01', 792, 708, 786, 636, 384, 478, 545, 190],
  ['2000-10-01', 739, 693, 691, 504, 417, 339, 391, 224],
  ['2001-01-01', 908, 911, 806, 734, 836, 428, 463, 232],
  ['2001-04-01', 820, 855, 744, 655, 596, 341, 369, 232],
  ['2001-07-01', 833, 1054, 813, 731, 447, 513, 548, 289],
  ['2001-10-01', 941, 1065, 903, 910, 535, 486, 429, 281],
  ['2002-01-01', 1212, 1377, 947, 1120, 1211, 586, 486, 267],
  ['2002-04-01', 1222, 1322, 953, 951, 855, 493, 447, 292],
  ['2002-07-01', 1132, 1185, 999, 1075, 594, 671, 645, 345],
  ['2002-10-01', 1212, 1046, 956, 962, 680, 517, 499, 312],
  ['2003-01-01', 1342, 1302, 1049, 1112, 1196, 559, 571, 327],
  ['2003-04-01', 1201, 1199, 986, 1076, 772, 611, 440, 323],
  ['2003-07-01', 1387, 1193, 1020, 1021, 677, 697, 749, 284],
  ['2003-10-01', 1189, 1041, 933, 1014, 651, 639, 500, 303],
  ['2004-01-01', 1389, 1110, 1097, 1070, 994, 662, 511, 403],
  ['2004-04-01', 1248, 1004, 925, 752, 849, 589, 433, 312],
  ['2004-07-01', 1163, 1019, 965, 790, 610, 725, 741, 307],
  ['2004-10-01', 1138, 884, 853, 781, 635, 526, 561, 358],
  ['2005-01-01', 1302, 889, 993, 958, 1079, 613, 555, 252],
  ['2005-04-01', 1131, 793, 882, 714, 693, 591, 478, 255],
  ['2005-07-01', 1194, 883, 929, 804, 509, 635, 683, 309],
  ['2005-10-01', 1050, 800, 796, 748, 519, 628, 502, 255],
  ['2006-01-01', 1203, 778, 910, 825, 868, 593, 457, 233],
  ['2006-04-01', 972, 745, 882, 644, 674, 558, 414, 293],
  ['2006-07-01', 1083, 736, 867, 735, 633, 659, 659, 329],
  ['2006-10-01', 972, 618, 795, 768, 456, 531, 424, 211],
  ['2007-01-01', 1166, 752, 911, 885, 922, 563, 476, 233],
  ['2007-04-01', 872, 749, 822, 689, 853, 555, 408, 231],
  ['2007-07-01', 1089, 621, 920, 743, 617, 665, 704, 307],
  ['2007-10-01', 907, 729, 911, 675, 641, 534, 492, 307],
  ['2008-01-01', 1120, 837, 1176, 893, 1099, 576, 471, 285],
  ['2008-04-01', 919, 796, 874, 736, 1057, 551, 373, 324],
  ['2008-07-01', 1329, 908, 1172, 866, 783, 776, 770, 350],
  ['2008-10-01', 1313, 1007, 1126, 1052, 1078, 797, 552, 434],
  ['2009-01-01', 1794, 1711, 1487, 1445, 1744, 792, 652, 571],
  ['2009-04-01', 1833, 1968, 1322, 1448, 1737, 964, 575, 561],
  ['2009-07-01', 1854, 1988, 1600, 1531, 1687, 1269, 1129, 570],
  ['2009-10-01', 1919, 1884, 1604, 1488, 1744, 1280, 785, 646],
  ['2010-01-01', 2154, 1918, 1804, 1614, 2194, 1175, 948, 623]
];

const unemploymentByIndustry: UnemploymentRow[] = QUARTERS.map(
  ([date, ...counts]) => {
    const row = { date: new Date(date) } as UnemploymentRow;
    INDUSTRIES.forEach((industry, i) => {
      row[industry] = counts[i] ?? 0;
    });
    return row;
  }
);

const MARGIN = { top: 48, right: 16, bottom: 36, left: 56 };
const LEGEND_COLUMNS = 4;

/** Rows carrying a date and one number per industry, plus the industries to stack, bottom first. */
export type Data = { industries: readonly Industry[]; rows: UnemploymentRow[] };

const DEMO: Data = { industries: INDUSTRIES, rows: unemploymentByIndustry };

export default function StackedAreaChart({
  data = DEMO,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.round(width * 0.58);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const series = useMemo(
    () =>
      d3
        .stack<UnemploymentRow, Industry>()
        .keys(data.industries)
        .value((row, key) => row[key])(data.rows),
    [data]
  );

  // Dates parse as UTC midnight, so the axis must read them in UTC too.
  const x = useMemo(
    () =>
      d3
        .scaleUtc()
        .domain(d3.extent(data.rows, (d) => d.date) as [Date, Date])
        .range([0, innerWidth]),
    [data, innerWidth]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([0, d3.max(series, (s) => d3.max(s, (p) => p[1]) ?? 0) ?? 0])
        .nice()
        .range([innerHeight, 0]),
    [series, innerHeight]
  );

  const color = useMemo(
    () =>
      d3
        .scaleOrdinal<Industry, string>()
        .domain(data.industries)
        .range(d3.schemeObservable10),
    [data]
  );

  const area = useMemo(
    () =>
      d3
        .area<d3.SeriesPoint<UnemploymentRow>>()
        .x((p) => x(p.data.date))
        .y0((p) => y(p[0]))
        .y1((p) => y(p[1]))
        .curve(d3.curveMonotoneX),
    [x, y]
  );

  const paths = useMemo(
    () => series.map((s) => ({ key: s.key, d: area(s) ?? '', fill: color(s.key) })),
    [series, area, color]
  );

  const xTicks: Tick[] = useMemo(
    () => x.ticks(6).map((v) => ({ value: d3.utcFormat('%Y')(v), offset: x(v) })),
    [x]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(5).map((v) => ({ value: d3.format('~s')(v), offset: y(v) })),
    [y]
  );

  if (width === 0) return null;

  const legendColumnWidth = innerWidth / LEGEND_COLUMNS;

  return (
    <svg viewBox={`0 0 ${width} ${height}`} width="100%" height={height} role="img"
         aria-label="Stacked area chart of US unemployed persons by industry, 2000 to 2010">
      <g transform={`translate(${MARGIN.left},12)`}>
        {data.industries.map((industry, i) => (
          <g
            key={industry}
            transform={`translate(${(i % LEGEND_COLUMNS) * legendColumnWidth},${
              Math.floor(i / LEGEND_COLUMNS) * 16
            })`}
          >
            <rect width={9} height={9} y={-8} rx={2} fill={color(industry)} />
            <text x={14} fontSize={11} fill="currentColor">
              {industry}
            </text>
          </g>
        ))}
      </g>
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />
        {paths.map((p) => (
          <path key={p.key} d={p.d} fill={p.fill} fillOpacity={0.9}>
            <title>{p.key}</title>
          </path>
        ))}
      </g>
    </svg>
  );
}
