// Streamgraph Transitions — Animation, route: ref
// Source: streamgraph-transitions
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useRef } from 'react';
import * as d3 from 'd3';

// ---- inlined from streamgraphTransitions ----
/** mulberry32, seeded so every layer's shape is byte-identical on every reload. */
function createRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const SERIES_COUNT = 12;
const POINT_COUNT = 120;
const BUMPS_PER_SERIES = 8;
const FRAME_COUNT = 4;

// Lee Byron's bump generator: a handful of Gaussian humps summed into one series.
function bump(series: number[], length: number, random: () => number): void {
  const x = 1 / (0.1 + random());
  const y = 2 * random() - 0.5;
  const z = 10 / (0.1 + random());
  for (let i = 0; i < length; ++i) {
    const w = (i / length - y) * z;
    series[i] += x * Math.exp(-w * w);
  }
}

function bumps(length: number, count: number, random: () => number): number[] {
  const series = new Array(length).fill(0);
  for (let i = 0; i < count; ++i) bump(series, length, random);
  return series;
}

function transpose(series: number[][]): number[][] {
  return Array.from({ length: POINT_COUNT }, (_, i) => series.map((s) => s[i]));
}

/** Rows (one per x position, POINT_COUNT of them), each holding SERIES_COUNT values — ready for d3.stack. */
type FrameRows = number[][];

const random = createRandom(1);

const FRAMES: FrameRows[] = Array.from({ length: FRAME_COUNT }, () =>
  transpose(Array.from({ length: SERIES_COUNT }, () => bumps(POINT_COUNT, BUMPS_PER_SERIES, random)))
);

const DURATION = 1500;
const INTERVAL = 2500; // matches the notebook's delay(1000) + duration(1500) pacing

// The notebook lets a <select> choose the offset and re-randomizes on every tick;
// here both the offset and the stack order cycle on a timer so the shape morph is visible
// without an interactive control.
const OFFSETS = [d3.stackOffsetWiggle, d3.stackOffsetSilhouette, d3.stackOffsetExpand, d3.stackOffsetNone];
const ORDERS = [d3.stackOrderInsideOut, d3.stackOrderNone];

/** One frame per step of the cycle; a frame is rows by x position, each row a value per series. */
export type Data = number[][][];

export default function StreamgraphTransitions({ data = FRAMES, width }:
  { data?: Data; width: number }) {
  const ref = useRef<SVGSVGElement>(null);
  const height = Math.min(500, Math.round(width * 0.54));

  useEffect(() => {
    if (!ref.current || width === 0) return;

    const pointCount = data[0].length;
    const seriesCount = data[0][0].length;

    const svg = d3.select(ref.current);
    svg.selectAll('*').remove(); // StrictMode runs this effect twice

    const x = d3.scaleLinear([0, pointCount - 1], [0, width]);
    const y = d3.scaleLinear([0, 1], [height, 0]);

    const area = d3
      .area<d3.SeriesPoint<number[]>>()
      .x((_d, i) => x(i))
      .y0((d) => y(d[0]))
      .y1((d) => y(d[1]));

    const stack = d3
      .stack<number[], number>()
      .keys(d3.range(seriesCount))
      .value((d, key) => d[key]);

    const color = (i: number) => d3.interpolateCool(i / (seriesCount - 1));

    function layersFor(step: number) {
      const frame = data[step % data.length];
      stack.offset(OFFSETS[step % OFFSETS.length]);
      stack.order(ORDERS[Math.floor(step / OFFSETS.length) % ORDERS.length]);
      const layers = stack(frame);
      y.domain([
        d3.min(layers, (l) => d3.min(l, (d) => d[0])) ?? 0,
        d3.max(layers, (l) => d3.max(l, (d) => d[1])) ?? 1
      ]);
      return layers;
    }

    let path = svg
      .selectAll<SVGPathElement, d3.Series<number[], number>>('path')
      .data(layersFor(0))
      .join('path')
      .attr('d', area)
      .attr('fill', (_d, i) => color(i));

    let step = 0;
    const timer = d3.interval(() => {
      step += 1;
      path = path
        .data(layersFor(step))
        .join('path')
        .attr('fill', (_d, i) => color(i));

      path.transition().duration(DURATION).ease(d3.easeCubicInOut).attr('d', area);
    }, INTERVAL);

    return () => {
      timer.stop();
      path.interrupt();
      svg.selectAll('*').remove();
    };
  }, [data, width, height]);

  if (width === 0) return null;

  return (
    <svg
      ref={ref}
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Streamgraph cycling through stack offsets and orderings"
    />
  );
}
