// Styled Axes — Encoding, route: jsx
// Source: styled-axes
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

/** The one series every panel draws, in chronological order. */
export type Data = { date: Date; value: number }[];

type Point = Data[number];

const VALUES = [
  0.42, 0.55, 0.51, 0.68, 0.74, 0.66, 0.83, 0.95, 0.88, 1.02, 1.15, 1.09, 1.24,
  1.18, 1.33, 1.47, 1.39, 1.52, 1.44, 1.61, 1.73, 1.66, 1.79, 1.88, 1.82
];

// Monthly from 2010-08 to 2012-08, in millions, matching the source notebook's domain.
const SERIES: Data = VALUES.map((value, i) => ({
  date: new Date(Date.UTC(2010, 7 + i, 1)),
  value
}));

type Treatment = {
  name: string;
  marginLeft: number;
  domain: boolean;
  tickOut: boolean;
  grid: boolean;
  insideLabels: boolean;
  color: string;
  labelColor: string;
};

const TREATMENTS: Treatment[] = [
  { name: 'Default axes', marginLeft: 34, domain: true, tickOut: true, grid: false, insideLabels: false, color: 'var(--line)', labelColor: 'var(--muted)' },
  { name: 'Domain lines removed', marginLeft: 34, domain: false, tickOut: true, grid: false, insideLabels: false, color: 'var(--line)', labelColor: 'var(--muted)' },
  { name: 'Inward ticks', marginLeft: 34, domain: true, tickOut: false, grid: false, insideLabels: false, color: 'var(--line)', labelColor: 'var(--muted)' },
  { name: 'Ticks as gridlines', marginLeft: 34, domain: false, tickOut: true, grid: true, insideLabels: false, color: 'var(--line)', labelColor: 'var(--muted)' },
  { name: 'Units on the top tick', marginLeft: 6, domain: false, tickOut: true, grid: true, insideLabels: true, color: 'var(--line)', labelColor: 'var(--muted)' },
  { name: 'Colored axes', marginLeft: 34, domain: true, tickOut: true, grid: false, insideLabels: false, color: 'var(--accent)', labelColor: 'var(--accent)' }
];

const PAD = { top: 8, right: 10, bottom: 20 };
const CAPTION = 18;
const GAP = 16;

function Panel({ data, treatment, width, height }:
  { data: Data; treatment: Treatment; width: number; height: number }) {
  const innerWidth = width - treatment.marginLeft - PAD.right;
  const innerHeight = height - PAD.top - PAD.bottom;

  const x = useMemo(
    () =>
      d3
        .scaleUtc()
        .domain([data[0].date, data[data.length - 1].date])
        .range([0, innerWidth]),
    [data, innerWidth]
  );

  const y = useMemo(() => d3.scaleLinear().domain([0, 2]).range([innerHeight, 0]), [innerHeight]);

  const areaPath = useMemo(
    () =>
      d3
        .area<Point>()
        .x((d) => x(d.date))
        .y0(innerHeight)
        .y1((d) => y(d.value))(data) ?? '',
    [data, x, y, innerHeight]
  );

  const linePath = useMemo(
    () =>
      d3
        .line<Point>()
        .x((d) => x(d.date))
        .y((d) => y(d.value))(data) ?? '',
    [data, x, y]
  );

  // Ticks every three months, but only the January ticks carry a label.
  const xTicks = useMemo(
    () =>
      x.ticks(d3.utcMonth.every(3) ?? d3.utcMonth).map((d) => ({
        key: d.toISOString(),
        offset: x(d),
        label: +d === +d3.utcYear(d) ? String(d.getUTCFullYear()) : null
      })),
    [x]
  );

  const yTicks = useMemo(() => y.ticks(4), [y]);
  const topTick = yTicks[yTicks.length - 1];

  // The unit lives on the topmost label; the rest are padded with a non-breaking
  // space so the digits line up under the dollar sign.
  const formatY = (v: number) =>
    treatment.insideLabels
      ? v === topTick
        ? `$${v.toFixed(1)} million`
        : `\u00a0${v.toFixed(1)}`
      : v.toFixed(1);

  return (
    <g transform={`translate(${treatment.marginLeft},${PAD.top})`}>
      <path d={areaPath} fill="var(--accent)" fillOpacity={0.16} />
      <path d={linePath} fill="none" stroke="var(--accent)" strokeWidth={1.5} />

      <g>
        {yTicks.map((v) => (
          <g key={v} transform={`translate(0,${y(v)})`}>
            {treatment.grid ? (
              <line
                x1={0}
                x2={innerWidth}
                stroke={treatment.color}
                strokeOpacity={v === 0 ? 1 : 0.5}
                strokeDasharray={v === 0 ? undefined : '2,2'}
              />
            ) : (
              <line x1={0} x2={treatment.tickOut ? -5 : 5} stroke={treatment.color} />
            )}
            <text
              x={treatment.insideLabels ? 4 : -8}
              dy={treatment.insideLabels ? -4 : '0.32em'}
              textAnchor={treatment.insideLabels ? 'start' : 'end'}
              fill={treatment.labelColor}
              fontSize={10}
            >
              {formatY(v)}
            </text>
          </g>
        ))}
        {treatment.domain && !treatment.grid && (
          <line y1={0} y2={innerHeight} stroke={treatment.color} />
        )}
      </g>

      <g transform={`translate(0,${innerHeight})`}>
        {treatment.domain && <line x1={0} x2={innerWidth} stroke={treatment.color} />}
        {xTicks.map((t) => (
          <g key={t.key} transform={`translate(${t.offset},0)`}>
            <line y2={treatment.tickOut ? 5 : -5} stroke={treatment.color} />
            {t.label && (
              <text y={15} textAnchor="middle" fill={treatment.labelColor} fontSize={10}>
                {t.label}
              </text>
            )}
          </g>
        ))}
      </g>
    </g>
  );
}

export default function StyledAxes({ data = SERIES, width }: { data?: Data; width: number }) {
  const columns = width < 560 ? 2 : 3;
  const rows = Math.ceil(TREATMENTS.length / columns);
  const panelWidth = (width - GAP * (columns - 1)) / columns;
  const panelHeight = Math.round(panelWidth * 0.72);
  const cellHeight = panelHeight + CAPTION;
  const height = rows * cellHeight + GAP * (rows - 1);

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Small multiples of one revenue series, each panel demonstrating a different axis treatment"
    >
      {TREATMENTS.map((treatment, i) => (
        <g
          key={treatment.name}
          transform={`translate(${(i % columns) * (panelWidth + GAP)},${
            Math.floor(i / columns) * (cellHeight + GAP)
          })`}
        >
          <text x={0} y={10} fill="var(--text)" fontSize={11} fontWeight={600}>
            {treatment.name}
          </text>
          <g transform={`translate(0,${CAPTION})`}>
            <Panel data={data} treatment={treatment} width={panelWidth} height={panelHeight} />
          </g>
        </g>
      ))}
    </svg>
  );
}
