// Sunburst — Hierarchy, route: jsx
// Source: sunburst_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from icicle ----
/** A node is either a leaf carrying a byte count or a package carrying children, never both. */
type PackageNode = {
  name: string;
  value?: number;
  children?: PackageNode[];
};

/** Invented source tree for a front-end monorepo: 4 levels, 49 leaves, sizes in bytes. */
const sourceTree: PackageNode = {
  name: 'app',
  children: [
    {
      name: 'core',
      children: [
        {
          name: 'runtime',
          children: [
            { name: 'scheduler', value: 14820 },
            { name: 'dispatcher', value: 9340 },
            { name: 'lifecycle', value: 6210 },
            { name: 'registry', value: 3980 }
          ]
        },
        {
          name: 'state',
          children: [
            { name: 'store', value: 18450 },
            { name: 'selectors', value: 7120 },
            { name: 'reducers', value: 11360 },
            { name: 'middleware', value: 5240 }
          ]
        },
        {
          name: 'events',
          children: [
            { name: 'emitter', value: 4610 },
            { name: 'bus', value: 6890 },
            { name: 'queue', value: 3470 }
          ]
        }
      ]
    },
    {
      name: 'render',
      children: [
        {
          name: 'dom',
          children: [
            { name: 'reconciler', value: 26340 },
            { name: 'patch', value: 12780 },
            { name: 'hydrate', value: 8150 },
            { name: 'portal', value: 3320 }
          ]
        },
        {
          name: 'layout',
          children: [
            { name: 'flexbox', value: 15960 },
            { name: 'grid', value: 13470 },
            { name: 'measure', value: 5810 }
          ]
        },
        {
          name: 'paint',
          children: [
            { name: 'rasterizer', value: 19230 },
            { name: 'compositor', value: 10640 },
            { name: 'shaders', value: 7480 }
          ]
        }
      ]
    },
    {
      name: 'data',
      children: [
        {
          name: 'fetch',
          children: [
            { name: 'client', value: 11290 },
            { name: 'cache', value: 8730 },
            { name: 'retry', value: 3160 }
          ]
        },
        {
          name: 'parse',
          children: [
            { name: 'json', value: 6540 },
            { name: 'csv', value: 5070 },
            { name: 'xml', value: 4290 }
          ]
        },
        {
          name: 'schema',
          children: [
            { name: 'validator', value: 14110 },
            { name: 'migrate', value: 6720 }
          ]
        }
      ]
    },
    {
      name: 'ui',
      children: [
        {
          name: 'controls',
          children: [
            { name: 'button', value: 4930 },
            { name: 'slider', value: 7260 },
            { name: 'toggle', value: 3540 },
            { name: 'menu', value: 12480 },
            { name: 'dialog', value: 9870 }
          ]
        },
        {
          name: 'charts',
          children: [
            { name: 'axis', value: 16720 },
            { name: 'legend', value: 6350 },
            { name: 'tooltip', value: 5480 },
            { name: 'brush', value: 9140 }
          ]
        },
        {
          name: 'theme',
          children: [
            { name: 'tokens', value: 5620 },
            { name: 'palette', value: 4180 },
            { name: 'typography', value: 6930 }
          ]
        }
      ]
    },
    {
      name: 'tooling',
      children: [
        {
          name: 'build',
          children: [
            { name: 'bundler', value: 22410 },
            { name: 'minifier', value: 13850 },
            { name: 'sourcemap', value: 7290 }
          ]
        },
        {
          name: 'test',
          children: [
            { name: 'runner', value: 15340 },
            { name: 'matchers', value: 8620 },
            { name: 'fixtures', value: 4750 }
          ]
        },
        {
          name: 'lint',
          children: [
            { name: 'rules', value: 10260 },
            { name: 'formatter', value: 6480 }
          ]
        }
      ]
    }
  ]
};

/** Root of the hierarchy: a node is a leaf carrying a `value` or a branch carrying `children`. */
export type Data = { name: string; value?: number; children?: Data[] };

type Cell = d3.HierarchyRectangularNode<Data>;

const MARGIN = 8;
const MAX_DIAMETER = 640;
/** Below this chord length a label would overlap its neighbours; skip it instead. */
const LABEL_MIN_ARC = 14;
/** Arcs thinner than this are invisible at gallery size and only cost render time. */
const MIN_ANGLE = 0.001;

const formatBytes = d3.format(',d');

function keyOf(node: Cell): string {
  return node
    .ancestors()
    .map((a) => a.data.name)
    .reverse()
    .join('/');
}

/** Every cell takes the colour of the depth-1 package it descends from. */
function packageOf(node: Cell): string {
  let current = node;
  while (current.depth > 1 && current.parent) current = current.parent;
  return current.data.name;
}

/** Rotate a label to follow its arc, flipping the far side upright. */
function labelTransform(d: Cell): string {
  const x = ((d.x0 + d.x1) / 2) * (180 / Math.PI);
  const y = (d.y0 + d.y1) / 2;
  return `rotate(${x - 90}) translate(${y},0) rotate(${x < 180 ? 0 : 180})`;
}

export default function Sunburst({ data = sourceTree, width }: { data?: Data; width: number }) {
  const diameter = Math.max(1, Math.min(width - MARGIN * 2, MAX_DIAMETER));
  const radius = diameter / 2;
  const height = diameter + MARGIN * 2;

  const root = useMemo(
    () =>
      d3.partition<Data>().size([2 * Math.PI, radius])(
        d3
          .hierarchy(data)
          .sum((d) => d.value ?? 0)
          .sort((a, b) => (b.value ?? 0) - (a.value ?? 0))
      ),
    [data, radius]
  );

  const cells = useMemo(
    () => root.descendants().filter((d) => d.depth > 0 && d.x1 - d.x0 > MIN_ANGLE),
    [root]
  );

  const color = useMemo(
    () =>
      d3
        .scaleOrdinal<string, string>()
        .domain((data.children ?? []).map((d) => d.name))
        .range(d3.schemeObservable10),
    [data]
  );

  const arc = useMemo(
    () =>
      d3
        .arc<Cell>()
        .startAngle((d) => d.x0)
        .endAngle((d) => d.x1)
        .padAngle((d) => Math.min((d.x1 - d.x0) / 2, 0.005))
        .padRadius(radius / 2)
        .innerRadius((d) => d.y0)
        .outerRadius((d) => Math.max(d.y0, d.y1 - 1)),
    [radius]
  );

  if (width === 0) return null;

  return (
    <svg
      viewBox={`${-width / 2} ${-height / 2} ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Sunburst of a source package hierarchy, sized by file bytes and coloured by top-level package"
      fontSize={10}
    >
      <g fillOpacity={0.6}>
        {cells.map((d) => (
          <path key={keyOf(d)} d={arc(d) ?? undefined} fill={color(packageOf(d))}>
            <title>{`${keyOf(d)}\n${formatBytes(d.value ?? 0)}`}</title>
          </path>
        ))}
      </g>
      <g pointerEvents="none" textAnchor="middle">
        {cells
          .filter((d) => ((d.y0 + d.y1) / 2) * (d.x1 - d.x0) > LABEL_MIN_ARC)
          .map((d) => (
            <text key={keyOf(d)} transform={labelTransform(d)} dy="0.35em" fill="var(--text)">
              {d.data.name}
            </text>
          ))}
      </g>
    </svg>
  );
}
