// Threshold Encoding — Encoding, route: jsx
// Source: threshold-encoding
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

const MARGIN = { top: 22, right: 20, bottom: 36, left: 52 };
const DAYS = 365;

// The gradient is referenced by id, so it must not collide with any other chart's defs.
const GRADIENT_ID = 'threshold-encoding-hardstop';

// schemeRdBu[3] is [red, neutral, blue]; the neutral middle is unused here.
const ABOVE = d3.schemeRdBu[3][0];
const BELOW = d3.schemeRdBu[3][2];

/** Readings in chronological order; the threshold drawn is their median temperature. */
export type Data = { date: Date; temperature: number }[];

/** Seeded LCG over a seasonal curve, not Math.random, so the series survives hot reloads. */
function temperatureSeries(count: number): Data {
  let seed = 20240101;
  return Array.from({ length: count }, (_, i) => {
    seed = (seed * 1103515245 + 12345) % 2147483648;
    const seasonal = 52 + 22 * Math.sin(((i - 110) / count) * 2 * Math.PI);
    return { date: new Date(2024, 0, 1 + i), temperature: seasonal + (seed / 2147483648 - 0.5) * 13 };
  });
}

const DEMO: Data = temperatureSeries(DAYS);

export default function ThresholdEncoding({ data = DEMO, width }: { data?: Data; width: number }) {
  const height = Math.round(width * 0.5);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const threshold = useMemo(() => d3.median(data, (d) => d.temperature) ?? 0, [data]);

  const x = useMemo(
    () =>
      d3
        .scaleTime()
        .domain(d3.extent(data, (d) => d.date) as [Date, Date])
        .range([0, innerWidth]),
    [data, innerWidth]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain(d3.extent(data, (d) => d.temperature) as [number, number])
        .nice()
        .range([innerHeight, 0]),
    [data, innerHeight]
  );

  const path = useMemo(
    () =>
      d3
        .line<Data[number]>()
        .curve(d3.curveStep)
        .x((d) => x(d.date))
        .y((d) => y(d.temperature))(data) ?? '',
    [data, x, y]
  );

  // Two stops at one offset make a hard color switch exactly at the threshold's y position.
  const stopOffset = useMemo(
    () => (innerHeight > 0 ? Math.min(1, Math.max(0, y(threshold) / innerHeight)) : 0),
    [y, threshold, innerHeight]
  );

  const xTicks: Tick[] = useMemo(
    () => x.ticks(6).map((v) => ({ value: d3.timeFormat('%b')(v), offset: x(v) })),
    [x]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(5).map((v) => ({ value: `${v}°F`, offset: y(v) })),
    [y]
  );

  if (width === 0) return null;

  const thresholdY = y(threshold);

  return (
    <svg viewBox={`0 0 ${width} ${height}`} width="100%" height={height} role="img"
         aria-label="Daily temperature drawn red above the median and blue below it">
      <defs>
        <linearGradient id={GRADIENT_ID} gradientUnits="userSpaceOnUse"
                        x1={0} y1={0} x2={0} y2={innerHeight}>
          <stop offset={stopOffset} stopColor={ABOVE} />
          <stop offset={stopOffset} stopColor={BELOW} />
        </linearGradient>
      </defs>
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />
        <line x1={0} x2={innerWidth} y1={thresholdY} y2={thresholdY} stroke="var(--text)"
              strokeWidth={1} strokeDasharray="5 4" strokeOpacity={0.55} />
        <text x={innerWidth} y={thresholdY - 6} textAnchor="end" fill="var(--muted)" fontSize={11}>
          {`median ${d3.format('.1f')(threshold)}°F`}
        </text>
        <path d={path} fill="none" stroke={`url(#${GRADIENT_ID})`} strokeWidth={1.5}
              strokeLinejoin="round" strokeLinecap="round" />
        <g fontSize={11}>
          <text x={0} y={-8} fill={ABOVE}>above median</text>
          <text x={88} y={-8} fill={BELOW}>below median</text>
        </g>
      </g>
    </svg>
  );
}
