// Tidy Tree — Hierarchy, route: jsx
// Source: tree_2
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from tree ----
interface ChartNode {
  name: string;
  children?: ChartNode[];
}

/** A taxonomy of chart families, several levels deep and unevenly branched. */
const chartTaxonomy: ChartNode = {
  name: 'Visualization',
  children: [
    {
      name: 'Comparison',
      children: [
        {
          name: 'Bar Chart',
          children: [
            { name: 'Grouped Bar' },
            { name: 'Stacked Bar' },
            { name: 'Horizontal Bar' },
          ],
        },
        { name: 'Radar Chart' },
        { name: 'Slope Chart' },
      ],
    },
    {
      name: 'Composition',
      children: [
        {
          name: 'Pie Chart',
          children: [{ name: 'Donut Chart' }],
        },
        {
          name: 'Treemap',
          children: [
            { name: 'Nested Treemap' },
            { name: 'Cascaded Treemap' },
            { name: 'Zoomable Treemap' },
          ],
        },
        { name: 'Icicle' },
      ],
    },
    {
      name: 'Distribution',
      children: [
        { name: 'Histogram' },
        { name: 'Box Plot' },
        { name: 'Violin Plot' },
        { name: 'Beeswarm' },
      ],
    },
    {
      name: 'Relationship',
      children: [
        {
          name: 'Scatterplot',
          children: [
            { name: 'Bubble Chart' },
            { name: 'Connected Scatter' },
            { name: 'Scatterplot Matrix' },
          ],
        },
        {
          name: 'Network',
          children: [
            { name: 'Force-Directed Graph' },
            { name: 'Chord Diagram' },
            { name: 'Sankey Diagram' },
            { name: 'Edge Bundling' },
          ],
        },
      ],
    },
    {
      name: 'Hierarchy',
      children: [
        {
          name: 'Tree',
          children: [
            { name: 'Tidy Tree' },
            { name: 'Cluster Dendrogram' },
            { name: 'Radial Tree' },
            { name: 'Indented Tree' },
          ],
        },
        { name: 'Circle Packing' },
        { name: 'Sunburst' },
      ],
    },
    {
      name: 'Geospatial',
      children: [
        { name: 'Choropleth' },
        { name: 'Cartogram' },
        { name: 'Hexbin Map' },
        { name: 'Spike Map' },
      ],
    },
    {
      name: 'Temporal',
      children: [
        { name: 'Timeline' },
        { name: 'Streamgraph' },
        { name: 'Calendar Heatmap' },
        { name: 'Horizon Chart' },
      ],
    },
  ],
};

/** Root of the taxonomy: every node has a name, and a branch also has children. */
export type Data = { name: string; children?: Data[] };

type Node = d3.HierarchyPointNode<Data>;
type Link = d3.HierarchyPointLink<Data>;

const MARGIN = { top: 18, right: 16, bottom: 18, left: 16 };
/** Breadth allotted to one leaf row. Height follows from this, never from an aspect ratio. */
const ROW_HEIGHT = 16;
const FONT_SIZE = 10;
/** Mean advance width of 10px sans-serif, used to drop labels that would overflow. */
const CHAR_WIDTH = 5.6;
const LABEL_GAP = 6;

function pathOf(node: Node): string {
  return node
    .ancestors()
    .map((a) => a.data.name)
    .reverse()
    .join('/');
}

export default function Tree({ data = chartTaxonomy, width }: { data?: Data; width: number }) {
  const innerWidth = Math.max(width - MARGIN.left - MARGIN.right, 0);

  // Unlike cluster, tree places each node at its own depth rather than aligning
  // every leaf to the same column, so shallow branches sit closer to the root.
  const root = useMemo(() => {
    const hierarchy = d3
      .hierarchy(data)
      .sort((a, b) => d3.ascending(a.data.name, b.data.name));
    const columnWidth = innerWidth / (hierarchy.height + 1);
    return d3.tree<Data>().nodeSize([ROW_HEIGHT, columnWidth])(hierarchy);
  }, [data, innerWidth]);

  const link = useMemo(
    () =>
      d3
        .linkHorizontal<Link, Node>()
        .x((d) => d.y)
        .y((d) => d.x),
    []
  );

  const [x0, x1] = useMemo(() => {
    const extent = d3.extent(root.descendants(), (d) => d.x);
    return [extent[0] ?? 0, extent[1] ?? 0];
  }, [root]);

  const height = Math.round(x1 - x0 + MARGIN.top + MARGIN.bottom);

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Tidy tree of a chart-type taxonomy, drawn left to right"
    >
      <g
        transform={`translate(${MARGIN.left},${MARGIN.top - x0})`}
        fontSize={FONT_SIZE}
        strokeLinejoin="round"
      >
        {root.links().map((l) => (
          <path
            key={pathOf(l.target)}
            d={link(l) ?? undefined}
            fill="none"
            stroke="var(--line)"
            strokeWidth={1.5}
          />
        ))}
        {root.descendants().map((d) => {
          const isLeaf = !d.children;
          const room = innerWidth - d.y - LABEL_GAP * 2;
          const fits = d.data.name.length * CHAR_WIDTH < room;

          return (
            <g key={pathOf(d)} transform={`translate(${d.y},${d.x})`}>
              <title>{pathOf(d)}</title>
              <circle r={2.5} fill={isLeaf ? 'var(--accent)' : 'var(--muted)'} />
              {fits && (
                <text
                  dy="0.32em"
                  x={LABEL_GAP}
                  textAnchor="start"
                  fill={isLeaf ? 'var(--text)' : 'var(--muted)'}
                  stroke="var(--bg)"
                  strokeWidth={3}
                  paintOrder="stroke"
                >
                  {d.data.name}
                </text>
              )}
            </g>
          );
        })}
      </g>
    </svg>
  );
}
