// US Population by State — Time Series, route: jsx
// Source: u-s-population-by-state-1790-1990
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from usPopulation ----
/**
 * Synthetic US population by state, 1790-1980, from a seeded logistic growth model.
 * These are NOT Census Bureau figures; only the shape of the story is real.
 */

const REGIONS = [
  'New England',
  'Middle Atlantic',
  'South Atlantic',
  'East South Central',
  'West South Central',
  'East North Central',
  'West North Central',
  'Mountain',
  'Pacific'
] as const;

type Region = (typeof REGIONS)[number];

const CENSUS_YEARS = Array.from({ length: 20 }, (_, i) => 1790 + i * 10);

// name, region, entry decade, capacity in millions, inflection year
const STATES: [string, Region, number, number, number][] = [
  ['Massachusetts', 'New England', 1790, 6.0, 1900],
  ['Connecticut', 'New England', 1790, 3.2, 1930],
  ['Maine', 'New England', 1820, 1.2, 1900],
  ['New York', 'Middle Atlantic', 1790, 18.5, 1900],
  ['Pennsylvania', 'Middle Atlantic', 1790, 12.0, 1900],
  ['New Jersey', 'Middle Atlantic', 1790, 7.5, 1930],
  ['Virginia', 'South Atlantic', 1790, 5.5, 1920],
  ['North Carolina', 'South Atlantic', 1790, 6.0, 1930],
  ['South Carolina', 'South Atlantic', 1790, 3.2, 1920],
  ['Georgia', 'South Atlantic', 1790, 5.6, 1930],
  ['Maryland', 'South Atlantic', 1790, 4.3, 1930],
  ['Florida', 'South Atlantic', 1830, 10.0, 1955],
  ['Kentucky', 'East South Central', 1790, 3.7, 1900],
  ['Tennessee', 'East South Central', 1790, 4.6, 1920],
  ['Mississippi', 'East South Central', 1800, 2.5, 1910],
  ['Alabama', 'East South Central', 1820, 3.9, 1920],
  ['Louisiana', 'West South Central', 1810, 4.2, 1930],
  ['Texas', 'West South Central', 1850, 14.5, 1940],
  ['Oklahoma', 'West South Central', 1890, 3.0, 1920],
  ['Ohio', 'East North Central', 1800, 10.8, 1910],
  ['Illinois', 'East North Central', 1810, 11.5, 1910],
  ['Michigan', 'East North Central', 1810, 9.3, 1930],
  ['Wisconsin', 'East North Central', 1840, 4.7, 1910],
  ['Missouri', 'West North Central', 1810, 4.9, 1910],
  ['Iowa', 'West North Central', 1840, 2.9, 1900],
  ['Minnesota', 'West North Central', 1850, 4.1, 1920],
  ['Utah', 'Mountain', 1850, 1.5, 1950],
  ['Colorado', 'Mountain', 1860, 2.9, 1950],
  ['California', 'Pacific', 1850, 23.7, 1950],
  ['Washington', 'Pacific', 1860, 4.1, 1950]
];

/** FNV-1a over name+year, mapped to a +/-4% multiplier so decades are not perfectly smooth. */
function jitter(name: string, year: number): number {
  let hash = 2166136261;
  for (const char of `${name}${year}`) {
    hash = Math.imul(hash ^ char.charCodeAt(0), 16777619);
  }
  return 0.96 + ((hash >>> 0) % 1000) * 0.00008;
}

function populationAt(
  name: string,
  entry: number,
  capacity: number,
  inflection: number,
  year: number
): number {
  if (year < entry) return 0;
  const logistic = capacity / (1 + Math.exp(-0.03 * (year - inflection)));
  // A new state enters small and reaches its trend line over four decades; the
  // original twelve are already settled at the first census and skip the ramp.
  const ramp =
    entry === CENSUS_YEARS[0] ? 1 : Math.min(1, 0.15 + ((year - entry) / 40) * 0.85);
  return logistic * ramp * jitter(name, year);
}

const ordered = [...STATES].sort(
  (a, b) =>
    a[2] - b[2] || REGIONS.indexOf(a[1]) - REGIONS.indexOf(b[1]) || b[3] - a[3]
);

const STATE_NAMES: string[] = ordered.map((s) => s[0]);

const regionByState = new Map<string, Region>(ordered.map((s) => [s[0], s[1]]));

type PopulationRow = { year: number; byState: Record<string, number> };

const populationByState: PopulationRow[] = CENSUS_YEARS.map((year) => ({
  year,
  byState: Object.fromEntries(
    ordered.map(([name, , entry, capacity, inflection]) => [
      name,
      populationAt(name, entry, capacity, inflection, year)
    ])
  )
}));

const MARGIN = { top: 14, right: 14, bottom: 34, left: 56 };
const MIN_LABEL_THICKNESS = 11;
const PATH_ID = 'us-population-midline';

/**
 * One row per census year holding a population per state, plus the keys those rows use:
 * the years in order, the state names in stacking order, and the region each state sits in.
 */
export type Data = {
  rows: { year: number; byState: Record<string, number> }[];
  years: number[];
  states: string[];
  regions: readonly string[];
  regionByState: Map<string, string>;
};

const DEMO: Data = {
  rows: populationByState,
  years: CENSUS_YEARS,
  states: STATE_NAMES,
  regions: REGIONS,
  regionByState
};

type Point = d3.SeriesPoint<Data['rows'][number]>;

export default function UsPopulationByState({ data = DEMO, width }:
  { data?: Data; width: number }) {
  const height = Math.round(width * 0.7);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const series = useMemo(
    () =>
      d3
        .stack<Data['rows'][number], string>()
        .keys(data.states)
        .value((row, key) => row.byState[key] ?? 0)(data.rows),
    [data]
  );

  const x = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([data.years[0], data.years[data.years.length - 1]])
        .range([0, innerWidth]),
    [data, innerWidth]
  );

  const y = useMemo(
    () =>
      d3
        .scaleLinear()
        .domain([0, d3.max(series, (s) => d3.max(s, (p) => p[1]) ?? 0) ?? 0])
        .nice()
        .range([innerHeight, 0]),
    [series, innerHeight]
  );

  const color = useMemo(
    () => d3.scaleOrdinal<string, string>().domain(data.regions).range(d3.schemeObservable10),
    [data]
  );

  const area = useMemo(
    () =>
      d3
        .area<Point>()
        .x((p) => x(p.data.year))
        .y0((p) => y(p[0]))
        .y1((p) => y(p[1])),
    [x, y]
  );

  const midline = useMemo(
    () =>
      d3
        .line<Point>()
        .curve(d3.curveBasis)
        .x((p) => x(p.data.year))
        .y((p) => y((p[0] + p[1]) / 2)),
    [x, y]
  );

  const bands = useMemo(
    () =>
      series.map((s) => {
        const fill = color(data.regionByState.get(s.key) ?? data.regions[0]);
        const widest = d3.maxIndex(s, (p) => p[1] - p[0]);
        const thickness = y(s[widest][0]) - y(s[widest][1]);
        return {
          key: s.key,
          fill,
          stroke: d3.lab(fill).darker(0.7).formatHex(),
          area: area(s) ?? '',
          top: area.lineY1()(s) ?? '',
          mid: midline(s) ?? '',
          // Suppress the label when its band is too thin to hold the text.
          labelOffset:
            thickness >= MIN_LABEL_THICKNESS
              ? Math.min(0.95, Math.max(0.05, widest / (s.length - 1))) * 100
              : null
        };
      }),
    [data, series, color, area, midline, y]
  );

  const xTicks: Tick[] = useMemo(
    () => x.ticks(Math.max(4, Math.round(innerWidth / 90))).map((v) => ({
      value: d3.format('d')(v),
      offset: x(v)
    })),
    [x, innerWidth]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(6).map((v) => ({ value: `${d3.format('d')(v)}M`, offset: y(v) })),
    [y]
  );

  if (width === 0) return null;

  return (
    <svg viewBox={`0 0 ${width} ${height}`} width="100%" height={height} role="img"
         aria-label="Stacked area chart of US population by state from 1790 to 1980, banded by census region, with each state entering the stack at its own decade. Synthetic data from a seeded generator, not US Census Bureau figures.">
      <defs>
        {bands.map((b) => (
          <path key={b.key} id={`${PATH_ID}-${b.key.replace(/\s+/g, '')}`} d={b.mid} />
        ))}
      </defs>
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        <AxisBottom ticks={xTicks} height={innerHeight} width={innerWidth} />
        {bands.map((b) => (
          <path key={b.key} d={b.area} fill={b.fill} fillOpacity={0.85}>
            <title>{b.key}</title>
          </path>
        ))}
        {bands.map((b) => (
          <path key={b.key} d={b.top} fill="none" stroke={b.stroke} strokeWidth={0.75} />
        ))}
        {bands.map((b) =>
          b.labelOffset === null ? null : (
            <text
              key={b.key}
              dy="0.35em"
              fontSize={10}
              textAnchor="middle"
              fill="var(--text)"
              stroke="rgba(0,0,0,0.55)"
              strokeWidth={2.5}
              paintOrder="stroke"
            >
              <textPath
                href={`#${PATH_ID}-${b.key.replace(/\s+/g, '')}`}
                startOffset={`${b.labelOffset}%`}
              >
                {b.key}
              </textPath>
            </text>
          )
        )}
      </g>
      {width >= 320 && (
        <text x={MARGIN.left} y={height - 4} fill="var(--muted)" fontSize={10}>
          Synthetic data from a seeded generator, not US Census Bureau figures.
        </text>
      )}
    </svg>
  );
}
