// US State Choropleth — Geo, route: jsx
// Source: us-state-choropleth_2
//
// Self-contained: every local import is inlined below. Requires only d3, geojson, react, topojson-client, topojson-specification, us-atlas, world-atlas.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { feature, mesh } from 'topojson-client';
import countries110m from 'world-atlas/countries-110m.json';
import statesUs from 'us-atlas/states-10m.json';
import type { GeometryCollection, Topology } from 'topojson-specification';
import type { Feature, FeatureCollection, Geometry, MultiLineString } from 'geojson';
import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from geo ----
// The atlases ship untyped JSON. One cast per topology at this boundary keeps every
// consumer strict, and converting here means each chart does not re-derive the same
// geometry at module load.

type Named = { name: string };
type NamedFeature = Feature<Geometry, Named>;

const world = countries110m as unknown as Topology<{
  countries: GeometryCollection<Named>;
  land: GeometryCollection;
}>;

const us = statesUs as unknown as Topology<{
  states: GeometryCollection<Named>;
  nation: GeometryCollection;
}>;

const worldCountries = feature(
  world,
  world.objects.countries
) as FeatureCollection<Geometry, Named>;

const worldLand = feature(world, world.objects.land) as FeatureCollection<Geometry>;

/** Shared borders only, so neighbouring outlines are stroked once instead of twice. */
const worldBorders = mesh(
  world,
  world.objects.countries,
  (a, b) => a !== b
) as MultiLineString;

const usNation = feature(us, us.objects.nation) as FeatureCollection<Geometry>;

const usStateBorders = mesh(
  us,
  us.objects.states,
  (a, b) => a !== b
) as MultiLineString;

/**
 * The 50 states plus DC. geoAlbersUsa cannot project FIPS ids of 60 and above
 * (territories) and returns null for them, which becomes a NaN centroid downstream.
 * Use this rather than the raw collection for anything Albers-projected.
 */
const usStates: NamedFeature[] = (
  feature(us, us.objects.states) as FeatureCollection<Geometry, Named>
).features.filter((d) => Number(d.id) < 60);

const usStatesCollection: FeatureCollection<Geometry, Named> = {
  type: 'FeatureCollection',
  features: usStates
};

/**
 * FNV-1a over an id, run through the murmur3 finalizer. Two-character FIPS ids barely
 * differ, and without the finalizer they map to a near-constant. Returns [0, 1).
 * Charts use it to synthesize per-region values deterministically instead of fetching.
 */
function hashUnit(id: string, salt = 0): number {
  let h = 2166136261 ^ salt;
  for (let i = 0; i < id.length; i++) {
    h = Math.imul(h ^ id.charCodeAt(i), 16777619);
  }
  h ^= h >>> 16;
  h = Math.imul(h, 2246822507);
  h ^= h >>> 13;
  return (h >>> 0) / 4294967296;
}

// ---- inlined from usStateChoropleth ----
// Synthetic unemployment rates keyed by FIPS state id. FNV-1a keeps them stable
// across reloads without shipping the real BLS table.
function stateRate(id: string): number {
  let hash = 2166136261;
  for (let i = 0; i < id.length; i++) {
    hash = Math.imul(hash ^ id.charCodeAt(i), 16777619);
  }
  return 2.1 + ((hash >>> 0) % 730) / 100;
}

const MARGIN = { top: 48, right: 8, bottom: 8, left: 8 };
const LEGEND = { x: 14, y: 20, width: 240, height: 10 };
const RAMP_STOPS = 48;

// Inferno's darkest and lightest ends both vanish against the gallery background.
const ramp = (t: number) => d3.interpolateInferno(0.22 + 0.7 * t);
const format = d3.format('.1f');

/** The value shaded per state, keyed by FIPS id. The state outlines are basemap, not data. */
export type Data = Map<string, number>;

const DEMO: Data = new Map<string, number>(
  usStatesCollection.features.map((d) => [String(d.id), stateRate(String(d.id))])
);

export default function UsStateChoropleth({ data = DEMO, width }:
  { data?: Data; width: number }) {
  const height = Math.round(width * 0.66);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const domain = useMemo(() => d3.extent(data.values()) as [number, number], [data]);

  const color = useMemo(() => d3.scaleSequential(domain, ramp), [domain]);

  const path = useMemo(() => {
    const projection = d3.geoAlbersUsa().fitSize([innerWidth, innerHeight], usStatesCollection);
    return d3.geoPath(projection);
  }, [innerWidth, innerHeight]);

  const legendScale = useMemo(
    () => d3.scaleLinear().domain(domain).range([LEGEND.x, LEGEND.x + LEGEND.width]),
    [domain]
  );

  const legendStops = useMemo(
    () =>
      d3.range(RAMP_STOPS).map((i) => ({
        x: LEGEND.x + (i * LEGEND.width) / RAMP_STOPS,
        fill: ramp(i / (RAMP_STOPS - 1))
      })),
    []
  );

  if (width === 0) return null;

  const showLegend = width >= LEGEND.width + 120;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Choropleth map of the United States shaded by unemployment rate per state"
    >
      {showLegend && (
        <>
          <text x={LEGEND.x} y={12} fill="var(--text)" fontSize={11} fontWeight={600}>
            Unemployment rate (%)
          </text>
          {legendStops.map((s) => (
            <rect
              key={s.x}
              x={s.x}
              y={LEGEND.y}
              width={LEGEND.width / RAMP_STOPS + 0.5}
              height={LEGEND.height}
              fill={s.fill}
            />
          ))}
          <g className="axis" transform={`translate(0,${LEGEND.y + LEGEND.height})`}>
            {legendScale.ticks(5).map((v) => (
              <g key={v} transform={`translate(${legendScale(v)},0)`}>
                <line y1={0} y2={5} />
                <text y={17} textAnchor="middle">
                  {format(v)}
                </text>
              </g>
            ))}
          </g>
        </>
      )}

      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        {usStatesCollection.features.map((d) => {
          const shape = path(d);
          const rate = data.get(String(d.id));
          if (!shape || rate === undefined) return null;
          return (
            <path key={String(d.id)} d={shape} fill={color(rate)}>
              <title>{`${d.properties.name}\n${format(rate)}%`}</title>
            </path>
          );
        })}
        <path
          d={path(usStateBorders) ?? undefined}
          fill="none"
          stroke="var(--panel)"
          strokeWidth={0.5}
          strokeLinejoin="round"
        />
      </g>
    </svg>
  );
}
