// Violin Plot — Distribution, route: jsx
// Source: original:gaps/violin
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from Axis ----
type Tick = { value: string; offset: number };

function AxisBottom({
  ticks,
  height,
  width
}: {
  ticks: Tick[];
  height: number;
  width: number;
}) {
  return (
    <g className="axis" transform={`translate(0,${height})`}>
      <line x1={0} x2={width} y1={0} y2={0} />
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(${offset},0)`}>
          <line y1={0} y2={5} />
          <text y={18} textAnchor="middle">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

function AxisLeft({ ticks, width }: { ticks: Tick[]; width: number }) {
  return (
    <g className="axis">
      {ticks.map(({ value, offset }) => (
        <g key={value} transform={`translate(0,${offset})`}>
          <line className="grid" x1={0} x2={width} y1={0} y2={0} />
          <text x={-10} dy="0.32em" textAnchor="end">
            {value}
          </text>
        </g>
      ))}
    </g>
  );
}

// ---- inlined from violin ----
// Seeded response-latency samples across four services. Service C is deliberately
// bimodal (cache hit vs miss) — the shape a box plot of the same data would hide,
// which is the violin's argument. Mulberry32 PRNG for determinism.
function mulberry32(seed: number) {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function randomNormal(rng: () => number, mean: number, stdDev: number) {
  const u1 = rng();
  const u2 = rng();
  const z = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
  return mean + z * stdDev;
}

const rng = mulberry32(20260820);

function sample(group: string, n: number, draw: () => number) {
  return Array.from({ length: n }, () => ({ group, value: Math.max(1, draw()) }));
}

const serviceLatency: { group: string; value: number }[] = [
  ...sample('Auth', 80, () => randomNormal(rng, 42, 8)),
  ...sample('Search', 80, () => randomNormal(rng, 65, 18)),
  // Cache hit ~30ms or miss ~110ms: bimodal on purpose.
  ...sample('Catalog', 80, () => (rng() < 0.55 ? randomNormal(rng, 30, 6) : randomNormal(rng, 110, 12))),
  ...sample('Checkout', 80, () => randomNormal(rng, 78, 12))
];

const MARGIN = { top: 16, right: 16, bottom: 30, left: 52 };

/** One observation per row; the violin mirrors a density per group. */
export type Data = { group: string; value: number }[];

function epanechnikov(bandwidth: number) {
  return (value: number) => {
    const u = value / bandwidth;
    return Math.abs(u) <= 1 ? (0.75 * (1 - u * u)) / bandwidth : 0;
  };
}

export default function ViolinPlot({ data = serviceLatency, width }: { data?: Data; width: number }) {
  const height = Math.round(width * 0.62);
  const innerWidth = width - MARGIN.left - MARGIN.right;
  const innerHeight = height - MARGIN.top - MARGIN.bottom;

  const groups = useMemo(() => [...new Set(data.map((d) => d.group))], [data]);

  const y = useMemo(() => {
    // Pad past the data extent so KDE tails taper inside the frame instead of
    // being cut flat at the domain edge.
    const [lo, hi] = d3.extent(data, (d) => d.value) as [number, number];
    const pad = (hi - lo) * 0.06;
    return d3.scaleLinear().domain([lo - pad, hi + pad]).nice().range([innerHeight, 0]);
  }, [data, innerHeight]);

  const x = useMemo(
    () => d3.scaleBand<string>().domain(groups).range([0, innerWidth]).padding(0.25),
    [groups, innerWidth]
  );

  const violins = useMemo(() => {
    const grid = y.ticks(60);
    return groups.map((group) => {
      const values = data.filter((d) => d.group === group).map((d) => d.value);
      // Silverman's rule of thumb, so spiky and smooth groups each get a sane bandwidth.
      const sd = d3.deviation(values) ?? 1;
      const kernel = epanechnikov(1.06 * sd * Math.pow(values.length, -0.2));
      const estimated = grid.map((t) => ({
        value: t,
        density: d3.mean(values, (v) => kernel(t - v)) ?? 0
      }));
      // Close each violin to a point at both ends.
      const density = [
        { value: grid[0], density: 0 },
        ...estimated,
        { value: grid[grid.length - 1], density: 0 }
      ];
      const median = d3.median(values) ?? 0;
      return { group, density, median };
    });
  }, [data, groups, y]);

  const maxDensity = useMemo(
    () => d3.max(violins, (v) => d3.max(v.density, (d) => d.density)) ?? 1,
    [violins]
  );

  const yTicks: Tick[] = useMemo(
    () => y.ticks(6).map((v) => ({ value: String(v), offset: y(v) })),
    [y]
  );

  const halfWidth = useMemo(
    () => d3.scaleLinear().domain([0, maxDensity]).range([0, x.bandwidth() / 2]),
    [maxDensity, x]
  );

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Violin plot of response latency distributions across four services, one of them bimodal"
    >
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <AxisLeft ticks={yTicks} width={innerWidth} />
        {violins.map(({ group, density, median }) => {
          const center = (x(group) ?? 0) + x.bandwidth() / 2;
          const area = d3
            .area<{ value: number; density: number }>()
            .x0((d) => center - halfWidth(d.density))
            .x1((d) => center + halfWidth(d.density))
            .y((d) => y(d.value))
            .curve(d3.curveCatmullRom);
          return (
            <g key={group}>
              <path
                d={area(density) ?? undefined}
                fill="var(--accent)"
                fillOpacity={0.35}
                stroke="var(--accent)"
              />
              <line
                x1={center - halfWidth(maxDensity) * 0.5}
                x2={center + halfWidth(maxDensity) * 0.5}
                y1={y(median)}
                y2={y(median)}
                stroke="var(--text)"
                strokeWidth={2}
              />
              <text
                x={center}
                y={innerHeight + 18}
                textAnchor="middle"
                fontSize={11}
                fill="var(--text)"
              >
                {group}
              </text>
            </g>
          );
        })}
      </g>
    </svg>
  );
}
