// Voronoi Labels — Distribution, route: jsx
// Source: voronoi-labels
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import * as d3 from 'd3';
import { useMemo } from 'react';

// ---- inlined from voronoiLabels ----
type LabeledPoint = { x: number; y: number; label: string };

const PREFIX = ['Ka', 'Ve', 'Ta', 'Mi', 'Lo', 'Ra', 'Se', 'No', 'Di', 'Fu', 'Ge', 'Hy', 'Ju', 'Ny', 'Ob', 'Pe', 'Qu'];
// 17 x 15 = 255 combinations, more than the 240 draws below, so every label is unique.
const SUFFIX = ['ra', 'lin', 'mos', 'ta', 'ven', 'dis', 'kar', 'nia', 'sol', 'ther', 'vex', 'pol', 'gan', 'rix', 'dun'];

const nameFor = (i: number) =>
  PREFIX[i % PREFIX.length] + SUFFIX[Math.floor(i / PREFIX.length) % SUFFIX.length];

// Seeded LCG, not Math.random, so the same blob survives every hot reload.
const source = d3.randomLcg(0.7362);
const randomX = d3.randomNormal.source(source)(0.5, 0.17);
const randomY = d3.randomNormal.source(source)(0.5, 0.27);

// Unit space; the chart scales to pixels. The y sigma is wider so the blob reads
// round once multiplied by the chart's 0.62 aspect ratio.
const voronoiPoints: LabeledPoint[] = d3
  .range(240)
  .map((i) => ({ x: randomX(), y: randomY(), label: nameFor(i) }))
  .filter((p) => p.x > 0 && p.x < 1 && p.y > 0 && p.y < 1);

const MARGIN = { top: 16, right: 16, bottom: 16, left: 16 };
const FONT_SIZE = 10;
const CHAR_WIDTH = FONT_SIZE * 0.56;
const LABEL_GAP = 6;

// A cell earns a label when it is at least as big as the average cell and big
// enough in absolute terms to hold 10px text at all.
const MIN_AREA_RATIO = 1;
const MIN_AREA_PX = 600;

/** Indexed by the quadrant of the point-to-centroid vector: 0 right, 1 bottom, 2 left, 3 top. */
const ORIENT = [
  { anchor: 'start', dx: LABEL_GAP, dy: 0, baseline: '0.35em' },
  { anchor: 'middle', dx: 0, dy: LABEL_GAP, baseline: '0.71em' },
  { anchor: 'end', dx: -LABEL_GAP, dy: 0, baseline: '0.35em' },
  { anchor: 'middle', dx: 0, dy: -LABEL_GAP, baseline: '0em' }
] as const;

type PlacedLabel = {
  index: number;
  label: string;
  x: number;
  y: number;
  anchor: 'start' | 'middle' | 'end';
  baseline: string;
};

/** Named points in unit coordinates: x and y both run 0 to 1 across the plot. */
export type Data = { x: number; y: number; label: string }[];

export default function VoronoiLabels({
  data = voronoiPoints,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.round(width * 0.62);
  const innerWidth = Math.max(1, width - MARGIN.left - MARGIN.right);
  const innerHeight = Math.max(1, height - MARGIN.top - MARGIN.bottom);

  const { points, mesh, labels, labelled } = useMemo(() => {
    const points = data.map((p) => ({
      label: p.label,
      x: p.x * innerWidth,
      y: p.y * innerHeight
    }));

    const voronoi = d3.Delaunay.from(
      points,
      (d) => d.x,
      (d) => d.y
    ).voronoi([0, 0, innerWidth, innerHeight]);

    const cells = points.map((_, i) => voronoi.cellPolygon(i));
    const areas = cells.map((cell) => (cell ? Math.abs(d3.polygonArea(cell)) : 0));
    const meanArea = d3.mean(areas) ?? 0;
    const minArea = Math.max(MIN_AREA_PX, meanArea * MIN_AREA_RATIO);

    const labels: PlacedLabel[] = [];
    points.forEach((point, i) => {
      const cell = cells[i];
      if (!cell || areas[i] < minArea) return;

      // The vector from the point to its cell's centroid points at the roomy side.
      const [cx, cy] = d3.polygonCentroid(cell);
      const quadrant = (Math.round(Math.atan2(cy - point.y, cx - point.x) / Math.PI * 2) + 4) % 4;
      const { anchor, dx, dy, baseline } = ORIENT[quadrant];

      const x = point.x + dx;
      const y = point.y + dy;
      const half = (point.label.length * CHAR_WIDTH) / (anchor === 'middle' ? 2 : 1);
      const left = anchor === 'start' ? x : x - half;
      const right = anchor === 'end' ? x : x + half;
      if (left < 0 || right > innerWidth || y < FONT_SIZE || y > innerHeight) return;

      labels.push({ index: i, label: point.label, x, y, anchor, baseline });
    });

    const labelled = new Set(labels.map((l) => l.index));
    return { points, mesh: voronoi.render(), labels, labelled };
  }, [data, innerWidth, innerHeight]);

  if (width === 0) return null;

  return (
    <svg viewBox={`0 0 ${width} ${height}`} width="100%" height={height} role="img"
         aria-label="Scatterplot labelled through its Voronoi diagram: only points whose cell has room carry a name, anchored on the roomy side of the cell">
      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <path d={mesh} fill="none" stroke="var(--line)" strokeWidth={1} />

        {points.map((p, i) => (
          <circle
            key={i}
            cx={p.x}
            cy={p.y}
            r={labelled.has(i) ? 2.5 : 1.8}
            fill={labelled.has(i) ? 'var(--accent)' : 'var(--muted)'}
          />
        ))}

        <g fontSize={FONT_SIZE} fill="var(--text)">
          {labels.map((l) => (
            <text key={l.index} x={l.x} y={l.y} dy={l.baseline} textAnchor={l.anchor}>
              {l.label}
            </text>
          ))}
        </g>
      </g>
    </svg>
  );
}
