// Voronoi Stippling — Distribution, route: jsx
// Source: voronoi-stippling
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import * as d3 from 'd3';
import { useMemo } from 'react';

// ---- inlined from voronoiStippling ----
/**
 * Weighted stippling normally reads its weights from a photograph's lightness. The gallery
 * never fetches, so the density field is analytic: concentric ripples inside a soft disc.
 */
const WAVELENGTH = 0.14;
const DISC_RADIUS = 0.36;
const EDGE_SHARPNESS = 6; // super-Gaussian exponent: 2 is a soft blur, 6 a defined rim
const FLOOR = 0.008; // keeps outlying cells from having zero weight and freezing in place

function stippleDensity(x: number, y: number): number {
  const dx = x - 0.5;
  const dy = y - 0.5;
  const radius = Math.sqrt(dx * dx + dy * dy);
  // Squaring narrows the bright bands and widens the gaps, so the rings survive relaxation.
  const ripple = Math.pow(Math.cos((radius * 2 * Math.PI) / WAVELENGTH) * 0.5 + 0.5, 2);
  const envelope = Math.exp(-Math.pow(radius / DISC_RADIUS, EDGE_SHARPNESS));
  return FLOOR + (1 - FLOOR) * ripple * envelope;
}

const GRID = 80; // density samples per side, standing in for the image's pixel raster
const POINTS = 600;
const ITERATIONS = 30;
const OVER_RELAX = 1.8;
const SEED = 0xc0ffee;

function mulberry32(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const clamp = (v: number) => (v < 0 ? 0 : v > 1 ? 1 : v);

type StipplePoint = { x: number; y: number };

/** Weighted Lloyd relaxation in the unit square, so the result is independent of pixel size. */
function computeStipple(): StipplePoint[] {
  const random = mulberry32(SEED);
  const step = 1 / GRID;

  const weights = new Float64Array(GRID * GRID);
  for (let gy = 0; gy < GRID; ++gy) {
    for (let gx = 0; gx < GRID; ++gx) {
      weights[gy * GRID + gx] = stippleDensity((gx + 0.5) * step, (gy + 0.5) * step);
    }
  }

  // Rejection sampling: up to 30 uniform darts, keeping the first the field accepts.
  const points = new Float64Array(POINTS * 2);
  for (let i = 0; i < POINTS; ++i) {
    for (let j = 0; j < 30; ++j) {
      const x = (points[i * 2] = random());
      const y = (points[i * 2 + 1] = random());
      if (random() < stippleDensity(x, y)) break;
    }
  }

  const delaunay = new d3.Delaunay<number>(points);
  const mass = new Float64Array(POINTS);
  const moment = new Float64Array(POINTS * 2);

  for (let k = 0; k < ITERATIONS; ++k) {
    mass.fill(0);
    moment.fill(0);

    let cell = 0;
    for (let gy = 0; gy < GRID; ++gy) {
      for (let gx = 0; gx < GRID; ++gx) {
        const x = (gx + 0.5) * step;
        const y = (gy + 0.5) * step;
        const w = weights[gy * GRID + gx];
        cell = delaunay.find(x, y, cell);
        mass[cell] += w;
        moment[cell * 2] += w * x;
        moment[cell * 2 + 1] += w * y;
      }
    }

    // Over-relax past the weighted centroid, with a shrinking jitter so points do not stick.
    const wiggle = Math.pow(k + 1, -0.8) * 0.008;
    for (let i = 0; i < POINTS; ++i) {
      const x0 = points[i * 2];
      const y0 = points[i * 2 + 1];
      const m = mass[i];
      const x1 = m ? moment[i * 2] / m : x0;
      const y1 = m ? moment[i * 2 + 1] / m : y0;
      points[i * 2] = clamp(x0 + (x1 - x0) * OVER_RELAX + (random() - 0.5) * wiggle);
      points[i * 2 + 1] = clamp(y0 + (y1 - y0) * OVER_RELAX + (random() - 0.5) * wiggle);
    }

    delaunay.update();
  }

  return Array.from({ length: POINTS }, (_, i) => ({
    x: points[i * 2],
    y: points[i * 2 + 1]
  }));
}

const MARGIN = { top: 14, right: 14, bottom: 26, left: 14 };
const MAX_SIDE = 560;
const LONG_CAPTION_WIDTH = 480;

export default function VoronoiStippling({ width }: { width: number }) {
  const side = Math.min(Math.max(1, width - MARGIN.left - MARGIN.right), MAX_SIDE);
  const height = side + MARGIN.top + MARGIN.bottom;
  const offsetX = Math.max(0, (width - MARGIN.left - MARGIN.right - side) / 2);

  // Relaxation runs in the unit square, so it survives a resize without recomputing.
  const points = useMemo(() => computeStipple(), []);
  const radius = Math.max(1.1, side / 190);

  if (width === 0) return null;

  const caption =
    width >= LONG_CAPTION_WIDTH
      ? 'Weights come from an analytic ripple field computed in code, not from a photograph.'
      : 'Analytic density field, not a photograph.';

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Weighted Voronoi stippling: 600 dots settled by 30 rounds of weighted Lloyd relaxation, so dot density tracks an underlying density field of concentric rings inside a disc. The field is an analytic function computed in code, standing in for the photograph the original technique stipples, because this gallery fetches no images."
    >
      <g transform={`translate(${MARGIN.left + offsetX},${MARGIN.top})`}>
        {points.map((p, i) => (
          <circle key={i} cx={p.x * side} cy={p.y * side} r={radius} fill="var(--text)" />
        ))}
      </g>

      {/* A stipple with no provenance reads as a photograph rendered in dots. */}
      <text x={MARGIN.left} y={height - 8} fill="var(--muted)" fontSize={10}>
        {caption}
      </text>
    </svg>
  );
}
