// Walmart's Growth — Geo, route: jsx
// Source: walmarts-growth
//
// Self-contained: every local import is inlined below. Requires only d3, geojson, motion, react, topojson-client, topojson-specification, us-atlas, world-atlas.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { feature, mesh } from 'topojson-client';
import countries110m from 'world-atlas/countries-110m.json';
import statesUs from 'us-atlas/states-10m.json';
import type { GeometryCollection, Topology } from 'topojson-specification';
import type { Feature, FeatureCollection, Geometry, MultiLineString } from 'geojson';
import * as d3 from 'd3';
import { useEffect, useMemo, useState } from 'react';
import { motion } from 'motion/react';

// ---- inlined from geo ----
// The atlases ship untyped JSON. One cast per topology at this boundary keeps every
// consumer strict, and converting here means each chart does not re-derive the same
// geometry at module load.

type Named = { name: string };
type NamedFeature = Feature<Geometry, Named>;

const world = countries110m as unknown as Topology<{
  countries: GeometryCollection<Named>;
  land: GeometryCollection;
}>;

const us = statesUs as unknown as Topology<{
  states: GeometryCollection<Named>;
  nation: GeometryCollection;
}>;

const worldCountries = feature(
  world,
  world.objects.countries
) as FeatureCollection<Geometry, Named>;

const worldLand = feature(world, world.objects.land) as FeatureCollection<Geometry>;

/** Shared borders only, so neighbouring outlines are stroked once instead of twice. */
const worldBorders = mesh(
  world,
  world.objects.countries,
  (a, b) => a !== b
) as MultiLineString;

const usNation = feature(us, us.objects.nation) as FeatureCollection<Geometry>;

const usStateBorders = mesh(
  us,
  us.objects.states,
  (a, b) => a !== b
) as MultiLineString;

/**
 * The 50 states plus DC. geoAlbersUsa cannot project FIPS ids of 60 and above
 * (territories) and returns null for them, which becomes a NaN centroid downstream.
 * Use this rather than the raw collection for anything Albers-projected.
 */
const usStates: NamedFeature[] = (
  feature(us, us.objects.states) as FeatureCollection<Geometry, Named>
).features.filter((d) => Number(d.id) < 60);

const usStatesCollection: FeatureCollection<Geometry, Named> = {
  type: 'FeatureCollection',
  features: usStates
};

/**
 * FNV-1a over an id, run through the murmur3 finalizer. Two-character FIPS ids barely
 * differ, and without the finalizer they map to a near-constant. Returns [0, 1).
 * Charts use it to synthesize per-region values deterministically instead of fetching.
 */
function hashUnit(id: string, salt = 0): number {
  let h = 2166136261 ^ salt;
  for (let i = 0; i < id.length; i++) {
    h = Math.imul(h ^ id.charCodeAt(i), 16777619);
  }
  h ^= h >>> 16;
  h = Math.imul(h, 2246822507);
  h ^= h >>> 13;
  return (h >>> 0) / 4294967296;
}

// ---- inlined from walmartsGrowth ----
/** Rogers, Arkansas, where the first store opened on 2 July 1962. */
const ORIGIN: [number, number] = [-94.128, 36.332];

const startDate = Date.UTC(1962, 6, 2);
const endDate = Date.UTC(2006, 0, 1);

// The dataset this stands in for covers the contiguous states only.
const contiguous = usStates.filter((d) => d.id !== '02' && d.id !== '15');

const lower48 = { type: 'FeatureCollection' as const, features: contiguous };

type Store = { id: string; lon: number; lat: number; date: number };

/** Seeded LCG, so the same store field is rebuilt byte for byte on every load. */
function seeded(seed: number): () => number {
  let state = seed >>> 0 || 1;
  return () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state / 4294967296;
  };
}

/** Rejection sampling inside each state outline: bounding-box points that miss the
 *  polygon are discarded, so no store lands offshore or in a neighbouring state. */
function samplePoints(): { id: string; lon: number; lat: number }[] {
  const points: { id: string; lon: number; lat: number }[] = [];
  for (const state of contiguous) {
    const fips = String(state.id);
    const next = seeded(Math.floor(hashUnit(fips, 7) * 2 ** 32));
    const count = 3 + Math.round(hashUnit(fips, 23) * 15);
    const [[minLon, minLat], [maxLon, maxLat]] = d3.geoBounds(state);
    let accepted = 0;
    for (let attempt = 0; accepted < count && attempt < count * 12; attempt += 1) {
      const lon = minLon + next() * (maxLon - minLon);
      const lat = minLat + next() * (maxLat - minLat);
      if (!d3.geoContains(state, [lon, lat])) continue;
      points.push({ id: `${fips}-${accepted}`, lon, lat });
      accepted += 1;
    }
  }
  return points;
}

const points = samplePoints();
const distances = points.map((p) => d3.geoDistance(ORIGIN, [p.lon, p.lat]));
const maxDistance = d3.max(distances) ?? 1;
const span = endDate - startDate;

/** Opening date rises with distance from Rogers, which is what makes the real
 *  expansion read as a wave rather than a scatter. Jitter keeps it off perfect rings. */
const dated: Store[] = points
  .map((p, index) => {
    const wave = (distances[index] / maxDistance) ** 0.8;
    const jitter = (hashUnit(p.id, 41) - 0.5) * 0.22;
    const t = Math.min(1, Math.max(0.01, wave + jitter));
    return { ...p, date: startDate + t * span };
  })
  .sort((a, b) => a.date - b.date);

const stores: Store[] = [
  { id: 'rogers-ar', lon: ORIGIN[0], lat: ORIGIN[1], date: startDate },
  ...dated
];

const MARGIN = { top: 26, right: 12, bottom: 38, left: 12 };
const FRAMES = 150;
const HOLD_FRAMES = 16;
const STEP_MS = 80;
const CAPTION =
  'Synthetic locations and opening dates from a seeded generator, not the real Walmart dataset.';

const formatDate = d3.utcFormat('%Y %b %-d');
const formatYear = d3.utcFormat('%Y');
const bisectDate = d3.bisector((d: Store) => d.date).right;

/** Openings sorted by date, plus the window the timeline sweeps (epoch milliseconds). */
export type Data = {
  stores: { id: string; lon: number; lat: number; date: number }[];
  startDate: number;
  endDate: number;
};

const DEMO: Data = { stores, startDate, endDate };

export default function WalmartsGrowth({
  data = DEMO,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.round(width * 0.68);
  const innerWidth = Math.max(0, width - MARGIN.left - MARGIN.right);
  const innerHeight = Math.max(0, height - MARGIN.top - MARGIN.bottom);
  const dotRadius = Math.max(1.6, width / 420);

  const [tick, setTick] = useState(0);

  useEffect(() => {
    const id = window.setInterval(
      () => setTick((t) => (t + 1) % (FRAMES + HOLD_FRAMES)),
      STEP_MS
    );
    return () => window.clearInterval(id);
  }, []);

  // The hold frames park the map on the finished field before the loop restarts.
  const frame = Math.min(tick, FRAMES - 1);
  const currentDate =
    data.startDate + (frame / (FRAMES - 1)) * (data.endDate - data.startDate);

  const { path, placed } = useMemo(() => {
    const projection = d3.geoAlbersUsa().fitSize([innerWidth, innerHeight], lower48);
    const project = (store: Store) => projection([store.lon, store.lat]);
    return {
      path: d3.geoPath(projection),
      placed: data.stores
        .map((store) => {
          const point = project(store);
          return { ...store, x: point?.[0] ?? NaN, y: point?.[1] ?? NaN };
        })
        .filter((d) => Number.isFinite(d.x) && Number.isFinite(d.y))
    };
  }, [data, innerWidth, innerHeight]);

  // `placed` keeps the source order, which is already sorted by opening date.
  const visible = placed.slice(0, bisectDate(placed, currentDate));
  const origin = placed[0];

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label={
        'Animated map of Walmart store openings across the contiguous United States from 1962 ' +
        `to 2006, spreading outward in a wave from the first store in Rogers, Arkansas. ${CAPTION}`
      }
    >
      <text x={MARGIN.left} y={16} fill="var(--muted)" fontSize={11}>
        {width >= 560 ? CAPTION : 'Synthetic data, not the real Walmart dataset.'}
      </text>

      <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
        <g stroke="var(--bg)" strokeWidth={0.6} strokeLinejoin="round">
          {lower48.features.map((state) => (
            <path key={String(state.id)} d={path(state) ?? undefined} fill="var(--line)" />
          ))}
        </g>

        <g fill="none" stroke="var(--text)" strokeWidth={0.9} strokeOpacity={0.75}>
          {visible.map((d) => (
            <motion.circle
              key={d.id}
              cx={d.x}
              cy={d.y}
              initial={{ r: 0 }}
              animate={{ r: dotRadius }}
              transition={{ duration: 0.35 }}
            />
          ))}
        </g>

        {/* The 1962 store stays marked once the wave has buried it in later openings. */}
        <circle cx={origin.x} cy={origin.y} r={dotRadius + 0.8} fill="var(--accent)" />

        <text
          x={0}
          y={innerHeight - 6}
          fill="var(--text)"
          fillOpacity={0.34}
          fontSize={Math.max(18, innerWidth / 16)}
          fontWeight={700}
          style={{ fontVariantNumeric: 'tabular-nums' }}
        >
          {formatDate(new Date(currentDate))}
        </text>
        <text
          x={0}
          y={innerHeight - 6}
          dy="1.5em"
          fill="var(--muted)"
          fontSize={11}
          style={{ fontVariantNumeric: 'tabular-nums' }}
        >
          {`${visible.length} stores open`}
        </text>

        <g transform={`translate(0,${innerHeight + 18})`}>
          <line x1={0} x2={innerWidth} stroke="var(--line)" strokeWidth={3} />
          <line
            x1={0}
            x2={(frame / (FRAMES - 1)) * innerWidth}
            stroke="var(--accent)"
            strokeWidth={3}
          />
          <circle cx={(frame / (FRAMES - 1)) * innerWidth} r={4} fill="var(--accent)" />
          <g className="axis" fill="var(--muted)" fontSize={10}>
            <text y={18}>{formatYear(new Date(data.startDate))}</text>
            <text x={innerWidth} y={18} textAnchor="end">
              {formatYear(new Date(data.endDate))}
            </text>
          </g>
        </g>
      </g>
    </svg>
  );
}
