// World Choropleth — Geo, route: jsx
// Source: world-choropleth_2
//
// Self-contained: every local import is inlined below. Requires only d3, geojson, react, topojson-client, topojson-specification, world-atlas.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { feature, mesh } from 'topojson-client';
import type { FeatureCollection, Geometry, MultiLineString } from 'geojson';
import type { GeometryCollection, Topology } from 'topojson-specification';
import countries110m from 'world-atlas/countries-110m.json';
import { useId, useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from worldChoropleth ----
type CountryProperties = { name: string };

const topology = countries110m as unknown as Topology<{
  countries: GeometryCollection<CountryProperties>;
}>;

const worldCountries = feature(
  topology,
  topology.objects.countries
) as FeatureCollection<Geometry, CountryProperties>;

/** Internal borders only, so the coastline is not double-stroked over islands and inlets. */
const countryBorders = mesh(
  topology,
  topology.objects.countries,
  (a, b) => a !== b
) as MultiLineString;

/** Two of the 177 geometries carry no ISO id, so the name backs the key. */
function countryKey(id: string | number | undefined, name: string): string {
  return id === undefined ? name : String(id);
}

// FNV-1a over the key: a fixed hash keeps the synthetic values identical across reloads.
function hashUnit(key: string): number {
  let hash = 2166136261;
  for (let i = 0; i < key.length; i++) {
    hash = Math.imul(hash ^ key.charCodeAt(i), 16777619);
  }
  return (hash >>> 0) / 4294967296;
}

const lifeExpectancy = new Map<string, number>(
  worldCountries.features.map((f) => {
    const key = countryKey(f.id, f.properties.name);
    return [key, Math.round((52 + hashUnit(key) * 26) * 10) / 10];
  })
);

const MARGIN = { top: 48, right: 2, bottom: 2, left: 2 };
const LEGEND = { x: 14, y: 20, width: 240, height: 10 };
const SPHERE: d3.GeoSphere = { type: 'Sphere' };

/** One value per country, keyed by `countryKey(feature id, feature name)`. */
export type Data = Map<string, number>;

export default function WorldChoropleth({
  data = lifeExpectancy,
  width
}: {
  data?: Data;
  width: number;
}) {
  const gradientId = useId();
  const height = Math.round(width / 2) + MARGIN.top;

  const path = useMemo(() => {
    const projection = d3.geoEqualEarth().fitExtent(
      [
        [MARGIN.left, MARGIN.top],
        [width - MARGIN.right, height - MARGIN.bottom]
      ],
      SPHERE
    );
    return d3.geoPath(projection);
  }, [width, height]);

  const color = useMemo(() => {
    const domain = d3.extent(data.values()) as [number, number];
    return d3.scaleSequential(domain, d3.interpolateYlGnBu);
  }, [data]);

  const stops = useMemo(
    () => d3.ticks(0, 1, 12).map((t) => ({ offset: t, color: color.interpolator()(t) })),
    [color]
  );

  const legendTicks = useMemo(() => {
    const x = d3.scaleLinear(color.domain(), [LEGEND.x, LEGEND.x + LEGEND.width]);
    return x.ticks(5).map((v) => ({ value: v, offset: x(v) }));
  }, [color]);

  const showLegend = width >= LEGEND.width + 120;

  if (width === 0) return null;

  return (
    <svg viewBox={`0 0 ${width} ${height}`} width="100%" height={height} role="img"
         aria-label="World choropleth of healthy life expectancy by country, Equal Earth projection">
      <defs>
        <linearGradient id={gradientId} x1="0%" x2="100%">
          {stops.map((stop) => (
            <stop key={stop.offset} offset={stop.offset} stopColor={stop.color} />
          ))}
        </linearGradient>
      </defs>

      {showLegend && (
        <g className="axis">
          <text x={LEGEND.x} y={12} fill="var(--text)" fontSize={11} fontWeight={600}>
            Healthy life expectancy (years)
          </text>
          <rect x={LEGEND.x} y={LEGEND.y} width={LEGEND.width} height={LEGEND.height}
                fill={`url(#${gradientId})`} />
          {legendTicks.map(({ value, offset }) => (
            <g key={value} transform={`translate(${offset},${LEGEND.y + LEGEND.height})`}>
              <line y1={0} y2={5} />
              <text y={17} textAnchor="middle">
                {value}
              </text>
            </g>
          ))}
        </g>
      )}

      <path d={path(SPHERE) ?? ''} fill="none" stroke="var(--muted)" />

      {worldCountries.features.map((f, i) => {
        const key = countryKey(f.id, f.properties.name);
        const value = data.get(key);
        return (
          <path key={`${key}-${i}`} d={path(f) ?? ''}
                fill={value === undefined ? 'var(--line)' : color(value)}>
            <title>{`${f.properties.name}\n${value ?? 'no data'}`}</title>
          </path>
        );
      })}

      <path d={path(countryBorders) ?? ''} fill="none" stroke="var(--panel)" strokeWidth={0.5} />
    </svg>
  );
}
