// World Airports Voronoi — Geo, route: jsx
// Source: world-airports-voronoi
//
// Self-contained: every local import is inlined below. Requires only d3, geojson, react, topojson-client, topojson-specification, us-atlas, world-atlas.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { feature, mesh } from 'topojson-client';
import countries110m from 'world-atlas/countries-110m.json';
import statesUs from 'us-atlas/states-10m.json';
import type { GeometryCollection, Topology } from 'topojson-specification';
import type { Feature, FeatureCollection, Geometry, MultiLineString } from 'geojson';
import { useMemo } from 'react';
import * as d3 from 'd3';

// ---- inlined from geo ----
// The atlases ship untyped JSON. One cast per topology at this boundary keeps every
// consumer strict, and converting here means each chart does not re-derive the same
// geometry at module load.

type Named = { name: string };
type NamedFeature = Feature<Geometry, Named>;

const world = countries110m as unknown as Topology<{
  countries: GeometryCollection<Named>;
  land: GeometryCollection;
}>;

const us = statesUs as unknown as Topology<{
  states: GeometryCollection<Named>;
  nation: GeometryCollection;
}>;

const worldCountries = feature(
  world,
  world.objects.countries
) as FeatureCollection<Geometry, Named>;

const worldLand = feature(world, world.objects.land) as FeatureCollection<Geometry>;

/** Shared borders only, so neighbouring outlines are stroked once instead of twice. */
const worldBorders = mesh(
  world,
  world.objects.countries,
  (a, b) => a !== b
) as MultiLineString;

const usNation = feature(us, us.objects.nation) as FeatureCollection<Geometry>;

const usStateBorders = mesh(
  us,
  us.objects.states,
  (a, b) => a !== b
) as MultiLineString;

/**
 * The 50 states plus DC. geoAlbersUsa cannot project FIPS ids of 60 and above
 * (territories) and returns null for them, which becomes a NaN centroid downstream.
 * Use this rather than the raw collection for anything Albers-projected.
 */
const usStates: NamedFeature[] = (
  feature(us, us.objects.states) as FeatureCollection<Geometry, Named>
).features.filter((d) => Number(d.id) < 60);

const usStatesCollection: FeatureCollection<Geometry, Named> = {
  type: 'FeatureCollection',
  features: usStates
};

/**
 * FNV-1a over an id, run through the murmur3 finalizer. Two-character FIPS ids barely
 * differ, and without the finalizer they map to a near-constant. Returns [0, 1).
 * Charts use it to synthesize per-region values deterministically instead of fetching.
 */
function hashUnit(id: string, salt = 0): number {
  let h = 2166136261 ^ salt;
  for (let i = 0; i < id.length; i++) {
    h = Math.imul(h ^ id.charCodeAt(i), 16777619);
  }
  h ^= h >>> 16;
  h = Math.imul(h, 2246822507);
  h ^= h >>> 13;
  return (h >>> 0) / 4294967296;
}

// ---- inlined from worldAirports ----
/**
 * A globally spread subset of the ~7000-row airport list the source notebook loads: 204 real
 * airports, hand-thinned so every ocean basin, both polar regions and Antarctica carry a site.
 * Positions are approximate to about a tenth of a degree, which is well under a pixel at
 * globe scale. Even coverage is what makes the spherical Voronoi readable rather than a mat
 * of hairline cells over Europe and three continent-sized ones everywhere else.
 *
 * [longitude, latitude, iata, name, country]
 */
type WorldAirport = [number, number, string, string, string];

const worldAirports: WorldAirport[] = [
  [-84.428, 33.637, 'ATL', 'Hartsfield-Jackson', 'United States'],
  [-118.408, 33.942, 'LAX', 'Los Angeles Intl', 'United States'],
  [-87.905, 41.978, 'ORD', "O'Hare Intl", 'United States'],
  [-97.038, 32.897, 'DFW', 'Dallas/Fort Worth', 'United States'],
  [-104.673, 39.858, 'DEN', 'Denver Intl', 'United States'],
  [-73.779, 40.64, 'JFK', 'John F. Kennedy Intl', 'United States'],
  [-122.375, 37.619, 'SFO', 'San Francisco Intl', 'United States'],
  [-122.309, 47.449, 'SEA', 'Seattle-Tacoma', 'United States'],
  [-80.29, 25.793, 'MIA', 'Miami Intl', 'United States'],
  [-112.012, 33.434, 'PHX', 'Sky Harbor', 'United States'],
  [-95.341, 29.984, 'IAH', 'George Bush Intercontinental', 'United States'],
  [-71.006, 42.363, 'BOS', 'Logan Intl', 'United States'],
  [-93.222, 44.882, 'MSP', 'Minneapolis-St Paul', 'United States'],
  [-149.996, 61.174, 'ANC', 'Ted Stevens Anchorage', 'United States'],
  [-157.922, 21.319, 'HNL', 'Daniel K. Inouye', 'United States'],
  [-156.766, 71.285, 'BRW', 'Wiley Post-Will Rogers', 'United States'],
  [-79.631, 43.677, 'YYZ', 'Toronto Pearson', 'Canada'],
  [-123.184, 49.194, 'YVR', 'Vancouver Intl', 'Canada'],
  [-73.741, 45.47, 'YUL', 'Montreal-Trudeau', 'Canada'],
  [-114.02, 51.114, 'YYC', 'Calgary Intl', 'Canada'],
  [-113.58, 53.31, 'YEG', 'Edmonton Intl', 'Canada'],
  [-97.24, 49.91, 'YWG', 'Winnipeg Richardson', 'Canada'],
  [-114.44, 62.463, 'YZF', 'Yellowknife', 'Canada'],
  [-68.556, 63.756, 'YFB', 'Iqaluit', 'Canada'],
  [-94.969, 74.717, 'YRB', 'Resolute Bay', 'Canada'],
  [-52.752, 47.619, 'YYT', "St John's Intl", 'Canada'],
  [-99.072, 19.436, 'MEX', 'Benito Juarez', 'Mexico'],
  [-86.877, 21.037, 'CUN', 'Cancun Intl', 'Mexico'],
  [-110.362, 24.073, 'LAP', 'Manuel Marquez de Leon', 'Mexico'],
  [-66.002, 18.439, 'SJU', 'Luis Munoz Marin', 'Puerto Rico'],
  [-82.409, 22.989, 'HAV', 'Jose Marti Intl', 'Cuba'],
  [-90.527, 14.583, 'GUA', 'La Aurora', 'Guatemala'],
  [-79.383, 9.071, 'PTY', 'Tocumen Intl', 'Panama'],
  [-64.679, 32.364, 'BDA', 'L.F. Wade Intl', 'Bermuda'],
  [-50.689, 67.017, 'SFJ', 'Kangerlussuaq', 'Greenland'],
  [-51.678, 64.191, 'GOH', 'Nuuk', 'Greenland'],
  [-177.382, 28.202, 'MDY', 'Henderson Field', 'Midway Atoll'],
  [-74.147, 4.702, 'BOG', 'El Dorado Intl', 'Colombia'],
  [-66.991, 10.601, 'CCS', 'Simon Bolivar Intl', 'Venezuela'],
  [-78.359, -0.129, 'UIO', 'Mariscal Sucre', 'Ecuador'],
  [-77.114, -12.022, 'LIM', 'Jorge Chavez Intl', 'Peru'],
  [-68.192, -16.513, 'LPB', 'El Alto Intl', 'Bolivia'],
  [-60.05, -3.039, 'MAO', 'Eduardo Gomes', 'Brazil'],
  [-47.921, -15.869, 'BSB', 'Brasilia Intl', 'Brazil'],
  [-34.923, -8.126, 'REC', 'Guararapes-Gilberto Freyre', 'Brazil'],
  [-46.473, -23.435, 'GRU', 'Guarulhos Intl', 'Brazil'],
  [-43.243, -22.809, 'GIG', 'Galeao Intl', 'Brazil'],
  [-58.254, 6.499, 'GEO', 'Cheddi Jagan Intl', 'Guyana'],
  [-52.36, 4.819, 'CAY', 'Felix Eboue', 'French Guiana'],
  [-57.52, -25.24, 'ASU', 'Silvio Pettirossi', 'Paraguay'],
  [-56.031, -34.838, 'MVD', 'Carrasco Intl', 'Uruguay'],
  [-58.536, -34.822, 'EZE', 'Ministro Pistarini', 'Argentina'],
  [-70.786, -33.393, 'SCL', 'Arturo Merino Benitez', 'Chile'],
  [-68.296, -54.843, 'USH', 'Malvinas Argentinas', 'Argentina'],
  [-70.855, -53.002, 'PUQ', 'Presidente Ibanez', 'Chile'],
  [-58.447, -51.823, 'MPN', 'Mount Pleasant', 'Falkland Islands'],
  [-109.422, -27.165, 'IPC', 'Mataveri', 'Chile'],
  [-90.266, -0.454, 'GPS', 'Seymour', 'Ecuador'],
  [-0.462, 51.47, 'LHR', 'Heathrow', 'United Kingdom'],
  [2.548, 49.01, 'CDG', 'Charles de Gaulle', 'France'],
  [4.764, 52.309, 'AMS', 'Schiphol', 'Netherlands'],
  [8.57, 50.037, 'FRA', 'Frankfurt am Main', 'Germany'],
  [-3.567, 40.472, 'MAD', 'Barajas', 'Spain'],
  [2.078, 41.297, 'BCN', 'El Prat', 'Spain'],
  [12.252, 41.8, 'FCO', 'Fiumicino', 'Italy'],
  [-6.27, 53.421, 'DUB', 'Dublin', 'Ireland'],
  [-9.135, 38.774, 'LIS', 'Humberto Delgado', 'Portugal'],
  [8.549, 47.464, 'ZRH', 'Zurich', 'Switzerland'],
  [16.57, 48.11, 'VIE', 'Vienna Intl', 'Austria'],
  [20.967, 52.166, 'WAW', 'Chopin', 'Poland'],
  [12.656, 55.618, 'CPH', 'Kastrup', 'Denmark'],
  [11.1, 60.194, 'OSL', 'Gardermoen', 'Norway'],
  [17.918, 59.652, 'ARN', 'Arlanda', 'Sweden'],
  [24.964, 60.317, 'HEL', 'Helsinki-Vantaa', 'Finland'],
  [-22.626, 63.985, 'KEF', 'Keflavik', 'Iceland'],
  [15.466, 78.246, 'LYR', 'Svalbard', 'Norway'],
  [23.947, 37.936, 'ATH', 'Eleftherios Venizelos', 'Greece'],
  [26.085, 44.572, 'OTP', 'Henri Coanda', 'Romania'],
  [30.895, 50.345, 'KBP', 'Boryspil', 'Ukraine'],
  [37.415, 55.973, 'SVO', 'Sheremetyevo', 'Russia'],
  [30.263, 59.8, 'LED', 'Pulkovo', 'Russia'],
  [32.75, 68.782, 'MMK', 'Murmansk', 'Russia'],
  [-25.706, 37.741, 'PDL', 'Joao Paulo II', 'Portugal'],
  [-16.774, 32.694, 'FNC', 'Madeira', 'Portugal'],
  [-15.386, 27.932, 'LPA', 'Gran Canaria', 'Spain'],
  [28.742, 41.275, 'IST', 'Istanbul', 'Turkey'],
  [33.625, 34.875, 'LCA', 'Larnaca', 'Cyprus'],
  [34.887, 32.011, 'TLV', 'Ben Gurion', 'Israel'],
  [35.993, 31.723, 'AMM', 'Queen Alia', 'Jordan'],
  [44.235, 33.263, 'BGW', 'Baghdad Intl', 'Iraq'],
  [51.152, 35.416, 'IKA', 'Imam Khomeini', 'Iran'],
  [47.972, 29.227, 'KWI', 'Kuwait Intl', 'Kuwait'],
  [46.699, 24.958, 'RUH', 'King Khalid', 'Saudi Arabia'],
  [39.157, 21.68, 'JED', 'King Abdulaziz', 'Saudi Arabia'],
  [51.608, 25.261, 'DOH', 'Hamad Intl', 'Qatar'],
  [55.364, 25.253, 'DXB', 'Dubai Intl', 'United Arab Emirates'],
  [58.284, 23.593, 'MCT', 'Muscat Intl', 'Oman'],
  [44.396, 40.147, 'EVN', 'Zvartnots', 'Armenia'],
  [50.047, 40.467, 'GYD', 'Heydar Aliyev', 'Azerbaijan'],
  [58.361, 37.987, 'ASB', 'Ashgabat', 'Turkmenistan'],
  [69.281, 41.258, 'TAS', 'Tashkent Intl', 'Uzbekistan'],
  [77.041, 43.352, 'ALA', 'Almaty Intl', 'Kazakhstan'],
  [69.212, 34.566, 'KBL', 'Hamid Karzai', 'Afghanistan'],
  [31.406, 30.122, 'CAI', 'Cairo Intl', 'Egypt'],
  [13.159, 32.664, 'TIP', 'Tripoli Intl', 'Libya'],
  [10.227, 36.851, 'TUN', 'Tunis-Carthage', 'Tunisia'],
  [3.215, 36.691, 'ALG', 'Houari Boumediene', 'Algeria'],
  [-7.59, 33.367, 'CMN', 'Mohammed V', 'Morocco'],
  [-17.073, 14.671, 'DSS', 'Blaise Diagne', 'Senegal'],
  [-3.933, 5.261, 'ABJ', 'Felix Houphouet-Boigny', "Cote d'Ivoire"],
  [-0.167, 5.605, 'ACC', 'Kotoka Intl', 'Ghana'],
  [3.321, 6.577, 'LOS', 'Murtala Muhammed', 'Nigeria'],
  [2.184, 13.481, 'NIM', 'Diori Hamani', 'Niger'],
  [15.034, 12.134, 'NDJ', "N'Djamena Intl", 'Chad'],
  [32.553, 15.589, 'KRT', 'Khartoum Intl', 'Sudan'],
  [38.799, 8.978, 'ADD', 'Bole Intl', 'Ethiopia'],
  [45.305, 2.014, 'MGQ', 'Aden Adde', 'Somalia'],
  [36.928, -1.319, 'NBO', 'Jomo Kenyatta', 'Kenya'],
  [39.203, -6.878, 'DAR', 'Julius Nyerere', 'Tanzania'],
  [15.445, -4.386, 'FIH', "N'djili", 'DR Congo'],
  [13.231, -8.858, 'LAD', 'Quatro de Fevereiro', 'Angola'],
  [31.093, -17.932, 'HRE', 'Robert Mugabe', 'Zimbabwe'],
  [32.573, -25.921, 'MPM', 'Maputo Intl', 'Mozambique'],
  [17.472, -22.48, 'WDH', 'Hosea Kutako', 'Namibia'],
  [28.246, -26.139, 'JNB', 'O.R. Tambo', 'South Africa'],
  [18.602, -33.965, 'CPT', 'Cape Town Intl', 'South Africa'],
  [47.478, -18.797, 'TNR', 'Ivato', 'Madagascar'],
  [55.51, -20.887, 'RUN', 'Roland Garros', 'Reunion'],
  [57.683, -20.43, 'MRU', 'Sir Seewoosagur Ramgoolam', 'Mauritius'],
  [55.521, -4.674, 'SEZ', 'Seychelles Intl', 'Seychelles'],
  [-14.394, -7.97, 'ASI', 'Wideawake Field', 'Ascension Island'],
  [72.826, 33.549, 'ISB', 'Islamabad Intl', 'Pakistan'],
  [67.161, 24.906, 'KHI', 'Jinnah Intl', 'Pakistan'],
  [77.103, 28.556, 'DEL', 'Indira Gandhi', 'India'],
  [72.868, 19.089, 'BOM', 'Chhatrapati Shivaji', 'India'],
  [80.169, 12.99, 'MAA', 'Chennai Intl', 'India'],
  [88.447, 22.654, 'CCU', 'Netaji Subhas Chandra Bose', 'India'],
  [85.359, 27.697, 'KTM', 'Tribhuvan Intl', 'Nepal'],
  [90.398, 23.843, 'DAC', 'Hazrat Shahjalal', 'Bangladesh'],
  [79.884, 7.181, 'CMB', 'Bandaranaike Intl', 'Sri Lanka'],
  [73.529, 4.192, 'MLE', 'Velana Intl', 'Maldives'],
  [96.133, 16.907, 'RGN', 'Yangon Intl', 'Myanmar'],
  [100.747, 13.69, 'BKK', 'Suvarnabhumi', 'Thailand'],
  [105.807, 21.221, 'HAN', 'Noi Bai Intl', 'Vietnam'],
  [106.66, 10.819, 'SGN', 'Tan Son Nhat', 'Vietnam'],
  [103.994, 1.359, 'SIN', 'Changi', 'Singapore'],
  [101.71, 2.746, 'KUL', 'Kuala Lumpur Intl', 'Malaysia'],
  [106.656, -6.126, 'CGK', 'Soekarno-Hatta', 'Indonesia'],
  [115.167, -8.748, 'DPS', 'Ngurah Rai', 'Indonesia'],
  [121.02, 14.509, 'MNL', 'Ninoy Aquino', 'Philippines'],
  [113.915, 22.309, 'HKG', 'Hong Kong Intl', 'Hong Kong'],
  [121.233, 25.078, 'TPE', 'Taoyuan Intl', 'Taiwan'],
  [113.299, 23.392, 'CAN', 'Baiyun Intl', 'China'],
  [121.805, 31.143, 'PVG', 'Pudong Intl', 'China'],
  [116.585, 40.08, 'PEK', 'Capital Intl', 'China'],
  [103.947, 30.579, 'CTU', 'Shuangliu Intl', 'China'],
  [90.912, 29.298, 'LXA', 'Gonggar', 'China'],
  [87.474, 43.907, 'URC', 'Diwopu Intl', 'China'],
  [106.82, 47.653, 'UBN', 'Chinggis Khaan', 'Mongolia'],
  [82.651, 55.013, 'OVB', 'Tolmachevo', 'Russia'],
  [87.332, 69.311, 'NSK', 'Alykel', 'Russia'],
  [104.389, 52.268, 'IKT', 'Irkutsk Intl', 'Russia'],
  [129.771, 62.093, 'YKS', 'Yakutsk', 'Russia'],
  [128.903, 71.698, 'IKS', 'Tiksi', 'Russia'],
  [170.597, 69.783, 'PWE', 'Pevek', 'Russia'],
  [158.454, 53.168, 'PKC', 'Yelizovo', 'Russia'],
  [132.148, 43.399, 'VVO', 'Vladivostok Intl', 'Russia'],
  [126.451, 37.469, 'ICN', 'Incheon Intl', 'South Korea'],
  [140.386, 35.765, 'NRT', 'Narita Intl', 'Japan'],
  [135.244, 34.427, 'KIX', 'Kansai Intl', 'Japan'],
  [141.692, 42.775, 'CTS', 'New Chitose', 'Japan'],
  [127.646, 26.196, 'OKA', 'Naha', 'Japan'],
  [144.796, 13.484, 'GUM', 'Antonio B. Won Pat', 'Guam'],
  [171.272, 7.065, 'MAJ', 'Marshall Islands Intl', 'Marshall Islands'],
  [173.147, 1.382, 'TRW', 'Bonriki Intl', 'Kiribati'],
  [-157.35, 1.986, 'CXI', 'Cassidy Intl', 'Kiribati'],
  [166.919, -0.548, 'INU', 'Nauru Intl', 'Nauru'],
  [147.22, -9.443, 'POM', 'Jacksons Intl', 'Papua New Guinea'],
  [160.055, -9.428, 'HIR', 'Honiara Intl', 'Solomon Islands'],
  [168.32, -17.699, 'VLI', 'Bauerfield Intl', 'Vanuatu'],
  [166.213, -22.015, 'NOU', 'La Tontouta', 'New Caledonia'],
  [177.443, -17.755, 'NAN', 'Nadi Intl', 'Fiji'],
  [-171.997, -13.83, 'APW', 'Faleolo Intl', 'Samoa'],
  [-175.15, -21.241, 'TBU', 'Fuaamotu Intl', 'Tonga'],
  [-149.612, -17.554, 'PPT', "Faa'a Intl", 'French Polynesia'],
  [-159.796, -21.203, 'RAR', 'Rarotonga Intl', 'Cook Islands'],
  [130.877, -12.415, 'DRW', 'Darwin Intl', 'Australia'],
  [153.117, -27.384, 'BNE', 'Brisbane Intl', 'Australia'],
  [151.177, -33.946, 'SYD', 'Kingsford Smith', 'Australia'],
  [144.843, -37.673, 'MEL', 'Melbourne Intl', 'Australia'],
  [138.531, -34.945, 'ADL', 'Adelaide Intl', 'Australia'],
  [115.967, -31.94, 'PER', 'Perth Intl', 'Australia'],
  [147.51, -42.836, 'HBA', 'Hobart Intl', 'Australia'],
  [167.939, -29.041, 'NLK', 'Norfolk Island', 'Australia'],
  [174.792, -37.008, 'AKL', 'Auckland Intl', 'New Zealand'],
  [172.532, -43.489, 'CHC', 'Christchurch Intl', 'New Zealand'],
  [168.313, -46.412, 'IVC', 'Invercargill', 'New Zealand'],
  [-68.128, -67.567, 'RTH', 'Rothera Research Station', 'Antarctica'],
  [-83.5, -79.767, 'UGL', 'Union Glacier', 'Antarctica'],
  [11.833, -70.833, 'NVL', 'Novolazarevskaya', 'Antarctica'],
  [62.87, -67.6, 'MAW', 'Mawson Station', 'Antarctica'],
  [111.523, -66.69, 'WLK', 'Wilkins Aerodrome', 'Antarctica'],
  [166.928, -77.867, 'MCM', 'Williams Field', 'Antarctica'],
  [139.267, -89.997, 'NPX', 'Jack F. Paulus Skiway', 'Antarctica']
];

const MARGIN = 6;
const MAX_HEIGHT = 560;
const CAPTION_BAND = 18;
const CAPTION_MIN_WIDTH = 440;
const ROTATE: [number, number] = [-10, -25];

/**
 * Centre of the stereographic frame the triangulation is computed in. Its antipode is the
 * one point the planar Delaunay cannot see, so it sits in the empty South Pacific, which is
 * also on the hidden hemisphere of the view below.
 */
const PIVOT: [number, number] = [40, 55];

const RADIANS = Math.PI / 180;
const sphere: d3.GeoSphere = { type: 'Sphere' };
const graticule = d3.geoGraticule().step([15, 15])();

type Vec3 = [number, number, number];

function cartesian([lon, lat]: [number, number]): Vec3 {
  const l = lon * RADIANS;
  const p = lat * RADIANS;
  const cosP = Math.cos(p);
  return [cosP * Math.cos(l), cosP * Math.sin(l), Math.sin(p)];
}

/**
 * The unit normal of the plane through three sites is equally far from all three, so it is
 * their spherical circumcentre — a Voronoi vertex. Both normals qualify; take the one on
 * the sites' own side of the globe.
 */
function circumcenter(a: Vec3, b: Vec3, c: Vec3): [number, number] {
  const n: Vec3 = [
    (b[1] - a[1]) * (c[2] - a[2]) - (b[2] - a[2]) * (c[1] - a[1]),
    (b[2] - a[2]) * (c[0] - a[0]) - (b[0] - a[0]) * (c[2] - a[2]),
    (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0])
  ];
  const facing =
    n[0] * (a[0] + b[0] + c[0]) + n[1] * (a[1] + b[1] + c[1]) + n[2] * (a[2] + b[2] + c[2]);
  const k = (facing < 0 ? -1 : 1) / Math.hypot(n[0], n[1], n[2]);
  return [
    Math.atan2(k * n[1], k * n[0]) / RADIANS,
    Math.asin(Math.min(1, Math.max(-1, k * n[2]))) / RADIANS
  ];
}

/**
 * Spherical Voronoi as the dual of a spherical Delaunay. Stereographic projection carries
 * spherical caps to disks, so the planar Delaunay of the projected sites IS the spherical
 * one, less the triangles whose cap swallows the point at infinity. Each interior half-edge
 * pair then gives one arc between two circumcentres, and geoPath draws those as great
 * circles. The planar Voronoi is never used — only the triangulation survives the trip.
 */
function buildCellMesh(airports: Data): MultiLineString {
  const sites = airports.map(([lon, lat]): [number, number] => [lon, lat]);
  const frame = d3.geoStereographic().translate([0, 0]).scale(1).rotate([-PIVOT[0], -PIVOT[1]]);
  const planar = sites.map((site) => frame(site) ?? [0, 0]);
  const vectors = sites.map(cartesian);

  const delaunay = d3.Delaunay.from(
    planar,
    (d) => d[0],
    (d) => d[1]
  );

  const vertices: [number, number][] = [];
  for (let t = 0; t < delaunay.triangles.length; t += 3) {
    vertices.push(
      circumcenter(
        vectors[delaunay.triangles[t]],
        vectors[delaunay.triangles[t + 1]],
        vectors[delaunay.triangles[t + 2]]
      )
    );
  }

  const coordinates: [number, number][][] = [];
  for (let e = 0; e < delaunay.halfedges.length; e++) {
    // -1 marks a hull edge, which has no cell arc; a lower index is the pair's second visit.
    const opposite = delaunay.halfedges[e];
    if (opposite < e) continue;
    coordinates.push([vertices[(e / 3) | 0], vertices[(opposite / 3) | 0]]);
  }

  return { type: 'MultiLineString', coordinates };
}

/** One site per row: [longitude, latitude, IATA code, airport name, country]. */
export type Data = [number, number, string, string, string][];

export default function WorldAirportsVoronoi({
  data = worldAirports,
  width
}: {
  data?: Data;
  width: number;
}) {
  const height = Math.min(Math.round(width * 0.72), MAX_HEIGHT);

  const cellMesh = useMemo(() => buildCellMesh(data), [data]);

  const shapes = useMemo(() => {
    const projection = d3
      .geoOrthographic()
      .rotate(ROTATE)
      .precision(0.3)
      .fitExtent(
        [
          [MARGIN, MARGIN],
          [Math.max(width - MARGIN, MARGIN + 1), Math.max(height - CAPTION_BAND, MARGIN + 1)]
        ],
        sphere
      );
    const path = d3.geoPath(projection).pointRadius(1.6);
    return {
      outline: path(sphere) ?? '',
      grid: path(graticule) ?? '',
      land: path(worldLand) ?? '',
      cells: path(cellMesh) ?? '',
      // A Point projects to nothing on the far hemisphere, which is how sites are hidden.
      sites: data.flatMap(([lon, lat, iata, name, country]) => {
        const d = path({ type: 'Point', coordinates: [lon, lat] });
        return d ? [{ iata, title: `${name} (${iata})\n${country}`, d }] : [];
      })
    };
  }, [data, cellMesh, width, height]);

  if (width === 0) return null;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label={`Orthographic globe carrying a spherical Voronoi diagram of ${data.length} major world airports, where every cell is the region of the Earth closest to one airport. The airports are a globally spread subset of the full list, chosen so each ocean basin and both polar regions carry a site.`}
    >
      <path d={shapes.outline} fill="var(--line)" fillOpacity={0.25} />
      <path d={shapes.grid} fill="none" stroke="var(--muted)" strokeWidth={0.4} opacity={0.55} />
      <path d={shapes.land} fill="var(--line)" />
      <path
        d={shapes.cells}
        fill="none"
        stroke="var(--accent)"
        strokeWidth={0.7}
        strokeOpacity={0.85}
        strokeLinejoin="round"
      />
      <path d={shapes.outline} fill="none" stroke="var(--text)" strokeWidth={1.25} />
      <g fill="var(--text)">
        {shapes.sites.map((site) => (
          <path key={site.iata} d={site.d}>
            <title>{site.title}</title>
          </path>
        ))}
      </g>
      {width >= CAPTION_MIN_WIDTH && (
        <text
          x={width / 2}
          y={height - CAPTION_BAND / 3}
          textAnchor="middle"
          fontSize={11}
          fill="var(--muted)"
          aria-hidden="true"
        >
          {data.length} major airports · cells bounded by great circles, not straight
          lines
        </text>
      )}
    </svg>
  );
}
