// Zoomable Icicle — Interaction, route: ref
// Source: zoomable-icicle
//
// Self-contained: every local import is inlined below. Requires only d3, react.
// Generated by scripts/build-exemplars.mjs — edit src/gallery/, not this file.

import { useEffect, useMemo, useRef } from 'react';
import * as d3 from 'd3';

// ---- inlined from zoomableIcicle ----
/** A node is either a title carrying watch hours or a grouping carrying children, never both. */
interface ArchiveNode {
  name: string;
  value?: number;
  children?: ArchiveNode[];
}

/** Invented streaming catalog: 4 levels, 34 titles, values are thousands of watch hours. */
const catalog: ArchiveNode = {
  name: 'catalog',
  children: [
    {
      name: 'Drama',
      children: [
        {
          name: 'Crime',
          children: [
            { name: 'Nightfall', value: 4820 },
            { name: 'Precinct', value: 3610 },
            { name: 'Undertow', value: 2940 }
          ]
        },
        {
          name: 'Period',
          children: [
            { name: 'Ironwood', value: 5170 },
            { name: 'Sable Court', value: 3080 }
          ]
        },
        {
          name: 'Legal',
          children: [
            { name: 'Docket', value: 2760 },
            { name: 'Appeal', value: 1930 }
          ]
        }
      ]
    },
    {
      name: 'Comedy',
      children: [
        {
          name: 'Sitcom',
          children: [
            { name: 'Third Floor', value: 4410 },
            { name: 'Roommates', value: 3220 },
            { name: 'Bodega', value: 2150 }
          ]
        },
        {
          name: 'Sketch',
          children: [
            { name: 'Cold Open', value: 2680 },
            { name: 'Punchline', value: 1740 }
          ]
        },
        {
          name: 'Standup',
          children: [
            { name: 'Late Set', value: 3050 },
            { name: 'Open Mic', value: 1460 }
          ]
        }
      ]
    },
    {
      name: 'Docs',
      children: [
        {
          name: 'Nature',
          children: [
            { name: 'Deep Reef', value: 5640 },
            { name: 'Tundra', value: 3870 },
            { name: 'Canopy', value: 2510 }
          ]
        },
        {
          name: 'History',
          children: [
            { name: 'Ledger', value: 3140 },
            { name: 'Cartograph', value: 2270 }
          ]
        },
        {
          name: 'Science',
          children: [
            { name: 'Lattice', value: 4090 },
            { name: 'Neutrino', value: 2830 }
          ]
        }
      ]
    },
    {
      name: 'Music',
      children: [
        {
          name: 'Live',
          children: [
            { name: 'Amphitheatre', value: 4730 },
            { name: 'Basement', value: 2360 }
          ]
        },
        {
          name: 'Studio',
          children: [
            { name: 'Session', value: 3520 },
            { name: 'B-Sides', value: 1890 }
          ]
        },
        {
          name: 'Archive',
          children: [
            { name: 'Reels', value: 2140 },
            { name: 'Acetates', value: 1270 }
          ]
        }
      ]
    },
    {
      name: 'Kids',
      children: [
        {
          name: 'Animated',
          children: [
            { name: 'Pocket Zoo', value: 5280 },
            { name: 'Sunbeam', value: 3640 },
            { name: 'Gizmo', value: 2470 }
          ]
        },
        {
          name: 'Learning',
          children: [
            { name: 'Counting', value: 2830 },
            { name: 'Phonics', value: 1950 }
          ]
        },
        {
          name: 'Shorts',
          children: [
            { name: 'Ten Minute', value: 1680 },
            { name: 'Bumpers', value: 1120 }
          ]
        }
      ]
    }
  ]
};

/** Root of a tree: a leaf carries `value`, a grouping carries `children`, never both. */
export type Data = { name: string; value?: number; children?: Data[] };

type Cell = d3.HierarchyRectangularNode<Data>;
type Rect = { x0: number; x1: number; y0: number; y1: number };

const MARGIN = { top: 8, right: 8, bottom: 8, left: 8 };
const FONT_SIZE = 10;
/** A row shorter than this cannot hold a baseline at y=13 without spilling into its neighbour. */
const MIN_ROW_HEIGHT = 16;
/** Mean advance width of 10px sans-serif, used to drop the value when it would overflow. */
const CHAR_WIDTH = 5.6;
const LABEL_INSET = 4;
const DURATION = 750;
/** The layout is one column wider than the viewport, so only three depths show at a time. */
const VISIBLE_COLUMNS = 3;

const format = d3.format(',d');
const TRANSLATE = /translate\(([-\d.e+]+),([-\d.e+]+)\)/;

/** Reads a cell's live position so an interrupted zoom resumes from where it stopped. */
function translationOf(node: SVGGElement): [number, number] {
  const parts = TRANSLATE.exec(node.getAttribute('transform') ?? '');
  return parts ? [Number(parts[1]), Number(parts[2])] : [0, 0];
}

function pathOf(node: Cell): string {
  return node
    .ancestors()
    .map((a) => a.data.name)
    .reverse()
    .join('/');
}

/** Every cell takes the colour of the depth-1 genre it descends from. */
function genreOf(node: Cell): string {
  let current = node;
  while (current.depth > 1 && current.parent) current = current.parent;
  return current.data.name;
}

export default function ZoomableIcicle({
  data = catalog,
  width
}: {
  data?: Data;
  width: number;
}) {
  // Hooks run before the width===0 guard below, and d3.partition throws on a zero-sized layout.
  const height = Math.round(Math.max(width, 1) * 1.25);
  const innerWidth = Math.max(width - MARGIN.left - MARGIN.right, 1);
  const innerHeight = Math.max(height - MARGIN.top - MARGIN.bottom, 1);
  const svgRef = useRef<SVGSVGElement>(null);

  const root = useMemo(() => {
    const hierarchy = d3
      .hierarchy(data)
      .sum((d) => d.value ?? 0)
      .sort((a, b) => b.height - a.height || (b.value ?? 0) - (a.value ?? 0));
    return d3
      .partition<Data>()
      .size([innerHeight, ((hierarchy.height + 1) * innerWidth) / VISIBLE_COLUMNS])(hierarchy);
  }, [data, innerWidth, innerHeight]);

  const color = useMemo(
    () =>
      d3
        .scaleOrdinal<string, string>()
        .domain((data.children ?? []).map((d) => d.name))
        .range(d3.schemeObservable10),
    [data]
  );

  useEffect(() => {
    const element = svgRef.current;
    if (!element) return;

    const svg = d3.select(element);
    svg.selectAll('*').remove();

    const nodes = root.descendants();
    const target = new Map<Cell, Rect>();
    const at = (d: Cell): Rect => target.get(d) ?? d;

    const rectHeight = (r: Rect) => r.x1 - r.x0 - Math.min(1, (r.x1 - r.x0) / 2);
    const labelVisible = (r: Rect) =>
      r.y1 <= innerWidth && r.y0 >= 0 && r.x1 - r.x0 > MIN_ROW_HEIGHT;

    // Column width never changes under zoom, so horizontal fit is decided once.
    const columnRoom = innerWidth / VISIBLE_COLUMNS - LABEL_INSET * 2;
    const valueFits = (d: Cell) =>
      (d.data.name.length + format(d.value ?? 0).length + 1) * CHAR_WIDTH < columnRoom;

    const cell = svg
      .append('g')
      .attr('transform', `translate(${MARGIN.left},${MARGIN.top})`)
      .attr('font-size', FONT_SIZE)
      .selectAll<SVGGElement, Cell>('g')
      .data(nodes)
      .join('g')
      .attr('transform', (d) => `translate(${d.y0},${d.x0})`);

    cell.append('title').text((d) => `${pathOf(d)}\n${format(d.value ?? 0)}`);

    const rect = cell
      .append('rect')
      .attr('width', (d) => Math.max(d.y1 - d.y0 - 1, 0))
      .attr('height', (d) => rectHeight(d))
      .attr('fill', (d) => (d.depth === 0 ? 'var(--muted)' : color(genreOf(d))))
      .attr('fill-opacity', 0.6)
      .style('cursor', 'pointer');

    const label = cell
      .append('text')
      .attr('x', LABEL_INSET)
      .attr('y', 13)
      .attr('fill', 'var(--text)')
      .attr('pointer-events', 'none')
      .attr('fill-opacity', (d) => Number(labelVisible(d)))
      .style('user-select', 'none');

    label.append('tspan').text((d) => d.data.name);

    const amount = label
      .append('tspan')
      .attr('fill-opacity', (d) => Number(labelVisible(d)) * 0.7)
      .text((d) => (valueFits(d) ? ` ${format(d.value ?? 0)}` : ''));

    let focus: Cell = root;

    // Rescale every cell so the clicked node fills the height and starts the first column.
    function clicked(_event: MouseEvent, clickedCell: Cell) {
      const next = focus === clickedCell ? clickedCell.parent ?? clickedCell : clickedCell;
      if (next === focus) return;
      focus = next;

      const span = next.x1 - next.x0;
      root.each((d) =>
        target.set(d, {
          x0: ((d.x0 - next.x0) / span) * innerHeight,
          x1: ((d.x1 - next.x0) / span) * innerHeight,
          y0: d.y0 - next.y0,
          y1: d.y1 - next.y0
        })
      );

      // Tweened by hand rather than via attr(): d3's transform interpolator reads
      // node.transform.baseVal, which jsdom does not implement, so the harness cannot click.
      cell
        .transition()
        .duration(DURATION)
        .attrTween('transform', function (d) {
          const [fromX, fromY] = translationOf(this);
          const to = at(d);
          const acrossTo = d3.interpolateNumber(fromX, to.y0);
          const downTo = d3.interpolateNumber(fromY, to.x0);
          return (t) => `translate(${acrossTo(t)},${downTo(t)})`;
        });
      rect
        .transition()
        .duration(DURATION)
        .attr('height', (d) => rectHeight(at(d)));
      label
        .transition()
        .duration(DURATION)
        .attr('fill-opacity', (d) => Number(labelVisible(at(d))));
      amount
        .transition()
        .duration(DURATION)
        .attr('fill-opacity', (d) => Number(labelVisible(at(d))) * 0.7);
    }

    rect.on('click', clicked);

    return () => {
      svg.interrupt();
      svg.selectAll('*').interrupt();
      rect.on('click', null);
      svg.selectAll('*').remove();
    };
  }, [root, color, innerWidth, innerHeight]);

  if (width === 0) return null;

  return (
    <svg
      ref={svgRef}
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height={height}
      role="img"
      aria-label="Zoomable icicle of a streaming catalog; click a cell to zoom in, the left column to zoom out"
      style={{ display: 'block' }}
    />
  );
}
